### ISSUE TITLE
OGC Address missing from HTML cover

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#100]
Picture:

<img width="725" alt="image" src="https://user-images.githubusercontent.com/11865/75947918-f38ad700-5edc-11ea-8ce5-fded2a1a9d42.png">

**Comment by opoudjis** [comment]
Oh, I already fixed this in "Make the contact box conditional in HTML: metanorma/mn-samples-ogc#21". (Bug had not been pointed out in that ticket, but I noticed it there.)

**Comment by opoudjis** [comment]
Note that in fact, the address is NOT SUPPLIED for certain types of document. That's a boilerplate issue.

**Comment by ronaldtse** [comment]
@opoudjis All OGC documents should show the OGC address regardless of document types. Please close this if it is the case. Thanks.

**Comment by opoudjis** [comment]
Currently they are only displayed `  {% if doctype == "Standard" or doctype == "Community Standard" %}`. And I did not make that rule up: it reflects OGC practice. See for example https://portal.ogc.org/files/?artifact_id=92039: Discussion papers do not have addresses.

I will not action this ticket unless I have explicit go-ahead from OGC.

**Comment by ronaldtse** [comment]
Asked for clarification from OGC.

**Comment by ronaldtse** [comment]
OGC: Do not display address in all documents, remove this section.
