### ISSUE TITLE
Review 10-110r3 bibliography issue

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#101]
>No "multiple bibliography section" markup was applied to solve the issue. The subsection markup (=== Recommended reading) was removed and put a boldface instead (*Recommended reading*).
> The references of the bibliography (Normative references) render properly. But the Recommended reading subsection is not shown.

From @manuel489 https://github.com/metanorma/mn-samples-ogc/pull/38

**Comment by opoudjis** [comment]
As I've already stated: currently the references section only renders bibliographic information, and nothing else. Clearly SDOs don't care about structure and put any random crap in their bibliogarphies, so I will relax that.

**Comment by opoudjis** [comment]
@manuel489  Bibliographies should now print any content they contain. Could you please review the documents this has come up with for you, and ensure that there are no unintended consequences?

**Comment by opoudjis** [comment]
... ALTHOUGH! I'm not sure what will happen with subclauses of bibliographies, and I will still be treating extraneous content as a grammar violation.

**Comment by opoudjis** [comment]
Ah, I also need to not strip extraneous material from bibliography in standoc.
