### ISSUE TITLE
From OGC: citations to OGC documents will display editor's names

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#102]
From today's DocTeam meeting:

* Citations to OGC documents should display editor's names.

Pending elaboration.

**Comment by opoudjis** [comment]
There is presumably a connection with LNCS and https://github.com/metanorma/mn-samples-ogc/issues/84

**Comment by ronaldtse** [comment]
This requirement is not made based on LNCS, but LNCS does allow displaying authorship, so that’s the only connection.

**Comment by ronaldtse** [comment]
@andrew2net does relaton-ogc provide names in entries? Thanks!

**Comment by andrew2net** [comment]
@ronaldtse there is a `contributor` element which could be a `person` or an `organization` with name:
```xml
<bibdata type="standard">
  <fetched>2020-04-01</fetched>
  <title type="title-main" format="text/plain" language="en" script="Latn">Development of Spatial Data Infrastructures for Marine Data Management</title>
  <title type="main" format="text/plain" language="en" script="Latn">Development of Spatial Data Infrastructures for Marine Data Management</title>
  <uri type="obp">https://portal.opengeospatial.org/files/?artifact_id=88037</uri>
  <docidentifier type="OGC">19-025r1</docidentifier>
...
  <contributor>
    <role type="author"/>
    <person>
      <name>
        <completename>Terry Idol</completename>
      </name>
    </person>
  </contributor>
  <contributor>
    <role type="publisher"/>
    <organization>
      <name>Open Geospatial Consortium</name>
    </organization>
  </contributor>
...
```

**Comment by ronaldtse** [comment]
In this case the ticket is actionable - ping @opoudjis :wink:

**Comment by opoudjis** [comment]
This issue becomes merged with https://github.com/metanorma/metanorma-ogc/issues/147, which is also requiring authors, where available, to be cited.
