### ISSUE TITLE
From OGC: keywords, submitting organizations and submitters only support structured data

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#103]
Confirmed in todays DocTeam meeting:

Question 3: 

Will enforce structured information.

> ii. Keywords

Didn't get to discuss the data structure, but assume it to be comma-delimited text (whitespace allowed).

> iv. Submitting organizations

Only organization name allowed. No country name. Probably just an unnumbered list.

> v. Submitters

Only personal name + affiliation. This can probably be encoded as a definition list.

Question 4:

No need for contact information. If authors want to present additional information or paragraphs, add new preface information. "Submitting organizations" and "Submitters" sections will be only structured data.

_Originally posted by @ronaldtse in https://github.com/metanorma/metanorma-ogc/issues/80#issuecomment-595282244_

**Comment by opoudjis** [comment]
The Submitters section has been implemented with affiliations, as requested: https://www.metanorma.com/author/ogc/authoring/#submitters
