### ISSUE TITLE
From OGC: pending update to document stages

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#104]
From DocTeam meeting:

Some document statuses may be changed. e.g. `swg-draft` => `swg-candidate`. 

<img width="738" alt="image" src="https://user-images.githubusercontent.com/11865/75995623-a8ea7880-5f37-11ea-86af-9f388c37f278.png">

Pending confirmation and elaboration.

**Comment by ronaldtse** [comment]
Ping @ogcscotts @gbuehler @ghobona do we have any updates in the document stages? Thanks!

**Comment by ogcscotts** [comment]
@ronaldtse We will shortly have standards entering our new (new-ish) policy of requiring evidence of implementation before becoming full standards. So we will need "published-draft" and "published-full." The two versions are identical in content other than the cover page and a list of evidence of implementation. The cover page difference would be in the approval, publication date, revision number, and title. The title would start at "OGC Noodle Markup Language Draft Standard" and be a full standard with the title changed to "OGC Noodle Markup Language Standard."

**Comment by ronaldtse** [comment]
Thanks @ogcscotts .

In the new cover page:
* the word "STANDARD" is for the document type
* the word "APPROVED" is for the document stage

<img width="624" alt="Screen Shot 2020-09-04 at 4 43 38 PM" src="https://user-images.githubusercontent.com/11865/92219916-cb9d2000-eecd-11ea-900a-7a1438fb5ff3.png">

Do we want to:
1. Write "DRAFT STANDARD" in place of "APPROVED" (which would normally be "SWG DRAFT", "OAB REVIEW", "PUBLIC RFC", "TC VOTE DRAFT", "APPROVED", "DEPRECATED", "RETIRED")
2. Write "DRAFT STANDARD" in place of "STANDARD" (at the location of the document type)
?

**Comment by ogcscotts** [comment]
@ronaldtse 2: "DRAFT STANDARD" in place of "STANDARD"

**Comment by ronaldtse** [comment]
@ogcscotts Got it. I'm concerned that the following can be confusing:

> DRAFT STANDARD
> Conceptual model & encoding
> APPROVED

vs

> DRAFT STANDARD
> Conceptual model & encoding
> SWG DRAFT

or

> DRAFT STANDARD
> Conceptual model & encoding
> OAB REVIEW DRAFT

Perhaps we can combine the stage and the document type as in:

> OAB REVIEW DRAFT STANDARD
> Conceptual model & encoding

> SWG REVIEW DRAFT STANDARD
> Conceptual model & encoding

> PUBLIC RFC DRAFT STANDARD
> Conceptual model & encoding

?

**Comment by ogcscotts** [comment]
@ronaldtse I agree - that has been the core of some contention in OGC about the naming "DRAFT." However, I still think keeping the stage and document type separate is good.
@ghobona @gbuehler - thoughts?

**Comment by ronaldtse** [comment]
@ogcscotts Personally I agree with you on keeping the stage and document type separate. However, there are organizations that mix them -- ISO conflates the naming, i.e. "International Standard", "Draft International Standard", "Working Draft", etc.

**Comment by opoudjis** [comment]
@ronaldtse Is this issue overridden by https://github.com/metanorma/metanorma-ogc/issues/187 ?

**Comment by ronaldtse** [comment]
Yes #187 already implements the solution. Closing.
