### ISSUE TITLE
From OGC: Display version number above "Additional Formats"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#106]
Requested by @ghobona:

> Please display the version number above the "Additional Formats" list. See the attached illustration.

![image](https://user-images.githubusercontent.com/11865/76267662-7b3e6000-62a6-11ea-9507-baa3be9e96ff.png)

**Comment by opoudjis** [comment]
The version is already displaying right above the additional formats:

<img width="914" alt="Στιγμιότυπο 2020-03-10, 11 35 18" src="https://user-images.githubusercontent.com/1911039/76268774-455ba480-62c3-11ea-85d3-b963c58cea76.png">

Is the request to put the version number inline with the version label?

**Comment by opoudjis** [comment]
Done.

**Comment by ronaldtse** [comment]
Confirmed done. It is now accessible via `:edition`: but once #109 is done `:version:` can be used.
