### ISSUE TITLE
Requirement blocks render badly in DOC output

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-ogc#108]
Nested requirement blocks are not showing up in DOC output. For example:

*Sample code*:
````
=== First sample

[.requirement,label="requirement label"]
====

[.requirement]
======
Description text
======

====

=== Second sample

[.requirement,label="requirement label"]
====

[.requirement]
======
Description text
======

[.requirement]
======
Description text
======

====
````

*HTML output*:
![capture3](https://user-images.githubusercontent.com/33627611/76357560-5241bd80-62ee-11ea-8974-01cc177488f8.PNG)

*DOC output*:
![capture4](https://user-images.githubusercontent.com/33627611/76357572-579f0800-62ee-11ea-9457-798c44465f8a.PNG)

Thanks!

Sample file:
[requirement-issue.zip](https://github.com/metanorma/metanorma-ogc/files/4314705/requirement-issue.zip)

**Comment by opoudjis** [comment]
The table is there in the Word markup, but is truly a table nested within a table; HTML can deal with that, DOC cannot. Need to do postprocessing cleanup.

**Comment by opoudjis** [comment]
Fixed shading of alternating rows in Word.
