### ISSUE TITLE
Alias `:version:` for `:edition:` and update documentation

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#109]
In opengeospatial/ogc-metanorma-testing#12 I had to rename :version: to :edition: to show the version number on the cover page. OGC uses the term "version", so it would be easier to follow that.

We should also update Metanorma.com to show this example:

```adoc
:doctype: IS
:abbrev: GWML
:edition: 2.3
:external-id: http://www.opengis.net/doc/{doctype}/{abbrev}/{edition}
```

`:external-id:` is automatically set IF
* it is not set manually, and
* all three of doctype, docstage, and edition are set

**Comment by opoudjis** [comment]
Documentation already done in https://github.com/metanorma/metanorma.com/pull/229
