### ISSUE TITLE
Duplicated example titles

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-ogc#114]
The title of example blocks are getting duplicated.

*Example*,
````
== Example sample

[example]
.Example title
====
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus condimentum hendrerit tortor vel consectetur. In ultricies elementum rhoncus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
====
````

*Output:*
![capture2](https://user-images.githubusercontent.com/33627611/77029637-9da13f00-6972-11ea-9682-dd4fb2857b4c.PNG)

Thanks!

**Comment by opoudjis** [comment]
Remove EXAMPLE label: made redundant by the added title.
