### ISSUE TITLE
Implement / update common "preface note"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#118]
As per #91 there is a common "preface note" across OGC publications.

This content shall be embedded in the MN XML.

It will be:

> Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.
> 
> Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.

**Comment by opoudjis** [comment]
> This content shall be embedded in the MN XML.

Not so fast.

This content is appended to the end of the Preface. What we have been doing to date for partial sections that are boilerplate is populate them in templates, rather than automatically in XML, so that people can still edit the text beforehand. Shouldn't we continue to do so?

**Comment by ronaldtse** [comment]
You have a sharp eye. What you said is indeed correct.

However, this content clearly has a legal tone to it (i.e. shouldn't change), and is consistent across all documents.

Instead of marking this as just "post-preface text", it seems to be THE "patent notice".

I'd propose we make this the "Patent Notice"?

**Comment by opoudjis** [comment]
We can do that, but we will need to alert people that we are doing it, so they don't replicate the content. What I will end up doing it store it in the XML as boilerplate (the patent notice within it), but realise it by appending it to the preface.

**Comment by ronaldtse** [comment]
Confirmed with OGC - we will add a post-preface section called "Patent notice" that contains this text.

**Comment by opoudjis** [comment]
Separate title? Or just inline with the preface?

**Comment by opoudjis** [comment]
We would prefer a separate title: The preface is what you data enter, the patent notice is what you don't.

On hold pending answer from @ronaldtse

**Comment by ronaldtse** [comment]
The "Patent notice" can be presented separately from the preface. The user does not get to enter the patent notice but it will always be included as boilerplate.

@opoudjis can we consolidate these boilerplate sections into YAML so they are easy to edit? Thanks!

**Comment by opoudjis** [comment]
> The "Patent notice" can be presented separately from the preface. The user does not get to enter the patent notice but it will always be included as boilerplate.

Will be appended after copyright notice.

> @opoudjis can we consolidate these boilerplate sections into YAML so they are easy to edit? Thanks!

Not within this ticket.
