### ISSUE TITLE
Generating text after "<" tag in tables

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-ogc#122]
Text between "<" and ">" tags cannot be generated in tables, if no additional space is added after "<".

For example, if table entries are written as follows:
![image](https://user-images.githubusercontent.com/55683568/77807439-1ea1ba00-7088-11ea-9a9e-7f68ccee88ce.png)

the first entry won't be generated, while the second one will. 
Moreover, both of these will be generated if they are not table entries.

[test.zip](https://github.com/metanorma/mn-samples-ogc/files/4396246/test.zip)

**Comment by opoudjis** [comment]
XML `&lt;` is being rendered as `<` and not `&lt;`. Investigating.

**Comment by opoudjis** [comment]
Bug has been introduced by https://github.com/metanorma/metanorma-standoc/issues/219, traverse messes with the encoding of escapes (I'd forgotten), and needs to be reencoded.
