### ISSUE TITLE
OGC sidebar document type "COMMUNITY STANDARD" overlapping with document status

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#124]
<img width="357" alt="image" src="https://user-images.githubusercontent.com/11865/77869692-02fa0780-7272-11ea-8c19-c2519713563e.png">

**Comment by opoudjis** [comment]
Also need to work out: is lettering on bands in OGC white or black? If black, then default band colour needs to be white instead of black.

**Comment by ronaldtse** [comment]
All lettering bands on OGC are white on color.

**Comment by opoudjis** [comment]
Duplicated in https://github.com/metanorma/metanorma-ogc/issues/124
