### ISSUE TITLE
HTML docstage/doctype layout conflict

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#128]
https://metanorma.github.io/mn-samples-ogc/documents/18-053r2.html

<img width="354" alt="Screen Shot 2020-04-01 at 2 16 07 AM" src="https://user-images.githubusercontent.com/11865/78060806-c12aa780-73be-11ea-81ab-8b06933f0c6c.png">

This is clearly a systematic problem: these elements are never supposed to clash, we need to use a permanent solution.

**Comment by opoudjis** [comment]
@w00lf and I have discussed: he will generalise this solution to all flavours, by creating a distinct docband-stage() function for stage bands, which ignores length as his solution here has done.

**Comment by ronaldtse** [comment]
Thanks @opoudjis @w00lf !

**Comment by opoudjis** [comment]
@w00lf Please tell me you're tracking which gems you've updated.

By my reckoning these are done:

* RSD
* CSA
* OGC

And these are to be done:

* CSD
* GB
* IEC
* ISO
* ITU
* M3D
* MPFD
* NIST
* UN
* VSD

**Comment by w00lf** [comment]
> @w00lf Please tell me you're tracking which gems you've updated.
> 
> By my reckoning these are done:
> 
> * RSD
> * CSA
> * OGC
> 
> And these are to be done:
> 
> * CSD
> * GB
> * IEC
> * ISO
> * ITU
> * M3D
> * MPFD
> * NIST
> * UN
> * VSD

yes, thats correct, waiting for isodoc version update and then will update remaining flavours

**Comment by opoudjis** [comment]
isodoc is out now, but wait to push, as I'm releasing all the gems in sequence. Will let you know when I'm done.

**Comment by w00lf** [comment]
> isodoc is out now, but wait to push, as I'm releasing all the gems in sequence. Will let you know when I'm done.

Got you

**Comment by w00lf** [comment]
@opoudjis finished with all flavors from the list:

RSD
CSA
OGC
CSD
GB
IEC
ISO
ITU
M3D
MPFD
NIST
UN
VSD

**Comment by opoudjis** [comment]
Thank you so much!
