### ISSUE TITLE
Spaces introduced into URIs and other phrases with /

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-ogc#138]
Metanorma appears to be introducing spaces into URIs and other phrases with `/`.

Please see the attached screenshot for an example. 

The arrows show the locations of the spaces.

On the screenshot, below the HTML presentation is the asciidoc content that was ingested by Metanorma. Note that the asciidoc content does not include spaces in the URIs, requirement identifier nor the label.

![](https://user-images.githubusercontent.com/18121038/80944289-15bbab00-8de1-11ea-8826-fa91d9c2874c.png)

**Comment by opoudjis** [comment]
Resolved in https://github.com/opengeospatial/ogc-metanorma-testing/issues/15
