### ISSUE TITLE
Duplicated publisher name in ISO19103:2005 reference

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#144]
From @ghobona :

I added the following line to the references and it produced a reference with a duplicated publisher name. See attached.

```
* [[[ISO19103,ISO 19103:2005]]] – Geographic information - Conceptual schema language
```

<img width="1356" alt="Screenshot 2020-05-19 at 14 25 34" src="https://user-images.githubusercontent.com/18121038/82332068-da260100-99dc-11ea-9a4c-778c736ab6b8.png">

Originally from: https://github.com/opengeospatial/ogc-metanorma-testing/issues/21

**Comment by opoudjis** [comment]
To be clear: the OGC reference style *does* duplicate the publisher name: e.g. http://docs.opengeospatial.org/as/15-104r5/15-104r5.html

> ISO: ISO 19101-1:2014,
> Geographic information – Reference model – Part 1: Fundamentals, 2014

The error here is that the "/TS" is being included in the first instance of "ISO".

**Comment by opoudjis** [comment]
Blocked by relaton/relaton-iso#90

**Comment by opoudjis** [comment]
Resolved in relaton-iso.
