### ISSUE TITLE
Revert OGC HTML font to previous font

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#145]
From @ghobona:

> Please change the default font to be what it was previously. See attached screenshot for what the previous font looked like.

![Screenshot 2020-05-19 at 12 28 23](https://user-images.githubusercontent.com/18121038/82321215-67ad2500-99cc-11ea-9805-70e83457c83a.png)

New font:

![image](https://user-images.githubusercontent.com/11865/82375798-b05bf100-9a53-11ea-865c-8fbb4242ed93.png)

Originally from: https://github.com/opengeospatial/ogc-metanorma-testing/issues/20

**Comment by ronaldtse** [comment]
@ghobona sorry about this! Because of the new addition of the PDF format, we streamlined font selection -- since OGC Word /PDF uses Times New Roman, we tried to match that. And eventually we abandoned the synchronized approach, but we forgot to revert it for OGC.

We may need a broader discussion on font/branding design across Print/Online layouts, but we will fix this HTML font issue first...

**Comment by opoudjis** [comment]
@ronaldtse Does this mean (as I had originally stated) that `.fonts_used` refers only to PDF fonts after all? Or am I going to add the HTML fonts to it? Should we rename the function?

**Comment by ronaldtse** [comment]
The best and most future proof way thing to do here is to provide fonts used for every output format, ie a hash with format keys for fonts used.

**Comment by opoudjis** [comment]
Is this going to blow up @abunashir's work?

**Comment by ronaldtse** [comment]
It's an easy fix for him.

**Comment by opoudjis** [comment]
I;'m changing the structure of `.fonts_used` in all gems. @ronaldtse please notify @abunashir, I've left a note in https://github.com/metanorma/metanorma-cli/pull/139
