### ISSUE TITLE
OGC support of authors and URLs in references

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-ogc#147]
*(I wanted to post this question in `relaton-bib` repo, but  I don't have enough privileges there to set assignees or labels. So, I'm posting here as this question is related to this issue https://github.com/metanorma/mn-samples-ogc/issues/67)*

I'm trying to encode this following reference using AsciiBib:

````
* [[[nasa1, NASA ESDS-RFC-011v2.00 R. Rew]]], E. Hartnett, D. Heimbigner, E. Davis, J. Caron: _NetCDF Classic and 64-bit Offset File Formats_ +
//http://www.esdswg.org/spg/rfc/esds-rfc-011/ESDS-RFC-011v2.00.pdf
````

For which I'm using the following markup:

````
[[nasa1]]
[%bibitem]
=== NetCDF Classic and 64-bit Offset File Formats
docid::
  type::: NASA
  id::: ESDS-RFC-011v2.00
link:: http://www.esdswg.org/spg/rfc/esds-rfc-011/ESDS-RFC-011v2.00.pdf
contributor::
contributor.person.name.completename.content:: E. Hartnett
contributor::
contributor.person.name.completename.content:: D. Heimbigner
contributor::
contributor.person.name.completename.content:: E. Davis
contributor::
contributor.person.name.completename.content:: J. Caron
````

Resulting in this output (HTML):
![cap-ref](https://user-images.githubusercontent.com/33627611/79927487-e6369700-840d-11ea-8b84-00393160457d.PNG)

As you can notice, contributors and link don't show up.

Am I using the correct AsciiBib markup in this case?

Thanks!

**Comment by opoudjis** [comment]
The rules for rendering citations in OGC, given in https://github.com/metanorma/metanorma-ogc/issues/46 and https://www.springer.com/engineering?SGWID=0-175-6-791930-0, are expanded as follows:

* If a personal author is available, they substitute the organisation name which prefixes the citation: 

`{personal names | organisation}: {document identifier}, {title}. {publisher}, {city} ({year})`

* Personal names follow LNCS practice:

  * If they are `bibitem/contributor/person/name/completename`, they are plunked in as is
  * If they are `bibitem/contributor/person/name/surname` + bibitem/contributor/person/name/initials`, they are inserted as `surname initials`
  *  If they are `bibitem/contributor/person/name/surname` + bibitem/contributor/person/name/forename`, they are inserted as `surname initials`, where initials is the first letter of each forename given, with no separating spaces
  * Names are comma delimited, with no "and" or ampersand

e.g. `Wahle A, Prause GPM, von Birgelen C, Erbel R, Sonka M `

* If a URL is present, it is appended to the end of the citation.

**Comment by opoudjis** [comment]
@Intelligent2013 This extension of citations will need to be implemented in PDF as well. I could realise it in Presentation XML, but you have implemented OGC citations anyway, so this should not be a major extension.

**Comment by opoudjis** [comment]
Actually, creating new ticket for you...
