### ISSUE TITLE
Copyright notice text alignment

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-ogc#161]
Copyright notice text alignment (from cover page area) differs in DOC and PDF versions

DOC:
![issue1-doc](https://user-images.githubusercontent.com/33627611/86543278-080ec880-beeb-11ea-9537-89ba0c2c6c4d.PNG)

PDF:
![issue1-pdf](https://user-images.githubusercontent.com/33627611/86543279-0c3ae600-beeb-11ea-8638-3c33b6f55972.PNG)

Which approach is correct?

**Comment by Intelligent2013** [comment]
In XSLT I've aligned it to center. But the next clause 'Note' also aligned to center.

![изображение](https://user-images.githubusercontent.com/5559926/86933669-74840480-c143-11ea-98c4-4f3de121f1ff.png)

It would be better to set `align` attribute for each `copyright-statement//p` in XML:
```xml
<boilerplate>
  <copyright-statement>
    <clause>
      <title>Copyright notice</title>

      <p id="_43c75c59-c704-4652-94cc-7228a6c574a7" align="center">Copyright
        © 2012 Open Geospatial Consortium<br/>
        To obtain additional rights of use, visit 
        <link target="http://www.opengeospatial.org/legal/">http://www.opengeospatial.org/legal/</link></p>
    </clause>
    <clause>
      <title>Note</title>
      <p id="_7adead23-4a65-48de-b8ce-2fbdb308f90f" align="left">Attention is drawn to t...
```
