### ISSUE TITLE
DOC vs PDF: Document metadata list differs

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-ogc#162]
Document metadata list (in cover page area) differs:

DOC:
![issue2-doc](https://user-images.githubusercontent.com/33627611/86544089-12809080-bef2-11ea-94f8-9238d3692462.PNG)

PDF:
![issue2-pdf](https://user-images.githubusercontent.com/33627611/86544091-16141780-bef2-11ea-9a07-0c93b54af129.PNG)

Which one is correct?
(Check complete outputs on [OGC published samples](https://metanorma.github.io/mn-samples-ogc/))

**Comment by Intelligent2013** [comment]
Fixed in XSLT:
![изображение](https://user-images.githubusercontent.com/5559926/86934158-0ab82a80-c144-11ea-9dd6-38e150f55cb2.png)
