### ISSUE TITLE
DOC vs PDF: Preface title is not numbered

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-ogc#163]
Preface section numbering is missing in PDF

DOC:
![issue5-doc](https://user-images.githubusercontent.com/33627611/86544289-af8ff900-bef3-11ea-8b31-e16831a55cfb.PNG)

PDF:
![issue5-pdf](https://user-images.githubusercontent.com/33627611/86544293-b3bc1680-bef3-11ea-98e2-68112814354c.PNG)

**Comment by Intelligent2013** [comment]
Fixed in XSLT:
![изображение](https://user-images.githubusercontent.com/5559926/86934403-51a62000-c144-11ea-8bbe-4adb324b3d87.png)
