### ISSUE TITLE
DOC vs PDF: "Normative references" title is misspelled in PDF

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-ogc#164]
According to @ronaldtse, the correct title is "Normative references", not "Normative References"

DOC:
![issue6-doc](https://user-images.githubusercontent.com/33627611/86544380-5d030c80-bef4-11ea-873e-ad5e42b2478f.PNG)

PDF:
![issue6-pdf](https://user-images.githubusercontent.com/33627611/86544383-65f3de00-bef4-11ea-8584-df082bb8aa3b.PNG)

(This issue can be seen in [16-080](https://metanorma.github.io/mn-samples-ogc/) document.)

**Comment by Intelligent2013** [comment]
This issue in XML source:
```xml
<bibliography>
<references id="_normative_references" normative="true" obligation="informative">
<title>Normative References</title>
...
```

**Comment by manuel489** [comment]
Oh sorry @Intelligent2013 , didn't notice. Closing.
