### ISSUE TITLE
DOC vs PDF: Large horizontal spacing in Note block

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-ogc#166]
Horizontal space between "NOTE" text and content is quite large in DOC version.

DOC:
![issue8-doc](https://user-images.githubusercontent.com/33627611/86544584-304ff480-bef6-11ea-9b70-369c74a73536.PNG)

PDF:
![issue8-pdf](https://user-images.githubusercontent.com/33627611/86544588-37770280-bef6-11ea-9b6e-f74a71deaeed.PNG)

**Comment by opoudjis** [comment]
This is about location of tab. 20pt is too little for "NOTE 1" to fit; making it 2 cm.
