### ISSUE TITLE
DOC vs PDF: Short horizontal spacing in Sections/Subsections

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-ogc#167]
Horizontal space between number and section is too short in DOC version

DOC:
![issue10-doc](https://user-images.githubusercontent.com/33627611/86544681-df8ccb80-bef6-11ea-8685-d99c6154074b.PNG)

PDF:
![issue9-pdf](https://user-images.githubusercontent.com/33627611/86544685-e3b8e900-bef6-11ea-8190-afdbab2e7d4c.PNG)

**Comment by opoudjis** [comment]
This is with inadequate amount of tab, as with #166. The tabs which (I presume) are inherited from OGC make no sense: "tab-stops:20.0pt list 21.6pt left 28.0pt;"

Making the tab here be 1.0cm to start with, with 0.5cm increment each level.
