### ISSUE TITLE
DOC vs PDF: Page numbering is missing in DOC version

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-ogc#168]
Page numbering and footer are missing in DOC version. Check [published samples](https://metanorma.github.io/mn-samples-ogc/) for illustration.

PDF: 
![issue11-pdf](https://user-images.githubusercontent.com/33627611/86544768-bae52380-bef7-11ea-9a8b-594dbdecc3ef.PNG)

DOC: nothing

**Comment by opoudjis** [comment]
Addressed in https://github.com/metanorma/metanorma-ogc/issues/160
