### ISSUE TITLE
DOC vs PDF: Preface content is not showing up in PDF version

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-ogc#170]
Unlike "Preface" sections itself, the rest of the preface content is not showing up in PDF version.
Check [16-080](https://metanorma.github.io/mn-samples-ogc/) for illustration.

DOC:
![issue14-doc](https://user-images.githubusercontent.com/33627611/86545260-ab67d980-befb-11ea-877c-bfc8470db5d8.PNG)

PDF: nothing

**Comment by Intelligent2013** [comment]
Fixed in XSLT:
![изображение](https://user-images.githubusercontent.com/5559926/86935021-0cceb900-c145-11ea-92cf-1d4957131a51.png)
