### ISSUE TITLE
References in subsections are not showing up

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-ogc#171]
References configured in subsections are not showing up in OGC.

For example (taken from [18-053r2](https://metanorma.github.io/mn-samples-ogc/)):
````
== References

[bibliography]
=== Normative

* [[[EPSG,EPSG]]], EPSG: 4979, 2007. http://spatialreference.org/ref/epsg/wgs-84-3/[http://spatialreference.org/ref/epsg/wgs-84-3/]

* [[[IETF_RFC2397,RFC 2397]]], IETF RFC2397: The "data" URL scheme, 1998. https://tools.ietf.org/html/rfc2397[https://tools.ietf.org/html/rfc2397]

* [[[IETF_RFC3629,RFC 3629]]], IETF RFC3629: UTF-8, a transformation format of ISO 10646, 2003. https://tools.ietf.org/html/rfc3629[https://tools.ietf.org/html/rfc3629]

* [[[IETF_RFC3986,RFC 3986]]], IETF RFC3986: IANA Registration for Enumservice 'XMPP', 2007. https://tools.ietf.org/html/rfc4979[https://tools.ietf.org/html/rfc4979]
````

No references are shown in this configuration, but they are so in other flavors like ISO.

Sample file:
[ogc-testing.zip](https://github.com/metanorma/metanorma-ogc/files/4881581/ogc-testing.zip)

**Comment by opoudjis** [comment]
Indeed: Normative References are separated from Bibliographies, and Normative References are being selected in isodoc with the xpath  `//bibliography/references[@normative = 'true']`, which is assuming no subclauses. If there is a subclause, the structure is instead `//bibliography/clause/references[@normative = 'true']`.

We have the pathological case of a clause being including both a normative and an informative bibliography, which would end up split apart on rendering. To deal with that, any clause within the Bibliography which contains normative references is treated as the (unique) normative references, and bibliography will use any clause which does not contains normative references, as determined by `@normative = 'true'`.

**Comment by opoudjis** [comment]
I've fixed this in isodoc, but this fix is colliding head on with the fixes I've put in for https://github.com/metanorma/metanorma-standoc/issues/285, and will result in extremely messy code mergers; so I'm deferring the propagation of this fix down to flavours until https://github.com/metanorma/metanorma-standoc/issues/285 is integrated into the code.

**Comment by opoudjis** [comment]
I've fixed this, but Manuel, you will need to wait until pres_xml is integrated into code to confirm it. Putting this on my on-hold queue.

**Comment by manuel489** [comment]
Ok @opoudjis, thanks!

**Comment by opoudjis** [comment]
@manuel489 That merger will happen next release

**Comment by manuel489** [comment]
Issue is fixed, thanks @opoudjis! Closing.
