### ISSUE TITLE
Change of Word/PDF layout for OGC Whitepaper

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#174]
As requested by @ogcscotts @ghobona we will update the OGC Whitepaper layout to the attached template.

NOTE: The disclaimer in the template is incorrect -- it should be changed to the normal Whitepaper disclaimer (i.e. no change on our side).

[OGC White Paper_DRAFT_Template_20200713.docx](https://github.com/metanorma/metanorma-ogc/files/4959226/OGC.White.Paper_DRAFT_Template_20200713.docx)

**Comment by Intelligent2013** [comment]
@ronaldtse 

what should I display instead of text '*Additional context, inspirational quote, etc. fits into this subheading area*'?

![изображение](https://user-images.githubusercontent.com/5559926/88486582-5d3c7800-cf87-11ea-9cec-11b46394912f.png)

**Comment by opoudjis** [comment]
@Intelligent2013 The problem here is, we have zero provision for "random inspirational quote" in Metanorma. There is not even provision in OGC (or standoc) for subtitles, by default. This does require clarification from OGC as to what they expect to see here, before I model it.

**Comment by opoudjis** [comment]
@ronaldtse I am only doing Word; please get someone else if you want this in HTML.

**Comment by opoudjis** [comment]
isodoc: need to allow options to be writeable, so that fonts can be redefined (there are different fonts for White Papers).

**Comment by ronaldtse** [comment]
@opoudjis OGC instructed that the HTML layout does not change. This layout change is only for Word and PDF. I will seek clarification on the subtitle/quote thing.

**Comment by ronaldtse** [comment]
This layout uses the fonts Lato and Segoe UI Light. Lato will be addressed in fontist/fontist#108 , will need alternative for Segoe UI Light.

**Comment by Intelligent2013** [comment]
> 
> 
> This layout uses the fonts Lato and Segoe UI Light. Lato will be addressed in [fontist/fontist#108](https://github.com/fontist/fontist/issues/108) , will need alternative for Segoe UI Light.

Ok, I'll need to updated OGC xslt and mn2pdf config.

**Comment by ronaldtse** [comment]
Confirmed with OGC that we will use Leto instead of Segoe UI Light for now. So only Leto is the new font here.
