### ISSUE TITLE
PDF: add personal authors and URIs to citations

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-ogc#179]
Implement https://github.com/metanorma/metanorma-ogc/issues/147 in PDF:

The rules for rendering citations in OGC, given in https://github.com/metanorma/metanorma-ogc/issues/46 and https://www.springer.com/engineering?SGWID=0-175-6-791930-0, are expanded as follows:

* If a personal author is available, they substitute the organisation name which prefixes the citation: 

`{personal names | organisation}: {document identifier}, {title}. {publisher}, {city} ({year})`

* Personal names follow LNCS practice:

  * Personal names are `bibitem/contributor[role/@type = 'author']/person`, or if none are present, `bibitem/contributor[role/@type = 'editor']/person`
  * If they are `bibitem/contributor/person/name/completename`, they are plunked in as is
  * If they are `bibitem/contributor/person/name/surname` + `bibitem/contributor/person/name/initials`, they are inserted as `surname initials`, stripping any full stops or spaces from the initials
  *  If they are `bibitem/contributor/person/name/surname` + bibitem/contributor/person/name/forename`, they are inserted as `surname initials`, where initials is the first letter of each forename given, with no separating spaces
  * Names are comma delimited, with no "and" or ampersand

e.g. `Wahle A, Prause GPM, von Birgelen C, Erbel R, Sonka M `

* If a URL is present, it is appended to the end of the citation.

So 

````
<contributor>
            <role type="author"/>
            <person>
              <name><completename>Fred Johnson</name></name>
            </person>
          </contributor>
        <contributor>
            <role type="author"/>
            <person>
              <name>
              <surname>Jackson</surname>
              <initial>K.G.</initial>
              </name>
            </person>
          </contributor>
        <contributor>
            <role type="author"/>
            <person>
              <name>
              <surname>Nixon</surname>
              <forename>Richard</forename>
              <forename>Milhouse</forename>
              </name>
            </person>
          </contributor>
````

renders as

`Fred Johnson, Jackson KG, Nixon RM`

**Comment by opoudjis** [comment]
From spec/isodoc/ref_spec.rb in the gem:

````
<bibitem id="ref11">
<contributor>
            <role type="author"/>
            <person>
              <name><completename>Fred Johnson</completename></name>
            </person>
          </contributor>
        <contributor>
            <role type="author"/>
            <person>
              <name>
              <surname>Jackson</surname>
              <initial>K.G.</initial>
              </name>
            </person>
          </contributor>
        <contributor>
            <role type="author"/>
            <person>
              <name>
              <surname>Nixon</surname>
              <forename>Richard</forename>
              <forename>Milhouse</forename>
              </name>
            </person>
          </contributor>
          <contributor>
            <role type="editor"/>
            <person>
              <name><completename>Euclid</completename></name>
            </person>
          </contributor>
  <title>Internet Calendaring and Scheduling Core Object Specification (iCalendar)</title>
  <docidentifier type="IETF">RFC 10</docidentifier>
</bibitem>
````

renders as:

`<p id="ref11" class="Biblio">[5]&#160; Fred Johnson, Jackson KG, Nixon RM: IETF RFC 10, <i>Internet Calendaring and Scheduling Core Object Specification (iCalendar)</i>. </p>`

````
<bibitem id="ISSN" type="ISSN">
          <title format="text/plain">Instruments for analytical laboratory use</title>
          <docidentifier type="ISSN">ISSN</docidentifier>
          <docidentifier type="metanorma">[2]</docidentifier>
  <uri>http://www.example.com</uri>
          <contributor>
            <role type="editor"/>
            <person>
              <name><completename>Euclid</completename></name>
            </person>
          </contributor>
          <contributor>
            <role type="publisher"/>
            <organization>
              <name>ISSN</name>
            </organization>
          </contributor>
        </bibitem>
````

renders as

`<p id="ISSN" class="Biblio">[2]&#160; Euclid: ISSN ISSN, <i>Instruments for analytical laboratory use</i>. <span>ISSN</span> <a href="http://www.example.com">http://www.example.com</a></p>`

**Comment by Intelligent2013** [comment]
Done. PDF render example:
![изображение](https://user-images.githubusercontent.com/5559926/90278408-1ba93980-de70-11ea-94e3-ab2eca3861d5.png)
