### ISSUE TITLE
Preview: Update OGC PDF document design

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#182]
[OGC Document Design_v6.pdf](https://github.com/metanorma/metanorma-ogc/files/5145021/OGC.Document.Design_v6.pdf)

Details TBD.

**Comment by Intelligent2013** [comment]
@ronaldtse Could you attach a source InDesign file also, please? I can't cut a logo from cover page.

**Comment by ronaldtse** [comment]
Of course, will do!

**Comment by Intelligent2013** [comment]
@ronaldtse 
OGC xslt updated in https://github.com/metanorma/mn-native-pdf/tree/master/xslt_src.

**Comment by Intelligent2013** [comment]
@ronaldtse 
there are a few differences in styles between design and resulted PDF:

1. In titles of tables/figures:

   - Design:
![изображение](https://user-images.githubusercontent.com/5559926/91965769-a1a2fc80-ed19-11ea-8e09-75f80583ea9b.png)

   - Resulted PDF:
![изображение](https://user-images.githubusercontent.com/5559926/91965798-abc4fb00-ed19-11ea-9c4a-48d219c9900c.png)


   - Design: 
![изображение](https://user-images.githubusercontent.com/5559926/91965890-ca2af680-ed19-11ea-87b8-1fbb908c62dc.png)

   - Resulted PDF:
![изображение](https://user-images.githubusercontent.com/5559926/91965945-e0d14d80-ed19-11ea-9327-ad62f31f4286.png)

   - Design:
![изображение](https://user-images.githubusercontent.com/5559926/91966087-0f4f2880-ed1a-11ea-920c-57e19195d36b.png)


   - Resulted PDF:
![изображение](https://user-images.githubusercontent.com/5559926/91966030-02323980-ed1a-11ea-9e13-30fe836abe32.png)

In source presentation XML table's/figure's name is:
```xml
<name>Table 1 — Conformance classes related to WPS 2.0</name>
```

If we need to support a different processing (bold style, for example) for table/figure number and name, then we need to split them in presentation xml into a few things, for example:
```
<name num="Table 1" splitby=" — ">Conformance classes related to WPS 2.0</name>
```

2. In Annexes titles:
   - Design:
![изображение](https://user-images.githubusercontent.com/5559926/91966775-fabf6000-ed1a-11ea-8bfb-7a92909b8896.png)

   - Resulted PDF:
![изображение](https://user-images.githubusercontent.com/5559926/91966813-090d7c00-ed1b-11ea-9002-67d7b45fe713.png)

   - Design:
![изображение](https://user-images.githubusercontent.com/5559926/91967094-69042280-ed1b-11ea-9db3-a3b5d64dfd4d.png)


   - Resulted PDF:

![изображение](https://user-images.githubusercontent.com/5559926/91967118-71f4f400-ed1b-11ea-80d0-754e0bea6b7f.png)

Souces XML:
```xml
<annex id="annex-abstract-test-suite" obligation="normative">
<title><strong>Annex A</strong><br/>(normative)<br/><strong>Abstract Test Suite</strong></title>
...
```

If we need to support it in resulted PDF, then we have to change a source presentation XML into:
```xml
<annex id="annex-abstract-test-suite" obligation="normative">
<title>ANNEX A <em>(normative)</em><br/>ABSTRACT TEST SUITE</title>
...
```
or

```xml
<annex id="annex-abstract-test-suite" obligation="normative">
<title><uppercase>Annex A</uppercase> <em>(normative)</em><uppercase>Abstract Test Suite</uppercase></title>
...
```

**Comment by Intelligent2013** [comment]
3. The cover page has a text
![изображение](https://user-images.githubusercontent.com/5559926/94951606-449f8f80-04ed-11eb-9543-078176f7d7b3.png)

is it a fixed text? Or what is xml tag for this?

**Comment by ronaldtse** [comment]
> 1. The cover page has a text
>    ![изображение](https://user-images.githubusercontent.com/5559926/94951606-449f8f80-04ed-11eb-9543-078176f7d7b3.png)
> 
> is it a fixed text? Or what is xml tag for this?

This is the document subtype. It’s supposed to be in the XML.
