### ISSUE TITLE
references for joint publications

### ISSUE THREAD

**Issue by ogcscotts** [metanorma/metanorma-ogc#184]
How are references handled to documents published jointly by two organizations? For instance, many OGC standards have an ISO equivalent (which may be different dates); OGC and W3C publish several joint documents as well, but they have the same date.

**Comment by ronaldtse** [comment]
@ogcscotts sorry I missed this.

In ISO 690:2020, we consider "joint published" (single document multiple publishers) and "dual-published" (multiple publications of the same content) separately. This is the relevant snippet.

<img width="718" alt="image" src="https://user-images.githubusercontent.com/11865/93416329-2a07cc80-f8d8-11ea-8ab5-5d0780db9689.png">

A jointly published document is realized with 1 bibliographic item: a single document with 2 publishers. 

A dual-published (should be "multi-published") document is realized with 2+ bibliographic items with independent publishers.

In this case, it seems that OGC/W3C documents are "jointly published", and OGC/ISO documents are multi-published.

This is tricky because OGC uses LNCS, which does not support this type of complex arrangement. Metanorma does not yet support these expressions.

**Comment by ogcscotts** [comment]
@ronaldtse Thanks for the examples. You are correct in the nature of publications between OGC and W3C vs. ISO. Jointly published in LNCS can be fairly simple, just have the editor enter two publishers in the front of the entry; for dual, the editor will need to enter both documents as single entries, I suppose.

**Comment by ronaldtse** [comment]
There is an issue here because the information about dual publishers isn't fetchable. We will have to enhance the reference source to provide this information.

**Comment by opoudjis** [comment]
ITU deals with this. Ensure that the span notation used to manually enhance referencs copes with dual publication requirement.

**Comment by opoudjis** [comment]
So will implement in metanorma a merge of two publications in references, to realise joint publications:

`*[ref1, merge(OGC 20-040r3, ISO 19170-1:2020)]`

This will fetch both references, treat the first reference as the basis, and merge into it details of the other documents that are specific to publication (publisher, docidentifier). I will also need to ensure that relaton-render deals with this; publishers won't be an issue, but it will be taken by surprise by multiple primary docidentifiers. 

I will also realise dual publications:

`*[ref1, dual(OGC 20-040r3, ISO 19170-1:2020)]`

This will be realised as the first publication being treated as basic, and the other publications appearing as separate publications in the same entry, as "also published as". The relation we have in relaton that captures that is one of

* `reproductionOf`: "document B is a Manifestation of the same Expression as document A", 
* the narrower `reprintOf`: "document B is a reproduction of document A, involving a new publisher or distributor and mass dissemination, and no overriding concern with reproducing the source manifestation precisely (not necessarily restricted to print media)"
* `adoptedFrom` : `identical`: "document A is adopted by a standards organisation from document B by a different organisation. (These are potentially the same content, but they have institutional authorship and application; this kind of appropriation of text is not characteristic of literary works.) document A is adopted from document B, without any change"

The slight problem is that our model assumes asymmetrical relations, that one SDO came first in this instance. I don't think this is that big a deal, but if we're going to call it "also published as", I'd be more comfortable with "reproductionOf", perhaps with a narrower qualification `independentPublicationOf` or `dualPublicationOf`.

**Comment by ronaldtse** [comment]
@opoudjis I wonder if this is better served at the Relaton level, because Relaton needs to handle dual publications (as per ISO 690).

**Comment by opoudjis** [comment]
>  I wonder if this is better served at the Relaton level, because Relaton needs to handle dual publications (as per ISO 690).

relaton-render clearly needs to deal with a bibliographic reference that contains dual publication information, and that will be output as a merger of two relaton records.

But the notion that relaton, as a scraper of information from SDO websites, is going to have the slightest idea that a document is dual published, is one I find acutely implausible. And I am of course correct:

* The string "OGC" appears nowhere in https://www.iso.org/standard/32588.html
* The string "ISO" appears nowhere in https://docs.ogc.org/as/20-040r3/20-040r3.html
* Expecting that such dual publication identifiers will routinely be published, and will occur somewhere predictable  on an SDO page, is naive.

What needs to happen is '<bibitem id="A">(Record 1) <relation type="reproductionOf"><bibitem id="B">(Record 2)</bibitem></relation></bibitem>`. That's a relaton record merger. But it is not going to have anything to do with relaton screenscraping.

**Comment by opoudjis** [comment]
Merge URIs as well as docidentifiers and publishers.

**Comment by opoudjis** [comment]
relaton-render: Add Japanese i18n (although we currently have not resolved at, in.)

Restricting document identifiers to primary if present.

**Comment by ronaldtse** [comment]
@opoudjis just a note that only certain Relaton flavors use screenscraping. For example OGC records do not come from screenscraping. Whether dual published information is available is a separate question.
