### ISSUE TITLE
(URGENT) PDF: Remove "PREFERRED" label (it is a default)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#186]
From @ghobona:

> The subheaders in Chapter 4 appear to be tagged with the label PREFERRED. This is not part of the spec and should be removed.
> 
> ![Screenshot 2020-09-22 at 17 49 27](https://user-images.githubusercontent.com/18121038/93912922-4fdc0980-fcfc-11ea-9d40-6c59948e182b.png)

From: https://github.com/opengeospatial/ogc-metanorma-testing/issues/31

**Comment by Intelligent2013** [comment]
Fixed. XSLT updated in mn-native-pdf master branch.
