### ISSUE TITLE
Update document stage notation on cover page

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#187]
Agreed with @ogcscotts @ghobona and @gbuehler

If status==’swg-draft’ then cover shows ‘Candidate SWG Draft’
If status==’oab-review’ then cover shows ‘Candidate OAB Review Draft’
If status==’public-rfc’ then cover shows ‘Candidate Public RFC Draft’
If status==’tc-vote’ then cover shows ‘Candidate TC Vote Draft'
If status==’approved/published’ then cover shows ‘Approved'
If status==’deprecated’ then cover shows ‘Deprecated’
If status==’retired’ then cover shows ‘Retired’

**Comment by opoudjis** [comment]
@Intelligent2013 I'm using the new local_bibdata structure to address this: the enum value of the stage name shall be in //bibdata/status/stage, and the version to display shall be in //local_bibdata/status/stage

**Comment by opoudjis** [comment]
The band name in HTML needs to be lengthened to fit the longer stage names.

**Comment by ronaldtse** [comment]
Implemented.
