### ISSUE TITLE
PDF: Incorrect formatting of Roman numerals

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#189]
From @ghobona:

> Some Roman numerals on headers are incorrectly formatted.

> <img width="586" alt="1_numerals_issue" src="https://user-images.githubusercontent.com/18121038/93906653-5a92a080-fcf4-11ea-8f51-5ca6ade21102.png">

@Intelligent2013 can you help check and fix? Thanks!

Originally at: https://github.com/opengeospatial/ogc-metanorma-testing/issues/30

**Comment by Intelligent2013** [comment]
@ronaldtse XSLT doesn't operate a section numbers for presentation xml. I assume that `III.1.` presents in source xml.
I don't have an access to https://github.com/opengeospatial/ogc-metanorma-testing/ repo, so please specify a document number and sources.

**Comment by ronaldtse** [comment]
@Intelligent2013 I've forked the repo here: https://github.com/metanorma/ogc-metanorma-testing 

Thanks!

**Comment by ronaldtse** [comment]
Ping @opoudjis for help.

**Comment by opoudjis** [comment]
So I've just compiled 19-013 in the ogc-metanorma-testing repo, and I get:

````
<foreword id="_preface" obligation="informative">
<title depth="1">iii.<tab/>Preface</title><clause id="_motivation" obligation="informative">
<title depth="2">iii.1.<tab/>Motivation</title>
````

... The title content seems to me to be exactly what it should be: I don't understand what the issue with the PDF is, and I don't know what subsection roman numerals are supposed to look like, but this is the content to be working from...

**Comment by Intelligent2013** [comment]
@ronaldtse 
> Some Roman numerals on headers are incorrectly formatted.
what do you mean under `incorrectly formatted'?

**Comment by Intelligent2013** [comment]
Would you like `iii.1. MOTIVATION` instead of `III.1. MOTIVATION`?

**Comment by Intelligent2013** [comment]
Done.
![изображение](https://user-images.githubusercontent.com/5559926/94961818-18403f00-04fe-11eb-97e7-fd83140f4259.png)

**Comment by opoudjis** [comment]
OK. I'm going to close this ticket, will reopen if we get advice to the contrary.

**Comment by opoudjis** [comment]
Lowercase roman numerals needed for HTML as well.

**Comment by opoudjis** [comment]
@Intelligent2013 Turns out the request was improperly formulated. It is not for iii.1 at all. It is for MLA ordering, following the sequence `I. A. 1. a. i. (1). (a).`. So III and III.A.

I will fix the Presentation XML to reflect this ordering.

**Comment by Intelligent2013** [comment]
No need to change OGC xslt. PDF displays ok:

![изображение](https://user-images.githubusercontent.com/5559926/95567402-91262600-0a2b-11eb-95bb-796f50ff03ca.png)
