### ISSUE TITLE
Update document stage notation on cover page: PDF

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-ogc#190]
Follow-on from https://github.com/metanorma/metanorma-ogc/issues/187 : read the display value for stage names from //local_bibdata/status/stage instead of //bibdata/status/stage

**Comment by opoudjis** [comment]
Attaching Presentation XML sample:

[a.presentation.xml.zip](https://github.com/metanorma/metanorma-ogc/files/5292246/a.presentation.xml.zip)

**Comment by Intelligent2013** [comment]
Done.
