### ISSUE TITLE
PDF: Add "Security considerations" section as 4th mandatory preface section

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-ogc#193]
Follow-on from #188:

Prefaces will now include a `<clause type="security">` before `<clause type="submitting_orgs">`. Please ensure it is included in output. Attaching sample doc.

[document.presentation.xml.zip](https://github.com/metanorma/metanorma-ogc/files/5293212/document.presentation.xml.zip)

**Comment by Intelligent2013** [comment]
Done.
