### ISSUE TITLE
Situation with "Foreword" and "Introduction" prefatory sections

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-ogc#194]
In [10-091r3](https://portal.ogc.org/files/?artifact_id=43733), *Foreword* and *Introduction* sections were typeset as follow:

````
[.preface]
== Foreword
_Attention is drawn...

[.preface]
== Introduction
The CF-netCDF standard defines...
````

Which results in (doc output):

![Capture](https://user-images.githubusercontent.com/33627611/94886928-ed44e500-0442-11eb-8136-aab575c15d39.PNG)

However, this rendering differs from [original layout](https://portal.ogc.org/files/?artifact_id=43733).
In original source, these prefatory sections don't follow the numbering order of their predecessors (they are unnumbered), and they take one whole page each.

**Comment by opoudjis** [comment]
This is an issue about how to deal with legacy preface sections in general, since this contradicts the mandatory preface ordering given in https://github.com/metanorma/metanorma-ogc/issues/188

Requires clear guidance from OGC: questions posed in that ticket need answer.

**Comment by ronaldtse** [comment]
@ogcscotts @ghobona @gbuehler can we confirm that this layout is acceptable? Since we now have implemented the latest approved document model, legacy documents will see their Foreword and Introductions moved into the numbered Preface. Thanks!

**Comment by ronaldtse** [comment]
Ping @ogcscotts @ghobona @gbeuhler for confirmation. Thanks!

**Comment by ronaldtse** [comment]
Ping @ogcscotts @ghobona @gbuehler:

Is it acceptable for the layout to use the new "fixed" preface structure for legacy documents?

e.g. in this particular example 10-091r3, the original "Foreword" and "Introduction" were unnumbered, but in the new structure all preface sections are numbered (and fixed to the newly-mandated order).

Thanks!

**Comment by ghobona** [comment]
@ronaldtse  It is acceptable to use the new fixed structure for legacy documents.

**Comment by ronaldtse** [comment]
Thank you @ghobona ! In this case let's close this task.
