### ISSUE TITLE
Rename stage code "published" to "approved" to match with OGC terminology

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-ogc#198]
Follow-on from https://github.com/metanorma/metanorma-ogc/issues/196

//bibdata/status/stage == "published" has been replaced with "approved"

**Comment by Intelligent2013** [comment]
No need to change OGC xslt, there isn't any processing for  //bibdata/status/stage.
Stage displays only from local_bibdata/status/stage just a text.
