### ISSUE TITLE
OGC: Bibliography anchor labels are mistakenly shown in the HTML

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#207]
From @ghobona (opengeospatial/ogc-metanorma-testing#35)

> The Bibliography of the [GroundwaterML](https://github.com/opengeospatial/ogc-metanorma-testing/tree/master/19-013) document is showing the anchor labels. They should not be showing.
> 
> This appears to affect the HTML version only.
> 
> See the text underlined in red on the attached image.
> 
> ![Screenshot 2020-10-26 at 08 19 49](https://user-images.githubusercontent.com/18121038/97149477-b40f4480-1764-11eb-8917-43c0b5cb2299.png)

**Comment by opoudjis** [comment]
Default behaviour in Metanorma bibliographies is to add document identifiers, where supplied, after the bibliography ordinal. The expectation is that you would code a reference like 

`American Nuclear Society, 1980. American national standard for evaluation of radionuclide transport in groundwater for nuclear power sites. ANSI/ANS-2.17-1980, American Nuclear Society, La Grange Park, Illinois.`

with the anchor

`* [[[ANS1980,1]]], `

And if you code it with

`* [[[ANS1980,ANS, 1980]]], `

that you _actually expect to see the `ANS, 1980` in the reference_.

I don't see why OGC would choose to put an identifier in the bibliography and then hide it, and I am concerned that OGC a month later will come back with "oh, we want to see the identifier under conditions X, Y, Z". But for now, with some trepidation, I am removing the document identifier for bibliography entries not overtly associated with SDOs.

**Comment by ronaldtse** [comment]
I believe the fix in 440cd4f will do this:

```adoc
* [[[ANS1980,1]]], American Nuclear Society, 1980. American national standard for evaluation of radionuclide transport in groundwater for nuclear power sites. ANSI/ANS-2.17-1980, American Nuclear Society, La Grange Park, Illinois.
```

=> Correct.

```adoc
* [[[ANS1980,ANS, 1980]]], American Nuclear Society, 1980. American national standard for evaluation of radionuclide transport in groundwater for nuclear power sites. ANSI/ANS-2.17-1980, American Nuclear Society, La Grange Park, Illinois.
```

=> Identical output. The "ANS, 1980" will be ignored because OGC only accepts numeric reference tags.

@opoudjis can you confirm this?

**Comment by opoudjis** [comment]
Yes

**Comment by ronaldtse** [comment]
Thanks @opoudjis !
