### ISSUE TITLE
Add font dependencies for OGC

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#212]
OGC needs a section like this:

https://github.com/metanorma/metanorma-iso/blob/55568ddec7defdefc8126495296e9b4cd04d2b3c/lib/metanorma/iso/processor.rb#L5-L12

OGC uses:
* Lato
* Arial

**Comment by opoudjis** [comment]
OGC uses those **IN PDF**. In HTML and Doc, it uses different fonts.
