### ISSUE TITLE
Security considerations statement should be generic across document types ("this document" instead of "this standard")

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-ogc#222]
The default statement "No security considerations have been made for this standard."

Should be modified for non-standards (e.g. Best Practice, Discussion Paper etc).

I have just created a Discussion Paper. The default statement still said "No security considerations have been made for this standard."

So I had to manually change it to "No security considerations have been made for this document."

**Comment by ronaldtse** [comment]
@ghobona thanks for raising this issue! @opoudjis could you help handle this? Thanks.
