### ISSUE TITLE
highlight, underline, and strikethrough do not work

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-ogc#225]
The normal asciidoc approach for **highlight, underline, and strikethrough** does not appear to work on neither HTML nor PDF (i.e. Example 7 of https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/ ).

**Comment by ghobona** [comment]
Cc: @cnreediii

**Comment by ronaldtse** [comment]
Strikethrough and underline syntaxes in Metanorma AsciiDoc are described here:
https://www.metanorma.com/author/topics/document-format/text/

<img width="806" alt="Screenshot 2021-02-12 at 3 59 01 PM" src="https://user-images.githubusercontent.com/11865/107743101-3ee37180-6d4b-11eb-8c8e-93adca071e2b.png">

Metanorma AsciiDoc does not support highlighting.

@ghobona is "highlight" something that OGC wishes to be supported?

**Comment by ghobona** [comment]
@ronaldtse Yes, please.

**Comment by ronaldtse** [comment]
@ghobona in this case let me make a new ticket that is only about "highlight". Thanks!
