### ISSUE TITLE
Implement "highlight" text formatting macro

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#226]
From @ghobona:

The "highlight" text formatting is described in Example 7 of the [AsciiDoctor syntax reference](https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference).

We should implement the "highlight" feature after these questions are answered:
- One type of highlight or is this multiple? Is the color always yellow? Or does the highlight color depend on the flavor?
- How is it represented in MN XML?

cc: @cnreediii

_Originally posted by @ghobona in https://github.com/metanorma/metanorma-ogc/issues/225#issuecomment-778029695_

**Comment by cnreediii** [comment]
Thanks for the discussion. For what I need to do - high light deprecated elements: So one color, such as yellow (warning) works for that use case.

**Comment by ghobona** [comment]
@ronaldtse 

Regarding color,  yellow highlighting would be fine. The color provides sufficient contrast with the light-blue pages and navy blue text to meet web accessibility guidelines.

**Comment by ronaldtse** [comment]
Thanks for the information. We can certainly implement something like `[highlight]#foobar#` as basic text formatting.

However, the use case here seems to be encoding "diffs"?

If so, I'm wondering if this relates to [machine-readable changes](https://www.metanorma.com/author/topics/document-format/changes/).

There are two ways I imagine this can work:
* Given two Metanorma documents, create a third document that is a red-lined version (with highlights, strikethroughs).
* Given one Metanorma document, manually encode "add", "modify" "delete" in text.

What's the particular scenario here?

**Comment by opoudjis** [comment]
Implementing with generic Asciidoc highlighting, `#mark#`. Machine readable changes and the `add`, `delete` macros of Metanorma ITU should be used, but I'm adding this as functionality anyway.

**Comment by ronaldtse** [comment]
@opoudjis 
> Machine readable changes and the add, delete macros of Metanorma ITU should be used, but I'm adding this as functionality anyway

Where is this documented?

**Comment by ronaldtse** [comment]
@opoudjis do you mean the `add` and `del` macros: https://www.metanorma.com/author/itu/topics/markup/#corrigenda ?

**Comment by opoudjis** [comment]
Yes, that is what I meant.

**Comment by ronaldtse** [comment]
Cool, lets go for it

**Comment by opoudjis** [comment]
Closing, since we are in fact generalising add and del in a separate ticket.
