### ISSUE TITLE
Link in OGC Copyright link needs updated

### ISSUE THREAD

**Issue by gbuehler** [metanorma/metanorma-ogc#227]
In lib/asciidoctor/ogc/boilerplate.xml
The current 

        <link target="http://www.opengeospatial.org/legal/">http://www.opengeospatial.org/legal/</link></p>

Needs to change to:

        <link target="http://www.ogc.org/legal/">http://www.ogc.org/legal/</link></p>

**Comment by ronaldtse** [comment]
Thanks @gbuehler !
