### ISSUE TITLE
Implement <hi> for PDF

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-ogc#229]
Follow-on from https://github.com/metanorma/metanorma-ogc/issues/226

I have introduced the new element `<hi>` for OGC Metanorma, which indicates highlighted text (yellow background).

**Comment by ronaldtse** [comment]
Are we going to get a `<hello>` soon? 😉

**Comment by Intelligent2013** [comment]
Done.
Example:
![изображение](https://user-images.githubusercontent.com/5559926/110004901-fa833a00-7d28-11eb-92bb-271e17d3c496.png)

**Comment by opoudjis** [comment]
> Are we going to get a `<hello>` soon? 😉

I'm waiting for `<blink>`, myself :-P
