### ISSUE TITLE
OGC 20-010 contains a term with two definitions

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#232]
<img width="952" alt="image" src="https://user-images.githubusercontent.com/11865/116073002-67300a80-a6c2-11eb-9c33-77570d8d7d7c.png">

Each with a different SOURCE.

We will need a way to do this.

**Comment by skalee** [comment]
I wonder if notes/examples, if present, should apply to specific definitions or to localized concept as whole.

**Comment by ronaldtse** [comment]
Notes and Examples can apply to a specific definition or the localized concept as a whole.

**Comment by opoudjis** [comment]
This has been resolved. The markup shall be:

````
=== conceptual schema

[.definition]
--
formal description of a {{conceptual model}}

[.source]
<<iso19101-1,clause=4.1.6>>
--

[.definition]
--
base schema. Formal description of the model of any geospatial information. term:[application schema,Application schemas] are built from conceptual schemas.

[.source]
<<OGCDR>>, http://www.opengis.net/def/glossary/term/ConceptualSchema
--
````
