### ISSUE TITLE
Numeric references in normative references causes crash

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#234]
The problem is in document 16-114r3.

In this document, normative references are marked up as numeric references. Since the Metanorma OGC validation rules do not support this, it crashes the whole process.

From @opoudjis:
> We now have a rigid rule, enforced because of problems with ISO, that entries in normative reference sections cannot have a numeric identifier; that is because consecutive numbering of normative and informative bibliographies (e.g. the normative ends with reference 3, the informative resumes with reference 4) was confusing, and was rejected by ISO. Because of the risk of confusion, I have ended up crashing on such input, rejecting it as illegal.
> 
> If numbers are to be accepted in normative bibliographies for a flavour, I am requiring explicit override and approval from the standards organisation, because of the risk of confusion that interrupted numbering leads to. I can revert the behaviour per-flavour, but I will not do so without signoff.
> 
> So this becomes a question for OGC: do they required numbered references for normative reference sections, and if they do, can the numbering be continuous between normative and informative references?

The question is whether OGC normative references will accept numeric references and how the mechanism will work, because numeric references will inevitably mix numbering across normative and informative references, while not confusing the reader.

I can see three options:
1. Do not accept numbered normative references, just like ISO.
2. Allow numbered normative references, but number them separately from the informative references, and differentiate them with informative references using some prefix, e.g. "[N1]" instead of just "[1]".
3. Treat the numbered normative references just like informative references, so they share the same numbering namespaces. But this risks the reader confusing these references.

Could we have your advice please @ogcscotts @ghobona @gbuehler ?

Full log:
```
Document Attributes: '' is not a permitted subtype of Standard: reverting to 'implementation'
[info]: Compiling /__w/mn-samples-ogc/mn-samples-ogc/sources/16-114r3/document.adoc ...
[relaton-ogc] ("OGC 14-083r2") fetching...
[relaton-ogc] ("OGC 14-083r2") found 14-083r2
[relaton-ogc] ("OGC 14-084r2") fetching...
[relaton-ogc] ("OGC 14-084r2") found 14-084r2
[relaton-ogc] WARNING: invalid document subtype: extesion
[relaton-ogc] ("OGC 11-165r2") fetching...
[relaton-ogc] ("OGC 11-165r2") found 11-165r2
[relaton-iso] ("ISO 19141") fetching...
[relaton-iso] ("ISO 19141") found ISO 19141:2008
AsciiDoc Input: (Section: Dataset): term reference not in expected format: <xref target="iso19101" type="inline"/>.
AsciiDoc Input: (Section: Attribute): term reference not in expected format: <xref target="ogc10-090r3" type="inline"/>.
Metanorma XML Style Warning: (XML Line 000305): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 000323): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 000324): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 000373): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 000510): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 000552): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 000601): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 000930): Figure should have title
Metanorma XML Style Warning: (XML Line 000088): Table should have title
Metanorma XML Style Warning: (XML Line 000307): Table should have title
Metanorma XML Style Warning: (XML Line 000326): Table should have title
Metanorma XML Style Warning: (XML Line 000342): Table should have title
Metanorma XML Style Warning: (XML Line 000358): Table should have title
Metanorma XML Style Warning: (XML Line 000375): Table should have title
Metanorma XML Style Warning: (XML Line 000420): Table should have title
Metanorma XML Style Warning: (XML Line 000437): Table should have title
Metanorma XML Style Warning: (XML Line 000453): Table should have title
Metanorma XML Style Warning: (XML Line 000471): Table should have title
Metanorma XML Style Warning: (XML Line 000526): Table should have title
Metanorma XML Style Warning: (XML Line 000554): Table should have title
Metanorma XML Style Warning: (XML Line 000570): Table should have title
Metanorma XML Style Warning: (XML Line 000586): Table should have title
Metanorma XML Style Warning: (XML Line 000618): Table should have title
Metanorma XML Style Warning: (XML Line 000653): Table should have title
Metanorma XML Style Warning: (XML Line 000717): Table should have title
Metanorma XML Style Warning: (XML Line 000745): Table should have title
Metanorma XML Style Warning: (XML Line 000809): Table should have title
Metanorma XML Style Warning: (XML Line 000875): Table should have title
Metanorma XML Style Warning: (XML Line 000891): Table should have title
Metanorma XML Style Warning: (XML Line 000906): Table should have title
Metanorma XML Style Warning: (XML Line 000934): Table should have title
Metanorma XML Style Warning: (XML Line 001005): Table should have title
Bibliography: (XML Line 000126): Numeric reference in normative references
Bibliography: (XML Line 000126): Numeric reference in normative references
Bibliography: (XML Line 000126): Numeric reference in normative references
Numeric reference in normative references
##[error]Process completed with exit code 1.
Post job cleanup.
```

I will open this as a new issue on metanorma-ogc.

_Originally posted by @ronaldtse in https://github.com/metanorma/mn-samples-ogc/issues/119#issuecomment-850923140_

**Comment by ronaldtse** [comment]
Actually this is a markup error by @metanorma/editors . The normative references in this document are NOT NUMBERED, so the fix is purely a document issue.

<img width="957" alt="image" src="https://user-images.githubusercontent.com/11865/120089007-f51b6d00-c128-11eb-9e88-6f0041026898.png">

In any case though, from OGC, we would like to have confirmation that normative references are not numbered. Thanks!

**Comment by ronaldtse** [comment]
If OGC does not allow numeric references in normative references, the generated XML not contain numeric references in normative references and therefore should not crash even if marked up as such. (for @opoudjis )

**Comment by ronaldtse** [comment]
Ping @ogcscotts @gbuehler @ghobona regarding labels for references. Are numeric references allowed? 

Three options available:

1. Do not accept numbered normative references, just like ISO.
2. Allow numbered normative references, but number them separately from the informative references, and differentiate them with informative references using some prefix, e.g. "[N1]" instead of just "[1]".
3. Treat the numbered normative references just like informative references, so they share the same numbering namespaces. But this risks the reader confusing these references.

**Comment by ogcscotts** [comment]
Historically, we have not had numbered normative references. I would prefer to keep this pattern. It makes compatibility with ISO easier and makes it easier for the reader to follow the external reference.

**Comment by ronaldtse** [comment]
Thank you @ogcscotts! So we'll go with option 1 -- no numbered normative references allowed, just like ISO.

@opoudjis is there anything else we need to do here? If not please close this. Thanks.

**Comment by opoudjis** [comment]
Nothing further, closing. The abort execution was in fact implemented for ISO explicitly, to block further parsing—because of the acute risk of confusion that markup introduces: https://github.com/metanorma/metanorma-iso/issues/470. I do not agree that the document should parse regardless: the document will have been structured around numeric cross-references, and they should not just be silently ignored.
