### ISSUE TITLE
Duplicated "Terms and definitions" clause

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#236]
<img width="580" alt="image" src="https://user-images.githubusercontent.com/11865/126142348-d8add49d-c18d-43ce-a334-16b129398569.png">

```adoc

== Terms, definitions and abbreviated terms

=== Terms and definitions

==== conceptual model
alt:[CM]

data model at the conceptual level
```

**Comment by opoudjis** [comment]
Cannot duplicate, see attached.

[a2.zip](https://github.com/metanorma/metanorma-ogc/files/6842173/a2.zip)

**Comment by ronaldtse** [comment]
Confirmed. There must be something funny happening earlier.
