### ISSUE TITLE
Change the term 'Requirement Class' to 'Requirements Class'

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-ogc#238]
To make the template consistent with the [OGC Standard for Modular Specifications](https://www.ogc.org/standards/modularspec) (Mod Spec), please change the term '**Requirement Class**' to '**Requirements Class**'.

This would also make the terminology consistent with ISO 19105.

**Comment by ronaldtse** [comment]
Thanks @ghobona for the report!
