### ISSUE TITLE
Possibility of using WorldWeatherSymbols in Metanorma

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#24]
@chris-little at the Met Office raised the issue of using https://github.com/OGCMetOceanDWG/WorldWeatherSymbols in Metanorma documents during the OGC DocTeam session.

It was said that we can either refer to a Unicode private plane (if a font supporting these symbols is included, such as from https://github.com/Unidata/MetPy), or we support their symbols.

I wonder if there is an easy way of supporting new symbols/icons.

Thoughts @opoudjis ?

**Comment by chris-little** [comment]
Ron,
The correct Unicode terminology is the 'Private Usea Area', preferably in the Basic Multilingual Plane. Not many apps support the full multiplane Unicode as described in ISO10646.
The six thousand or so codes points of the PUA in the Basic Multilingual Plane are (U+E000 to U+F8FF) and are more than enough for all the interntionally standardised WMO and ICAO weather symbols.
The other two PUAs are 64K in size each. HTH, Chris

**Comment by opoudjis** [comment]
I'm not delighted about using the PUA, because that really presupposes that all recipients of the document are using the self-same font. But even PUA characters are cleaner than icons (and in fact, fonts like FontAwesome increasingly realise icons as Unicode characters anyway).

So, yes, we can support PUA fonts readily; but (a) we would have to enforce use of the corresponding font in OGC Metanorma output, and (b) we would have to make sure that Word and PDF do not balk at any Astral Plane characters (over U+10000). @chris-little is proposing to use Plane 0, so there should be no issue there.

All that said: it may well be desirable to limit the custom font to just those icons and not to enforce them throughout the document. That would most readily be done in postprocessing: detect all instances of the PUA characters, and wrap them in a CSS style enforcing the use of the particular font for just those character spans.

**Comment by opoudjis** [comment]
@ronaldtse Is there an action here? If the ticket is assigned to me, it does need to have a priority.

**Comment by ronaldtse** [comment]
It's certainly possible to implement support for a private code point for a particular gem, but the solution would be allowing to address a codepoint in a particular "genre" of font.

Currently we don't seem to have commitment in using these weather symbols, so let's postpone it for now (feel free to correct if I'm wrong @chris-little 😉 ).

**Comment by chris-little** [comment]
@ronaldtse I have no problem with that. Private Use Areas are undoubtedly not a success of Unicode!

**Comment by opoudjis** [comment]
@chris-little is there any change in the commitment to using the weather symbols?

**Comment by chris-little** [comment]
@opoudjis No wew still think it a good idea to get the WMO/ICAO standardised weather symbols into Unicode to make them much more readily useable, rather than having to invoke computer graphics packages. It also fits with the strategy that eventually weather specific applications will be replaced by generic GIS applications, perhaps with a 'weather style sheet', and then perhaps generic GIS apps being replaced by position-aware Web browsers.
Apologies for not having had any spare time to push this recently.

**Comment by ronaldtse** [comment]
For the record the MetPy font for these symbols is here: https://github.com/Unidata/MetPy/tree/cee9d4de5bc37a4cd2efc381f0a08f3a53d00940/metpy/plots/fonts

To use these symbols we will need to have a textual way of referring to a particular character code of a particular font (the MetPy font here).

e.g.
```adoc
sym:[wws,icao:SevereTurbulence]
```

To show https://github.com/OGCMetOceanDWG/WorldWeatherSymbols/blob/master/symbols/ICAO_SigWx/WeatherSymbol_ICAO_SevereTurbulence.svg.

Or if there is a URN for the symbols we can have something like:
```adoc
sym:[wws,urn:ogc:symbols:wws:icao-severe-turbulence]
```

**Comment by ronaldtse** [comment]
A hark back to the past: with the implementation of https://github.com/metanorma/metanorma-standoc/issues/618 , we are now able to handle custom fonts (as long as the font is supported in Fontist). We can technically use the MetPy symbols (https://github.com/Unidata/MetPy/blob/cee9d4de5bc37a4cd2efc381f0a08f3a53d00940/metpy/plots/fonts/wx_symbols.ttf) in Metanorma.

The challenge is that the MetPy font makes heavy use of the Unicode Private Use Area, so that the user needs to know the Unicode code point of the character to use it in Metanorma:

<img width="1276" alt="Screenshot 2022-04-27 at 11 49 42 AM" src="https://user-images.githubusercontent.com/11865/165436159-8b28b575-4b94-4fc5-854d-408241765e4e.png">

Now, this has gotten me thinking that perhaps we should support "Symbol Libraries", which are actually not so different from reusing Terms/Concepts from Termbases:

- IEC provides a symbol library, e.g. https://symbols.demo.paneron.org/symbols/
- IEC Electropedia contains entries that have symbols (or international symbols)

If we treat Symbols as generic concepts, and that we have a way to import/refer to concept libraries, then this will be extremely useful.

**Comment by opoudjis** [comment]
And we can specify arbitrary fonts on text spans:

https://www.metanorma.org/author/topics/document-format/text/#css-declarations

````
[css font-family:"Noto Sans Canadian Aboriginal"]#ᓀᐦᐃᔭᐍᐏᐣ#
````

@ronaldtse what remains to be actioned here?

**Comment by ronaldtse** [comment]
`[css font-family...]` does not apply to PDF output.

**Comment by opoudjis** [comment]
> `[css font-family...]` does not apply to PDF and Word output...

I was wrong, the CSS does travel through to the Word, and there is no intrinsic reason why it cannot be parsed in the PDF.

**Comment by Intelligent2013** [comment]
As I note in https://github.com/metanorma/pdfa-iso-32000-2/issues/11#issuecomment-1688240475, we need to specify the font name `Noto Sans Canadian Aboriginal` in the document attribute `:fonts:` additionally, for the installation by `fontist` (but `fontist`(or metanorma) doesn't pass the font name for the manifest generation).

**Comment by ghobona** [comment]
OGC Staff briefed on 2023-09-04.

**Comment by ronaldtse** [comment]
> I was wrong, the CSS does travel through to the Word, and there is no intrinsic reason why it cannot be parsed in the PDF.

PDF processing should never be parsing CSS. The solution is at:
* https://github.com/metanorma/metanorma/issues/339

**Comment by opoudjis** [comment]
The Semantic XML solution is in place. @Intelligent2013 can I confirm that you still cope with `<span style="font-family:&quot;Code 2000&quot;">`? If so, any code change in Presentation XML to deal with inline styling in a more granular way can be deferred, and this ticket can be closed.

**Comment by Intelligent2013** [comment]
> @Intelligent2013 can I confirm that you still cope with `<span style="font-family:&quot;Code 2000&quot;">`?

@opoudjis yes. But, please note, that we need to specify `:fonts: Code 2000` in the `document.adoc` additionally, and there is the non-resolved issue https://github.com/metanorma/metanorma/issues/311 regarding passing `:fonts:` list into fontist manifest.

**Comment by opoudjis** [comment]
Ok. Since those are pre-existing issues, closing this issue. I've mentioned in documentation the need for :fonts:

**Comment by ronaldtse** [comment]
@Intelligent2013 how come the don’t is called “Code 2000”?

**Comment by opoudjis** [comment]
It is an example of a font that implements Klingon in the PUA.
