### ISSUE TITLE
No numbering of tables generated via Requirements/Conformance classes

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#240]
Currently in OGC documents, Requirements/Conformance classes rendered as tables are assigned table numbers, e.g. `Table A.2`. Given that Requirement objects are already numbered like `Requirement A.2`, it is not necessary to provide an additional Table handle.

In OGC documents, Requirements/Conformance classes etc. rendered as tables should not have table numbers. It should allow a `[%numbered]` override.

In ISO documents, table numbers are required, so we can use the `[%unnumbered]` override which is already implemented.

**Comment by manuel489** [comment]
@opoudjis, the issue seems to be solved already. (I can't reproduce it.)

**Comment by ronaldtse** [comment]
Thanks!
