### ISSUE TITLE
Requirement component part class not working correctly

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-ogc#243]
*In relation to https://github.com/metanorma/metanorma-ogc/issues/242 and https://github.com/metanorma/ogcapi-processes/issues/1*

Requirement Component block is being ignored.

Markup sample:
````
[[per_core_limit-default-minimum-maximum]]
[.permission,label="/per/core/limit-default-minimum-maximum"]
====
[.component,class=part]
---
The values for `minimum`, `maximum` and `default` in requirement `/req/core/limit-definition` are only examples and MAY be changed.
---
====
````

Output:
![cap2](https://user-images.githubusercontent.com/33627611/129819909-e90fa7eb-81e8-44b7-80be-99f08f664b1d.PNG)

**Comment by manuel489** [comment]
In addition, in regard to Conformance Classes, there are cases where the order of the field is not what expected.

For example:
````
[[ats_html]]
[requirement,type="conformanceclass",label="http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/dismiss",
subject='<<rc_core,Requirements Class "Core">>',
inherit='<<ats_core,Conformance Class "Core">>',classification="Target Type:Web API"]
====
====
````

renders:
![cap3](https://user-images.githubusercontent.com/33627611/129820961-76e65e4e-f27c-4fa7-8040-d479c59aa107.PNG)


Note that *Target Type* field resulted in the last row.
This is a little different to original source:

````
[[ats_html]]
[cols="1,4",width="90%"]
|===
2+|*Conformance Class*
2+|http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/html
|Target type |Web API
|Requirements class |<<rc_html,Requirements Class "HTML">>
|Dependency |<<ats_core,Conformance Class 'Core'>>
|===
````
Not sure if it's relevant though.

**Comment by manuel489** [comment]
Another issue occurs when single quotes are used inside inherit field:
````
[[ats_oas30]]
[requirement,type="conformanceclass",
label="http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/oas30",
subject='<<rc_oas30,Requirements Class "OpenAPI Specification 3.0">>',
inherit="<<ats_core,Conformance Class 'Core'>>",
classification="Target Type:Web API"]
====
====
````

I get a malformed string:
![cap4](https://user-images.githubusercontent.com/33627611/129821963-e3502312-5337-40b7-92a3-7f41747d709e.PNG)

If I change the `inherit` to: `inherit='<<ats_core,Conformance Class "Core">>'`
the problem gets solved.

**Comment by opoudjis** [comment]
> [[per_core_limit-default-minimum-maximum]]
> [.permission,label="/per/core/limit-default-minimum-maximum"]
> ====
> [.component,class=part]
> ---
> The values for `minimum`, `maximum` and `default` in requirement `/req/core/limit-definition` are only examples and MAY be changed.
> ---
> ====

Error in my sample markup: An open block must be notated with `--`, not `---`. `---` is only used if embedded inside a `--`-delimited block. Replace all instances of `---` with `--`.

**Comment by opoudjis** [comment]
> In addition, in regard to Conformance Classes, there are cases where the order of the field is not what expected.
> 
> For example:
> 
> ```
> [[ats_html]]
> [requirement,type="conformanceclass",label="http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/dismiss",
> subject='<<rc_core,Requirements Class "Core">>',
> inherit='<<ats_core,Conformance Class "Core">>',classification="Target Type:Web API"]
> ====
> ====
> ```
> 
> renders:
> ![cap3](https://user-images.githubusercontent.com/33627611/129820961-76e65e4e-f27c-4fa7-8040-d479c59aa107.PNG)
> 
> Note that _Target Type_ field resulted in the last row.
> This is a little different to original source:
> 
> ```
> [[ats_html]]
> [cols="1,4",width="90%"]
> |===
> 2+|*Conformance Class*
> 2+|http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/html
> |Target type |Web API
> |Requirements class |<<rc_html,Requirements Class "HTML">>
> |Dependency |<<ats_core,Conformance Class 'Core'>>
> |===
> ```
> 
> Not sure if it's relevant though.

The metadata fields are being extracted in a fixed order, since I'm building the table out of source XML. I think we can treat that as a feature, not a bug:

* Obligation
* Subject (inc. Requirements class)
* Dependency
* Components other than Part
* Part Components
* Classifications
* Everything else (including nested requirements)

**Comment by opoudjis** [comment]
> Another issue occurs when single quotes are used inside inherit field:
> 
> ```
> [[ats_oas30]]
> [requirement,type="conformanceclass",
> label="http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/oas30",
> subject='<<rc_oas30,Requirements Class "OpenAPI Specification 3.0">>',
> inherit="<<ats_core,Conformance Class 'Core'>>",
> classification="Target Type:Web API"]
> ====
> ====
> ```
> 
> I get a malformed string:
> ![cap4](https://user-images.githubusercontent.com/33627611/129821963-e3502312-5337-40b7-92a3-7f41747d709e.PNG)
> 
> If I change the `inherit` to: `inherit='<<ats_core,Conformance Class "Core">>'`
> the problem gets solved.

Quotes are going to cause mischief within attributes at the best of times. I suggest you start using the metadata definition list workaround, it will be much more readable and less fragile:

````
[[ats_oas30]]
[requirement,type="conformanceclass",
label="http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/oas30",
subject='<<rc_oas30,Requirements Class "OpenAPI Specification 3.0">>',
inherit="<<ats_core,Conformance Class 'Core'>>",
classification="Target Type:Web API"]
====
====
````

I'd forgotten to check this functionality in with release; doing hotfix now.
