### ISSUE TITLE
"Submitters" table should not be numbered by default

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#246]
<img width="1256" alt="Screenshot 2021-08-24 at 10 16 07 AM" src="https://user-images.githubusercontent.com/11865/130545144-8ab33f7d-cc6a-480e-b2a6-d13b9d4d44e8.png">

**Comment by ronaldtse** [comment]
Not working with latest metanorma-ogc:

<img width="770" alt="image" src="https://user-images.githubusercontent.com/11865/132436038-330cd0f6-abc8-4d94-9268-f5c9b6d8dafa.png">

```adoc
== Submitters

|===
|Name |Affiliation

|Emmanuel Devys |Institut national de l'information géographique et forestière (IGN), France
|Volker Coors |HFT Stuttgart, Germany
```

**Comment by opoudjis** [comment]
Slippage between branches, adding back into fix/reqt-dl-attrs branch
