### ISSUE TITLE
Vertical alignment in table cells: always center?

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#250]
In OGC documents, vertical alignment in tables is set to the top by default instead of to center:

Generated PDF:
![image](https://user-images.githubusercontent.com/11865/130754282-7ed5caf4-bf7d-4b88-ae9a-a7a833e7d737.png)

From design:
![image](https://user-images.githubusercontent.com/11865/130754306-54c2d03e-851f-41b6-a1c9-dd9fe3c40588.png)

From https://github.com/metanorma/mn-native-pdf/issues/308.

Can we have an OGC opinion on whether table headers/cells are always vertically aligned at centre?

Ping @ogcscotts @gbuehler @ghobona

**Comment by ogcscotts** [comment]
@ronaldtse Centered looks better to me.

**Comment by ronaldtse** [comment]
Thanks @ogcscotts . @opoudjis @Intelligent2013 so we will always enforce vertically centred table cells in OGC presentation.

**Comment by opoudjis** [comment]
The valign value, in turn, is being inherited from asciidoc, which defaults it to top; we have no straightforward way of determining whether the user has set valign to top explicitly, or has just left it unspecified:

https://github.com/asciidoctor/asciidoctor/blob/ff559f8dcb69642053ab5425d40a57ade197a836/lib/asciidoctor/table.rb#L190

FWIW, ITU have decided to have valign = top: https://github.com/metanorma/metanorma-itu/issues/85

So the only way to implement this, short of reparsing the raw Asciidoctor (which we want to avoid), is to impose middle valign as a universal requirement in OGC, and always ignore any attempt to set valign manually to top. I'm going to need confirmation on that.

**Comment by ronaldtse** [comment]
> impose middle valign as a universal requirement in OGC

Confirmed.
