### ISSUE TITLE
OGC documents will mostly follow ISO rules on "Terms and definitions"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#251]
In the OGC Testbed 17 meeting on MBS it was confirmed with @gbuehler that OGC documents should mostly follow current ISO practice on "Terms and definitions", namely:

* The "Terms and definitions" clause will be called exactly that, with the clause title in sentence case (only first letter of first word capitalised)
* "Abbreviated terms", "Symbols" clauses will be folded into "Terms and definitions" as subclauses, and the parent clause should have the following structure:
  * "Terms, definitions and abbreviated terms" will contain T&D and "Abbreviated terms" subclauses.
  * "Terms, definitions and symbols" will contain T&D and "Symbols" subclauses.
  * "Terms, definitions, symbols and abbreviated terms" will contain T&D, "Symbols" and "Abbreviated terms" subclauses.
* There will be a "Glossary" for informative terms used in the document, which will only contain terms and definitions (no abbreviations or symbols subclauses), and presented as an Appendix.

This ticket is to document this practice.

**Comment by manuel489** [comment]
Updates added in https://github.com/metanorma/metanorma.org/pull/506
