### ISSUE TITLE
OGC API 18-062: Generating alternative designation

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-ogc#256]
Subsection which addresses terms REST and RESTful (alternative) appears to have two titles - "REST" and "RESTful", with a line break in between.

Old:
![image](https://user-images.githubusercontent.com/55683568/130701981-f4343807-4715-4950-8d64-558a775d8b2b.png)

New:
![image](https://user-images.githubusercontent.com/55683568/130701976-7277d473-6ded-476a-a13b-cdd70bbbc7d4.png)

We should have some styling that makes an alternative designation visible like in PDF. (https://github.com/metanorma/ogcapi-processes/issues/14#issuecomment-905764935)
<img width="750" alt="Screenshot 2021-08-26 at 2 15 17 AM" src="https://user-images.githubusercontent.com/11865/130843883-729a5e82-1103-4cb8-8b6b-c0c0c04a6212.png">

**Comment by opoudjis** [comment]
Well, I have just introduced a notion of alternative title for sections, to be used in ToC: https://www.metanorma.org/author/topics/document-format/xrefs/#variant-titles . I'll proceed to expand that to subtitles. So:

````
=== REST

[.variant-title,type=sub]
RESTful
````

I'm going to render these by default in HTML with a line break. @Intelligent2013, if there are going to be  alternative designation requirements for you, that's going to be have to be a separate ticket. The XML rendering is going to be `<variant-title type="sub">...</variant-title>`.

**Comment by ronaldtse** [comment]
@opoudjis just a reminder that there can be multiple `alt:[]` terms. An alternative term is different from a `variant-title`.

**Comment by opoudjis** [comment]
Oh. I didn't understand that at all. Sigh.

OK, reopening.

**Comment by opoudjis** [comment]
OK, so... how is this not addressed by the existing markup?

````
==== REST
alt:[RESTful]

Representational state transfer.  REST-compliant Web services allow requesting systems to access and manipulate textual representations of Web resources using a uniform and predefined set of stateless operations.
````

That generates, correctly, the following Presentation XML:

````
<term id="term-rest"><name>2.1.1.</name><preferred>REST</preferred>
<admitted>RESTful</admitted>

<definition><p id="_4c6dd419-bdc9-47ea-822b-41ef9a01115c">Representational state transfer.  REST-compliant Web services allow requesting systems to access and manipulate textual representations of Web resources using a uniform and predefined set of stateless operations.</p></definition></term>
````

How the admitted term is then rendered is up to the renderer; there is no reason at all why it can't be rendered with an "admitted" tag, as is done elsewhere. What am I missing?

**Comment by opoudjis** [comment]
I didn't understand: request is to render alt terms in HTML the same as in PDF, inline.

**Comment by ronaldtse** [comment]
Ah, right indeed. The request is to render in HTML an alt term like in PDF such that it differentiates term designation status. Thanks!
