### ISSUE TITLE
`community-practice` doctype not working on docker

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#257]
From @ghobona on https://github.com/metanorma/metanorma-docker/issues/103:

`community-practice` is supposed to be a valid doctype on the OGC Metanorma template, according to https://www.metanorma.org/author/ogc/authoring/

However, when I run this command

`docker run -v "$(pwd)":/metanorma metanorma/mn  metanorma new -d community-practice -t ogc  -l https://github.com/metanorma/mn-templates-ogc folder_for_community_practice`

I get the following error message.

```
Unable to generate document:
Templates for type ogc cannot be found -- please provide a valid `type` or a template URL
```

I presume it is a problem with metanorma-docker, but it might be a problem caused by the [template itself](https://github.com/metanorma/metanorma-ogc).

**Comment by manuel489** [comment]
@ronaldtse,
*community-practice* template hasn't been created yet because there is no document sample to do so.
There is a ticket that has been on hold since while: https://github.com/metanorma/mn-templates-ogc/issues/13

**Comment by ronaldtse** [comment]
@ghobona, would you be able to provide us with a `community-practice` sample structure? Currently the template doesn't exist because back then we did not have a sample. (From 2020 Jan: metanorma/mn-templates-ogc#13)

**Comment by ghobona** [comment]
Published Community Practice documents are listed at https://www.ogc.org/docs/cp

**Comment by manuel489** [comment]
Community practice template is created in https://github.com/metanorma/mn-samples-ogc/pull/123
Waiting for further instructions.
