### ISSUE TITLE
variant titles in PDF

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-ogc#259]
Follow-on from https://github.com/metanorma/metanorma-ogc/issues/256

If you see any instance of `<variant-title type="sub">...</variant-title>` in Presentation XML, that is a subtitle of a clause; that can include annexes, and it applies to all of Metanorma.

In HTML and Word, I am treating variant titles as part of the header tag, separated by the main title by two break-lines.

**Comment by Intelligent2013** [comment]
All XSLTs updated.

Example
XML:
```xml
<clause id="_conventions" obligation="normative" displayorder="10">
	<title depth="1">5.<tab/>Conventions</title>
	<variant-title type="sub">Variant title</variant-title>
	<p id="">This section provides ...</p>
	<clause id="_identifiers" obligation="normative">
		<title depth="2">5.1.<tab/>Identifiers</title>
		<variant-title type="sub">Identifiers variant</variant-title>
```
rendered in PDF:
![image](https://user-images.githubusercontent.com/5559926/131224809-aedc08f8-b738-415c-8c25-48c468d29c1d.png)
