### ISSUE TITLE
ModSpec says "Requirements class", not "Requirement class"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#264]
We need to verify that we generate the text "Requirements class" (with an S), not "Requirement class".

This applies to when generating captions and also cross-reference titles.

<img width="364" alt="Screenshot 2021-09-02 at 11 02 44 AM" src="https://user-images.githubusercontent.com/11865/131774934-9dc71226-ba3b-481d-a187-1d47453778da.png">

**Comment by opoudjis** [comment]
Confirmed for requirement class captions and crossreferences. This was already done in https://github.com/metanorma/metanorma-ogc/issues/238
