### ISSUE TITLE
Failure to display reference tag with `ö`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#268]
From ogc-citygml-xmi:

Original:
<img width="807" alt="Screenshot 2021-09-03 at 2 54 12 PM" src="https://user-images.githubusercontent.com/11865/131963340-ff94f030-6343-45b6-b104-d3d052c79365.png">

Now:
<img width="646" alt="Screenshot 2021-09-03 at 2 54 21 PM" src="https://user-images.githubusercontent.com/11865/131963363-363ed9e3-c710-4739-9575-ec6c56a21f17.png">

Encoding:

```adoc
[[figure-floorplan]]
.Floor plan representation (LOD0) of a building (left), combined LOD2 indoor and outdoor representation (right). Image adopted from <<Löwner2016>>.
image::images/Floorplan.png[]
```

Bibliography:

```adoc
* [[[Löwner2016,Löwner et al. 2016]]], Löwner, M.-O., Gröger, G., Benner, J., Biljecki, F., Nagel, C., 2016: *Proposal for a new LOD and multi-representation concept for CityGML*. In: Proceedings of the 11th 3D Geoinfo Conference 2016, ISPRS Annals of the Photogrammetry, Remote Sensing and Spatial Information Sciences, Vol. IV-2/W1, 3–12. https://doi.org/10.5194/isprs-annals-IV-2-W1-3-2016
```

**Comment by opoudjis** [comment]
ids and idrefs are being HTML escaped; they need not to be, since & # ; are not legal characters in XML ids

**Comment by opoudjis** [comment]
The issue is that the XML is being saved to ASCII after the ids are being processed; so non-ascii characters are being accepted during validation, but then converted to escapes illegal in ids afterwards. The proper approach is to eliminate non-ascii characters beforehand.
