### ISSUE TITLE
Ordering of "Abbreviated terms" entries

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#272]
The order of entries inside "Abbreviated terms" is not currently defined.

By default, Metanorma does an alphabetical sort ([a,Z]-[z,Z]) then numeric (ascending order).

In CityGML 3.0, numbers (ascending) is listed first then the alphabetical order.

What is the desired OGC order?

Ping @ogcscotts @gbuehler @ghobona

(This is originally from https://github.com/metanorma/ogc-citygml-xmi/issues/74)

**Comment by ghobona** [comment]
Numbers (ascending) first then the alphabetical order, please.

**Comment by ronaldtse** [comment]
Thanks @ghobona -- and can we also confirm:
- capitalisation does not affect the order (i.e. x comes before Y, X comes before y)
- shorter length is considered earlier in order than longer length ("bar" comes before "barber")

**Comment by ghobona** [comment]
Yes, capitalisation does not affect the order. (e.g. in https://docs.ogc.org/is/17-069r4/17-069r4.html[OGC 17-069r4] )

Yes, shorter length is considered earlier in order than longer length.

**Comment by ronaldtse** [comment]
Thanks @ghobona for rewinding the clock back 2 years 😜
