### ISSUE TITLE
Ordering of references in Normative references / Bibliography

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#273]
In ISO, the defined order is:
* ISO standards sorted according to ascending document number
* International SDO standards sorted according to ascending document number
* Other SDO standards sorted according to ascending document number
* Others in order defined

Should there be a defined order in OGC?
* OGC standards sorted according to ascending document number (year, then number)
* Standards
* Others

Ping @ogcscotts @gbuehler @ghobona

**Comment by ogcscotts** [comment]
@ronaldtse We generally follow the pattern of OGC, ISO, everyone else in alphabetic order, sorted by document title (OGC) or number (ISO). The everyone else category is by number or title based on the convention most used... e.g., W3C is title, IETF is number. All that being said, we never enforce the rule!

**Comment by ronaldtse** [comment]
Thanks @ogcscotts ! Let’s see how much we can automate here. 

So the scheme goes:
- OGC, by title (do we strip out the prefix of “OGC” which occasionally appears?)
- ISO sorted by docnumber
- Other SDOs like IEC, IETF, ITU, W3C sorted by their conventions  
- non-standards

For non-standards, should they be in author surname order or title order?

**Comment by ogcscotts** [comment]
@ronaldtse I suggest surname, at least while we are using the current styling

**Comment by ronaldtse** [comment]
Thanks @ogcscotts. The caveat is that most publication references are entered in free form text (except the auto-fetched ones), so the ordering by surname of non standards will remain manually enforced. 

But some day when OGC authors are ready for structured bibliographic entries then automatic sorting can be done.

**Comment by ronaldtse** [comment]
I ran into this issue:

```
* [[[topic5,OGC 08-126]]] OGC: The OpenGIS® Abstract Specification Topic 5: Features, OGC document 08-126 (2009)

* [[[topic8,OGC 99-108r2]]] OGC: The OpenGIS™ Abstract Specification Topic 8: Relationships Between Features, OGC document 99-108r2 (1999)

* [[[topic10,OGC 99-110]]] OGC: The OpenGIS™ Abstract Specification Topic 10: Feature Collections, OGC document 99-110 (1999)

* [[[ogc08-094r1,OGC 08-094r1]]] OGC: SWE Common Data Model Encoding Standard, OGC document 08-094r1 (2008)

* [[[ogc15-043r3,OGC 15-043r3]]] OGC: Timeseries Profile of Observations and Measurements, OGC document 15-043r3 (2015)
```

How does this title sort: "OGC: The OpenGIS™ Abstract Specification Topic 8: Relationships Between Features"?

* Should Abstract Specification Topic documents should be grouped together? Even so, "Abstract Specification Topic 10:" will sort before "Abstract Specification Topic 5:" because it is a string sort, not a number sort.

**Comment by ronaldtse** [comment]
The scheme goes:

* OGC, by title (do we strip out the prefix of “OGC” which occasionally appears?)
* ISO sorted by ISO docnumber
* Other SDOs like IEC, IETF, ITU, W3C sorted by their conventions
* non-standards, author order (whatever text that was given).
