### ISSUE TITLE
Smart terms references to terms to Glossary create wrong anchors in XML

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#275]
These are mistakes are present in both Semantic and Presentational XML files:

Let's take the term "URI" as an example.

It is defined here:
```xml
<term id="term-uri"><name>C.2.43.</name><preferred>URI</preferred><definition><p id="_6b7df6b6-1687-477d-85be-6843222dca96">Uniform Resource Identifier (URI), is a compact string of characters used to identify or name a resource</p></definition>
```

However, the `<xref>` elements look like this:
```xml
<p id="_38cdbeb0-a8a8-460a-865d-944c7ab6a31e"><xref target="URI-section">URI</xref> [0..1]</p>
```

_Originally posted by @ronaldtse in https://github.com/metanorma/ogc-citygml-xmi/issues/101#issuecomment-917786884_

**Comment by opoudjis** [comment]
Invalid: this turns out to be an issue in processing of XMI by Lutaml, without access to all anchors in the document.
