### ISSUE TITLE
Rename ModSpec types names in Metanorma

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#276]
Right now we have:

* `general` for Requirement, Recommendation or Permission (default value)
* `class` for Requirements class
* `verification` for Conformance test
* `conformanceclass` for Conformance class
* `abstracttest` for Abstract test

But they are not intuitive. We should follow the original ModSpec names for clarity.

```
[requirement]
[recommendation]
[permission]
[requirement_class]
[conformance_test]
[conformance_class]
[abstract_test] // or [conformance_test,%abstract]
```

**Comment by opoudjis** [comment]
I'll do these as synonyms

**Comment by ronaldtse** [comment]
These are also very confusing -- when to use the dot, or not:

```
[.permission,label="/per/core/prev"]
```

We should get rid of the dot.

**Comment by opoudjis** [comment]
> These are also very confusing -- when to use the dot, or not:
> 
> ```
> [.permission,label="/per/core/prev"]
> [.recommendation,label="/rec/core/api-definition-oas"]
> ```
> 
> We should get rid of the dot completely.

No we should not. Asciidoctor treats the dotless labels (style attributes) as a closed vocabulary, and I've found that recognition of them by the parser is haphazard. Dotted labels (role attributes) are an open vocabulary, and Asciidoctor does not raise any problems in recognising them. We should make the dot universal, and I have been doing so in documentation.

Don't fight me on this.

**Comment by ronaldtse** [comment]
@opoudjis has confirmed offline that all these labels work without the dot and we could update the manual to reflect that. Thanks!
