### ISSUE TITLE
Multi-paragraph not working in DL syntax

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-ogc#277]
Multi-paragraph content is not being shown in DL syntax.

Example:

````
[requirement]
====
[%metadata]
type:: general
label:: /req/job-list/status-response
conditions::
+
--
. If the `status` parameter is not specified then only jobs that are running (status: `running`)
or have completed execution (`successful`, `failed` or `dismissed`)
SHALL be considered for inclusion in the response.

. If the `status` parameter is specified, then only jobs with the specified status
SHALL be considered for inclusion in the response.
--
part:: If only the `minDuration` parameter is specified with the operation,
only jobs with the appropriate status and a duration of at least the specified
`minDuration` value SHALL be included in the response.
====
````

renders
![cap1](https://user-images.githubusercontent.com/33627611/133848791-7c99d7c5-ccd5-4344-9a8c-f18f983905ba.PNG)

**Comment by opoudjis** [comment]
I cannot replicate this; see attached.

Could you retry with a github pull?

[a1.zip](https://github.com/metanorma/metanorma-ogc/files/7196326/a1.zip)

**Comment by manuel489** [comment]
@opoudjis, I'm still getting the issue. Maybe I'm not using the correct gem versions. This is my Gemfile:

````
source "https://rubygems.org"

gem "metanorma-cli"
gem "metanorma-ogc", :git => "https://github.com/metanorma/metanorma-ogc.git", :branch => "fix/reqt-dl-attrs"
gem "metanorma-standoc", :git => "https://github.com/metanorma/metanorma-standoc.git", :branch => "main"
gem "sassc"
````

Is it ok?

**Comment by manuel489** [comment]
When I fetch from main branch I get compilation error.

**Comment by opoudjis** [comment]
Yes, I've run with that Gemfile, though I had to repaste the branch name: `fix/reqt-dl-nesting`. It still compiled fine.

Don't know; just in case, add:

`gem "isodoc", :git => "https://github.com/metanorma/isodoc.git", :branch => "main"`

**Comment by manuel489** [comment]
It works fine now with the "isodoc" gem. Thanks @opoudjis.
Closing.
