### ISSUE TITLE
Update on OGC document status for non-Standard deliverables

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#288]
As per an offline discussion with @ogcscotts @ghobona @gbeuhler, non-Standard deliverables only have a “draft” and “published” status. 

These types are:
* best-practice: Best Practice (a document subtype is necessary, see [ogc-docsubtype])
* change-request-supporting-document: Change Request Supporting Document
* community-practice: Community Practice
* discussion-paper: Discussion Paper
* engineering-report: Engineering Report
* other: Note, Primer, etc.
* policy: Policy, Policy — Name Type Specification
* reference-model: Reference Model
* release-notes: Release Notes
* test-suite: Test Suite
* user-guide: User Guide
* white-paper: White Paper

For these types, they have the full set of draft statuses (described in #104):
* abstract-specification-topic: Abstract Specification
* community-standard: Community Standard
* standard: Standard (a document subtype is necessary, see [ogc-docsubtype]) (default)

There are three tasks in this issue:
- Only allow “draft” and “published” status for the doctypes in the first list 
- Only allow the full set of statuses for the second list
- Make “draft” an alias to “swg-draft” for the second list

**Comment by ronaldtse** [comment]
And of course, we would have to update documentation.

**Comment by opoudjis** [comment]
Superseded by: https://github.com/metanorma/metanorma-ogc/issues/303
