### ISSUE TITLE
Anchor upper-case lost after conversion into XML, causing warnings to not make sense

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#289]
Given this encoding,
```adoc
[requirements_class]
====
[%metadata]
label:: http://www.opengis.net/spec/ogcapi-processes-1/1.0/req/json
obligation:: requirement
subject:: Web API
inherit:: <<rc_core,OGC API - Processes Core>>
inherit:: <<JSON,JSON>>
====
```

The resulting XML is:

```xml
<clause id="sc_requirements_class_json" obligation="normative">
  <title depth="2">9.2.<tab/>Requirement Class &#8220;JSON&#8221;</title>
  <p id="_ecc89658-69e2-731c-9caa-bc2cb1f7907f">This section defines the requirements class JSON.</p>
  <table id="rc_json" type="recommendclass" obligation="requirement" class="requirement">
    <thead>
      <tr>
        <th scope="colgroup" colspan="2">
          <p class="RecommendationTitle">Requirements class 3</p>
        </th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td colspan="2">
          <p>
          </p>
        </td>
      </tr>
      <tr>
        <td>Obligation</td>
        <td>requirement</td>
      </tr>
      <tr>
        <td>Target type</td>
        <td>Web API</td>
      </tr>
      <tr>
        <td>Dependency</td>
        <td>
          <xref target="rc_core">OGC API&#x2009;&#x2014;&#x2009;Processes Core</xref>
        </td>
      </tr>
      <tr>
        <td>Dependency</td>
        <td>
          <xref target="_json">JSON</xref>
        </td>
      </tr>
    </tbody>
  </table>
```

Notice that the anchor for `<<JSON,JSON>>` became:
```
<xref target="_json">JSON</xref>
```

While there is no anchor called `JSON`, the resulting message is:

```
_json is undefined
```

Which does not make sense, because the original anchor specified is `JSON`, not `_json`.

We need to do something right here.

**Comment by opoudjis** [comment]
@ronaldtse  I cannot replicate this. What document does this come from?

**Comment by ronaldtse** [comment]
The ogcapi document.

**Comment by opoudjis** [comment]
Date check for logo is failing with malformed date, as in the ogcapi document; patching.

**Comment by opoudjis** [comment]
I had to reintroduce the error to see this. You really aren't being helpful...

The issue arises because there is a term title elsewhere in the document that is `== JSON`, and that Asciidoctor would have generated its anchor automatically as `_json`. What is happening here is built in Asciidoctor behaviour: if there is no match by case with an anchor anywhere in the document, Asciidoctor downcases the anchor and tries again, and it's found a match in `== JSON`.

This is an erroneous scenario, and Asciidoctor is being too clever here for us, but cannot be helped, that's the tool's behaviour when confronted with an error in anchors not pointing anywhere.

**Comment by ronaldtse** [comment]
I disagree. The warning message should directly say the "JSON" anchor is missing. Asciidoctor is only used as a parser. It is NOT a validator (it cannot do any validation). The validation is a Metanorma step.

The title of the ticket says "the warnings do not make sense".

**Comment by ronaldtse** [comment]
The problem here is that the author of a document will not understand:
1. What is the problem that caused the warning
2. Where to fix the problem
3. How to fix the problem

The user will try to grep for `_json` and will never come up with an answer. It took me, who is familiar with the system and code, a long time to figure out why this error occurs.

**Comment by opoudjis** [comment]
At best, this will require monkeypatching of Asciidoctor source, which is a very bad idea. When Asciidoctor does not find a match for an xref, it tries again by lowercasing the anchor, and if it finds a match, it rewrites the source document to fit it: in this case, it is finding a match of `<<JSON>>` to an instance of `== JSON`, which autogenerates the anchor `_json`.

https://github.com/asciidoctor/asciidoctor/blob/d4b576c990ec001b13c1ea298b1ead91e8cf01f1/lib/asciidoctor/substitutors.rb#L823

**Comment by ghobona** [comment]
Discussed with OGC staff on 2023-11-06.

Agreement: There should be an OGC editors' guidance requirement that states that anchors should always be in lowercase.
