### ISSUE TITLE
Update boilerplate text for `doctype` varieties

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#29]
These are from https://github.com/opengeospatial/templates .

`doctype == 'standard'`:

> This document is not an OGC Standard. This document is distributed for review and comment. This document is subject to change without notice and may not be referred to as an OGC Standard.
> 
> Recipients of this document are invited to submit, with their comments, notification of any relevant patent rights of which they are aware and to provide supporting documentation.

`doctype == 'best-practice'`:

> This document defines an OGC Best Practice on a particular technology or approach related to an OGC standard. This document is not an OGC Standard and may not be referred to as an OGC Standard. It is subject to change without notice. However, this document is an official position of the OGC membership on this particular technology topic.
>
> Recipients of this document are invited to submit, with their comments, notification of any relevant patent rights of which they are aware and to provide supporting documentation.

`doctype == 'discussion-paper'`

> This document is not an OGC Standard. This document is an OGC Discussion Paper and is therefore not an official position of the OGC membership. It is distributed for review and comment. It is subject to change without notice and may not be referred to as an OGC Standard. Further, an OGC Discussion Paper should not be referenced as required or mandatory technology in procurements.

`doctype == 'white-paper'`

> This document is not an OGC Standard. This document is an OGC White Paper and is therefore not an official position of the OGC membership. It is distributed for review and comment. It is subject to change without notice and may not be referred to as an OGC Standard. Further, an OGC White Paper should not be referenced as required or mandatory technology in procurements.

`doctype == 'release-notes'`

> This document is not an OGC standard. This document provides release notes for an OGC standard. This document is subject to change without notice and may not be referred to as an OGC Standard.
> 
> Recipients of this document are invited to submit, with their comments, notification of any relevant patent rights of which they are aware and to provide supporting documentation.

NOTE: We don't currently support `white-paper` and `release-notes`

**Comment by ronaldtse** [comment]
@opoudjis can we place all this text in some YAML file? We now have duplicated text in HTML and Word. Thanks!

**Comment by opoudjis** [comment]
@ronaldtse if you reopen a ticket I have closed on my project board, I will never see it again.

Closing this, as it has been overtaken by the boilerplate xml.
