### ISSUE TITLE
Unnumbered document elements still take up the unique number

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#290]
This table is unnumbered, but still takes up the first number:
```
== Submitters

All questions regarding this document should be directed to the editor or the contributors:

[%unnumbered]
[options="header"]
|===
| Name | Organization | Role

| Sergio Taleisnik | Skymantics, LLC | Editor
| Clemens Portele | interactive instruments GmbH | Contributor
| Johannes Echterhoff | interactive instruments GmbH | Contributor
| Jarrod Lichty | Mosaic ATM | Contributor
| Frantisek Albert | NG Aviation SE | Contributor
| Ignacio "Nacho" Correas | Skymantics, LLC | Contributor
| Felipe Carrillo Romero | Hexagon | Contributor
|===
```

The next table (the first numbered table) is labelled "Table 2".

<img width="832" alt="Screenshot 2021-10-19 at 12 47 50 PM" src="https://user-images.githubusercontent.com/11865/137845754-e375e100-1969-4b33-9fea-efbd5a45fa11.png">

**Comment by opoudjis** [comment]
Cannot replicate, see attached. I will need the source document.
[a1.zip](https://github.com/metanorma/metanorma-ogc/files/7381003/a1.zip)

**Comment by ronaldtse** [comment]
Confirmed fixed.
