### ISSUE TITLE
OGC PDF contains additional bookmarks for Figures/Tables/Recs

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#292]
I noticed that in the OGC PDF bookmarks it contains Figures / Tables / Recommendations.

<img width="214" alt="Screenshot 2021-10-20 at 2 09 08 PM" src="https://user-images.githubusercontent.com/11865/138037542-8aa27c0c-c4cc-4c73-b1b9-435076a53a92.png">

These are probably not supposed to show, right?

**Comment by Intelligent2013** [comment]
> * While the bookmarks should provide the same links as the TOC, there is no "list of figures" in the TOC but exists in the bookmarks.
> 
> * The names of "Tables" (bookmark) vs "List of tables" (TOC) are also different

>  * Maybe we add a bookmark "section" after the main content to separate the bookmarks?

Done:

![image](https://user-images.githubusercontent.com/5559926/138079254-15019459-0962-44c8-bd8d-1c3b0716eff8.png)
