### ISSUE TITLE
Question: order of requirements in "List of requirements" in PDF

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#293]
Right now the TOC provides a "List of requirements" list but it reads a little funny, because:

* the types of requirements (recommendation, requirements, permissions) are interleaved
* the "requirements class" should technically be the container of all "requirements", hierarhically
* but if we group those here, it might be more of an "index" rather than a TOC because a TOC is always presented in a sequential order
* in addition, a Requirement in the TOC is not provided with a descriptive name, so just telling me "requirement 3 is at page 10" isn't very useful

<img width="635" alt="Screenshot 2021-10-20 at 5 15 18 PM" src="https://user-images.githubusercontent.com/11865/138064995-af7da5bc-0b42-4898-939d-b72891529c9b.png">

**Comment by opoudjis** [comment]
... Is there any guidance from OGC about this? 

Failing that, you are not telling me what to do, but asking me to come up with something. Ok:

I will not make up some bizarre containerised index of requirements without sequential numbers, because believe you me, that is going to look even more bizarre.

I will instead sort the requirements by requirement class, in something resembling hierarchy order: 

* Conformance class
* Conformance test
* Abstract test
* Requirement class
* Requirement
* Recommendation
* Permission

The requirements will be accompanied by their titles, where available.

**Comment by opoudjis** [comment]
In fact, the Word ToC (which is completely independent of the PDF implementation) does include titles where provided:

<img width="918" alt="Στιγμιότυπο 2021-11-16, 00 32 49" src="https://user-images.githubusercontent.com/1911039/141790615-e9b25656-8f4f-49d3-90b9-369331fbaec8.png">

So:

* Word ToC stays as is, except that requirement classes are not interleaved, but sorted by requirement class then location in the given order.
* PDF ToC adds requirement title to requirement number, where available, and sorted by requirement class then location in the given order.

@ronaldtse Please confirm. I'll implement the Word version now.

**Comment by ronaldtse** [comment]
Word ToC should sync with PDF ToC. OGC only treats PDF and HTML as normative.

A sort like this would be more appropriate:

I will instead sort the requirements by requirement class, in something resembling hierarchy order:

* Requirement class
* Requirement
* Recommendation
* Permission

* Conformance class
* Abstract test
* Conformance test

**Comment by opoudjis** [comment]
Formerly Conformance test and Abstract test was excluded from Word ToC. We will no longer do so.

**Comment by opoudjis** [comment]
So @Intelligent2013 the task is to sort all entries in the list of recommendations by:

1. The requirement class (the prefix to the label, in the order given)
2. The number of the requirement

So the sort key of _Recommendation 7: The Wrath of Khan_ is `3::0007` ("Recommendation" is 3rd in the list above)

The sort key of _Recommendation test 2_ is `8::0002` ("Recommendation test" is 8th in the list above)

````
      def recommmendation_sort_key(header)
        m = /^([^0-9]+) (\d+)/.match(header)
        "#{recommmendation_sort_key1(m[1])}::#{'%04d' % m[2].to_i}"
      end

      def recommmendation_sort_key1(type)
        case type.downcase
        when "requirement class" then "1"
        when "requirement" then "2"
        when "recommendation" then "3"
        when "permission" then "4"
        when "conformance class" then "5"
        when "abstract test" then "6"
        when "requirement test" then "7"
        when "recommendation test" then "8"
        when "permission test" then "9"
        else "z"
        end
      end
````

**Comment by Intelligent2013** [comment]
@opoudjis OGC xslt updated.
Looks like instead of `requirement class` should be `requirements class` in `def recommmendation_sort_key1(type)`.

Example of presentation xml:
```xml
<table id="rc_html" obligation="requirement" type="recommendclass" class="requirement">
	<thead>
		<tr>
			<th scope="colgroup" colspan="2">
				<p class="RecommendationTitle">Requirements class 2</p>
			</th>
		</tr>
	</thead>
```
