### ISSUE TITLE
OGC: document behavior of abstract test / conformance test method part vs test method step (sample images helpful)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#295]
From @opoudjis 

> part : cap letters (A, B...)
> steps: `<ol>` default (a. then 1. etc)

**Comment by ronaldtse** [comment]
@opoudjis this is rather urgent, can you please help here? thanks.

**Comment by opoudjis** [comment]
Addressed in https://github.com/metanorma/metanorma-ogc/issues/300
