### ISSUE TITLE
`alt:[...]` macro resulting misplaced in output

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-ogc#298]
*In relation to https://github.com/metanorma/ogcapi-processes/issues/1 and https://github.com/opengeospatial/ogcapi-processes/pull/247*

`alt:[...]` macro result is being wrongly placed right after the first term title.

From [18-062](https://github.com/metanorma/ogcapi-processes/issues/1):

```adoc
=== Terms and definitions

==== process
...

==== job
...

==== REST
alt:[RESTful]

Representational state transfer.  REST-compliant Web services allow requesting systems to access and manipulate textual representations of Web resources using a uniform and predefined set of stateless operations.
```

renders:
![issue1-generated](https://user-images.githubusercontent.com/33627611/138335491-d6acc4f2-f99f-4ec2-bc7f-ca32b3a857e2.PNG)

**Comment by opoudjis** [comment]
<img width="739" alt="Στιγμιότυπο 2021-11-16, 00 12 32" src="https://user-images.githubusercontent.com/1911039/141787819-6364533a-df46-43fa-a988-554ab69fb5b7.png">
