### ISSUE TITLE
Realise `<ol @class = 'steps'>` in PDF

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-ogc#300]
Carried across from NIST, to address https://github.com/metanorma/metanorma-ogc/issues/299 : any instance of `<ol @class = 'steps'>`, at whatever depth, in OGC must have arabic numbering.

**Comment by ronaldtse** [comment]
The current behavior seems wrong:

<img width="718" alt="image" src="https://user-images.githubusercontent.com/11865/142755098-aa5fe995-be38-42b4-871a-8b316a8b5109.png">

<img width="927" alt="image" src="https://user-images.githubusercontent.com/11865/142755136-f71a3318-51ad-46c5-b68d-f97059147c1f.png">


This is supposed to be 1. then a), not 1. then 1..

**Comment by opoudjis** [comment]
The markup provided here is NOT what was requested: there is no use of "part" in the markup (`[.component,class=part]`), as stated in https://www.metanorma.org/author/ogc/topics/requirements/. 

What we have is nested `ol[@class = 'steps']`, which had not been anticipated. I will implement HTML styling for nested `ol[@class = 'steps']`, @Intelligent2013 will need to do so as well.

**Comment by opoudjis** [comment]
No, I'll do it in Presentation XML for PDF.
