### ISSUE TITLE
Update OGC document type stages

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#303]
From the latest discussion with @ogcscotts @gbuehler @ghobona we have confirmed that OGC document types will have the following stages.

This task is to update them.

* [x] Update stages and cover label for that stage.
* [x] metanorma/metanorma.org#510
* [x] metanorma/metanorma-model-ogc#22

------

standard: Standard (and all its subtypes)
* swg-draft
* oab-review
* public-rfc
* tc-vote
* approved/published
* deprecated
* rescinded
* retired

abstract-specification-topic: Abstract Specification
* swg-draft
* oab-review
* public-rfc
* tc-vote
* approved/published^
* deprecated
* rescinded
* retired

best-practice: Best Practice (and all subtypes)
* draft
* published
* retired

change-request-supporting-document: Change Request Supporting Document
* draft
* published
* retired

community-practice: Community Practice
* draft
* published
* retired

community-standard: Community Standard
* work-item-draft
* oab-review
* public-rfc
* tc-vote
* approved/published
* deprecated
* rescinded
* retired

discussion-paper: Discussion Paper
* draft
* published
* retired

engineering-report: Engineering Report
* draft
* published
* retired

other: Note, Primer, etc.
* draft
* published
* retired

policy: Policy, Policy — Name Type Specification
* draft
* published
* retired

reference-model: Reference Model
* draft
* published
* retired

release-notes: Release Notes
* draft
* published
* retired

test-suite: Test Suite
* draft
* published
* retired

user-guide: User Guide
* draft
* published
* retired

white-paper: White Paper
* draft
* published
* retired

**Comment by opoudjis** [comment]
Changing stage from "approved" to "published" in Presentation XML for document types that do not explicitly list "approved".
