### ISSUE TITLE
Update OGC branding in HTML output

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#305]

**Comment by opoudjis** [comment]
Adding date sensitivity to logo, as done for https://github.com/metanorma/metanorma-ogc/issues/306

Adding logo to HTML output. Logo is only used in Word output in White Papers currently.

**Comment by opoudjis** [comment]
SVGs being converted to data uri within isodoc were missing "+xml" in "image/svg+xml" processing.

**Comment by ronaldtse** [comment]
@opoudjis is this done and ready to close?
