### ISSUE TITLE
Update OGC branding in PDF output, and change yellow color to `#00b1ff`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#306]

**Comment by Intelligent2013** [comment]
@ronaldtse OGC xslt updated. Examples (the publication date for 20-010 changed to Dec,2021 just for testing purposes):
![image](https://user-images.githubusercontent.com/5559926/140053102-d28f020d-071c-4e4d-975b-0312e5d924b7.png)
![image](https://user-images.githubusercontent.com/5559926/140053211-a299536f-7370-4304-a52c-076f5ba8fdcf.png)
![image](https://user-images.githubusercontent.com/5559926/140053285-501e5714-e116-4e58-86be-e4379b46c98e.png)
![image](https://user-images.githubusercontent.com/5559926/140053335-88c17fe8-d703-4fba-8578-f4f0eb5be1c5.png)
![image](https://user-images.githubusercontent.com/5559926/140053388-4d1530d3-6845-4d73-b4d6-bf269780a0c0.png)


Xslt displays the new logo and blue color in case if the document's date (most latest date in bibdata/date) is equal or more 2021-11-08.
Please ping me, if I need this logic.

**Comment by ronaldtse** [comment]
This is perfect. Thank you!
