### ISSUE TITLE
Terms section of all OGC document types

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-ogc#309]
The first paragraph of the Terms, Definitions and Abbreviated Terms section uses the phrase "this standard". Please see attached.

For all OGC document types, the instance of the phrase where circled on the attached screenshot should be changed to "this document". Please update the template.

![Screenshot 2021-11-10 at 08 51 13](https://user-images.githubusercontent.com/18121038/141121461-2535f50e-8c11-41eb-b173-ead53ae5b699.png)

**Comment by ronaldtse** [comment]
Agree, thanks @ghobona!
