### ISSUE TITLE
Executive Summary in Engineering Reports

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-ogc#310]
Please add an Executive Summary section, appearing immediately after the Abstract section (i.e. before the Keywords section). 

The Executive Summary section should be optional, as it is only required in Engineering Reports.

Some helper text to include, if possible, is below.

```
The Executive Summary clause shall contain the key findings and results in a concise form. A more detailed description of the findings should be in the body of the report.

The Executive Summary shall contain a business value statement that should describe the value of this Engineering Report to improve interoperability, advance location-based technologies or realize innovations.

This section shall include precise descriptions of the requirements that have been addressed by the work documented in this Engineering Report; together with the research motivation that answers the fundamental question: What motivated us to address this topic in this report?

This section provides an overview of recommendations on how to further proceed with the achievements documented in this ER.

This section shall be between 1-3 pages.
```

**Comment by ghobona** [comment]
Cc: @ogcscotts @gbuehler

**Comment by ronaldtse** [comment]
@ghobona is this a request to add text in the Engineering Report template?

It is already possible to add an Executive Summary preface section like this:

```adoc
[.preface]
== Executive Summary

The Executive Summary clause shall contain the key findings and results in a
concise form. A more detailed description of the findings should be in the body
of the report.
```

<img width="233" alt="Screenshot 2021-11-11 at 5 02 14 PM" src="https://user-images.githubusercontent.com/11865/141269167-ae6f0caf-2122-40ec-be9a-59c0d3aaa0f1.png">


<img width="742" alt="Screenshot 2021-11-11 at 5 02 39 PM" src="https://user-images.githubusercontent.com/11865/141269236-a1688fcd-b97e-4621-9744-d8b27cd9170f.png">

So the only issue is that this section is placed last in the preface sections.

That said, we already have the:
* "I. Abstract"
* "III. Preface"
* "??. Executive summary"

But as an ER editor I am at a loss on what content to provide to them...

**Comment by ghobona** [comment]
Yes, please place the Executive Summary immediately after the Abstract. The structure would be:

* I. Abstract
* II. Executive Summary
* ...
* ...

Regarding what to write in them, I'll provide some further guidance via email.

**Comment by ronaldtse** [comment]
Thanks @ghobona, I can understand "Abstract" vs "Executive Summary".

How about the content that goes into the Preface section which is now a mandatory section for all deliverables?

**Comment by ghobona** [comment]
@ronaldtse I agree, there is some overlap in the role of an **Executive Summary** in comparison to that of the **Preface**.

I suggest keeping the Preface of an Engineering Report short (e.g. only containing the statement about the subject of patent rights) and placing the rest of the summary content in the Executive Summary.

**Comment by opoudjis** [comment]
Ok, if the Executive Summary is present, it goes after the Abstract.

**Comment by ronaldtse** [comment]
@opoudjis FYI the "Executive summary" is only available for Engineering Reports, no other types should allow the "Executive summary".
