### ISSUE TITLE
PDF: List of figures not showing some figures

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#317]
<img width="262" alt="Screenshot 2021-11-24 at 12 14 48 AM" src="https://user-images.githubusercontent.com/11865/143061757-db31acba-efff-4893-99dc-793f3a28449a.png">

Figure 12 is missing from the TOC.

But Figure 12 exists and even has a caption.

<img width="493" alt="Screenshot 2021-11-24 at 12 15 04 AM" src="https://user-images.githubusercontent.com/11865/143061829-f44f4631-3561-4d44-b829-067ff68dc2b2.png">

**Comment by Intelligent2013** [comment]
@ronaldtse xslt puts the information into 'List of Figures' from the element `figure` with:
- `@id` 
- element `name` that contains '—'.

It seems some another element is using for figure displaying. Could you put here xml fragment for 'Figure 12`, please? Thanks.

**Comment by ronaldtse** [comment]
Will prepare. Why is the `--` in name necessary?

**Comment by Intelligent2013** [comment]
> Will prepare. Why is the `--` in name necessary?

@ronaldtse we should put the figures/tables in ToC with Figure's/Table's number + Figure's/Table's title. `—` is indication of this (i.e. there are two parts). I.e. we don't put such values:
- `Figure 1` (figure without title)
- `CityGML official logo` (just image title, not figure)

**Comment by ronaldtse** [comment]
@Intelligent2013 we also want to list the Figures without title, just like how Tables without titles are also shown. Can you help update?

**Comment by Intelligent2013** [comment]
> @Intelligent2013 we also want to list the Figures without title, just like how Tables without titles are also shown. Can you help update?

@ronaldtse done.

**Comment by Intelligent2013** [comment]
Some figure's title missing in ToC, because actually this is formally isn't 'figure', just the element with title starts with 'Figure ':
```xml
<sourcecode id="mn-modspec-types" lang="adoc">
    <name>Figure 13&#160;&#8212; ModSpec types supported</name>
```

So, then in ToC I have to put all elements with the name starts with 'Figure '.

**Comment by Intelligent2013** [comment]
@ronaldtse OGC xslt updated:
- Tables ToC:
![image](https://user-images.githubusercontent.com/5559926/143231308-1de580ca-c3c4-450d-b1e8-96414aa063d7.png)

- Figures ToC:
![image](https://user-images.githubusercontent.com/5559926/143231462-2800a886-847d-47ed-aa50-300f892e018e.png)

but in the source xml there is a gap in the figure's numeration between 'Figure 13' and 'Figure 24'.

**Comment by ronaldtse** [comment]
The real cause of the missing Figures is #317 .
