### ISSUE TITLE
PDF: reduce font size of monospace / fixed-width font

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#318]
Source Code Pro is known to be slightly larger, we want a balanced look with the normal text font size. Maybe 2 sizes down?

<img width="504" alt="Screenshot 2021-11-24 at 12 16 33 AM" src="https://user-images.githubusercontent.com/11865/143062050-f68ab301-5586-4594-a00a-0b247202c2c7.png">

**Comment by Intelligent2013** [comment]
Done.

**Comment by ronaldtse** [comment]
Thanks! Confirmed.
