### ISSUE TITLE
Broken numbering of figures (sample document skipping Fig 14-23)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#319]
OGC 20-010 is attached. This document is missing Figures 14 to 23.

This is due to "Figures" being embedded within "Examples", e.g.
```adoc
.Bibliographic item example from OGC 20-010 (CityGML 3.0) of "OGC 15-001r4"
======
[source,adoc]
----
[bibliography]
= Bibliography

* [[[three-dps_citation,OGC 15-001r4]]], Hagedorn, B., Thum, S., Reitz, T.,
Coors, V., Gutbell, R.: _OGC® 3D Portrayal Service 1.0_, Open Geospatial
Consortium, Available from
https://docs.opengeospatial.org/is/15-001r4/15-001r4.html[OGC Doc. 15-001r4].
----

image::mn-citygml-bib.png[]
======
```

The `[source,adoc]` block inside is technically a figure, and occupies a unique numbering, but is not showing the Figure number and caption.

[Archive.zip](https://github.com/metanorma/metanorma-ogc/files/7596370/Archive.zip)

**Comment by opoudjis** [comment]
Sourcecode instances within examples should not be numbered, just as they are not captioned: that would be utterly confusing.  (The block on sourcecode labelling within examples is implemented at isodoc level.) Need to make sure they are not assigned numbering either.

**Comment by opoudjis** [comment]
@ronaldtse Clearly I need the source asciidoc to do any debugging here.

**Comment by opoudjis** [comment]
Figures, like sourcecode, within examples are not captioned; they should not be numbered either.

More generally: the exceptions to labelling in presentation XML need to be respected in xref labelling.
