### ISSUE TITLE
Availability of `charter` doctype (was: `charter` not working on docker)

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-ogc#324]
`charter` is supposed to be a valid doctype on the OGC Metanorma template.

However, when I run this command

`docker run -v "$(pwd)":/metanorma metanorma/mn metanorma new -d charter -t ogc -l https://github.com/metanorma/mn-templates-ogc folder_for_charter`

I get the following error message.

```
Unable to generate document:
Templates for type ogc cannot be found -- please provide a valid `type` or a template URL
```

**Comment by ronaldtse** [comment]
@ghobona we have never supported `charter`, and do not have a sample for `charter`.
https://www.metanorma.org/author/ogc/ref/document-attributes/

<img width="704" alt="Screenshot 2021-12-14 at 12 38 19 PM" src="https://user-images.githubusercontent.com/11865/145934025-1dd8d0f6-392e-4e14-8813-5dc2710e6134.png">

1. Should we implement `charter` as a new document type?
2. Do you have an existing sample we can work on?

Thanks.

**Comment by ghobona** [comment]
@ronaldtse Ok, agreed. 

I suggest updating the error message to say "The template for charter documents can be downloaded from https://github.com/opengeospatial/templates/tree/master/charter_templates".

**Comment by opoudjis** [comment]
OK, I will trigger that error in case "charter" is requested, but it remains the case that this is not going to be recognised in Metanorma, it will generate legacy OGC Asciidoctor HTML.

**Comment by opoudjis** [comment]
Implementing this ends up requiring a custom error to be generated in metanorma-ogc, to override the error message for a missing template given in https://github.com/metanorma/metanorma-cli/blob/278a54093e0dd1659c0170786f7eaac6af240286/lib/metanorma/cli/generator.rb#L53
