### ISSUE TITLE
Replace `white-paper` document type with `technical-paper`

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-ogc#325]
As of 16 December 2021, the 'White Paper' document type will be renamed 'Technical Paper'.

Please update metanorma with the change.

**Comment by ghobona** [comment]
Please wait until 16 December 2021 before proceeding with this change. The change is still subject to review until then.

**Comment by ronaldtse** [comment]
Thanks @ghobona for letting us know. Do you want to use the same date cut-off treatment as the branding, i.e. before 2021-12-16 "White Paper", 2021-12-16 and beyond "Technical Paper"?

**Comment by ghobona** [comment]
Yes, please use the same date cut-off as the branding.

**Comment by ronaldtse** [comment]
@opoudjis this issue is a go. I've confirmed with @gbuehler.

**Comment by opoudjis** [comment]
Assuming URI type is TP, e.g. `<docidentifier type='ogc-external'>http://www.opengis.net/doc/TP/A/2.0</docidentifier>`
