### ISSUE TITLE
Enable the Table of Contents to go further than level 2 headers

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-ogc#328]
There's a request to enable the Table of Contents (ToC) to go further than second level headers (e.g. 2.1). 

That is, to enable the ToC to present headers like 3.2.1, or even 4.3.2.1.

**Comment by ronaldtse** [comment]
@ghobona has the user tried setting `:toclevels:`? It is documented here: https://www.metanorma.org/author/topics/document-format/sections/

> By default, the table of contents includes two levels of heading. More levels of heading can be set by using the document attribute :toclevels:; e.g. :toclevels: 3 for three levels of heading included. The number of levels of heading to include can be set separately for HTML/PDF and for DOC, by using the document attributes :htmltoclevels: and :doctoclevels:.

**Comment by ghobona** [comment]
@ronaldtse Thanks. 

`:htmltoclevels:` works.
