### ISSUE TITLE
Request support for generating clause titles instead of clause numbers

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#330]
From @cportele via @gbuehler :

>> * How can I change the link titles back to the section title instead of, e.g. "Clause 5"?
>
> This one is easy:
>
> "This discussion is followed by a brief chapter titled `<<scenario>>`..."
>
> becomes:
>
> "This discussion is followed by a brief chapter titled `<<scenario,Scenario>>`..."

> Regarding the link titles, it would really be good, if metanorma could - in the future - also support the capability to automatically use the title in the link, like asciidoctor. This avoids redundant titles in the links that will also become outdated, if the section title is changed. I had already updated a few places with explicit link titles in the r1 version that I uploaded today, but I noticed there are more places where "Clause x.y" is not very helpful, but this is how it will be in this ER.

Perhaps we should have an option in a cross-reference to use the section title instead of "Clause x.y" for the times that they are really necessary (I have encountered some occasions as well).

**Comment by opoudjis** [comment]
Do you want optional use of title instead of number, or for that to be a per-document option?

**Comment by cportele** [comment]
Since I was the original source, let me add that I agree, a per-document option would seem right to me, too.

**Comment by ronaldtse** [comment]
Thanks @cportele !

**Comment by opoudjis** [comment]
@cportele I'm really sorry it's taken me this long to get to this, but we have a massive backlog

**Comment by cportele** [comment]
@opoudjis - No worries, fully understood. I appreciate the support.

**Comment by opoudjis** [comment]
Will do per-document for now, if we need to make it per-reference, it be a specialisation of the per-document solution.

**Comment by ronaldtse** [comment]
@opoudjis the per-reference solution is necessary. To keep us on the big picture here, references in OGC should utilize clause numbers, but occasionally authors want a link with the full title.

**Comment by opoudjis** [comment]
What Metanorma has implemented to date is `:xrefstyle: short`, https://docs.asciidoctor.org/asciidoc/latest/macros/xref-text-and-style/ . We will support basic and full for sections.

**Comment by opoudjis** [comment]
I cannot use the `xref:xxxx[xrefstyle=basic]`  macro of Asciidoctor, because its implementation does not pass the xrefstyle attribute back to the parsed document: it resolves it in situ, which means I cannot recover it. So xrefstyle will instead be realised as a `%style` parameter of xref, although I will also capture the xrefstyle document attribute.
