### ISSUE TITLE
Request to support collapsible figures / code snippets

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#331]
From @cportele via @gbuehler

> I personally would also like to see support for "collapsible", which I had been using in this ER and which I find helpful in document for code snippets, etc. metanorma unfortunately does not support it at the moment, I guess since pdf publishing is a primary target.

This request applies to HTML output. I agree that collapsible figures, snippets, are useful.

Let's address this in the ongoing reimplementation of the HTML output as performed by @s4birli (ping).

**Comment by opoudjis** [comment]
Need to ensure that any Javascript solution degrades gracefully if Javascript is unavailable/disabled on the browser.

**Comment by opoudjis** [comment]
Have discussed with OGC 2023-11-07, pending finding a resource, HTML refactor has been initiated and is 70% complete.

**Comment by ghobona** [comment]
Discussed 2024-02-15

**Comment by ghobona** [comment]
@ronaldtse Any update on this?

**Comment by opoudjis** [comment]
Will just do the quick-and-easy from https://www.w3schools.com/howto/howto_js_collapsible.asp

**Comment by opoudjis** [comment]
Have implementation concept in place. Am assuming snippets open by default, and can collapse. Will want an icon to signal this: up-chevron and down-chevron: https://www.flaticon.com/packs/arrows-868

**Comment by opoudjis** [comment]
There is no capability right now to add flavour-specific Javascript to the global Javascript. There is a piece of Javascript to turn on the snippets by default, that I want to restrict to OGC.

**Comment by opoudjis** [comment]
Need to move caption for figure outside of hidable block, so it can still display when collapsed.

**Comment by opoudjis** [comment]
@ghobona Please review:

[a1.html.zip](https://github.com/user-attachments/files/16637790/a1.html.zip)
