### ISSUE TITLE
Reserved section names causes recognization problems

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#335]
From @gbeuhler:

> In the "Data-centric security engineering report" they had a “Security considerations” section in one of the content sections, but it was promoted to the preface. We should provide a list of reserved section headers somewhere so authors can recognise them.

We also should look at the possibility of "declaring" sections instead of recognising section names, matching section names is rarely a good idea.

**Comment by opoudjis** [comment]
I believe it is a very good idea, but I will concede that if the section is in the main body, it can be assumed not to be part of the preface.

The work-around for reusing a reserved section header (and we've already used it several times) is 

````
[heading=clause]
== Security considerations
````

Where if heading is something other than the title, it is not processed in the default title way. https://www.metanorma.org/author/topics/document-format/sections/#fixed-section-names

I'll put in the workaround for blocking movement between main body and preface. I will not declare sections. That is just inviting authors to forget to declare sections.

**Comment by opoudjis** [comment]
So there are two types of reserved title: preface, and main. If we are in the preface, we do not recognise main titles, and if we are in the main section, we don't recognise preface titles.
