### ISSUE TITLE
Structured contributors: add role of "contributor" in addition to "editor" and "author"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#336]
Other than "author" and "editor" roles, we should add the role of a "contributor" which is often used in OGC deliverables.

For example, CityGML has a preface section for non-author/editor contributors:

<img width="605" alt="Screenshot 2021-12-20 at 5 24 56 PM" src="https://user-images.githubusercontent.com/11865/146744019-6398b7d2-fd7b-4a45-8631-ca43ea75f641.png">
 
This is suggested by @gbuehler / @ronaldtse to be confirmed by @ghobona @ogcscotts

We will also provide the contributor as metadata output.

**Comment by opoudjis** [comment]
There is no problem with doing this using `:role_{i}: contributor`, the only thing is to make the output processing recognise this. Is this still waiting on confirmation?

**Comment by ronaldtse** [comment]
@opoudjis yes this is a go. Thanks!
