### ISSUE TITLE
HTML: "Admitted term" qualification not showing up

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#339]
Raised by @gbuehler.

**Comment by opoudjis** [comment]
`alt:[....]` is being recognised, but contra documentation, `admitted:[...]` is not. That's an error in documentation, but I'm introducing `admitted:[]` as a synonym of `alt:[]`.

**Comment by ronaldtse** [comment]
@opoudjis thanks for adding “admitted” but this ticket is for the rendering in OGC documents to use the phrase “Admitted” instead of “Alt”?

**Comment by opoudjis** [comment]
Not what I'm getting.

<img width="791" alt="Στιγμιότυπο 2022-01-11, 21 30 10" src="https://user-images.githubusercontent.com/1911039/148926426-377c8cf8-b40a-4f8b-a603-8e7f92708632.png">

I remind you that declining to provide me source to replicate behaviour from is a poor use of my time.

**Comment by ronaldtse** [comment]
Thank you!

I think we might want to move the Admitted terms to the next lines like ISO to prevent confusion. (cc @Intelligent2013 )

P.S. source -- any OGC doc...

**Comment by opoudjis** [comment]
> I think we might want to move the Admitted terms to the next lines like ISO to prevent confusion. (cc @Intelligent2013 )

We deliberately put the admitted term on the same line because of https://github.com/metanorma/metanorma-ogc/issues/256

Nothing happens without explicit authorisation from OGC, we can't keep doing and undoing formatting changes.

**Comment by ronaldtse** [comment]
> Nothing happens without explicit authorisation from OGC, we can't keep doing and undoing formatting changes.

In #256 the request wasn't to put alternative designations on the same line...

In fact, the PDF layout has been updated to have alternative designations on separate lines (#350), we should follow that. Do you prefer a new ticket or reopening of this one?
