### ISSUE TITLE
Question: Concern about terminology on "admitted term"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#340]
In ISO, an accepted term but not "preferred" is called the "admitted term". 

In OGC, they have traditionally used the "alternative term" term for this concept.

There has been some concern that some OGC audiences will confuse "admitted term" and "alternative term", such that "admitted term" sounds too informal.

This was raised by @gbuehler and @cmheazel, and that we need to seek opinion from @ogcscotts and @ghobona (ping ).

**Comment by ghobona** [comment]
The markup used is :

```
=== milled rice
alt:[white rice] 
```

However, currently the text is rendered as 'admitted term'.

@opoudjis is going to modify it to change the text to 'alternative term'.

**Comment by ronaldtse** [comment]
To summarize we have to:

* [ ] metanorma.org: document OGC uses "alternative term" instead of ISO's "admitted term" and explain
* [ ] metanorma-ogc: change the label to "alternative" instead of "admitted"
