### ISSUE TITLE
Enhancement: auto-link Requirement to the corresponding Conformance test (vice versa), and Requirements Class to Conformance test class

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#341]
As requested in https://github.com/metanorma/ogc-citygml-xmi/issues/128, we need to implement linking in Conformance test and its linked Requirement both ways.

We should also warn if there are requirements that do not link to any conformance tests and vice versa.

**Comment by ronaldtse** [comment]
We need to update the https://github.com/metanorma/ogc-citygml-xmi/issues/128 document once done.

**Comment by ronaldtse** [comment]
Every requirement has a corresponding test, they should link to each other

Every requirements class should have a link to their corresponding conformance class, they should link each other.

**Comment by opoudjis** [comment]
The cross-reference is specified as the "subject" attribute of conformance tests and conformance classes. The requirement appears to be for bidirectional linking in rendering, and validation of the correspondences.

**Comment by opoudjis** [comment]
Validation works on crossreferences. It expects that each conformance test shall have as its subject a cross-reference to the anchor of a general requirement, and that each general requirement shall be pointed to by the subject of a conformance test. Ditto for requirement classes and conformance classes. If there is a mismatch, an error is logged.

**Comment by opoudjis** [comment]
OGC are not providing any indication of what they want the link rendered as. This is novel content that has not featured to date in existing documents.

Please ensure in future that we have actual specification of required behaviour from OGC. 

Absent any actual rendering guidance, I am going to introduce the link from Requirement to Conformance as "Conformance test", uniformly.

**Comment by opoudjis** [comment]
No additional markup is needed; just using "subject" markup with xrefs in conformance tests, the directional link will be inserted automatically. See the attached for exemplar.

[Αρχειοθήκη 2.zip](https://github.com/metanorma/metanorma-ogc/files/7846737/2.zip)

@ronaldtse Please confirm with OGC.

**Comment by opoudjis** [comment]
I'm closing this issue. If OGC can't provide feedback within 6 months, they can raise a new ticket if they don't like it.
