### ISSUE TITLE
(URGENT) HTML: Large spaces between items in the Table of Contents

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#344]
From @gbuehler:

> there are large spaces between items in the Table of Contents.

This is presumably from the latest version.

![Screenshot 2022-01-06 at 11 46 54](https://user-images.githubusercontent.com/11865/148511599-aad92087-b7de-4cf2-ad21-1da853db07db.png)

**Comment by CAMOBAP** [comment]
Issue introduced by this commit https://github.com/metanorma/metanorma-ogc/commit/202475c273e6edee1a13939d7adab54557c15463

I will try to update CSS selector to not apply `.h1, .h2, .h3, .h4, .h5, .h6` if they are inside `nav`

**Comment by CAMOBAP** [comment]
I have compared the document with https://github.com/metanorma/metanorma-ogc/commit/202475c273e6edee1a13939d7adab54557c15463 and without this commit, and don't see any difference except this commit, trying to understand the feature which it should introduce to make correct fix
