### ISSUE TITLE
"Introduction" section goes missing in OGC

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#35]
Given this header section:

```adoc
.Preface

This document specifies...

[abstract]
== Abstract

This document specifies...

=== Introduction

The ...
```

The document is rendered with this ToC (noticed Introduction is now "1.1", which is wrong):
<img width="305" alt="Screen Shot 2019-05-31 at 11 42 33 AM" src="https://user-images.githubusercontent.com/11865/58680171-2f669e00-8399-11e9-83b8-da246cb975a5.png">

Moreover, if I change Introduction to this:

```adoc
== Introduction

The ...
```

The entire section goes missing in the rendered HTML.

Perhaps there should be some "tag" like `[preface]`, which we have in NIST, to deal with unnumbered clauses?

**Comment by opoudjis** [comment]
Yes: the prefatory material provides for Abstract, Keywords, Foreword, Submitting Organizations, Submitters, but not for Introduction, and not for other arbitrary prefatory chapters.

For now, I'm just going to add Introduction, which is inherited from metanorma-standoc. I would prefer to have confirmation before I allow arbitrary clauses into the preface.

**Comment by opoudjis** [comment]
@ronaldtse This is pending on you

**Comment by ronaldtse** [comment]
@opoudjis asked, pending reply.

**Comment by ronaldtse** [comment]
@opoudjis I have confirmation: the "Introduction" is not allowed. The "Introduction" should belong to the scope. Will see how OGC decides on whether to allow it as an "optional" one for backwards compatibility.

**Comment by opoudjis** [comment]
In that case, closing; you can reopen if there is advice to the contrary.
