### ISSUE TITLE
PDF: Move "Admitted" term instances to separate lines to prevent confusion

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#350]
It is confusing to see that the "preferred term" and "admitted term" are on the same line. I can't tell whether the term is "conceptual model CM" or "conceptual model".

<img width="791" alt="Στιγμιότυπο 2022-01-11, 21 30 10" src="https://user-images.githubusercontent.com/1911039/148926426-377c8cf8-b40a-4f8b-a603-8e7f92708632.png">

@intelligent2013 could you help do that at the same indentation? Thanks!

_Originally posted by @opoudjis in https://github.com/metanorma/metanorma-ogc/issues/339#issuecomment-1009825970_

**Comment by Intelligent2013** [comment]
OGC xslt updated.
Before:
![image](https://user-images.githubusercontent.com/5559926/149491449-f39eeb26-4c2d-42fd-8b3b-850895d96364.png)

After:
![image](https://user-images.githubusercontent.com/5559926/149491496-c40ce155-5cc1-417f-9354-653a7b55eeb0.png)

**Comment by ronaldtse** [comment]
@Intelligent2013 thabks. Can we keep the “CM” aligned with “conceptual model”?

**Comment by Intelligent2013** [comment]
> Can we keep the “CM” aligned with “conceptual model”?

@ronaldtse done:

![image](https://user-images.githubusercontent.com/5559926/149498819-825e5299-aa9c-43c9-8dd7-06e1b47be314.png)

**Comment by ronaldtse** [comment]
Thank you @Intelligent2013 this is perfect!
