### ISSUE TITLE
Failures in fetching some references

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#352]
```
[relaton-w3c] ("W3C XML Base") not found.
[relaton-w3c] ("W3C XMLSchema-1") not found.
[relaton-w3c] ("W3C XMLSchema-2") not found.
[relaton-w3c] ("W3C XPointer") not found.
[relaton-w3c] ("W3C XLink") not found.
[relaton-w3c] ("W3C XML") not found.
[relaton-w3c] ("W3C XMLName") not found.
[relaton-iso] WARNING: no match found online for ISO/IEC 19775:2004. The code must be exactly like it is on the standards website.
[relaton-iso] If you wanted to cite all document parts for the reference, use "ISO/IEC 19775 (all parts)".
```

**Comment by ronaldtse** [comment]
@andrew2net any idea how to cite the W3C standards? Thanks! (ping @anermina @manuel489 )

**Comment by andrew2net** [comment]
@ronaldtse suppose we should use these references:
`W3C XML Base` -> `W3C REC-XMLBase-20010627` or `W3C REC-XMLBase-20090128`
`W3C XMLSchema-1` -> `W3C REC-xmlschema-1`
`W3C XMLSchema-2` -> `W3C REC-xmlschema-2`
`W3C XPointer` -> `W3C WD-XPTR-XPointer-20021219`
`W3C XLink` -> `W3C REC-XLink-20010627`
`W3C XML` -> `'W3C REC-XML`
`W3C XMLName` -> `W3C REC-XML-names`

**Comment by opoudjis** [comment]
Ribose has a site where you enter name of doc and it gives you the authoritative identifier; is that working now?

I will check whether these iDs fetch, and whether it is straightforward for end users to find those IDs online. Using the simpler IDs is desirable, but if it is not feasible, we will just need to document this on relaton.org

**Comment by opoudjis** [comment]
Of the foregoing codes, all of:

* W3C XML Base
* W3C XMLSchema-1
* W3C XMLSchema-2
* W3C XLink
* W3C XML

successfully retrieve a bibliographic record on Relaton.

The following do not:

* W3C XPointer
* W3C XMLName

Instead, the following do:

* W3C XPTR; cf: https://www.w3.org/TR/xptr/
* W3C XML-Names; cf: http://www.w3.org/TR/xml-names/

Given that the successful searches match the undated  reference codes in the URLs, I think the major issue this ticket was about has been addressed: if you want to retrieve a W3C document, get its latest URL, and look up in it as the reference code, prefixed by W3C. https://github.com/relaton/relaton-w3c points to the source data, which is (of course) in RDF.

I think the behaviour here is reasonable. Closing ticket.

**Comment by ronaldtse** [comment]
Thanks for the timely reminder — we should update the Relaton site to teach users how to find the IDs for referencing.

**Comment by opoudjis** [comment]
> Thanks for the timely reminder — we should update the Relaton site to teach users how to find the IDs for referencing.

Ticket or it won't happen.

**Comment by opoudjis** [comment]
@ghobona The site you are recalling that you could search bibliography on is https://bib.ietf.org , but its coverage is specific to IETF, so it does not have all the W3C specifications.
