### ISSUE TITLE
Replace text of License Agreement with a reference

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-ogc#356]
Please replace the text of the License Agreement with a reference to this web page on the OGC website https://www.ogc.org/license 

An illustration is below.

![LicenseAgreement](https://user-images.githubusercontent.com/18121038/150401657-fee8c925-3070-4f31-a605-ac075669ac09.png)

**Comment by ronaldtse** [comment]
@ghobona can we confirm that all documents, legacy and future, will use this new license agreement content?

**Comment by opoudjis** [comment]
@ghobona We cannot action this ticket without a response as to whether this change applies to documents created only from this point forward, or retrospectively as well. Please respond.

**Comment by opoudjis** [comment]
I'm going to make it retrospective.
