### ISSUE TITLE
CLI failing to load stix_two_math font causes pipeline to fail

### ISSUE THREAD

**Issue by gbuehler** [metanorma/metanorma-ogc#357]
I have attempted to run Metanorma via the .gitlab-ci.yml file on the Gitlab pipeline and also locally 

> docker run -v "$(pwd)":/metanorma metanorma/mn metanorma compile -t ogc -x xml,html,doc,pdf --agree-to-terms document.adoc

on several different repositories (one of which build successfully yesterday with no changes)

Here is the snippet of the log:

```
....
- /config/fonts/trebucbi.ttf
- /config/fonts/Verdanaz.ttf
Downloading font "google/stix_two_math" from https://fonts.google.com/download?family=STIX%20Two%20Math
/usr/local/bundle/gems/fontist-1.13.0/lib/fontist/utils/downloader.rb:39:in `raise_if_tampered': The downloaded file from https://fonts.google.com/download?family=STIX%20Two%20Math doesn't match with the expected sha256 checksum (429bd510636b72ac19d9dbcdaa5d4e3992bd9719bcb5e175be468110c971877c)! (Fontist::Errors::TamperedFileError)
Beginning of content: PK\x03\x04\x14\0\b\b\b\0\0\0�R\0\0\0\0\0\0\0\0\0\0\0\0\a\0\0\0OFL.txt�Wێ��\x11}'�\c?(�C�\x0183\x1Eg�\0~�%�C�Di)��~�Ȗ�1�f�I���/ɧ�Kr����8�e��5dwթSU��#����l;�����݇�\x1F\x1E)�
Zf��4QM
....
```

I understand that the issue is with the font package, but is there a way to bypass such problems?

**Comment by ronaldtse** [comment]
Thank you @gbuehler (also ping @ghobona), we will deal with this issue here: fontist/formulas#98

**Comment by ronaldtse** [comment]
@gbuehler @ghobona there is one way to avoid these remote font issues once and for all -- to host these fonts internally from OGC. That may require removal of support for non-open-source fonts. Is that an option?

**Comment by gbuehler** [comment]
@ronaldtse 
I would think that this could be an optional  flag, so
 
--use-local-fonts 
 --agree-to-terms

should be exclusive flags.   Then I would only use the local fonts as a work around for when fonts break.

Would that make sense?

**Comment by opoudjis** [comment]
From Alexei:

> It's a tricky question: there is no direct option for fontist not to attempt installing fonts if some of them is not found in a system. But if all fonts are found (either among system ones, or in fontist cache), fontist will just use cached fonts.

@ronaldtse @gbuehler  need your feedback here. My inclination is to close this ticket, and possibly create a backlog ticket on fontist to install from a local directory. But this was raised two years ago, so I want to confirm that there is still a need for such functionality.

**Comment by opoudjis** [comment]
@ghobona @gbuehler I am going away on holiday from 16 Jan until 29 Jan, and I expect we will catch up in early Feb as normal. A reminder that this issue is still pending.

**Comment by opoudjis** [comment]
Fontist caching has go-ahead

**Comment by ghobona** [comment]
Discussed 2024-02-15

**Comment by ghobona** [comment]
Discussed 2024-04-29

- Agreed to replace proprietary fonts with open alternatives.

**Comment by ronaldtse** [comment]
@gbuehler @ghobona please let us know what set of alternative fonts work so we can enact the change. For those who use Word Doc output they will need to install those non-Microsoft fonts manually.

**Comment by ghobona** [comment]
2024-07-08 Discussed with OGC Staff and confirmed to proceed with open fonts.

**Comment by opoudjis** [comment]
Still waiting on https://github.com/fontist/fontist/issues/375

**Comment by opoudjis** [comment]
@Intelligent2013 I've just replaced Arial with Roboto in OGC PDF config; do you need to update anything?

**Comment by Intelligent2013** [comment]
@opoudjis  `ogc.white-paper.xsl` updated.
