### ISSUE TITLE
Debug request: images not shown in Windows Word?

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#36]
A user reported:

> images are coming through fine in the html renders of the documents, but they aren’t visible in the word.doc file. The word file’s size implies that the figures are in there but maybe not in a format that can be displayed...
> [...] I note that for a .gif image, is at least showing something, but it still isn’t correct.

I'm running the same document on macOS but they show up in Word.

This seems to be an incompatibility we have with Windows Word.

@CAMOBAP795 can you help debug / fix this? Thanks!

**Comment by CAMOBAP795** [comment]
Ok let me summarize my research:
 - produced `.doc` file actually not isn't [MS Word .doc format](https://docs.microsoft.com/en-us/openspecs/office_file_formats/ms-doc/ccd7b486-7881-484c-a137-51170af7cc22) it's actually [MIME Encapsulation of Aggregate Documents (MHTML)](https://tools.ietf.org/html/rfc2557) usually these files have `mht` extension
 - According to https://www.techwalla.com/articles/how-to-open-mht-documents-on-a-mac `mht` can be opened with Google Chrome or Microsoft Word on OSX

Unfortunately, I have no Microsoft Word for Mac, so I cannot test it.
But I have tested `doc` which was generated during test execution, and chrome shows a blank page

@ronaldtse if you can request examples of generated doc files (which doesn't render images) or can instruct me how to generate ones it will be nice

Till this, I will investigate why `doc` which was generated during tests show nothing in Google Chrome

**Comment by ronaldtse** [comment]
@CAMOBAP795 you might have misunderstood the issue:

* The issue is that images are shown in the generated Word file in Mac Word, but seems to be hidden in Windows Word.
* DO NOT test this in Chrome

You can get the generated files here: https://metanorma.github.io/isodoc-rice/ , all word files here show up properly in Mac Word.

I suspect you have to tweak the MHT syntax to have images show up in Windows Word.

**Comment by CAMOBAP795** [comment]
@ronaldtse just checked with MS Word 2016, on windows it works perfectly, can we request more info about application versions which used to open/edit `doc` file?

**Comment by ronaldtse** [comment]
Thanks. Hmmm OK I will find out!

On the other hand, can you check AppVeyor's output to see if you can also open them?
* It might be the case where the "MHT generation" mechanism on Windows doesn't work, where the same mechanism on Linux (Travis) and macOS works?

**Comment by CAMOBAP795** [comment]
@ronaldtse good point, let me check

**Comment by CAMOBAP795** [comment]
@ronaldtse your assumption was right, thanks

There is a problem with generation base64 images on windows because they can not be decoded back, AFAIR I already fixed a similar problem in some gem, so I hope it will not take much time

Except this, we have an issue with path handling on windows because `metanorma compile` issues for `mn-templates-*` repos for example https://ci.appveyor.com/project/ribose/mn-templates-csd/builds/24981596

If you will switch to the directory where `.adoc` located compilation works without any problems, there is no such problem on *nix OSes

---

Let me summarize a list of issues:
 - [ ] base64 image encoding on windows
 - [ ] `metanorma compile ...` path handling issues on windows
 - [ ] `metanorma compile ...` don't return non-zero exit code in case of error

I will create separate issues for the last 2 problems

**Comment by ronaldtse** [comment]
Thank you @CAMOBAP795 !

I think the path issues are also related to:
* https://github.com/metanorma/metanorma-standoc/issues/53
* https://github.com/metanorma/metanorma/issues/49

**Comment by CAMOBAP795** [comment]
@ronaldtse https://github.com/metanorma/html2doc/pull/25 -ready for review

**Comment by CAMOBAP795** [comment]
> I think the path issues are also related to

@ronaldtse I'm not sure because this issue reproduces on windows only

**Comment by CAMOBAP795** [comment]
@ronaldtse I think it's ready to be closed

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP795 !

**Comment by ronaldtse** [comment]
@CAMOBAP795 I created the two missing issues now. Can you please help handle them? Thanks.
