### ISSUE TITLE
PDF: Exclude subfigures from index of figures

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-ogc#362]
Follow-on from #361:

There is no reason to list the subfigures separately from figures in an index of figures

![](https://user-images.githubusercontent.com/1911039/153173940-c22c0721-b08d-47ad-9992-a30569be83bb.png)

**Comment by Intelligent2013** [comment]
@opoudjis does this task relate for empty subfigure's title or for all? For instance, there are cases, when subfigures titles aren't empty:
![image](https://user-images.githubusercontent.com/5559926/153181084-f461fb5a-29c5-41a9-9d24-927636c35735.png)

**Comment by opoudjis** [comment]
In my opinion, it does apply to all subfigures, but let's confirm with @ronaldtse

**Comment by ronaldtse** [comment]
I think we should still display subfigure captions. Why do we want to omit them?

**Comment by opoudjis** [comment]
Because particularly if the subfigures don't have captions (and they often don't, as in the example above), what value are they adding? But won't insist.

**Comment by opoudjis** [comment]
Annuled
