### ISSUE TITLE
PDF: Annex subsections should be styled in the same font size as normal subsections

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#364]
<img width="580" alt="Screenshot 2022-02-10 at 8 55 45 AM" src="https://user-images.githubusercontent.com/11865/153316152-00b9257d-57f3-499c-97d3-066831e8d82a.png">

**Comment by Intelligent2013** [comment]
Done:
![image](https://user-images.githubusercontent.com/5559926/153351942-22587f45-c336-4878-ba61-ab63fae332f5.png)

**Comment by Intelligent2013** [comment]
Completed half-year ago.
