### ISSUE TITLE
PDF: reduce list bullet indentation and list item indentation

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#365]
The indentation amount now causes text to be pushed to the right (not enough space).

Can we reduce both the:
* list bullet indentation
* list text indentation from the bullet
?

We still want these two indentations to be "balanced" (equal whitespace for both types). Thanks!

![image](https://user-images.githubusercontent.com/11865/153316749-ee854d64-cdbb-4356-8f0f-d1dfa60e0482.png)

This is quite visible in the attached document.
[21-035r1.zip](https://github.com/metanorma/metanorma-ogc/files/8037214/21-035r1.zip)

**Comment by Intelligent2013** [comment]
Done:
![image](https://user-images.githubusercontent.com/5559926/153351639-aac8fb74-76cc-4b1b-beb2-b9822f4bd360.png)
