### ISSUE TITLE
(URGENT) HTML: LucidChart generated SVGs appearing with broken text

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#366]
I have encountered this problem in authoring OGC 21-035r1:
http://ogc.pages.ogc.org/T17-D022-Model-Driven-Standards-ER/documents/document.html

(For those with access, the repo is at https://gitlab.ogc.org/ogc/T17-D022-Model-Driven-Standards-ER/)

Here's the HTML output from Metanorma:

Figure 1:

PDF | HTML
--|--
<img width="589" alt="Screenshot 2022-02-10 at 12 13 18 PM" src="https://user-images.githubusercontent.com/11865/153335873-63cfbf48-8bca-4728-a249-327881ec050d.png"> | <img width="760" alt="Screenshot 2022-02-10 at 12 12 43 PM" src="https://user-images.githubusercontent.com/11865/153335815-9c0b0bea-3702-42d1-a7f7-5f346466b6af.png"> 

So far so good. But in Figure 2:

PDF | HTML
--|--
<img width="611" alt="Screenshot 2022-02-10 at 12 13 53 PM" src="https://user-images.githubusercontent.com/11865/153335929-b8738221-1cc6-46f4-ac3a-c98aeca20f7e.png">| <img width="835" alt="Screenshot 2022-02-10 at 12 08 15 PM" src="https://user-images.githubusercontent.com/11865/153335332-c5ede8a6-8307-4773-8bbf-1ff62a50614f.png">

Notice that HTML Figure 2 is still showing some remnant from Figure 1?

I think this may be related to the fact we are using "Inline SVG" instead of "Embedded SVG". However, it is very strange that the different SVGs interfere with each other. I suspect that there are SVG/CSS styling classes in Figure 1 that break Figure 2.

The questions for us:
* is there a way for us to "contain" these styling rules even during inlining?
* do we preprocess these SVG images?
* do we inline them?

This is the original file:
* Figure 1: ![conceptual-truth-derived](https://user-images.githubusercontent.com/11865/153336012-0e0a3db7-a4b0-4eec-893f-a20946af9f77.svg)
* Figure 2: ![conceptual-pim-psm](https://user-images.githubusercontent.com/11865/153336034-d01e6b85-6a4c-40ea-882d-57131763f220.svg)

These diagrams were directly exported from LucidChart via the "Export as SVG with transparent background" function.

**Comment by opoudjis** [comment]
Because imagemaps are currently already working in 10303, and are assuming globally unique ids, we don't want to just append suffixes to all ids in all svgs: we only want to do so in non-unique ids. This means we do have to iterate through all svgs. Per the makeIdsUnique method in https://github.com/iconfu/svg-inject/blob/master/src/svg-inject.js , that's going to be quite an expensive transformation, but the alternative of embedded SVG is also a non-starter, since we want to distribute the HTML as a single file.

Oh well.
