### ISSUE TITLE
Add requirement label to requirement caption automatically

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-ogc#367]
So _Requirement 1: /req/xxxx_. This will make cross-references more intelligible, including from ToC.

**Comment by ronaldtse** [comment]
Thanks @opoudjis , would be much better than this!

<img width="551" alt="Screenshot 2022-02-10 at 7 38 44 PM" src="https://user-images.githubusercontent.com/11865/153401535-f81dbb39-2624-471a-bc1e-3eb45918240c.png">

**Comment by opoudjis** [comment]
The label is already given a heading row in the table, so I will only include it in the crossreference.

**Comment by opoudjis** [comment]
I've implemented these xrefs, which is a value add to OGC; but it turns out that the PDF ToC is generated autonomously by @Intelligent2013,  and not (currently) out of Presentation XML. So I'll assign him a separate task.

**Comment by opoudjis** [comment]
Add RecommendationLabel class to paragraph containing recommendation labels, so that ToC entry can identify and include it.
