### ISSUE TITLE
Policy template generated broken Normative References section

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-ogc#369]
Using the latest docker image to build a policy document generates a 'broken' references section. See attached.

![Screenshot 2022-02-16 at 11 28 30](https://user-images.githubusercontent.com/18121038/154256228-c41f426e-d18a-4282-9020-ff9df9b30a9b.png)

The source files are in this archive.

[OGCNANameTypeSpecificationForDefinitions.zip](https://github.com/metanorma/metanorma-ogc/files/8079491/OGCNANameTypeSpecificationForDefinitions.zip)

**Comment by ronaldtse** [comment]
@ghobona this issue is resolved here:
https://github.com/metanorma/OGCNANameTypeSpecificationForDefinitions/issues/1
