### ISSUE TITLE
PDF: Add requirement label to requirement caption for ToC

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-ogc#370]
Follow-on from https://github.com/metanorma/metanorma-ogc/issues/367

In the table of contents, you currently give the label of the requirement:

![](https://user-images.githubusercontent.com/11865/153401535-f81dbb39-2624-471a-bc1e-3eb45918240c.png)

It is desired to append to this the label of the requirement if present; e.g.

````
<table id="annotation-format" class="recommendation" type="recommend">
<thead><tr><th scope="colgroup" colspan="2"><p class="RecommendationTitle">Recommendation 1</p></th></tr></thead><tbody><tr><td colspan="2"><p class="RecommendationLabel">/rec/mbs/annotation-format</p></td>
....
</table>
````

This is currently indexed as "Recommendation 1" in the Recommendations ToC. If a RecommendationLabel paragraph is present (which I'm now adding to OGC), then we wish the ToC to instead have the entry `Recommendation 1: <tt>/rec/mbs/annotation-format</tt>`

**Comment by Intelligent2013** [comment]
Done.
Rendering example (I've added `class="RecommendationLabel"` manually  in my xml sample):
![image](https://user-images.githubusercontent.com/5559926/154295503-3297ab2c-9a2f-4234-a213-4df106c35a38.png)
