### ISSUE TITLE
Add a way to mark dependencies as indirect

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-ogc#374]
Some requirements may be direct and others may be indirect. A definition is in Clause 4.10 of the [ModSpec](https://portal.ogc.org/files/?artifact_id=34762).

Please add a way to mark dependencies as indirect, as illustrated on the attached figure.

![Screenshot 2022-02-25 at 14 59 52](https://user-images.githubusercontent.com/18121038/155737828-dfc30040-8b16-44e4-8a8d-dfd1bac675c2.png)

**Comment by ghobona** [comment]
@opoudjis Any update on this ?

**Comment by opoudjis** [comment]
I'm about to look at this.

**Comment by opoudjis** [comment]
Dependency is marked up as `inherit:[]`. Indirect dependency, as with every category not in our default model of requirements, shall be marked up as a metadata definition list term:

````
[%metadata]
indirect-dependency: xxx
````
