### ISSUE TITLE
Generated templates should not include introductory paragraph of Terms and Definitions section

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-ogc#376]
When generating a document template using metanorma,  the text highlighted on the following screenshot is automatically added to the template.

![Screenshot 2022-04-22 at 11 23 52](https://user-images.githubusercontent.com/18121038/164691591-2c40040b-14d3-4bbb-a08a-931dc76db1e1.png)

However, when compiling the document, similar text is automatically added above the text that was provided in the template. See the screenshot below.

![Screenshot 2022-04-22 at 11 24 46](https://user-images.githubusercontent.com/18121038/164693009-8555fa2d-39b7-4719-aa38-448bf261f537.png)

The text highlighted on the screenshot above should not be added when generating the document template.

**Comment by opoudjis** [comment]
There is a way to do this in metanorma with options, will locate and add to template.

**Comment by ghobona** [comment]
Ideally we should just update the documentation in the template to remind editors that metanorma will automatically add the header information.

**Comment by opoudjis** [comment]
@ghobona I have unearthed a new issue:

In the templates, several document types have supplied their own notice, which omits mention of Modspec (and which I think reflects the older wording of the notice):

* Abstract specification (but not Abstract specification notice)
* Best practice
* Discussion paper
* Release notes
* Standard implementation

Is the omission of Modspec in error? If so, then I will get rid of these.

Is the omission of Modspec deliberate? If so, then I need to be customising the default message in code, not in the templates.

**Comment by opoudjis** [comment]
@ghobona I am going away on holiday from 16 Jan until 29 Jan, and I expect we will catch up in early Feb as normal. A reminder that this issue is still pending.

**Comment by opoudjis** [comment]
Modspec should be mentioned.

**Comment by ghobona** [comment]
Discussed 2024-02-15

**Comment by opoudjis** [comment]
I am replacing the supplied older text

````
This document uses the terms defined in Sub-clause 5.3 of <<OGC06-121r9>>, which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word "`shall`" (not "`must`") is the verb form used to indicate a requirement to be strictly followed to conform to this standard.

For the purposes of this document, the following additional terms and definitions apply.
````

with a comment, as done in other types, that the default text is being inserted, that is:

````
  <p>This document uses the terms defined in <link target="https://portal.ogc.org/public_ogc/directives/directives.php">OGC Policy Directive 49</link>, which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this document and OGC documents do not use the equivalent phrases in the ISO/IEC Directives, Part 2.</p>
  <p>This document also uses terms defined in the OGC Standard for Modular specifications (<link target="https://portal.opengeospatial.org/files/?artifact_id=34762">OGC 08-131r3</link>), also known as the 'ModSpec'. The definitions of terms such as standard, specification, requirement, and conformance test are provided in the ModSpec.</p>
````
