### ISSUE TITLE
HTML: odd behavior of side table of contents

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-ogc#378]
Table of contents in HTML output gets broken when clicking to retract it.

Check the page: https://docs.ogc.org/is/20-010/20-010.html

**Comment by ronaldtse** [comment]
@s4birli would you be able to help here?

**Comment by opoudjis** [comment]
Once @s4birli has actioned this, let me know so I can incorporate into metanorma. Right now, I cannot do anything about this.

**Comment by opoudjis** [comment]
This still needs to be fixed. @ronaldtse we need access to a front end developer.

**Comment by ghobona** [comment]
Discussed 2024-02-15

Can be closed

**Comment by opoudjis** [comment]
Dupe of https://github.com/metanorma/metanorma-ogc/issues/557
