### ISSUE TITLE
(URGENT) Failure of footnote reference syntax `footnote:ref[]`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#383]
In https://github.com/metanorma/isodoc/issues/155 the syntax `footnote:ref[]` can be used to reuse a footnote called `ref`.

It is not working in OGC HTML and PDF.

```adoc
.Parts of BoundingBox data structure
[cols="a,a,a,a",options="header"]
|===
| Names | Definition | Data type and values | Multiplicity and use

| lowerLeft
| Coordinates of bounding box corner at which the value of each coordinate
normally is the algebraic minimum within this bounding box

footnote:a[Values other than the minimum and maximum may be used as discussed below.]

| Ordered sequence of double values

footnote:b[The number of axes included, and the order of these axes, as specified by the referenced CRS.]
| One (mandatory)

| upperRight
| Coordinates of bounding box corner at which the value of each coordinate
normally is the algebraic maximum within this bounding box{blank}footnote:a[]
| Ordered sequence of double values{blank}footnote:b[]
| One (mandatory)

...
```

Rendered as:

PDF:
<img width="657" alt="Screenshot 2022-05-26 at 2 29 35 AM" src="https://user-images.githubusercontent.com/11865/170340118-7845f024-9a7b-4d31-a73c-42ff4638b8ff.png">

HTML:
<img width="887" alt="Screenshot 2022-05-26 at 2 29 59 AM" src="https://user-images.githubusercontent.com/11865/170340242-96da1305-98cd-40ba-aaf9-42993a8b6455.png">

Document: https://github.com/metanorma/ogc-2D-Tile-Matrix-Set

**Comment by opoudjis** [comment]
Normal footnotes and table footnotes are processed separately. As normal footnotes, the behaviour is correct; the redundant footnotes need to be extended to tables.

**Comment by opoudjis** [comment]
The bug is: if asciidoctor formatting is used in a table, the cell has no visibility of any other footnotes in the document. I suspect that is because each table cell is treated as a brand new document, without inheriting the footnotes generated elsewhere.

In any case, I don't see an earthly reason why you're saying that the cells need to be Asciidoctor documents to begin with. Just make this `[cols="1,1,1,1"]`: you're not going any special formatting here.

**Comment by opoudjis** [comment]
Raised as https://github.com/asciidoctor/asciidoctor/issues/4295

I can't fix this, and suggest you avoid this scenario.
