### ISSUE TITLE
(URGENT) Notes with multiple paragraphs inside are shown as one single paragraph

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#386]
From @anermina: 

> * PDF: It seems that paragraphs aren't being separated in multi-paragraph notes to entries. @manuel489 , could you please confirm before I open a ticket to address this issue?

![image](https://user-images.githubusercontent.com/55683568/173700061-f30f85e6-7bec-4f5b-9d98-7103fbb4c8a4.png)
vs. original:
![image](https://user-images.githubusercontent.com/55683568/173700104-0fcd4f19-4077-47a8-a499-21587078542b.png)

I can confirm this -- the paragraphs inside a NOTE are all mixed into one.

In HTML it is kept as separate paragraphs though.

<img width="794" alt="Screenshot 2022-06-15 at 9 23 34 AM" src="https://user-images.githubusercontent.com/11865/173710894-b53ac2e4-e510-4dd8-b192-2bcfab987cb7.png">

And it is correct in Presentation XML:

```xml
        <termnote id="_3b974d8a-ecb8-0c82-efd5-bccd9eb48c4f">
          <name>Note 1 to entry</name>
          <p id="_86bc8221-980c-453d-bf8a-75df10228e0b">Each <em>requirement</em> is a normative criterion for a single <strong>type of standardization target</strong>. In this standard, requirements will be associated to
<em> conformance tests</em> that can be used to prove
compliance to the underlying criteria by the
<em>standardization target</em>.</p>
          <p id="_fd167ca6-1b18-3176-c9c4-66710aec076f">The implementation of a <em>requirement</em> is dependent on the type of
specification being written. A data specification requires data structures, but a
procedural specification requires software implementations. The view of a standard in
terms of a set of testable <em>requirements</em> allows us to
use set descriptions of both the standard and its implementations.</p>
          <p id="_cf2be0aa-724a-5cc8-9240-3c0d099d46ba">The specification of a <em>requirement</em> is usually expressed in terms
of a model of the <em>standardization target</em>, such as a UML model, or
an XML or SQL schema. Anything without a defined test is <em>a priori</em> not testable and
thus would be better expressed as a <em>recommendation</em>.</p>
          <p id="_29715bde-5e25-c1a4-0c9f-82f45544eff9"><em>Requirements</em> use normative language and in particular
are commands and use the imperative “shall” or similar imperative constructs.
Statements in standards which are not requirements and need to be either conditional
or future tense normally use “will” and should not be confused with requirements that
use “shall” imperatively.</p>
        </termnote>
```

@Intelligent2013 this is a bug -- can you please help handle it?

_Originally posted by @ronaldtse in https://github.com/metanorma/ogc-modspec/issues/3#issuecomment-1155838853_

**Comment by Intelligent2013** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/5559926/173771534-82680611-15fc-4f28-87f1-da4f63c848dd.png)

**Comment by ronaldtse** [comment]
Thanks!
