### ISSUE TITLE
Conformance tests unable to link to requirements containing IDs

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-ogc#394]
In relation to https://github.com/metanorma/ogc-GeoPose/pull/2

According to my tests, it seems that conformance tests are unable to link to
their corresponding requirements when the latter contain an `id` value.

```adod
[[conf_geopose_instant_sdu]]
[conformance_test,id="rta13"]
====
[%metadata]
name:: GP-Instant-SDU
label:: /conf/geopose_instant/sdu
subject:: <<req_time_geopose_instant_sdu,Requirement "GP-Instant-SDU">>
description:: To confirm the correct properties of a GeoPose Instant.
test-purpose:: To confirm that a Logical Model attribute GeoPoseInstant is Unix Time in
seconds multiplied by 1,000 and that the unit of measure is milliseconds.
reference:: /req/time/geopose_instant/sdu
test-method:: Inspection
====

...

[[req_time_geopose_instant_sdu]]
[requirement,id="req11"]
====
[%metadata]
name:: Graph-SDU
label:: /req/time/geopose_instant/sdu
description:: The Logical Model attribute GeoPoseInstant SHALL be expressed in Unix
Time in seconds multiplied by 1,000. The unit of measure SHALL be milliseconds.
====
````

From this configuration I get:
````
Requirements: (XML Line 001942): Conformance test rta13 has no corresponding Requirement
````

If I remove `id="req11"`, the problem gets solved.

**Comment by ronaldtse** [comment]
@manuelfuenmayor why do we have need an "id" value?

This line:
```
reference:: /req/time/geopose_instant/sdu
```

Already links the conformance test with the requirement?

**Comment by manuelfuenmayor** [comment]
@ronaldtse well, that comes from original source... So I didn't want to remove it because I didn't know if it was necessary in some aspect. Are going to need it?

**Comment by ronaldtse** [comment]
> @ronaldtse well, that comes from original source... So I didn't want to remove it because I didn't know if it was necessary in some aspect. Are going to need it?

I've investigated, we should remove all of those.

**Comment by opoudjis** [comment]
I agree. 

The link from conformance test to requirement is made in `subject:: <<req_time_geopose_instant_sdu,Requirement "GP-Instant-SDU">>`. That link, obviously, requires the anchor of the requirement block to be req_time_geopose_instant_sdu

If you provide an id attribute for that requirement, that id will override the supplied anchor! As far as I know, that's built in Asciidoctor behaviour --- I don't use "id" as an attribute myself. So:

````
[[req_time_geopose_instant_sdu]]
[requirement,id="req11"]
````

req11 ends up overwriting req_time_geopose_instant_sdu as the anchor, and the link to req_time_geopose_instant_sdu ends up broken.

Don't know how the ids got there and why, but yes, they are breaking the links, and if nothing links to them, they should go. (If something does link to them, then those links need to be replaced with the other id anyway.)
