### ISSUE TITLE
ModSpec implementation refinement: link between requirement/conformance test and classes only needs to be defined one-way

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#395]
Links between these objects only require definition from one (1) end:
- requirements class and conformance class
- requirement and conformance test

i.e.
```adoc
[requirements_class]
====
[%metadata]
identifier:: /req/regular_series/sdu
subject:: Implementation of Logical Model
inherit:: /req/global

Regular Series Logical Model SDU
====

[conformance_class]
====
[%metadata]
name:: Regular Series SDU
identifier:: /conf/class/regular_series/sdu
requirements-class:: /req/regular_series/sdu
subject:: Target Type:SDU
inherit:: /conf/global

To confirm that components of a Regular Series conform to the Logical Model.
====
```

This should render both the Requirements class and Conformance class with a link (or links) to each other.

**Comment by opoudjis** [comment]
.... Huh?

There is no "requirements-class" attribute. The links are already bidirectional, you're just not specifying the subjects in a format that metanorma-ogc recognises:

````
[[a1]]
[requirements_class]
====
[%metadata]
identifier:: /req/regular_series/sdu
subject:: Implementation of Logical Model
inherit:: /req/global

Regular Series Logical Model SDU
====

[conformance_class]
====
[%metadata]
name:: Regular Series SDU
identifier:: /conf/class/regular_series/sdu
subject:: <<a1,Target Type:SDU>>
inherit:: /conf/global

To confirm that components of a Regular Series conform to the Logical Model.
====
````

i don't know what universe `subject:: Target Type:SDU` comes from, but in what I've actually implemented, the subject of a conformance class is a concrete crossreference (by anchor ID or by xref) to the corresponding requirements class. So either `subject:: <<a1,Target Type:SDU>>` or subject:: a1`, where a1 is the supplied Metanorma identifier of the requirements class.

The foregoing markup works, and hyperlinks bidirectionally; see attached.

[document.html.zip](https://github.com/metanorma/metanorma-ogc/files/9242218/document.html.zip)

I therefore regard this ticket as already satisfied. If you want things done differently, you're going to have to explain why. But making up unimplemented attributes like requirements-class, and complaining that I haven't implemented bidirectional linking when I have, is bogus.

**Comment by ronaldtse** [comment]
I have no idea what `subject:: <<a1,Target Type:SDU>>` even means. This link should be:
```
{some keyword for specifying requirements class}:: /req/regular_series/sdu
```

No one should use anchor names for specifying links between requirements, requirements classes and the counterparts in conformance testing.

**Comment by opoudjis** [comment]
Done in https://github.com/metanorma/metanorma-ogc/issues/398
