### ISSUE TITLE
ModSpec implementation refinement: use `id` and `identifier` as metadata labels for the definition list

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#396]
The name of `label` for the ModSpec instance identifier makes no sense at all.

It is the unique identifier of the instance (a URI), and therefore should be called `identifier` or `id` (as a shortcut).

Moreover, this `id` must be a PLAIN STRING because it is **a URI**. Anything else is wrong.

This is from https://www.metanorma.org/author/ogc/topics/requirements/:
```adoc
[requirements_class]
.GWML2 core logical model
====
[%metadata]
label:: http://www.opengis.net/spec/waterml/2.0/req/xsd-xml-rules[*req/core*]
...
====
```

It should just be:
```adoc
[requirements_class]
.GWML2 core logical model
====
[%metadata]
id:: /req/core
...
====
```

**Comment by opoudjis** [comment]
Have done, as identifier not id.
