### ISSUE TITLE
ModSpec implementation refinement: `id` accepting fields should only accept IDs

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#397]
In ModSpec instance specifications, there are fields that take `id`s of other instances (their URIs) as identifiers.

e.g.

```adoc
[requirements_class]
====
[%metadata]
id:: /req/req-class-building
subject:: Implementation Specification
inherit:: <<rc_core,/req/req-class-core>>
inherit:: <<rc_construction,/req/req-class-construction>>
====

[conformance_class]
====
[%metadata]
id:: /conf/crs
subject:: <<rc_crs,Requirements Class 'Coordinate Reference Systems by Reference'>>
conformance-test:: /conf/crs/module
====

[abstract_test]
====
[%metadata]
id:: /conf/core/classes
requirement:: /req/core/classes

[.component,class=test-purpose]
--
To validate that the Implementation Specification correctly implements the UML
Classes defined in the Conceptual Model.
--
====

```

The fields are:
* `inherit` in requirements class, conformance class, requirement, conformance test
* `requirement` in requirements class, conformance test
* `conformance-test` in conformance class, requirement

In the current implementation,
* conformance test (of which abstract test is a specialization of) takes `subject` but it should really be `requirement`.

**Comment by opoudjis** [comment]
Requirement / Conformance-Test as headings have already been implemented as `target`, taking an identifier.

Introducing hyperlinking for inherit fields, and restriction to label links.
