### ISSUE TITLE
Conformance class not linking to Requirement Class when URI is provided as subject

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-ogc#401]
As described in @ronaldtse's [comment](https://github.com/metanorma/ogc-GeoPose/pull/2#discussion_r928285539).
A conformance class subject attribute should point to the URI of their
corresponding Requirement Class, through the `subject` attribute.

For example, following conformance class:

```adoc
[[conf_global]]
[conformance_class]
====
[%metadata]
label:: /conf/global
subject:: /req/global
...
====
````

Should be linked to:

```adoc
[[rc_global]]
[requirements_class]
====
[%metadata]
label:: /req/global
subject:: SDU
description:: Global SDU Requirements
requirement:: /req/target_dependency
requirement:: /req/sdu_general
requirement:: /req/lm_general
====
````

However, this is not happening:
````
Requirements: (XML Line 003272): Conformance class test conf_global has no corresponding Requirement class
````

**Comment by opoudjis** [comment]
Well, we're doing it (grrrr). The current implementation is being abandoned in favour of target:: and labels. Merging into https://github.com/metanorma/metanorma-ogc/issues/398

**Comment by opoudjis** [comment]
Done in https://github.com/metanorma/metanorma-ogc/issues/398
