### ISSUE TITLE
PDF version swaps Conformance and Scope sections

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-ogc#403]
The generated PDF appears to swap the Conformance and Scope sections around.

![Screenshot 2022-08-05 at 17 36 35](https://user-images.githubusercontent.com/18121038/183121985-4c704c51-791a-49c6-89cc-f2a692922e90.png)

Please fix the problem so that the sections are arranged in the same way as the HTML version.

**Comment by Intelligent2013** [comment]
@ghobona could you point me to the odocument adoc, please? Thanks.

**Comment by ghobona** [comment]
@Intelligent2013 There are two documents.

The first and more urgent one is in this `1.0.1` branch https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/tree/1.0.1

The second one is https://github.com/opengeospatial/ogcapi-common/pull/316

Both documents appear to be affected the same.

**Comment by Intelligent2013** [comment]
It seems the issue relates to fixed issue https://github.com/metanorma/metanorma-ogc/issues/390, but I can't check it due the processing error https://github.com/metanorma/metanorma-standoc/issues/659. I'll return here after fixing it.

**Comment by ronaldtse** [comment]
@ghobona I'm looking at this now.

**Comment by Intelligent2013** [comment]
@ghobona I can't repeat this issue. Looks like, it fixed earlier (https://github.com/metanorma/metanorma-ogc/issues/390). With latest gems, both rendered PDF look correct:
![image](https://user-images.githubusercontent.com/5559926/183469282-b7d8c454-b3c1-4c94-ad81-d0ca0a56fbd1.png)

Please make sure that you've installed the latest updates.

**Comment by ghobona** [comment]
Thanks @Intelligent2013.

We will update the gems and try compiling the document again.

**Comment by ghobona** [comment]
@Intelligent2013 The problem is still there after running `docker pull metanorma/mn:latest`.

@ronaldtse Does that mean metanorma-docker has not been updated with the latest gems?

**Comment by ronaldtse** [comment]
@ghobona I believe this is now fixed. This is a screenshot from GeoPose. Thanks!

<img width="522" alt="Screen Shot 2022-08-16 at 2 39 13 AM" src="https://user-images.githubusercontent.com/11865/184695567-cb39d4d4-a52c-4bb1-b08e-62f9c9e53df2.png">
