### ISSUE TITLE
Abstract tests are displayed with the label "Requirement test" not "Abstract test"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#409]
The abstract tests are being displayed with the label "Requirement test". 

![Screenshot 2022-08-08 at 10 51 12](https://user-images.githubusercontent.com/18121038/183391217-ae866153-e16d-4939-9f06-1267851bc818.png)

The label should be "Abstract test" just like in https://docs.ogc.org/is/18-062r2/18-062r2.html#toc61

_Originally posted by @ghobona in https://github.com/metanorma/ogc-GeoPose/issues/2#issuecomment-1207911200_

**Comment by opoudjis** [comment]
<img width="852" alt="Στιγμιότυπο 2022-08-16, 20 45 58" src="https://user-images.githubusercontent.com/1911039/184861433-77b416d2-5b2e-49d4-9be4-42458f5dcf28.png">

Spurious issue.

I am much too busy to have erroneous issues raised to me. Closed with extreme prejudice, earth around it salted.
