### ISSUE TITLE
OGC logo is not being displayed on the generated HTML document

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-ogc#418]
This issue appears to have started today (2022-09-09).

The OGC logo is not being displayed on the generated HTML document. Please see the attached image.

The document was compiled using `docker run -v "$(pwd)":/metanorma -v ${HOME}/.fontist/fonts/:/config/fonts metanorma/metanorma metanorma compile --agree-to-terms -t ogc -x xml,html,doc document.adoc`

![Screenshot 2022-09-09 at 16 57 06](https://user-images.githubusercontent.com/18121038/189392469-9803da48-ab9a-4802-9141-486e7145e622.png)

**Comment by ghobona** [comment]
It appears metanorma is specifying the absolute path to the svg file on the local filesystem. Ideally this should a data URI containing the image.

![Screenshot 2022-09-09 at 17 11 37](https://user-images.githubusercontent.com/18121038/189395262-fc6ac083-d8a4-4703-8929-838d12521ef9.png)

**Comment by ronaldtse** [comment]
For some reason I'm not seeing this with the same command using Docker, I tried with the ogc-tcpnp document:

```sh
docker run -v "$(pwd)":/metanorma \
  -v ${HOME}/.fontist/fonts/:/config/fonts \
  metanorma/metanorma \
  metanorma compile \
  --agree-to-terms \
  -t ogc \
  -x xml,html,doc \
  sources/ogc-tcpnp.adoc
```

<img width="859" alt="Screen Shot 2022-09-10 at 2 21 28 AM" src="https://user-images.githubusercontent.com/11865/189418355-4007c903-528b-48ed-8114-a69c308d7b0d.png">


I changed the dates to 2029 but this issue still doesn't appear:
<img width="886" alt="Screen Shot 2022-09-10 at 2 23 56 AM" src="https://user-images.githubusercontent.com/11865/189418742-37056973-bbbf-4d83-971f-b8a6583b6908.png">

@ghobona could you please help share the full source of the document for us to reproduce? Thanks!

**Comment by ronaldtse** [comment]
@ghobona could you let me know which platform this docker run was performed in?

**Comment by ghobona** [comment]
@ronaldtse The docker was run on macOS Catalina, as well as on GitHub Action workflows.

**Comment by opoudjis** [comment]
I have just cloned https://github.com/metanorma/ogc-2D-Tile-Matrix-Set/ , and run `bundle exec metanorma site generate`. The logo is encoded as a Data URI when I generate the HTML, so I cannot replicate this error, and I strongly suspect this is an installation issue.

I've repeated with `bundle exec metanorma compile --agree-to-terms -t ogc -x xml,html,doc standard/17-083r4.adoc`  in the ogc-2D-Tile-Matrix-Set directory, reflecting what @gbuehler originally did in https://github.com/opengeospatial/ogc-metanorma-testing/issues/77 . The image was still Data URI encoded.

The only thing I can think is happening is that the installation is not finding the logo at the designated location, so it can't open it to convert it to Data URI. But the location shown looks entirely correct.

@ronaldtse You can't replicate this either, from what I read. Not clear to me what else I can do here. I'm doing a release on Monday; could I ask you to rerun it then?

**Comment by ghobona** [comment]
@opoudjis @ronaldtse When I checked this morning the issue was still there but now it is fixed.

The [daily builds](https://github.com/opengeospatial/ogcna-auto-review) have the logo embedded as a data-url. I don't know how you fixed it, but it's fixed, thanks!

**Comment by ghobona** [comment]
You may close this GitHub Issue.

**Comment by ronaldtse** [comment]
Thank you @ghobona !
