### ISSUE TITLE
Odd rendering in abstract test

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-ogc#421]
In relation to PR: https://github.com/metanorma/ogc-GeoPose/pull/2

The requirement field of an abstract test is rendering badly.

For example:
```adoc
[abstract_test]
.B-YPR-SDU
====
[%metadata]
label:: /conf/basic_ypr/target
description:: To confirm that an implementation of a Basic-YPR consists of an Outer Frame specified by an implicit WGS-84 CRS and an implicit EPSG 4461-CS (LTP-ENU) coordinate system and explicit parameters to define the tangent point. To confirm that the Inner Frame is expressed as a rotation-only transformation using Yaw, Pitch, and Roll angles.
test-purpose:: Verify that this requirement is satisfied
test-method:: Inspection
requirement:: /req/basic_ypr/target
====
````

renders

HTML:
![issue1-1](https://user-images.githubusercontent.com/33627611/190288325-07c0f9b3-d3ec-4c68-8899-a8bcc1377499.PNG)

DOC:
![issue1-2](https://user-images.githubusercontent.com/33627611/190288335-ae9d7b41-0c80-4d27-a9cf-7d5b5ccbf535.PNG)

**Comment by ronaldtse** [comment]
In the DOC, the contents of the "Abstract test" should be under a heading of "Description".

**Comment by opoudjis** [comment]
mn-requirements assumed that only Recommendation classes could contain other requirements in this way.

**Comment by opoudjis** [comment]
I'm moving specs back to mn-requirements, the separation of tests from code development is nonsense.
