### ISSUE TITLE
Erroneous warning for requirement already linked with conformance test

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#428]
Following up #420, the linking validation is not working in the GeoPose document (https://github.com/metanorma/ogc-GeoPose/pull/2).

Warning:
```
Requirements: (XML Line 001385): Requirement /req/target_dependency has no corresponding Conformance test
```

But clearly the corresponding conformance test exists, and is linked to that requirement:
<img width="706" alt="Screen Shot 2022-09-23 at 3 26 24 PM" src="https://user-images.githubusercontent.com/11865/191910836-5ab2a2be-9f3a-4474-b62a-4264ade79021.png">

**Comment by ronaldtse** [comment]
The full list of warnings I'm getting:

```
Requirements: (XML Line 001385): Requirement /req/target_dependency has no corresponding Conformance test
Requirements: (XML Line 001397): Requirement /req/sdu_general has no corresponding Conformance test
Requirements: (XML Line 001410): Requirement /req/lm_general has no corresponding Conformance test
Requirements: (XML Line 001460): Requirement /req/basic_ypr/target has no corresponding Conformance test
Requirements: (XML Line 001469): Requirement /req/tangent_plane/longitude has no corresponding Conformance test
Requirements: (XML Line 001482): Requirement /req/tangent_plane/latitude has no corresponding Conformance test
Requirements: (XML Line 001495): Requirement /req/tangent_plane/h has no corresponding Conformance test
Requirements: (XML Line 001511): Requirement /req/orientation/ypr_angles has no corresponding Conformance test
Requirements: (XML Line 001560): Requirement /req/orientation/quaternion has no corresponding Conformance test
Requirements: (XML Line 001612): Requirement /req/time/instant has no corresponding Conformance test
Requirements: (XML Line 001623): Requirement /req/frame_specification/authority has no corresponding Conformance test
Requirements: (XML Line 001634): Requirement /req/frame_specification/id has no corresponding Conformance test
Requirements: (XML Line 001645): Requirement /req/frame_specification/parameters has no corresponding Conformance test
Requirements: (XML Line 001658): Requirement /req/orientation/quaternion has no corresponding Conformance test
Requirements: (XML Line 001710): Requirement /req/frame_specification/authority has no corresponding Conformance test
Requirements: (XML Line 001721): Requirement /req/frame_specification/id has no corresponding Conformance test
Requirements: (XML Line 001732): Requirement /req/frame_specification/parameters has no corresponding Conformance test
Requirements: (XML Line 001745): Requirement /req/chain/transform_index has no corresponding Conformance test
Requirements: (XML Line 001794): Requirement /req/frame_specification/authority has no corresponding Conformance test
Requirements: (XML Line 001805): Requirement /req/frame_specification/id has no corresponding Conformance test
Requirements: (XML Line 001816): Requirement /req/frame_specification/parameters has no corresponding Conformance test
Requirements: (XML Line 001873): Requirement /req/regular_series/header has no corresponding Conformance test
Requirements: (XML Line 001884): Requirement /req/time/duration has no corresponding Conformance test
Requirements: (XML Line 001895): Requirement /req/frame_specification/authority has no corresponding Conformance test
Requirements: (XML Line 001906): Requirement /req/frame_specification/id has no corresponding Conformance test
Requirements: (XML Line 001917): Requirement /req/frame_specification/parameters has no corresponding Conformance test
Requirements: (XML Line 001930): Requirement /req/series/regular/trailer has no corresponding Conformance test
Requirements: (XML Line 001985): Requirement /req/irregular_series/header has no corresponding Conformance test
Requirements: (XML Line 001996): Requirement /req/frame_specification/authority has no corresponding Conformance test
Requirements: (XML Line 002007): Requirement /req/frame_specification/id has no corresponding Conformance test
Requirements: (XML Line 002018): Requirement /req/frame_specification/parameters has no corresponding Conformance test
Requirements: (XML Line 002031): Requirement /req/irregular_series/frame_and_time has no corresponding Conformance test
Requirements: (XML Line 002042): Requirement /req/series/regular/trailer has no corresponding Conformance test
Requirements: (XML Line 002101): Requirement /req/transition_model has no corresponding Conformance test
Requirements: (XML Line 002112): Requirement /req/frame_specification/authority has no corresponding Conformance test
Requirements: (XML Line 002123): Requirement /req/frame_specification/id has no corresponding Conformance test
Requirements: (XML Line 002134): Requirement /req/frame_specification/parameters has no corresponding Conformance test
Requirements: (XML Line 002147): Requirement /req/stream/frame_time_element has no corresponding Conformance test
Requirements: (XML Line 002177): Requirement /req/basic_ypr/encoding/json has no corresponding Conformance test
Requirements: (XML Line 002285): Requirement /req/basic_quaternion/encoding/json_strict has no corresponding Conformance test
Requirements: (XML Line 002385): Requirement /req/basic_quaternion/encoding/json has no corresponding Conformance test
Requirements: (XML Line 002483): Requirement /req/advanced/encoding/json has no corresponding Conformance test
Requirements: (XML Line 002586): Requirement /req/graph/encoding/json has no corresponding Conformance test
Requirements: (XML Line 002761): Requirement /req/chain/encoding/json has no corresponding Conformance test
Requirements: (XML Line 002878): Requirement /req/series/regular/encoding/json has no corresponding Conformance test
Requirements: (XML Line 003274): Requirement /req/stream/header/encoding/json has no corresponding Conformance test
Requirements: (XML Line 003349): Requirement /req/stream/element/encoding/json has no corresponding Conformance test
Requirements: (XML Line 003412): Requirement /req/stream/record/encoding/json has no corresponding Conformance test
```

**Comment by opoudjis** [comment]
Ok, now I'm getting new errors. @ronaldtse I resent being given incomplete specs like this, it is a waste of my time, and therefore your time.

I am forced to assume from the document that an abstract test can but does not need to have a requirement target.

I will add that this such a counterintuitive finding, I'm not going to action it unless you explicitly confirm this.

**Comment by ronaldtse** [comment]
There is some misunderstanding here. An Abstract test is exactly a conformance test, except that it has an attribute checkbox of "abstract". There is no special case here.

**Comment by opoudjis** [comment]
Then be prepared for a ton of abstract tests not linked to a requirement.

**Comment by opoudjis** [comment]
Requirements: (XML Line 001460): Requirement /req/basic_ypr/target has no corresponding Conformance test
Requirements: (XML Line 001469): Requirement /req/tangent_plane/longitude has no corresponding Conformance test
Requirements: (XML Line 001482): Requirement /req/tangent_plane/latitude has no corresponding Conformance test
Requirements: (XML Line 001495): Requirement /req/tangent_plane/h has no corresponding Conformance test
Requirements: (XML Line 001511): Requirement /req/orientation/ypr_angles has no corresponding Conformance test
Requirements: (XML Line 001560): Requirement /req/orientation/quaternion has no corresponding Conformance test
Requirements: (XML Line 001612): Requirement /req/time/instant has no corresponding Conformance test
Requirements: (XML Line 001623): Requirement /req/frame_specification/authority has no corresponding Conformance test
Requirements: (XML Line 001634): Requirement /req/frame_specification/id has no corresponding Conformance test
Requirements: (XML Line 001645): Requirement /req/frame_specification/parameters has no corresponding Conformance test
Requirements: (XML Line 001658): Requirement /req/orientation/quaternion has no corresponding Conformance test
Requirements: (XML Line 001710): Requirement /req/frame_specification/authority has no corresponding Conformance test
Requirements: (XML Line 001721): Requirement /req/frame_specification/id has no corresponding Conformance test
Requirements: (XML Line 001732): Requirement /req/frame_specification/parameters has no corresponding Conformance test
Requirements: (XML Line 001745): Requirement /req/chain/transform_index has no corresponding Conformance test
Requirements: (XML Line 001794): Requirement /req/frame_specification/authority has no corresponding Conformance test
Requirements: (XML Line 001805): Requirement /req/frame_specification/id has no corresponding Conformance test
Requirements: (XML Line 001816): Requirement /req/frame_specification/parameters has no corresponding Conformance test
Requirements: (XML Line 001873): Requirement /req/regular_series/header has no corresponding Conformance test
Requirements: (XML Line 001884): Requirement /req/time/duration has no corresponding Conformance test
Requirements: (XML Line 001895): Requirement /req/frame_specification/authority has no corresponding Conformance test
Requirements: (XML Line 001906): Requirement /req/frame_specification/id has no corresponding Conformance test
Requirements: (XML Line 001917): Requirement /req/frame_specification/parameters has no corresponding Conformance test
Requirements: (XML Line 001930): Requirement /req/series/regular/trailer has no corresponding Conformance test
Requirements: (XML Line 001985): Requirement /req/irregular_series/header has no corresponding Conformance test
Requirements: (XML Line 001996): Requirement /req/frame_specification/authority has no corresponding Conformance test
Requirements: (XML Line 002007): Requirement /req/frame_specification/id has no corresponding Conformance test
Requirements: (XML Line 002018): Requirement /req/frame_specification/parameters has no corresponding Conformance test
Requirements: (XML Line 002031): Requirement /req/irregular_series/frame_and_time has no corresponding Conformance test
Requirements: (XML Line 002042): Requirement /req/series/regular/trailer has no corresponding Conformance test
Requirements: (XML Line 002112): Requirement /req/frame_specification/authority has no corresponding Conformance test
Requirements: (XML Line 002123): Requirement /req/frame_specification/id has no corresponding Conformance test
Requirements: (XML Line 002134): Requirement /req/frame_specification/parameters has no corresponding Conformance test
Requirements: (XML Line 002147): Requirement /req/stream/frame_time_element has no corresponding Conformance test
Requirements: (XML Line 002177): Requirement /req/basic_ypr/encoding/json has no corresponding Conformance test
Requirements: (XML Line 002285): Requirement /req/basic_quaternion/encoding/json_strict has no corresponding Conformance test
Requirements: (XML Line 002385): Requirement /req/basic_quaternion/encoding/json has no corresponding Conformance test
Requirements: (XML Line 002483): Requirement /req/advanced/encoding/json has no corresponding Conformance test
Requirements: (XML Line 002586): Requirement /req/graph/encoding/json has no corresponding Conformance test
Requirements: (XML Line 002761): Requirement /req/chain/encoding/json has no corresponding Conformance test
Requirements: (XML Line 002878): Requirement /req/series/regular/encoding/json has no corresponding Conformance test
Requirements: (XML Line 003274): Requirement /req/stream/header/encoding/json has no corresponding Conformance test
Requirements: (XML Line 003349): Requirement /req/stream/element/encoding/json has no corresponding Conformance test
Requirements: (XML Line 003412): Requirement /req/stream/record/encoding/json has no corresponding Conformance test
Requirements: (XML Line 003770): Conformance test /conf/basic_ypr/target has no corresponding Requirement
Requirements: (XML Line 003790): Conformance test /conf/tangent_plane/longitude has no corresponding Requirement
Requirements: (XML Line 003810): Conformance test /conf/tangent_plane/latitude has no corresponding Requirement
Requirements: (XML Line 003830): Conformance test /conf/tangent_plane/h has no corresponding Requirement
Requirements: (XML Line 003850): Conformance test /conf/orientation/ypr_angles has no corresponding Requirement
Requirements: (XML Line 003904): Conformance test /conf/basic_quaternion/target has no corresponding Requirement
Requirements: (XML Line 003904): Conformance test /conf/basic_quaternion/target has no corresponding Conformance class
Requirements: (XML Line 003960): Conformance test /conf/time/instant has no corresponding Requirement
Requirements: (XML Line 003981): Conformance test /conf/frame_specification/authority has no corresponding Requirement
Requirements: (XML Line 004001): Conformance test /conf/frame_specification/id has no corresponding Requirement
Requirements: (XML Line 004021): Conformance test /conf/frame_specification/parameters has no corresponding Requirement
Requirements: (XML Line 004079): Conformance test /conf/graph/index has no corresponding Requirement
Requirements: (XML Line 004137): Conformance test /conf/chain/index has no corresponding Requirement
Requirements: (XML Line 004198): Conformance test /conf/series_header has no corresponding Requirement
Requirements: (XML Line 004218): Conformance test /conf/time/duration has no corresponding Requirement
Requirements: (XML Line 004238): Conformance test /conf/regular_series/trailer has no corresponding Requirement
Requirements: (XML Line 004302): Conformance test /conf/irregular_series/frame_and_time has no corresponding Requirement
Requirements: (XML Line 004380): Conformance test /conf/stream/frame_time_element has no corresponding Requirement
Requirements: (XML Line 004380): Conformance test /conf/stream/frame_time_element has no corresponding Conformance class
Requirements: (XML Line 004405): Conformance class /conf/basic_ypr/encoding/json has no corresponding Requirement class
Requirements: (XML Line 004425): Conformance test /conf/basic_ypr/encoding/json/test has no corresponding Requirement
Requirements: (XML Line 004447): Conformance class /conf/basic_quaternion/encoding/json has no corresponding Requirement class
Requirements: (XML Line 004467): Conformance test /conf/basic_quaternion/encoding/json/test has no corresponding Requirement
Requirements: (XML Line 004490): Conformance class /conf/basic_quaternion/encoding/json_strict has no corresponding Requirement class
Requirements: (XML Line 004510): Conformance test /conf/basic_quaternion/encoding/json_strict/test has no corresponding Requirement
Requirements: (XML Line 004532): Conformance class /conf/advanced/encoding/json has no corresponding Requirement class
Requirements: (XML Line 004552): Conformance test /conf/advanced/encoding/json/test has no corresponding Requirement
Requirements: (XML Line 004574): Conformance class /conf/chain/encoding/json has no corresponding Requirement class
Requirements: (XML Line 004594): Conformance test /conf/chain/encoding/json/test has no corresponding Requirement
Requirements: (XML Line 004616): Conformance class /conf/graph/encoding/json has no corresponding Requirement class
Requirements: (XML Line 004636): Conformance test /conf/graph/encoding/json/test has no corresponding Requirement
Requirements: (XML Line 004658): Conformance class /conf/regular_series/encoding/json has no corresponding Requirement class
Requirements: (XML Line 004678): Conformance test /conf/regular_series/encoding/json/test has no corresponding Requirement
Requirements: (XML Line 004678): Conformance test /conf/regular_series/encoding/json/test has no corresponding Conformance class
Requirements: (XML Line 004700): Conformance class /conf/irregular_series/encoding/json has no corresponding Requirement class
Requirements: (XML Line 004720): Conformance test /conf/irregular_series/encoding/json/test has no corresponding Requirement
Requirements: (XML Line 004742): Conformance class /conf/stream/encoding/json has no corresponding Requirement class
Requirements: (XML Line 004765): Conformance test /conf/stream/encoding/json/test has no corresponding Requirement

**Comment by opoudjis** [comment]
Confirmed as issues:

Requirement /req/orientation/quaternion has no corresponding Conformance test
Requirement /req/orientation/quaternion has no corresponding Conformance test
Requirement /req/chain/transform_index has no corresponding Conformance test
Requirement /req/regular_series/header has no corresponding Conformance test
Requirement /req/series/regular/trailer has no corresponding Conformance test
Requirement /req/irregular_series/header has no corresponding Conformance test
Requirement /req/series/regular/trailer has no corresponding Conformance test
Requirement /req/series/regular/encoding/json has no corresponding Conformance test
Requirement /req/stream/header/encoding/json has no corresponding Conformance test
Requirement /req/stream/element/encoding/json has no corresponding Conformance test
Requirement /req/stream/record/encoding/json has no corresponding Conformance test


The following have a conformance class testing a requirement instead of a requirement class

Requirement /req/basic_ypr/encoding/json has no corresponding Conformance test
Requirement /req/basic_quaternion/encoding/json_strict has no corresponding Conformance test
Requirement /req/basic_quaternion/encoding/json has no corresponding Conformance test
Requirement /req/advanced/encoding/json has no corresponding Conformance test
Requirement /req/graph/encoding/json has no corresponding Conformance test
Requirement /req/chain/encoding/json has no corresponding Conformance test

**Comment by opoudjis** [comment]
Remaining errors:

Requirements: (XML Line 001560): Requirement /req/orientation/quaternion has no corresponding Conformance test
Requirements: (XML Line 001661): Requirement /req/orientation/quaternion has no corresponding Conformance test
Requirements: (XML Line 001812): Requirement /req/regular_series/header has no corresponding Conformance test
Requirements: (XML Line 001891): Requirement /req/irregular_series/header has no corresponding Conformance test
Requirements: (XML Line 002017): Requirement /req/basic_ypr/encoding/json has no corresponding Conformance test
Requirements: (XML Line 002125): Requirement /req/basic_quaternion/encoding/json_strict has no corresponding Conformance test
Requirements: (XML Line 002225): Requirement /req/basic_quaternion/encoding/json has no corresponding Conformance test
Requirements: (XML Line 002323): Requirement /req/advanced/encoding/json has no corresponding Conformance test
Requirements: (XML Line 002426): Requirement /req/graph/encoding/json has no corresponding Conformance test
Requirements: (XML Line 002601): Requirement /req/chain/encoding/json has no corresponding Conformance test
Requirements: (XML Line 002718): Requirement /req/regular_series/encoding/json has no corresponding Conformance test
Requirements: (XML Line 002923): Requirement /req/irregular_series/encoding/json has no corresponding Conformance test
Requirements: (XML Line 003127): Requirement /req/stream/header/encoding/json has no corresponding Conformance test
Requirements: (XML Line 003202): Requirement /req/stream/element/encoding/json has no corresponding Conformance test
Requirements: (XML Line 003265): Requirement /req/stream/record/encoding/json has no corresponding Conformance test
Requirements: (XML Line 003759): Conformance test /conf/basic_quaternion/target has no corresponding Requirement
Requirements: (XML Line 003759): Conformance test /conf/basic_quaternion/target has no corresponding Conformance class
Requirements: (XML Line 003934): Conformance test /conf/graph/index has no corresponding Requirement
Requirements: (XML Line 004053): Conformance test /conf/series_header has no corresponding Requirement
Requirements: (XML Line 004235): Conformance test /conf/stream/frame_time_element has no corresponding Conformance class
Requirements: (XML Line 004260): Conformance class /conf/basic_ypr/encoding/json has no corresponding Requirement class
Requirements: (XML Line 004280): Conformance test /conf/basic_ypr/encoding/json/test has no corresponding Requirement
Requirements: (XML Line 004304): Conformance class /conf/basic_quaternion/encoding/json has no corresponding Requirement class
Requirements: (XML Line 004324): Conformance test /conf/basic_quaternion/encoding/json/test has no corresponding Requirement
Requirements: (XML Line 004347): Conformance class /conf/basic_quaternion/encoding/json_strict has no corresponding Requirement class
Requirements: (XML Line 004367): Conformance test /conf/basic_quaternion/encoding/json_strict/test has no corresponding Requirement
Requirements: (XML Line 004389): Conformance class /conf/advanced/encoding/json has no corresponding Requirement class
Requirements: (XML Line 004409): Conformance test /conf/advanced/encoding/json/test has no corresponding Requirement
Requirements: (XML Line 004431): Conformance class /conf/chain/encoding/json has no corresponding Requirement class
Requirements: (XML Line 004451): Conformance test /conf/chain/encoding/json/test has no corresponding Requirement
Requirements: (XML Line 004473): Conformance class /conf/graph/encoding/json has no corresponding Requirement class
Requirements: (XML Line 004493): Conformance test /conf/graph/encoding/json/test has no corresponding Requirement
Requirements: (XML Line 004515): Conformance class /conf/regular_series/encoding/json has no corresponding Requirement class
Requirements: (XML Line 004535): Conformance test /conf/regular_series/encoding/json/test has no corresponding Requirement
Requirements: (XML Line 004535): Conformance test /conf/regular_series/encoding/json/test has no corresponding Conformance class
Requirements: (XML Line 004557): Conformance class /conf/irregular_series/encoding/json has no corresponding Requirement class
Requirements: (XML Line 004577): Conformance test /conf/irregular_series/encoding/json/test has no corresponding Requirement
Requirements: (XML Line 004599): Conformance class /conf/stream/encoding/json has no corresponding Requirement class
Requirements: (XML Line 004622): Conformance test /conf/stream/encoding/json/test has no corresponding Requirement

**Comment by opoudjis** [comment]
Have needed to use l10n less naively: we do not want to localise colon in isolation, but only as part of a complete string.

**Comment by ronaldtse** [comment]
We won't be able to verify this until https://github.com/metanorma/ogc-GeoPose/issues/8 is fixed.

**Comment by opoudjis** [comment]
You can verify this now.

**Comment by ronaldtse** [comment]
https://github.com/metanorma/ogc-GeoPose/issues/8 is completed and closed. Thanks @opoudjis !
