### ISSUE TITLE
The Table of Contents is not showing

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-ogc#43]
See the left-hand side of the following screenshot. 

<img width="1289" alt="Screen Shot 2019-07-31 at 11 27 57" src="https://user-images.githubusercontent.com/18121038/62205469-68b28e80-b387-11e9-9353-95ef80f1ae3e.png">

The source for this document is at the following URL https://portal.opengeospatial.org/files/?artifact_id=86696

Initially we thought the issue was caused by a specific image but now the issue persists even when the image is not included in the document.

**Comment by ghobona** [comment]
Possibly addressed by https://github.com/metanorma/metanorma-ogc/issues/42

**Comment by ronaldtse** [comment]
Indeed I believe this is resolved in #42 .

* @opoudjis can you notify this thread once the fix is released?
* and @CAMOBAP795 can you help trigger the docker image rebuild after the release?

Thanks.

**Comment by opoudjis** [comment]
Released

**Comment by CAMOBAP795** [comment]
done https://hub.docker.com/r/metanorma/metanorma/tags#1.2.3
