### ISSUE TITLE
PDF links wrong for RFCs are in Normative References

### ISSUE THREAD

**Issue by gbuehler** [metanorma/metanorma-ogc#430]
This is output from https://gitlab.ogc.org/ogc/T18-Secure_Asynchronous_Catalogs/-/pipelines/2382

The HTML seems fine, but the PDF Normative References have improper links to only IETF RFC documents.

Text example here (first is non RFC and is correct, second is an RFC and the link is to the relaton data) :

- Open API Initiative: OpenAPI Specification 3.0.2, 2018 https://github.com/OAI/OpenAPISpecification/blob/master/versions/3.0.2.md

- R. Fielding, J. Gettys, J. Mogul, H. Frystyk, L. Masinter, P. Leach, T. Berners-Lee: RFC 2616,
Hypertext Transfer Protocol — HTTP/1.1. Internet Engineering Task Force (1999).
https://raw.githubusercontent.com/relaton/relaton-data-ietf/master/data/reference.RFC.2616.xml

Here is a screenshot of the PDF:

![Screen Shot 2022-09-28 at 12 44 04 PM](https://user-images.githubusercontent.com/221625/192841912-907d7e0c-4915-4aad-9585-56c72d07b084.png)

**Comment by ronaldtse** [comment]
@gbuehler thank you for reporting! This is indeed a bug, we should be giving the authoritative link to the RFCs instead. We have those links in the bibliographic data so it's doable.

**Comment by opoudjis** [comment]
@ronaldtse @gbuehler Require access to repository. `[nick.nicholas@ribose.org](https://gitlab.ogc.org/opoudjis)`

**Comment by opoudjis** [comment]
I cannot replicate with the current version of Metanorma and Relaton. Be aware that infrastructure changes frequently, and the IETF Relaton infrastructure in particular has been overhauled. The PDF and HTML have been copying their references from a common source for several weeks now, so I strongly suspect your gems are out of date.


Current versions of relevant gems are:

````
relaton-ietf (1.13.2)
metanorma-ogc (2.2.3)
````

Input:

````
[bibliography]
== Bibliography
* [[[A,RFC 2616]]]
````

HTML output:

<img width="1128" alt="Στιγμιότυπο 2022-10-09, 23 37 11" src="https://user-images.githubusercontent.com/1911039/194757219-1b2b56ff-a3c8-4ff4-a529-06021b241b3b.png">


PDF output:
<img width="892" alt="Στιγμιότυπο 2022-10-09, 23 37 55" src="https://user-images.githubusercontent.com/1911039/194757242-0189686d-ebf9-4dbb-953b-09dacbb1e4d3.png">

**Comment by ronaldtse** [comment]
@gbuehler could you let us know with the updated versions? Thanks.

**Comment by opoudjis** [comment]
@gbuehler please verify with the updated version of Metanorma. This issue has been pending response from you for the past month.

**Comment by opoudjis** [comment]
We cannot replicate the issue, and the issue reflects a bug that had been fixed several months ago, so we believe it has been solved, and will be addressed by updating software (and clearing relaton cache: delete contents of ~/.relaton if needed). 

Closing ticket. @gbuehler If the issue persists, please reopen the ticket.
