### ISSUE TITLE
Add example of Metanorma importing bibliographic items from relaton-doi

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#431]
Relaton has relaton-doi that allows citing from any DOI/CrossRef item.

We need to ensure that Metanorma can use that information and provide instructions on how to do that.

This was raised during the OGC Metanorma Workshop on 2022-09-28.

**Comment by opoudjis** [comment]
Need to call relaton-doi from Metanorma with DOI prefix.

**Comment by ronaldtse** [comment]
Make it an actionable ticket in relaton-doi?

**Comment by ronaldtse** [comment]
@andrew2net , @opoudjis wants these features to be able to integrate:

* https://github.com/relaton/relaton-doi/issues/4
* https://github.com/relaton/relaton-doi/issues/5
