### ISSUE TITLE
Occasionally a requirement does not link against a conformance class with correct encoding

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#433]
Somehow this particular one does not validate. Not sure why.

```
Requirements: (XML Line 001714): Requirement /req/basic-quaternion/quaternion has no corresponding Conformance test
Requirements: (XML Line 004376): Conformance test /conf/basic-quaternion/quaternion has no corresponding Requirement
```

They are clearly matching though. This seems like a bug for @opoudjis ?

Requirement:
<img width="1107" alt="Screen Shot 2022-10-10 at 3 43 51 PM" src="https://user-images.githubusercontent.com/11865/194819102-b2e0e5e8-b6ab-493b-889e-bb91299dabd4.png">

Conformance test:
<img width="1139" alt="image" src="https://user-images.githubusercontent.com/11865/194819068-a9e820ed-709d-4abb-ac3e-4357457828c2.png">

_Originally posted by @ronaldtse in https://github.com/metanorma/ogc-GeoPose/issues/9#issuecomment-1272868939_

**Comment by manuelfuenmayor** [comment]
This was a markup issue that is solved now: https://github.com/metanorma/ogc-GeoPose/pull/9#issuecomment-1273212133
Closing.
