### ISSUE TITLE
Conformance test label in Requirements Class table should be Conformance Class

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-ogc#434]
This issue is repeated across all Requirements Class tables that are generated by metanorma.

The issue was encountered on 2022-10-14 on a newly pulled docker image of metanorma/metanorma, when compiling the [GeoPose 1.0 document](https://github.com/opengeospatial/geopose).

The word circled in red in the table should say 'class' instead of 'test.

![Screenshot 2022-10-14 at 09 20 21](https://user-images.githubusercontent.com/18121038/195799387-9ff1aca5-036b-494e-8d99-630a5da6413e.png)

**Comment by ronaldtse** [comment]
Thank you @ghobona , this is indeed a bug. We'll get this handled!

**Comment by ronaldtse** [comment]
Confirm this is fixed. Thanks @opoudjis .

<img width="633" alt="Screen Shot 2022-10-19 at 12 16 35 AM" src="https://user-images.githubusercontent.com/11865/196486287-8c473671-3030-427f-bd28-8814bda6ab67.png">

**Comment by ghobona** [comment]
@ronaldtse Please let me know when the fix is available on the metanorma/metanorma docker image.
