### ISSUE TITLE
PDF: OGC Requirements table cell alignment broken

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#437]
All ModSpec instances are now presented with "centered" alignment in the headings and caption, which is not what we want.

* All table header cells should be left aligned.
* The requirements caption should be left aligned.

Requirements class:
<img width="497" alt="Screen Shot 2022-10-19 at 12 09 45 AM" src="https://user-images.githubusercontent.com/11865/196484909-3e1505cb-1b9a-4b45-beb5-13bfb72ca583.png">

Requirement:
<img width="495" alt="Screen Shot 2022-10-19 at 12 11 01 AM" src="https://user-images.githubusercontent.com/11865/196485161-31007896-93d5-4dbe-8fa3-917e769c76b6.png">

**Comment by Intelligent2013** [comment]
@opoudjis could you send me the presentation XML, please? The repo https://github.com/metanorma/ogc-modspec doesn't contain the data from the initial post. Thanks.

**Comment by opoudjis** [comment]
Sent.

**Comment by Intelligent2013** [comment]
OGC XSLT updated:
- `th` left aligned by default
- table header height increased a bit, now renders as normal table row
- font size for `tt` decreased in the table

![image](https://user-images.githubusercontent.com/5559926/197007274-0caedf3e-6c8a-49f6-b06a-42d53261047d.png)
![image](https://user-images.githubusercontent.com/5559926/197007383-d2a3c2e8-a40c-46a5-9fef-20cb9e456faf.png)

**Comment by ronaldtse** [comment]
This is fixed. Thanks.
