### ISSUE TITLE
PDF: ModSpec instance tables need some shading background

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#438]
Right now it is impossible to know if a table has ended. Look at this:

<img width="511" alt="Screen Shot 2022-10-19 at 12 12 39 AM" src="https://user-images.githubusercontent.com/11865/196485491-2ed0b05b-3c9e-4149-b4d6-bbdddf2c897b.png">

<img width="501" alt="Screen Shot 2022-10-19 at 12 12 09 AM" src="https://user-images.githubusercontent.com/11865/196485462-cf308557-7346-4ef7-8079-05f3bcfec22d.png">

We should provide a shading (not skip rows) that differentiates table content from the body content.

**Comment by Intelligent2013** [comment]
Regarding source design layout:
- tables in the main sections (parent element `sections`) have the smaller font-size than the main text.
- tables in the preface and annex have the font-size as the main text.

In any case, if the table is latest element in the clause, and the last row has white background, then hard to clearly determine that the last row is part of table or not.

@ronaldtse  how would you like to shade a row:
   - same color
![image](https://user-images.githubusercontent.com/5559926/196511994-342c5548-dd86-4a4f-9c29-8ee26b778dc3.png)
   or 
   - light color
![image](https://user-images.githubusercontent.com/5559926/196513234-d9c6bcd9-5465-40f7-8cc6-4748647735c9.png)

**Comment by ronaldtse** [comment]
> * tables in the main sections (parent element `sections`) have the smaller font-size than the main text.
> * tables in the preface and annex have the font-size as the main text.

The font-sizes in tables should be identical regardless where they are located in the document.

> @ronaldtse how would you like to shade a row:
> * light color

Light color please. Thanks!

**Comment by ronaldtse** [comment]
BTW, the color of the table heading is also messed up right now.

**Comment by Intelligent2013** [comment]
> BTW, the color of the table heading is also messed up right now.

@ronaldtse would you like to set blue color for all tables? Currently, blue color is using for Requirements/Recommendations tables only. Earlier, Requirements/Recommendations table headers renders in yellow, but in  'Update OGC branding in PDF output, and change yellow color to `#00b1ff`' https://github.com/metanorma/metanorma-ogc/issues/306 changed to blue.

**Comment by ronaldtse** [comment]
@Intelligent2013 that's a good point. Can you help select reasonable colors? Thanks.

**Comment by Intelligent2013** [comment]
Table header color changed to 'white' for all tables:
![image](https://user-images.githubusercontent.com/5559926/196789149-c9aa3c82-9032-44e6-b85c-11b48802ab8b.png)

**Comment by ronaldtse** [comment]
@intelligent2013 is the center alignment of the table heading specified in the XML or at the XSLT? The “Requirement” caption should probably be left aligned?

**Comment by Intelligent2013** [comment]
In the presentation XML there isn't the text alignment attributes:
```xml
<table id="req_1" class="modspec" type="recommend">
	<thead>
		<tr>
			<th scope="colgroup" colspan="2">
				<p class="RecommendationTitle">Requirement 1</p>
			</th>
		</tr>
	</thead>
	...
</table>
```
By default in XSLT, the text in the table header (`th`) displays centered.
```xml
	<!-- cell in table header row -->
	<xsl:template match="*[local-name()='th']">
		<fo:table-cell xsl:use-attribute-sets="table-header-cell-style">
			<xsl:call-template name="setTextAlignment">
				<xsl:with-param name="default">center</xsl:with-param>
			</xsl:call-template>
```

I can add a special condition for `class="modspec"` for display left aligned text.

HTML (https://metanorma.github.io/mn-samples-ogc/documents/18-095r7/document.html#toc13) displays the centered header also:
![image](https://user-images.githubusercontent.com/5559926/196905022-554b70c7-9543-4672-bdf7-9e16364b9d72.png)

**Comment by Intelligent2013** [comment]
Text alignment issue relates to https://github.com/metanorma/metanorma-ogc/issues/437.
