### ISSUE TITLE
Tables with merged cells are not showing

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-ogc#44]
It appears tables that have merged cells are not shown correctly.

See the screenshots below. The following figure is how the metanorma-ogc template presents the Requirement 1 table.

<img width="1289" alt="Screen Shot 2019-07-31 at 11 27 57" src="https://user-images.githubusercontent.com/18121038/62206787-7cabbf80-b38a-11e9-93a4-4968b78ccef7.png">

The following figure is how asciidoctor presents the Requirement 1 table.

<img width="1290" alt="Screen Shot 2019-07-31 at 11 28 39" src="https://user-images.githubusercontent.com/18121038/62206805-86352780-b38a-11e9-9dec-c50171c18078.png">

Alternative approaches for achieving the same effect through metanorma would be appreciated.

The source for the document is at https://portal.opengeospatial.org/files/?artifact_id=86696

Note that the source for Requirement 1 is in the file requirements/REQ001.adoc

**Comment by ronaldtse** [comment]
For debugging purposes here's the content of `REQ001.adoc`:

```adoc
[width="90%",cols="2,6"]
|===
.2+|*Requirement 1*{set:cellbgcolor:#CACCCE}
|/req/pipelineml-conceptual/similarity
 {set:cellbgcolor:#FFFFFF} +
a|
An encoding, when claiming compliance with this conceptual model, SHALL implement its components (classes, attributes, relationships) respecting the conceptual model definitions and intent, such that high semantic similarity is obtained between the encoding and conceptual model components.
|===
```

There are two separate issues:
1. Why is normal table syntax not working? (@opoudjis can you help answer this? Maybe because MN doesn't support )
2. How do we achieve the same effect?

For 2, let me give a brief answer.

Metanorma supports machine-readable requirements, and they utilize a different syntax than tables. This functionality provides a method to extract requirements directly from the XML, and provides other benefits such as auto-numbering, supporting hierarchical requirements and allowing them to be referenced.

* Details can be found here: https://www.metanorma.com/author/topics/document-format/requirements-recommendations-permissions/
* Samples are located here: https://github.com/metanorma/metanorma-mrr-samples . Specifically, here's an example from GeoJSON (https://raw.githubusercontent.com/metanorma/metanorma-mrr-samples/master/ogc-geojson.adoc)

So the converted `REQ001.adoc` will be this:
```adoc
[.requirement,type="general",id="/req/pipelineml-conceptual/similarity",obligation="shall"]
====
An encoding, when claiming compliance with this conceptual model, SHALL implement its components (classes, attributes, relationships) respecting the conceptual model definitions and intent, such that high semantic similarity is obtained between the encoding and conceptual model components.
====
```

**Comment by ronaldtse** [comment]
@ghobona , I confirm this works:

```adoc
[requirement,type="general",id="/req/pipelineml-conceptual/similarity",obligation="shall"]
====
This is a test. An encoding, when claiming compliance with this conceptual model, SHALL implement its components (classes, attributes, relationships) respecting the conceptual model definitions and intent, such that high semantic similarity is obtained between the encoding and conceptual model components.
====
```

Renders into this:

<img width="795" alt="image" src="https://user-images.githubusercontent.com/11865/62273105-96ccb880-b3f1-11e9-9b2c-ddd969f37714.png">

**Comment by ronaldtse** [comment]
Problems remaining now:

* Requirement ID not showing
* Requirement obligation not showing
* Requirement "type" not showing
* Accept both `[.requirement,...]` and `[requirement,...]` syntaxes
* Find out why original table rendering didn't work.

**Comment by opoudjis** [comment]
OGC and Standoc requirements were developed independently, and that will stop now. The OGC legacy table format in Asciidoctor will be accepted, and I will debug what happened with it here, but the two formats need to be reconciled.

In standoc (i.e. the rest of metanorma), requirements are represented as a div, not a table, and I am reluctant to preserve completely distinct rendering. I will do so for now, but recommend you reconsider.

**Comment by ronaldtse** [comment]
@opoudjis 

> The OGC legacy table format in Asciidoctor will be accepted, and I will debug what happened with it here, but the two formats need to be reconciled.

We don't want to accept the legacy table format for requirements, but want to ensure that normal tables actually work.

**Comment by opoudjis** [comment]
> We don't want to accept the legacy table format for requirements, but want to ensure that normal tables actually work.

Are you asking me to remove this functionality? Thats going to be a lot of rekeying from OGC if so.

**Comment by opoudjis** [comment]
Ah, I see now. 

The original spec assumed that requirement tables only had one row, with one cell containing the requirement label, and the second containing the requirement body. 

That means that the gem is currently doing exactly what it was designed to do, based on the sample documents you gave us. But the sample documents had the equivalent of

````
[width="90%",cols="2,6"]
|===
|*Requirement 1* +
/req/pipelineml-conceptual/similarity
a|
An encoding, when claiming compliance with this conceptual model, SHALL implement its components (classes, attributes, relationships) respecting the conceptual model definitions and intent, such that high semantic similarity is obtained between the encoding and conceptual model components.
|===
````

They did not have arbitrary table structure, and it is not fair to expect arbitrary table structure to be encoded. If there is no one single table structure that all recommendations comply to, then we cannot proceed with tables as representations of requirements.

**Comment by ronaldtse** [comment]
@opoudjis 

> > We don't want to accept the legacy table format for requirements, but want to ensure that normal tables actually work.
>
> Are you asking me to remove this functionality? Thats going to be a lot of rekeying from OGC if so.

1. "Requirements" should ONLY be entered using the new requirements syntax. Arbitrary tables should still be supported to be rendered (in XML) as tables, but they will NOT automatically be encoded as MRR.

2. We should still support tables. In the case above, the arbitrary "requirement table" was treated as a special "requirement" which rendered funnily. We should support tables but should stop assuming that a table with a "requirement" text is a table.

**Comment by opoudjis** [comment]
OK then. In that case, I am disabling that functionality, but I am going to continue to render requirements like tables—although since we have such an elaborate structure for Metanorma requirements, the table is really just going to be a wrapper.

**Comment by ronaldtse** [comment]
> continue to render requirements like tables—although since we have such an elaborate structure for Metanorma requirements, the table is really just going to be a wrapper.

That's absolutely fine. It's purely a representational issue. Thanks!

**Comment by opoudjis** [comment]
@ghobona FYI: updating Metanorma to deal with the issues you are raising involves updating several gems in the stack, and we try to release the entire stack once every week or two weeks, so that the updates are coordinated. Ronald (or I) will let you know when the next gem release happens.

**Comment by opoudjis** [comment]
@ghobona I have to add that Ronald has given you obsolete instructions on what attributes are supported for Metanorma requirements; please consult https://www.metanorma.com/author/topics/document-format/requirements-recommendations-permissions/

````
[.recommendation,label="/ogc/recommendation/wfs/2",subject="user",inherit="/ss/584/2015/level/1",classification="control-class:Technical;priority:P0;family:System and Communications Protection,System and Communications Protocols",obligation="permission,recommendation"]
====
I recommend this
====
````
