### ISSUE TITLE
(URGENT) Add document type of "Draft Standard"

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-ogc#442]
@ronaldtse Could you please make the following enhancement to the metanorma-ogc template?

OGC [policies](http://docs.opengeospatial.org/pol/05-020r27/05-020r27.html#the-two-track-standards-process-characteristics) allow for two types of draft standards:

* a draft standard that is in work. For the purpose of this message, let's call it a **Draft Standard** document.
* a draft standard that has been approved by the Technical Committee (TC). For the purpose of this message, let's call it an **Approved Draft Standard** document.

Metanorma is currently configured to support Draft Standard documents. However, we also need to support Approved Draft Standard documents as well. For example, **GeoPose 1.0** is an Approved Draft Standard document.

Attached is a screenshot of a mock-up, kindly created by @gbuehler, to illustrate what an Approved Draft Standard document should look like.  

![approved_draft_standard_illustration](https://user-images.githubusercontent.com/18121038/197135063-8907fa76-d0a6-4ad0-970b-6b824a5a881f.png)

There are three areas to change when a document is an Approved Draft Standard are:

- side band on left
  -- <document-stage> = Approved
  -- <document-type> = OGC Draft Standard

- text in center of coverpage
  -- <coverpage-stage> = OGC Draft Standard
  -- <coverpage-maturity> = Approved
 
- lightblue box on bottom (docstage-box)
  -- Document type = OGC Draft Standard
  -- Document stage = Approved

Notice for a "Draft Standard" would be exactly the same as for a "Standard".

Cc: @ogcscotts

**Comment by ronaldtse** [comment]
@ghobona and @gbeuhler I would like to clarify, that right now we have these stages listed here:
https://www.metanorma.org/author/ogc/ref/document-attributes/

<img width="790" alt="Screen Shot 2022-10-21 at 5 38 26 PM" src="https://user-images.githubusercontent.com/11865/197165226-16bf8874-f386-469f-ab64-8a3897e3c67d.png">

And this particular table that indicates the sequence of stages:
<img width="808" alt="Screen Shot 2022-10-21 at 5 38 41 PM" src="https://user-images.githubusercontent.com/11865/197165279-b78d38e8-842b-459f-9163-3ac2edf2fa06.png">

Can you help clarify where *exactly* does this fit in?
* Is this the "tc-vote" stage document?
* Or is this a new stage, between "tc-vote" and "approved"?

**Comment by ghobona** [comment]
With reference to Table 1 above, it's a new stage which sits between tc-vote and approved (published).

**Comment by ogcscotts** [comment]
not exactly: a Draft Standard is a document type just like a Standard or a Abstract Specification Topic. It is not a stage at all.

**Comment by ronaldtse** [comment]
@ogcscotts Is “Draft Standard” meant to be the equivalent of the DIS stage at ISO? In ISO, it is implemented as a stage, so when a document progresses from DIS to IS, it is just a stage progression.

**Comment by ogcscotts** [comment]
@ronaldtse no, per our policies a Standard that has no compliance tests nor reference implementations is approved as a Draft Standard (only applies to the past few years). It is a final stage, but "uplift" can occur to a Standard once there is the evidence for implementation against tests.

**Comment by ronaldtse** [comment]
@ogcscotts Aha, so it's something like a "Technical Specification" in ISO where it is a different document type that can be uplifted/upgraded to a Standard. I have to say that the nomenclature is a rather confusing... perhaps that could be reflected to the PC one day... 😉

**Comment by ronaldtse** [comment]
@ogcscotts can we also confirm the document stages that happen to the "Draft Standard"?

Does it go through the same stages as a Standard? i.e.:
* draft
* work-item-draft
* swg-draft
* oab-review
* public-rfc
* tc-vote
* approved (published)
* deprecated
* rescinded
* retired

Or are certain stages omitted?

**Comment by ogcscotts** [comment]
@ronaldtse all of the same stages are used in a Draft Standard. As to the name, I think there were 18 months of debate in the TC and PC, but we ultimately settled on DRAFT as all other options seemed artificial!

**Comment by ronaldtse** [comment]
@ogcscotts thank you for the clarification, does this diagram reflect the correct flow?
![ogc-doctype-pub-process](https://user-images.githubusercontent.com/11865/197444642-8bcf7f85-1490-482c-a539-93fd989c3667.svg)

**Comment by ogcscotts** [comment]
@ronaldtse Great diagram! Yes, this is correct for Standards. Once note: Best Practices and Community Practices have a public RFC and can also be deprecated or rescinded. These two documents do not go to the OAB. I know, complex!

**Comment by ronaldtse** [comment]
Does this reflect the full flow? We will need to update the allowed stages for Best Practice and Community Practice then.
![OGC publication process flow-2](https://user-images.githubusercontent.com/11865/197557395-3bb2b7a0-ad81-4160-8248-452525b9e746.svg)

**Comment by ogcscotts** [comment]
@ronaldtse yes, with a minor change to call the first step for a Best/Community Practice document a "draft" as it is not a Work Item. As a heads up, the new propose Policies for OGC include two types of deprecated Standards. The second type will be "Legacy." I think from a logic standpoint, both can be represented by "Deprecated" and the tag chosen at time of status change. Also... there is no order to Deprecated, Rescinded, or Retired: a document can jump directly to any status. Each can be an end-state.

**Comment by ronaldtse** [comment]
@ogcscotts updated: will this work? (Not including the Legacy standard yet)
![OGC publication process flow-3](https://user-images.githubusercontent.com/11865/197561807-629566a9-42ac-40cb-87a7-2c183a35f2fb.svg)

I have a question on the Legacy. Can all document types become Legacy? Or only certain types?

**Comment by ogcscotts** [comment]
@ronaldtse perfect!

**Comment by ronaldtse** [comment]
@opoudjis this issue is ready for action. This task calls for:

1. Addition of a document type (`doctype`): "Draft Standard", with value `draft-standard`.
2. For `draft-standard`, allow these stages: 
    * swg-draft
    * oab-review
    * public-rfc
    * tc-vote
    * approved (published)
    * deprecated
    * rescinded
    * retired
3. Implement updated layout as described by @ghobona / @gbuehler

Let me know if there are any clarifications needed. Thanks!

**Comment by opoudjis** [comment]
Pending creation of draft-standard XSLT stylesheet.

**Comment by ghobona** [comment]
@ronaldtse Please let @gbuehler know when metanorma-ogc has been updated with the enhancement.

**Comment by ronaldtse** [comment]
@ghobona @gbuehler the code is updated but the next scheduled version release is in 2 weeks. To use this functionality please use the Git version.

In addition, we do not have a sample document/template for Draft Standard. Could you please help provide some content? Thanks!

**Comment by opoudjis** [comment]
Update template of standard to document draft-standard as an option.
