### ISSUE TITLE
Update stages for OGC Best Practice and Community Practice

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#443]
From @ogcscotts:

Best Practices and Community Practices have a public RFC and can also be deprecated or rescinded. These two documents do not go to the OAB.

The diagram illustrates this:
![OGC publication process flow](https://user-images.githubusercontent.com/11865/197561807-629566a9-42ac-40cb-87a7-2c183a35f2fb.svg)

So for `best-practice` and `community-practice`, they have these stages:
* `draft`
* `public-rfc`
* `tc-vote`
* `approved`
* `deprecated`
* `rescinded`
* `retired`

_Originally posted by @ogcscotts in https://github.com/metanorma/metanorma-ogc/issues/442#issuecomment-1289086082_

**Comment by ronaldtse** [comment]
@ogcscotts could you help confirm that for these two document types, the status `retired` cannot be assigned to it?

**Comment by ogcscotts** [comment]
@ronaldtse yes, they can be retired

**Comment by ronaldtse** [comment]
Thanks!
