### ISSUE TITLE
(under discussion) Add "deprecated Standard type" of "Legacy"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#444]
From @ogcscotts :

As a heads up, the new propose Policies for OGC include two types of deprecated Standards. The second type will be "Legacy." I think from a logic standpoint, both can be represented by "Deprecated" and the tag chosen at time of status change. Also... there is no order to Deprecated, Rescinded, or Retired: a document can jump directly to any status. Each can be an end-state.

_Originally posted by @ogcscotts in https://github.com/metanorma/metanorma-ogc/issues/442#issuecomment-1289172004_

**Comment by ronaldtse** [comment]
@ogcscotts would the flow look like this?

![OGC publication process flow - with-legacy-flow](https://user-images.githubusercontent.com/11865/197678917-fc53c8d5-0fc4-45cd-9e46-c74836b6a555.svg)

**Comment by opoudjis** [comment]
Should be straightforward grammar change and rendering addition.

**Comment by opoudjis** [comment]
This issue is pending https://github.com/relaton/relaton-ogc/issues/25 ; will only publish update to grammar if I can be sure it will not disrupt @andrew2net ’s generation of relaton records for OGC.

**Comment by opoudjis** [comment]
@ghobona Our bibliographic feed does not have clear indication of statuses: https://github.com/relaton/relaton-ogc/issues/25

**Comment by ghobona** [comment]
A mock up of the cover pages of the PDFs is in the attached PPTX.

[new_document_statuses_v2.pptx](https://github.com/metanorma/metanorma-ogc/files/13860906/new_document_statuses_v2.pptx)

A mock up of the html cover pages is in the attached zip file.

[20240108_html_mockups.zip](https://github.com/metanorma/metanorma-ogc/files/13860920/20240108_html_mockups.zip)

**Comment by ghobona** [comment]
Please note the different notices on each cover type.

**Comment by opoudjis** [comment]
![Screenshot 2024-01-12 at 21 19 46](https://github.com/metanorma/metanorma-ogc/assets/1911039/a36353ad-df17-4cab-98f6-898ba4c2d9ea)

**Comment by opoudjis** [comment]
No legacy docs, but 01-042 is retired. Check on relaton, and resolve this ticket with grammar update.

**Comment by ghobona** [comment]
Discussed 2024-02-15
