### ISSUE TITLE
Fix behavior of `toclevels` to apply to all output formats, and provide per-output-type toc levels

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#449]
In contrast with documentation at https://www.metanorma.org/author/ref/document-attributes/:

<img width="693" alt="image" src="https://user-images.githubusercontent.com/11865/199139527-a7ff6c2f-d709-4818-98bc-845b21b7a874.png">

`toclevels` controls the PDF TOC levels only, and does not affect HTML or DOC outputs.
`htmltoclevels` controls the HTML TOC levels.
`doctoclevels` controls the DOC TOC levels.

I've tried this out against https://github.com/opengeospatial/CoverageJSON .

**Comment by ronaldtse** [comment]
Would `toclevels-html` and `toclevels-doc`  etc be more reasonable? We do have different output formats for other flavors.

**Comment by opoudjis** [comment]
toclevels not being passed on from metanorma gem

**Comment by opoudjis** [comment]
> Would `toclevels-html` and `toclevels-doc` etc be more reasonable? We do have different output formats for other flavors.

Defer.
