### ISSUE TITLE
Use sentence case on titles and headers

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-ogc#45]
The names of OGC standards are often written using a combination of upper and lower case e.g. GeoPackage, PipelineML, CityGML.

Currently the metanorma-ogc template uses all caps on titles and headers. 

Please change the template to use sentence case on titles and headers.

**Comment by ronaldtse** [comment]
Got it. The templates are located in https://github.com/metanorma/mn-templates-ogc/ , we'll fix them there.

**Comment by ronaldtse** [comment]
So the templates aren't the problem, this is probably a pure CSS issue.

The XML also faithfully represents whatever the title was entered, e.g.:

```xml
  <title language="en" format="text/plain">OGC PipelineML Conceptual and Encoding Model Standard</title>
```

**Comment by ronaldtse** [comment]
@ghobona P.S. this was a design decision when we designed the OGC template.
