### ISSUE TITLE
HTML: TOC at the 4-th level not rendering correctly

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#450]
The 4th level TOC entries are rendered back at the first level.

<img width="358" alt="Screen Shot 2022-11-01 at 9 19 51 AM" src="https://user-images.githubusercontent.com/11865/199139894-5662499b-38be-4c01-a17b-909651728c1c.png">

To reproduce, add `:htmltoclevels: 4`.

Document: https://github.com/opengeospatial/CoverageJSON

**Comment by opoudjis** [comment]
No provision in HTML CSS for ToC indentation past h3. Will need to rectify throughout Metanorma.
