### ISSUE TITLE
Word: TOC at the 4-th level not rendering correctly

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#451]
The 4th level TOC entries are rendered back at the first level in appearance.

<img width="939" alt="Screen Shot 2022-11-01 at 9 20 31 AM" src="https://user-images.githubusercontent.com/11865/199140068-0a4f0704-5474-46c3-9daf-08f44e3b3001.png">

To reproduce, add `:doctoclevels: 4`.

Document: https://github.com/opengeospatial/CoverageJSON

**Comment by opoudjis** [comment]
Fourth-level ToC only defined in Word stylesheet for those flavours that had it defined in their native Word template: IEC, ITU, IEEE. For the remainder, will need to provide TOC levels 4-6, with additional idnent.

**Comment by opoudjis** [comment]
Need to insert style names into all ToC, else if using language other than English, ToC styled names will be ignored when ToC is updated.
