### ISSUE TITLE
Change TOC level per format specification to `toclevels-*` from `*-toclevels`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#454]
Instead of:

`html-toclevels` and `doc-toclevels`, we will have `toclevels-html` and `toclevels-doc`.

_Originally posted by @opoudjis in https://github.com/metanorma/metanorma-ogc/issues/449#issuecomment-1308670212_

**Comment by opoudjis** [comment]
Adding distinct toclevels-pdf
