### ISSUE TITLE
source blocks - no line numbers

### ISSUE THREAD

**Issue by jechterhoff** [metanorma/metanorma-ogc#460]
The metanorma compiler does not appear to support line numbers on source blocks.

I’ve prepared a test case. See [test.zip](https://github.com/metanorma/metanorma-ogc/files/10084983/test.zip). The folder contained in the archive was copied from the OGC templates repository on GitHub, for Best Practice document, and renamed to “test”.

You can see the issue in document.html, section 7.1.1, where I’ve added two source blocks – both of which in sections\clause_7_normative_text.adoc are declared with `[source,json,linenumbers]`. No line numbers occur in the HTML.

Ideally, I'd like to get an output (regarding the behavior of line numbers) as shown [here](https://docs.ogc.org/per/20-012.html#example_jsonschema_union_minMaxProperties), an example from the UGAS-2020 engineering report.

----

The HTML file was created using the following command, executed in a Windows environment, with local installation (as described on https://www.metanorma.org/install/windows/): `metanorma compile --agree-to-terms -t ogc -x xml,html document.adoc`

Command “metanorma --version” returns:

Metanorma 1.5.2
Metanorma::Cli 1.6.6
Metanorma::Standoc 2.2.7/IsoDoc 2.3.5
Metanorma::ISO 2.2.3
Metanorma::Iec 2.1.12
Metanorma::IEEE 0.1.2
Metanorma::Ietf 3.0.13
Metanorma::Generic 2.2.4
Metanorma::BIPM 2.1.12
Metanorma::CC 2.1.12
Metanorma::Csa 2.1.12
Metanorma::IHO 0.6.12
Metanorma::M3AAWG 2.1.12
Metanorma::UN 0.9.12
Metanorma::Ogc 2.2.6
Metanorma::ITU 2.1.12

The log output when executing the compile command was:

Document Attributes: '' is not a permitted subtype of Standard: reverting to 'implementation'
[relaton] Identification of Common Molecular Subsequences does not have a recognised prefix
[relaton] ZIB Structure Prediction Pipeline does not have a recognised prefix
[relaton] The Grid does not have a recognised prefix
[relaton] Grid Information Services for Distributed Resource Sharing does not have a recognised prefix
[relaton] The Physiology of the Grid does not have a recognised prefix
[relaton] NCBI does not have a recognised prefix
[relaton] (OGC 15-097) not found.
[relaton] Identification of Common Molecular Subsequences does not have a recognised prefix
[relaton] ZIB Structure Prediction Pipeline does not have a recognised prefix
[relaton] The Grid does not have a recognised prefix
[relaton] Grid Information Services for Distributed Resource Sharing does not have a recognised prefix
[relaton] The Physiology of the Grid does not have a recognised prefix
[relaton] NCBI does not have a recognised prefix
AsciiDoc Input: (Section: Bibliography): no anchor on reference, markup may be malformed: see
https://www.metanorma.com/author/topics/document-format/bibliography/ ,
https://www.metanorma.com/author/iso/topics/markup/#bibliographies
: For citations in the text please use square brackets and consecutive numbers: [1], [2], [3]
[relaton] OGCTB12 does not have a recognised prefix
[relaton] OGCTB12 does not have a recognised prefix
Anchors: (XML Line 000273): normalised identifier in <requirement id="http___www.opengis.net_spec_ABCD_m.n_req_req-class-a" model="ogc" obligation="requirement" type="class"/> from http://www.opengis.net/spec/ABCD/m.n/req/req-class-a
Anchors: (XML Line 000297): normalised identifier in <requirement id="_req_req-class-a_req-name-1" model="ogc" obligation="requirement" type="general"/> from /req/req-class-a/req-name-1
Anchors: (XML Line 000215): Crossreference target OGC06-121r9 is undefined
Style: Submitters is missing!
Metanorma XML Style Warning: (XML Line 000235): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 000249): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 000263): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 000267): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 000379): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 000302): Table should have title
Metanorma XML Style Warning: (XML Line 000412): Table should have title
Requirements: (XML Line 000273): Requirement class http___www.opengis.net_spec_ABCD_m.n_req_req-class-a has no corresponding Conformance class
Requirements: (XML Line 000297): Requirement _req_req-class-a_req-name-1 has no corresponding Conformance test
Document Attributes: swg-draft is not an allowed status for best-practice
Metanorma XML Syntax: (XML Line 000143:104): element "clause" not allowed here; expected the element end-tag or element "submitters"
Metanorma XML Syntax: (XML Line 000400:221): element "docidentifier" not allowed yet; missing required element "title"
Metanorma XML Syntax: (XML Line 000401:364): element "docidentifier" not allowed yet; missing required element "title"
Metanorma XML Syntax: (XML Line 000402:229): element "docidentifier" not allowed yet; missing required element "title"
Metanorma XML Syntax: (XML Line 000403:354): element "docidentifier" not allowed yet; missing required element "title"
Metanorma XML Syntax: (XML Line 000404:301): element "docidentifier" not allowed yet; missing required element "title"
Metanorma XML Syntax: (XML Line 000405:161): element "docidentifier" not allowed yet; missing required element "title"
Metanorma XML Syntax: (XML Line 000496:185): element "docidentifier" not allowed yet; missing required element "title"
Metanorma XML Syntax: (XML Line 000554:18): element "docidentifier" not allowed yet; missing required element "title"
No label has been processed for ID OGC06-121r9

**Comment by opoudjis** [comment]
The Rouge solution is to generate a table, with the line numbers in one column, and the code in another; CodeRay does the same. (CodeRay has only one row in its table; Rouge has the option of one row, or one row per line of code.) The example you've posted is doing that, and I'll do the same unless there's a compelling reason not to.

There is one reason not to:

>  Therefore, while the table is more DOM-friendly for JavaScript scripting, long code lines will mess with the column alignment.

—because of line overflow. But there are mitigations for that, including optional horizontal scrolling.

**Comment by jechterhoff** [comment]
Just tested with the latest version of metanorma on Windows (using Chocolatey for install). 

For the following example:

```text
[[example_req_core_jsonschema_types_inheritance_generalization]]
.JSON Schema example for realizing generalization using "allOf"
[source,json,linenumbers]
----
{
  "$schema": "http://json-schema.org/draft/2019-09/schema",
  "$defs": {
    "TypeA": {
      "properties": {
        "propertyA": {
          "type": "number"
        }
      },
      "required": [
        "propertyA"
      ]
    },
    "TypeB": {
      "allOf": [
        {
          "$ref": "#/$defs/TypeA"
        },
        {
          "type": "object",
          "properties": {
            "propertyB": {
              "type": "string"
            }
          },
          "required": [
            "propertyB"
          ]
        }
      ]
    }
  },
  "$ref": "#/$defs/TypeB"
}
----
```

The result is:

![line_number_example_questionable_start](https://user-images.githubusercontent.com/4831647/211249597-c4380c1a-442c-457a-8d3f-b55fc0adb271.png)

Notice the first two empty lines, which are not present in the source. I would have expected that the first line from the source ("{") is numbered as "1".

**Comment by opoudjis** [comment]
Addressing in https://github.com/metanorma/metanorma-ogc/issues/490
