### ISSUE TITLE
table with regular expressions

### ISSUE THREAD

**Issue by jechterhoff** [metanorma/metanorma-ogc#466]
Here is another interesting issue: I'd like to add a couple regular expressions within a table. However, I am having a really hard time achieving a useful - and, which is the real issue: correct - rendering of these expressions:

```
^\d{4}-\d{2}-\d{2}$
^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d)?(Z|((\+|-)\d{2}:\d{2}))?$
^\d{2}:\d{2}:\d{2}(\.\d)?(Z|((\+|-)\d{2}:\d{2}))?$
```

Here is the source code:

```text
[[table_req_core_iso19103_primitive_types]]
.JSON Schema implementation of ISO 19103 primitive types
[width="90%",options="header"]
|===
| UML class | JSON Schema simple type | JSON Schema keywords
|Boolean |boolean |
|CharacterString |string |
|Date |string a|format=date, pattern= ^\d{4}-\d{2}-\d{2}$
[options="unnumbered"]
....
^\d{4}-\d{2}-\d{2}$
....
|DateTime |string a|format=date-time, pattern= ^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d)?(Z\|((\+\|-)\d{2}:\d{2}))?$
[options="unnumbered"]
....
^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d)?(Z\|((\+\|-)\d{2}:\d{2}))?$
....
|Decimal |number |
|Integer |integer |
|Number |number |
|Real |number |
|Time |string a|format=time, pattern= ^\d{2}:\d{2}:\d{2}(\.\d)?(Z\|((\+\|-)\d{2}:\d{2}))?$
[options="unnumbered"]
....
^\d{2}:\d{2}:\d{2}(\.\d)?(Z\|((\+\|-)\d{2}:\d{2}))?$
....
|URI |string |format=uri
|===

JSON Schema pattern values for specific values of JSON Schema keyword 'format':

* date: ^\d{4}-\d{2}-\d{2}$
* date-time: ^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d)?(Z|((\+|-)\d{2}:\d{2}))?$
* time: ^\d{2}:\d{2}:\d{2}(\.\d)?(Z|((\+|-)\d{2}:\d{2}))?$
```

As you can see, I tried different ways of including the regular expressions - both inside and outside of the table.

When compiled, I get the following:

![table_with_regex_issue](https://user-images.githubusercontent.com/4831647/205074830-e70eb9ee-b3f2-48ed-aff0-51f20b07cc39.png)

and 

![table_with_regex_issue2](https://user-images.githubusercontent.com/4831647/205075085-ad756bf6-058b-41de-bddd-a0a73a3cd797.png)

In the table, when the expressions are written as plain text, I get 
`^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d)?(Z|\+|-)\d{2}:\d{2}?$` instead of 
`^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d)?(Z|((\+|-)\d{2}:\d{2}))?$`. 
Notice the missing parentheses after 'Z|'!

So I tried literal blocks. However, on the one hand, they are numbered as figures, even though I've included the 'unnumbered' option (and, to be honest, the cell content looks fairly ugly with the literal block), on the other hand, I've read on https://www.metanorma.org/author/topics/document-format/#unsupported-asciidoc-features that literal content is disallowed in most SDOs - not sure if OGC is one of them.

I also tried to write the regular expressions below the table, but then the parentheses are also omitted.

@ronaldtse Is there a way to solve this?

**Comment by ronaldtse** [comment]
@jechterhoff in general it is very difficult to do these escapes in AsciiDoc using the inline code format.

The recommendation is to use source code blocks. Would that work?

**Comment by ronaldtse** [comment]
Sorry I just finished reading the message! 

> they are numbered as figures, even though I've included the 'unnumbered' option

This may be a bug for us to solve.

> the cell content looks fairly ugly with the literal block

This is something we need to deal with.

> literal content is disallowed in most SDOs

How about using source blocks?

**Comment by jechterhoff** [comment]
@ronaldtse Source blocks indeed solve the issue - both inside table cells as well as outside. Thank you for the suggestion.

![table_with_regex_issue_solution](https://user-images.githubusercontent.com/4831647/205081081-3a27ecb4-5a8d-4316-9538-5a83e02963db.png)

For me, the issue is solved, so I'm closing it.

**Comment by ronaldtse** [comment]
Thank you @jechterhoff !
