### ISSUE TITLE
background color of text selected by the user

### ISSUE THREAD

**Issue by jechterhoff** [metanorma/metanorma-ogc#467]
When compiling a draft OGC document with metanorma to an HTML page, then the text selection behavior is an issue:

* When the page is opened in Firefox (107.0.1 (64-Bit)), then the background color of text selected by the user is white - even though the background of the page already is white (or some slight variation of it). Thus, one cannot really see the text selection in Firefox.
* On the other hand, when the page is opened in Chrome, the background color for selected text is blue, and the text color is white.

Could this have something to do with the following CSS statement, which I found in the HTML page:

```
::selection,
::-moz-selection {
  background: white;
  color: #00335b; }
```

**Comment by opoudjis** [comment]
It does. There are two issues (and this is not my CSS):

* First, ::selection without a preceding CSS selector is syntax recognised by Firefox, but not Safari or Chrome
* Second, the intention of this design (and it's been done by the CSS designer consistently) is to highlight the selected text the same way as hover over links is highlighted, with distinctive foreground and background colours. In the case of OGC, they are not distinctive enough.

Will fix once I work out the correct CSS syntax

**Comment by opoudjis** [comment]
<img width="1011" alt="Στιγμιότυπο 2022-12-13, 14 14 01" src="https://user-images.githubusercontent.com/1911039/207217582-e809e168-5154-4334-906d-522aaec124dc.png">

Issue was the ::selection and the ::-moz-selection pseudo-elements being in the same line.

**Comment by jechterhoff** [comment]
Works as expected now. :-) Thanks!
