### ISSUE TITLE
Document identifiers for OGC references depend on stages?

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#47]
Does the OGC document identifier take into account the document stage?

For example, https://github.com/metanorma/relaton-iso/issues/61 is an example of how ISO document identifiers depend on the stage.

> * FDIS Stage: "ISO 11136:2014/FDAmd 1"
> * DIS Stage: "ISO 3839:1996/DAmd 1"
> * CD Stage: "ISO 16063-1:1998/CD Amd 2"
> * WD Stage: "ISO/IEC 23008-1/WD Amd 1"
> * AWI Stage: "ISO 10844:2014/AWI Amd 1"
> * NP Stage: "ISO 18562-1:2017/NP Amd 1"

Right now, we only know they go like this:
* `OGC 18-005r4`

ping @ghobona @gbuehler @ogcscotts

**Comment by ronaldtse** [comment]
PIng @ghobona -- thanks!

**Comment by ghobona** [comment]
@ronaldtse 

No, the document identifier does not reflect the document stage.

**Comment by ronaldtse** [comment]
Thanks @ghobona ! Closing.
