### ISSUE TITLE
Add meta tags for keywords and description to the generated HTML document

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-ogc#470]
Please add meta tags for keywords and description to the generated HTML document.

This idea originated from https://github.com/opengeospatial/templates/issues/18 by @heidivanparys.

Some guidance information is at https://www.w3schools.com/tags/tag_meta.asp

**Comment by opoudjis** [comment]
Keywords are already supported in metanorma, and would be a straightforward addition.

Wouldn't the description be just the abstract?

**Comment by opoudjis** [comment]
The description, contrary to @heidivanparys example, is taken from the abstract, which is already supplied to documents as a matter of course, rather than creating a new element.
