### ISSUE TITLE
PDF: Identifier label is cut off in rendering due to cell width

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-ogc#473]
Issue originally recorded at https://github.com/opengeospatial/ogcapi-tiles/issues/147

This appears to happen on requirements and recommendation identifiers - only the `IDENTIFI` is legible (with part of the `E` and none of the `R`)

An example (rendered in Chromium or Firefox):

![image](https://user-images.githubusercontent.com/174642/206423017-e5fbe6bf-3973-454e-9080-996a86751b71.png)

**Comment by Intelligent2013** [comment]
This issue similar to https://github.com/metanorma/mn-native-pdf/issues/463 (fixed a week ago):
![image](https://user-images.githubusercontent.com/5559926/204902496-332b2a27-72be-4832-a8d6-e65c9486ea8a.png)

May be there is an another reason... Will check.

**Comment by ronaldtse** [comment]
@ghobona thank you for reporting this!

**Comment by Intelligent2013** [comment]
Confirmed, there isn't issue with latest metanorma-ogc gem v2.3.0:
![image](https://user-images.githubusercontent.com/5559926/206505346-821d1c99-f71b-4faf-bdf9-192202d8879e.png)

@ghobona please update metanorma to the latest version.

**Comment by Intelligent2013** [comment]
@ghobona thank you for the information, you are right, the metanorma docker isn't released yet due the build error (https://github.com/metanorma/metanorma-docker/actions/runs/3621578919/jobs/6105421888). Will fix it.

**Comment by Intelligent2013** [comment]
@ghobona sorry for a delay, I've checked with metanorma-docker v1.6.9 released today, and issue fixed:
![image](https://user-images.githubusercontent.com/5559926/208663998-964a52ae-9962-4803-b639-2c6991eecc63.png)

**Comment by ronaldtse** [comment]
I believe this has been fixed. @ghobona can we close this issue? Thanks.

**Comment by ronaldtse** [comment]
Closing.
