### ISSUE TITLE
sourcecode highlighting: PDF

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-ogc#478]
Follow-on from https://github.com/metanorma/metanorma-ogc/issues/465

The css to apply to the input sourcecode will be in `/misc-container/source-highlighter-css`. If that element is absent, there is no highlighting.

If there are no spans in the sourcecode, there is nothing to highlight.

I'll post sample Presentation XML sourcecode here soon.

**Comment by opoudjis** [comment]
Sample Presentation XML:
[Αρχειοθήκη 4.zip](https://github.com/metanorma/metanorma-ogc/files/10237189/4.zip)

**Comment by Intelligent2013** [comment]
Done:
![image](https://user-images.githubusercontent.com/5559926/208264576-5645f896-f7db-48e9-9a49-06b618b817e1.png)
...
![image](https://user-images.githubusercontent.com/5559926/208264604-9467fc9f-f1e1-42de-8f5a-b9c4007f6e2e.png)

**Comment by Intelligent2013** [comment]
From https://github.com/metanorma/metanorma-ogc/issues/465#issuecomment-1365684772
Need update for line numbers. Presentation XML fragment:
```xml
<sourcecode id="_2d41c394-330f-97fe-07d9-b2f0826c1e3b" lang="ruby" linenums="true">
	<name>Figure 2</name>
	<table class="rouge-line-table">
		<tbody>
			<tr id="line-1" class="lineno">
				<td class="rouge-gutter gl" style="-moz-user-select: none;-ms-user-select: none;-webkit-user-select: none;user-select: none;">
					<pre>1</pre>
				</td>
				<td class="rouge-code">
					<sourcecode>
						<span class="nb">require</span>
						<span class="s2">"isodoc/ogc/html_convert"</span>
						<span class="c">
							<callout target="_d96031ec-d7c7-d5b7-2650-2aa4dd78adfa">1</callout>
						</span>
						<span class="c">
							<callout target="_60deac24-f8b4-530e-1e1d-ab047ee35671">2</callout>
						</span>
					</sourcecode>
				</td>
			</tr>
			<tr id="line-2" class="lineno">
				<td class="rouge-gutter gl" style="-moz-user-select: none;-ms-user-select: none;-webkit-user-select: none;user-select: none;">
					<pre>2</pre>
				</td>
				<td class="rouge-code">
					<sourcecode>
						<span class="nb">require</span>
						<span class="s2">"isodoc/ogc/pdf_convert"</span>
					</sourcecode>
				</td>
			</tr>
```

**Comment by Intelligent2013** [comment]
Done:

![image](https://user-images.githubusercontent.com/5559926/209817524-7027cab3-439a-49ef-b30c-48af62fc2092.png)

![image](https://user-images.githubusercontent.com/5559926/209817393-877fbdac-3ad7-40b1-85d0-b15ddef73a7e.png)

**Comment by Intelligent2013** [comment]
Line numbers on-fly in XSLT converted to mathml:
```xml
<math xmlns="http://www.w3.org/1998/Math/MathML">
	<mtext>1</mtext>
</math>
```
and text selection is working for source code only now:
![image](https://user-images.githubusercontent.com/5559926/209842983-e8ab1d30-6e0c-4a88-affd-05ef65036704.png)

Mathml text renders a bit bolded than main text, so I will investigate it.

**Comment by Intelligent2013** [comment]
> Mathml text renders a bit bolded than main text, so I will investigate i

There isn't issue: https://github.com/metanorma/mn2pdf/issues/117#issuecomment-1368016480
