### ISSUE TITLE
Fix Standard Clause 0 text

### ISSUE THREAD

**Issue by ogcscotts** [metanorma/metanorma-ogc#488]
https://github.com/opengeospatial/templates/blob/master/standard/template/sections/clause_0_front_material.adoc

Somehow, much of the Clause 0 template text disappeared in a previous version of the Metanorma template. See retored text. Some is generated automatically (e.g., Submitting organizations), so adjust template, if needed.

**Comment by opoudjis** [comment]
The current template is a bit messy too. So:

````
Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.
````

The OGC declaration is text already included in the document boilerplate automatically. I don't think it should be in both places. I do see that the optional ISO text is left, commented out, in the template preface.

The keywords, submitters, and submitting organisations are automatically inserted, so I'm only inserting the security considerations and contributors clauses into the template.
