### ISSUE TITLE
Add example in the documentation about use of conformance-test tag in the Definitions List

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-ogc#489]
Currently none of the [examples](https://www.metanorma.org/author/topics/document-format/requirements-modspec/#conformance-class) in the metanorma.org documentation uses the `conformance-test` tag in the Definitions List.

I suggest adding an example such as the one shown in the attached figure.

![Screenshot 2023-01-13 at 11 09 23](https://user-images.githubusercontent.com/18121038/212306932-48252cd2-400a-41d6-b9c4-688baa9cd9f5.png)

**Comment by opoudjis** [comment]
Added as PR, but @ronaldtse is refactoring the site contents, so won't be merged in soon.
