### ISSUE TITLE
PDF: definition lists unclear where the term ends and where the definition starts

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#523]
There are actually 3 definition lists here.

<img width="499" alt="Screenshot 2023-03-29 at 12 23 37 AM" src="https://user-images.githubusercontent.com/11865/228305663-57c68fe5-205d-4611-be8f-12ab0ab9f208.png">

We need to make some visual distinction:
1. The indentation is not very clear
2. The text formatting and color

The following lists are also hard to distinguish.
<img width="477" alt="Screenshot 2023-03-29 at 12 24 32 AM" src="https://user-images.githubusercontent.com/11865/228305879-b330c941-64e9-4380-ab98-b9b178d41bd8.png">

**Comment by ronaldtse** [comment]
Maybe add a "blue" vertical bar between the term and the definition in the definition list? (like a table border)

**Comment by Intelligent2013** [comment]
I've tried to add the vertical bar:
![image](https://user-images.githubusercontent.com/5559926/228824700-81b27d03-1e4c-4907-a33d-dd1b1a08f7ed.png)

![image](https://user-images.githubusercontent.com/5559926/228824824-0cc1a763-5f5f-4142-bb3f-669bdee86ef2.png)

![image](https://user-images.githubusercontent.com/5559926/228824924-7b0f3c4b-fb45-485a-858b-595afce77f2d.png)

I'll try one more variant - increase the minimal distance between the term and description up to 5mm, and add a vertical bar at the left of term.

**Comment by ronaldtse** [comment]
How about we use a two light background colors for the term vs definition?

**Comment by Intelligent2013** [comment]
> I'll try one more variant - increase the minimal distance between the term and description up to 5mm, and add a vertical bar at the left of term.

![image](https://user-images.githubusercontent.com/5559926/228832886-0326eccb-6550-48ea-bd1f-a6b6f81287e1.png)

![image](https://user-images.githubusercontent.com/5559926/228832998-068e3184-b03c-41b5-bab5-384815b930c2.png)

![image](https://user-images.githubusercontent.com/5559926/228833117-640579c8-abfe-4eed-982b-983350fd181b.png)

> How about we use a two light background colors for the term vs definition?

ok, I'll try.

**Comment by Intelligent2013** [comment]
![image](https://user-images.githubusercontent.com/5559926/228837511-838bdc36-b946-4692-80c8-45b463f6da26.png)
![image](https://user-images.githubusercontent.com/5559926/228837583-06b950c9-0429-4785-9c63-8c2ad757cad7.png)
![image](https://user-images.githubusercontent.com/5559926/228837730-51efb1bb-3531-4259-81d0-ca438bc009eb.png)

Nested `dl` example:
![image](https://user-images.githubusercontent.com/5559926/228837837-d000022f-32b2-43ba-bd99-98b57bc8a507.png)

**Comment by ogcscotts** [comment]
@ronaldtse I like the style - it is very clear.

**Comment by ghobona** [comment]
@ronaldtse The style looks good. 

The only issue is that on the screenshot of clause 6.2.2, there is a line that appears to merge 'NOTE' with 'A', creating **NOTE**A ....

The same applies to the notes in clause 9.5.2.

**Comment by ronaldtse** [comment]
Thanks @ogcscotts @ghobona !

The "**NOTE**A" issue should have been fixed in #522.

**Comment by ronaldtse** [comment]
@Intelligent2013 let's confirm the most recent style change, and once that is done let's close this ticket. Thanks!

**Comment by Intelligent2013** [comment]
All done:
![image](https://user-images.githubusercontent.com/5559926/232194470-92ac1864-1204-44d0-a647-b805b8d19c36.png)

**Comment by ronaldtse** [comment]
Thank you!
