### ISSUE TITLE
PDF: TOC lists of tables showing strange empty line

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#524]
<img width="576" alt="Screenshot 2023-03-29 at 12 27 20 AM" src="https://user-images.githubusercontent.com/11865/228306514-25893f79-ffcf-4e11-a737-7bc62f4c57fd.png">

Source: [Archive.zip](https://github.com/metanorma/metanorma-ogc/files/11091990/Archive.zip)

**Comment by Intelligent2013** [comment]
This issue occurs due the table in `metanorma-extension`:
```xml
<metanorma-extension>
		<table id="_misccontainer_anchor_aliases">
			<name>Table</name>
```
Will fix.

**Comment by Intelligent2013** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/5559926/228666351-ef47dd64-e5c4-4397-9546-f7175596cf37.png)
