### ISSUE TITLE
Change structure of Engineering Report documents and removal of validation

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-ogc#527]
OGC Staff discussed the structure of Engineering Reports during the week of March 20th, 2023 and agreed to change the structure of Engineering Report documents to:

* Executive Summary
* Keywords
* Contributors (table as we have in Submitters right now)
* Introduction
* Chapters as needed (all references should be inline)
* Annex A: Abbreviations/Acronyms
* Annex B-Z as needed

OGC Staff also agreed to remove all validation from Engineering Report documents.

Please note that the changes described above only affect Engineering Report documents.

@ronaldtse Could you please make the changes to the metanorma-ogc plugin?

**Comment by ronaldtse** [comment]
Thank you for the information @ghobona . What is the timeline for enactment of this new policy?

We will have to update metanorma-ogc implementation as well as documentation.

FYI @opoudjis .

**Comment by ghobona** [comment]
@ronaldtse Ideally in May-June 2023. This would enable editors of Testbed-19 engineering reports to use the template.

**Comment by jerstlouis** [comment]
@ghobona I imagine the intent is to have a Bibliography Annex in most ERs? (but no more _Normative References_).

**Comment by opoudjis** [comment]
Do I get rid of the following validation rules as well, @ghobona? (I advise not to)

* No version permitted on Engineering reports
* Executive Summary required for Engineering reports
* Document integrity checks shared throughout Metanorma:
  * repetition of anchors (fatal error)
  * referential integrity of cross-references
  * nested assets (table contains table, note contains note, example contains example)
  * normative references (should not be there)
  * iev_validate(doc.root) (term cited from IEV has correct term name)
  * concept_validate(doc, "concept", "refterm") (term citations should point to actual terms)
  * concept_validate(doc, "related", "preferred//name") (related terms should point to actual terms)
   * table_validate(doc) (table has internally consistent number of rows and columns)
   * requirement_validate(doc) (validation rules specific to requirements modelling language)
   * image_validate(doc) (images exist and are valid)
   * math_validate(doc) (formulas are well-formed)

**Comment by jerstlouis** [comment]
@opoudjis @ghobona My $0.02 is that these validation rules are very useful for ERs as well.

**Comment by ghobona** [comment]
@opoudjis Yes, please remove all of the validation rules on Engineering Reports.

**Comment by ghobona** [comment]
@ronaldtse @opoudjis I defer to you on which validation rules are a must-have and which ones are not.

**Comment by ronaldtse** [comment]
Thank you @ghobona !

**Comment by opoudjis** [comment]
The structure already being enacted in the templates directory and legal, no further changes are required.
