### ISSUE TITLE
Source code annotation key color: use blue instead of red

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#537]
@Intelligent2013 for the OGC flavor, can we use the blue color accent instead of red? Thanks!

_Originally posted by @ronaldtse in https://github.com/metanorma/metanorma-standoc/issues/769#issuecomment-1501040173_

**Comment by Intelligent2013** [comment]
@ronaldtse the styles determined in the element `source-highlighter-css` with CSS (`sourcecode .c`, `class="c"`):
```xml
<source-highlighter-css>
...
sourcecode .c, sourcecode .ch, sourcecode .cd, sourcecode .cm, sourcecode .cpf, sourcecode .c1 {
  color: #FF0000;
}
...
</source-highlighter-css>
...
<sourcecode id="_" lang="adoc"><name>Figure 32 — Terms and definitions in Metanorma AsciiDoc</name>== Terms and definitions <span class="c"><callout target="_91a20d95-12f8-77be-6549-d8679a9e0eb0">1</callout></span>
...
<dt id="_91a20d95-12f8-77be-6549-d8679a9e0eb0"><span class="c">1</span></dt>
<dd><p id="_">Mandatory clause title</p>
</dd>
```

So, this task for @opoudjis.

**Comment by opoudjis** [comment]
Yes it is, but at least it's just modifying a stylesheet definition (which pdf also accepts)

**Comment by opoudjis** [comment]
We will override Rouge CSS stylesheets, rather than add overrides to the default CSS, so that the PDF processing from @Intelligent2013 is not having to parse overrides in its processing of the CSS.

**Comment by opoudjis** [comment]
Keywords are already blue. How about cyan for comments?

<img width="500" alt="Screenshot 2023-04-09 at 23 28 58" src="https://user-images.githubusercontent.com/1911039/230781871-fb0e9af6-c6d9-4c70-8eaa-ad5e785ff6d4.png">

<img width="734" alt="Screenshot 2023-04-09 at 23 28 33" src="https://user-images.githubusercontent.com/1911039/230781865-94325b87-ae1a-4e7d-b0ad-03783fd5d771.png">

**Comment by ronaldtse** [comment]
@opoudjis happy with that. Thanks!
