### ISSUE TITLE
Support new document type: "Community Practice"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#54]
Latest document type mapping: (from @ghobona)

AS => Abstract Specification
BP => Best Practice
CAN => Candidate Standard
CC => Conformance Class
CR => Change Request
CS => Community Standard
CP => Community Practice
DP => Discussion Paper
DP-Draft => Draft Discussion Paper
IPR => Interoperability Program Report-Engineering Specification
IS => Implementation Standard
ISC => Implementation Standard Corrigendum
ISx => Extension Package Standard
Notes => Notes
ORM => OGC Reference Model
PC => Profile Corrigendum
PER => Public Engineering Report
POL => Policy
POL-NTS => Policy - Name Type Specification
Primer => Primer
Profile => Profile
RFC => Request for Comment
Retired => Retired document
SAP => Standard Application Profile
TS => Test Suite
WhitePaper => Whitepaper

The "D-" prefix means that a document is deprecated

> 1. CP — is there a special template / structure to be enforced for it? Or is it similar to any other kind of existing template?

> It's similar to the other documents.

This is a master task that needs the following issues:

1. Update OGC document model in https://github.com/metanorma/metanorma-model-ogc (@opoudjis )
2. Implement CP as document type in Metanorma https://github.com/metanorma/metanorma-ogc
3. Support CP citation in Relaton (https://github.com/metanorma/relaton-ogc) and Metanorma (https://github.com/metanorma/metanorma-ogc)
4. Create a CP template in OGC templates (https://github.com/metanorma/mn-templates-ogc)

**Comment by opoudjis** [comment]
````
"abstract-specification" | "best-practice" | "candidate-standard" | "conformance-class" | "change-request" | "community-practice" | "community-standard" | "discussion-paper" | "draft-discussion-paper" | "interoperability-program-report" | "implementation-standard" | "implementation-standard-corrigendum" | "extension-package-standard" | "notes" | "ogc-reference-model" | "profile-corrigendum" | "public-engineering-report" | "policy" | "policy-name-type=specification" | "primer" | "profile" | "request-for-comment" | "retired" | "standard-application-profile" | "test-suite" | "whitepaper" | "approved-technical-baseline" | "recommendation-paper"
````

**Comment by opoudjis** [comment]
Update OGC document model: done.
Support CP citation in Relaton: @andrew2net, is  https://github.com/relaton/relaton-ogc/issues/2 doing that?
Implement CP as document type in Metanorma: to do
Document types in metanorma.com: to do
Create a CP template in OGC templates: to do, and that will be Manuel.

**Comment by ronaldtse** [comment]
In case it wasn't clear before:

> The “D-“ prefix in the type attribute means that the document is deprecated.

**Comment by ronaldtse** [comment]
@opoudjis just for the record, I know you're doing to do it, but we need to update documentation :wink:

**Comment by opoudjis** [comment]
Do I need to care about these abbreviations at all?

**Comment by ronaldtse** [comment]
@opoudjis probably not at this point.

**Comment by andrew2net** [comment]
> 3\. Support CP citation in Relaton (https://github.com/metanorma/relaton-ogc)

@ronaldtse what is CP citation? Does it mean references with CP prefix?

**Comment by ronaldtse** [comment]
@andrew2net yes, you're exactly right. Inline references of CP documents.

Such as:

```adoc
== Content

Refer to <<OGCCP123>>.

[bibliography]
== Bibliography
* [[[OGCCP123,OGC CP 123-r3]]]
```

And @opoudjis I might be wrong -- the abbreviations may only be needed for @andrew2net 's work in relation, but it might spill over to Metanorma references.

**Comment by andrew2net** [comment]
@ronaldtse I can't find any CP references in the JSON data.

**Comment by ronaldtse** [comment]
@andrew2net perhaps there aren’t any CP document published yet.

**Comment by andrew2net** [comment]
@ronaldtse I think it should fetch such a kind of reference, but to be sure we need published documents to test.

**Comment by opoudjis** [comment]
Document types in metanorma.com: done.

**Comment by opoudjis** [comment]
I am assuming that naming `:doctype: community-practice` in the document attributes is all that is needed, and that the document band and title page do not need to be adjusted. In that case, there is nothing else for me to do...

**Comment by ronaldtse** [comment]
> I am assuming that naming :doctype: community-practice in the document attributes is all that is needed, and that the document band and title page do not need to be adjusted. In that case, there is nothing else for me to do...

Yes.

As long as Relaton-OGC supports "CP" prefix, we're good.

**Comment by opoudjis** [comment]
There aren't any CP prefixed documents to test this on, as @andrew2net has indicated, and I'm certainly not finding any on the site.

Closing issue. If a CP prefixed document is published and relaton-ogc does not find it, that becomes a new issue.

**Comment by ronaldtse** [comment]
> There aren't any CP prefixed documents to test this on, as @andrew2net has indicated, and I'm certainly not finding any on the site.

As described this is a new document type with nothing published yet. It still means we need to support it.
