### ISSUE TITLE
PlantUML rendering broken?

### ISSUE THREAD

**Issue by securedimensions** [metanorma/metanorma-ogc#549]
# The rendering for plantuml diagrams is broken.
The rendering of plantuml diagrams was working fine I think, but now it's broken.

# Example
````
.Conformance Class Model
[plantuml]
....
@startuml

package OGC {
    GeoXACML_Core ..d.|> GeoXACML_API: <<optional>>
    GeoXACML_Core ..d.|> GeoXACML_CRS_Transformation: <<optional>>
    GeoXACML_Spatial_Analysis -r-|> GeoXACML_Core: <<optional>>
}

package ISO {
    SimpleFeatures -o GeoXACML_Core : use
}

package OASIS {
    XACML3 <|-d- GeoXACML_Core: <<extends>>
}

abstract class SimpleFeatures {
    ISO 19125:2004
    # Geometry
    # WKT
    # WKB
    Functions ()
}

abstract class XACML3 {
    OASIS XACML 3.0
    Policy schema
    AD and ADR schema
    Functions ()
}

class GeoXACML_Core {
    # XACML DataType Geometry
    # XACML AttributeValue attribute 'srid'
    # XACML AttributeValue attribute 'precision'
    # Boolean allowTransformation=false

    Geometry encoding based on WKT and WKB
    Processing may result in 'geometry-error'
    
    CRS default 'urn:ogc:def:crs:OGC::CRS84'
    Processing different CRS result in 'crs-error'
    
    Processing may result in 'precision-error'
    
    Geometry Functions ()
    Spatial Relations Functions ()
    XACML Bag / Set Functions ()
}

class GeoXACML_Spatial_Analysis {
    # Boolean allowTransformation=false

    Spatial Analysis Functions ()
}

interface GeoXACML_CRS_Transformation {
    # XACML AttributeValue attribute 'allowTransformation'
    # Boolean allowTransformation={false, true}
}

interface GeoXACML_API {
    OGC OpenAPI
    OGC Landing Page
    OGC Conformance Class Page
}

@enduml
....
````

# Visual Studio Code rendering
Rendering the code above produces the following image:

![grafik](https://github.com/metanorma/metanorma-ogc/assets/25054643/30e858cf-6d8c-4b07-809a-b3b98ddcbc3c)

# Metanorma rendering
Rendering the code above with metanorma (`docker run -v "$(pwd)":/metanorma metanorma/metanorma metanorma compile -t ogc -x html,pdf --agree-to-terms 22-050.adoc`) produces the following image:

![grafik](https://github.com/metanorma/metanorma-ogc/assets/25054643/ad271f1f-92e0-4dca-bbdf-aa1d6dad6d07)

**Comment by ronaldtse** [comment]
Thank you @securedimensions for the report.

This is interesting because Metanorma does not do anything special with PlantUML diagrams. We will investigate.

**Comment by opoudjis** [comment]
The command line plantuml (`plantuml a.txt`) does the following with the supplied PlantUML:

![a](https://github.com/metanorma/metanorma-ogc/assets/1911039/991c6d2e-82e3-467c-92aa-3dc8ed08d195)

That is identical to what you are getting when Metanorma parses the document. 

So clearly the Visual Studio Code implementation of PlantUML is cleverer than the command line implementation: the former is conflating package and class diagram definitions, and fleshing out classes found in the former with class definitions found in the latter. The command line tool doesn't.

**Comment by opoudjis** [comment]
Looking more closely at PlantUML, I refer you first to the halfway solution of embedding class definitions within packages

https://forum.plantuml.net/8975/dependency-between-packages-containing-classes?show=9003#c9003

which however does not work:

//www.plantuml.com/plantuml/png/ZLJlQzim4Ftkl-9W7xp1xFL71vl9GXsNbh2EX3XiWp72HJvdPh9a99ajfFdV9_-eMtkc95yKI-_UlNjtqhKsg4oPSwT0zXjt18kx27uuXuF3E6eDToI_Xz6N-qrSeCcGRqA1VAyp3GS7xEyLpAJaX0AGS_bdhL3eLAhSWgNub2BNvDJ0DXww-DjIi0gauVKRv-WucJ2aKcJqb3DSpjiqbQf5GSBkTD_tA99Cx61fPNURaHHrUc5vegg2vdYSFrh5cxxYhgeQ0A4nAjkMXhuYBmdmyHFSaMhT4mmvr8wy1QDAEbfLGvSZgMYWuGODhlT5BJide_OdAjGgIzmJiOKYbkckXbERsaa24apMpTYYfWIaW6-Vru0YiUkiXYwLPAHrXSbn3ufqoGra0jnTI-AHKbAv3RDj3IIKOWLoIoK2kME1tGYOqe5jT11On8ShTyYTP6bAYeIf69vdiN5TWfVrT6Qq-7wflRdjJVQAE3O7GqZh_mnty0vYCl_D_l7e_7IwApYF5yqLnAqs2fc1PahYB2yutHAQKb5x0Mlm-SVpY_V1nTdPLTk-mQZONdJ_ccuC1BH4_Y239wixvVUdCu1IqwDa1vvaBy9u7eyAhwCl6y4jh77aqZzhcY5vnlQWsI_AiTu9RwhfiSlg-UwuRzNHY53VJ_o7QV_0lXy1J2Qog5YGJwSdnew_5YzGZR-Pdl8grc6w0K_dajyQDtdm4cyyZFuQ4ecsKTTsBNF-3m00
````
@startuml
package OGC [
{{
class GeoXACML_Spatial_Analysis {
    # Boolean allowTransformation=false

    Spatial Analysis Functions ()
}

interface GeoXACML_API {
    OGC OpenAPI
    OGC Landing Page
    OGC Conformance Class Page
}

interface GeoXACML_CRS_Transformation {
    # XACML AttributeValue attribute 'allowTransformation'
    # Boolean allowTransformation={false, true}
}

class GeoXACML_Core {
    # XACML DataType Geometry
    # XACML AttributeValue attribute 'srid'
    # XACML AttributeValue attribute 'precision'
    # Boolean allowTransformation=false

    Geometry encoding based on WKT and WKB
    Processing may result in 'geometry-error'

    CRS default 'urn:ogc:def:crs:OGC::CRS84'
    Processing different CRS result in 'crs-error'

    Processing may result in 'precision-error'

    Geometry Functions ()
    Spatial Relations Functions ()
    XACML Bag / Set Functions ()
}

}}
]

package ISO [
{{
abstract class SimpleFeatures {
    ISO 19125:2004
    # Geometry
    # WKT
    # WKB
    Functions ()
}
    ISO.SimpleFeatures -o OGC.GeoXACML_Core : use

}}
]


 

package OASIS [
{{
abstract class XACML3 {
    OASIS XACML 3.0
    Policy schema
    AD and ADR schema
    Functions ()
}

}}
]


    OGC.GeoXACML_Core ..d.|> OGC.GeoXACML_API: <<optional>>
    OGC.GeoXACML_Core ..d.|> OGC.GeoXACML_CRS_Transformation: <<optional>>
    OGC.GeoXACML_Spatial_Analysis -r-|> OGC.GeoXACML_Core: <<optional>>
    OASIS.XACML3 <|-d- OGC.GeoXACML_Core: <<extends>>




@enduml
````

--- the classes and packages are drawn, but the arrows are not.


And then to the current PlantUML solution, which is to conflate namespaces and packages completely. PlantUML command-line will simply not deal with both packages and class definitions; and by getting rid of packages completely and replacing them with namespaces, you are no longer forcing it to.

So the following *does* work:

//www.plantuml.com/plantuml/png/bLHRRzem57xdLnof3spIoEXbqXOnr92g5Led447Rtj31EM6M73ko7Mq8-j_dM34R3LCf3oJ-pkNxpYM-DHQrhKlHwu7xpHxIw87KZoJz-hXAbIQ8eZpQZuyDoNmQmsYaAikLH34Ulo8sNMIhfKPf2gLBR1Ayb2ghd1kALUBiMyCD3FHWF-xIFSlZ4qspMPJniX9qJsXhJIvQdL0QGsseRK6IJRF8swvXj1_aWzDKzDkIp4t3rCEriHgP1IRGc5Eiko07BZzTNds8huR36mzTWCjSajNRzlZzo_BmDl5lzxLaJLa6thpjFNNOZWJl_jO07eBhQEYnkHASRS6mdrIYHv8xG9cxnoAWfzWyIRS5BTD5otA75fVRYewh2TR4MitNjQLlA6e234Ve6ytp_fc-bIR6ZPCM0YPA2K89A8JwTRnKdmiKOQ914f1aAkTo0siqb8EIJRDz3qAhvrenCgRnAN4BRdAriC0bz3TjaW5fhRHN0FxFBJJaL63ZsA-rZDM6nGw8cJQnQriSEu-FD_td-NDU5AH9Md3sVvbSN8Va_xeEJUd4XBAF9kejxHS52nBe3LqNFmkOu0RUGqRsdAteVAUxruqfg0hn7KukBUa26Rrqey3kp8tgAZfhjtPUzJkmkgQdqyh2FTbASJ3CAf8EEPmVKVfbdEE63c2gfEUHZ23rFVPcnz6x9PdNfVW3

````
@startuml
OGC.GeoXACML_Core ..d.|> OGC.GeoXACML_API: <<optional>>
    OGC.GeoXACML_Core ..d.|> OGC.GeoXACML_CRS_Transformation: <<optional>>
    OGC.GeoXACML_Spatial_Analysis -r-|> OGC.GeoXACML_Core: <<optional>>

    ISO.SimpleFeatures -o OGC.GeoXACML_Core : use

    OASIS.XACML3 <|-d- OGC.GeoXACML_Core: <<extends>>


abstract class ISO.SimpleFeatures {
    ISO 19125:2004
    # Geometry
    # WKT
    # WKB
    Functions ()
}

abstract class OASIS.XACML3 {
    OASIS XACML 3.0
    Policy schema
    AD and ADR schema
    Functions ()
}

class OGC.GeoXACML_Core {
    # XACML DataType Geometry
    # XACML AttributeValue attribute 'srid'
    # XACML AttributeValue attribute 'precision'
    # Boolean allowTransformation=false

    Geometry encoding based on WKT and WKB
    Processing may result in 'geometry-error'
    
    CRS default 'urn:ogc:def:crs:OGC::CRS84'
    Processing different CRS result in 'crs-error'
    
    Processing may result in 'precision-error'
    
    Geometry Functions ()
    Spatial Relations Functions ()
    XACML Bag / Set Functions ()
}

class OGC.GeoXACML_Spatial_Analysis {
    # Boolean allowTransformation=false

    Spatial Analysis Functions ()
}

interface OGC.GeoXACML_CRS_Transformation {
    # XACML AttributeValue attribute 'allowTransformation'
    # Boolean allowTransformation={false, true}
}

interface OGC.GeoXACML_API {
    OGC OpenAPI
    OGC Landing Page
    OGC Conformance Class Page
}
@enduml
````

**Comment by opoudjis** [comment]
I am reasonably confident that the Visual Studio rendering of PlantUML that you are appealing to has never worked with command-line PlantUML, and therefore with Metanorma. Metanorma uses the command-line implementation alone; please refer to that in future.

**Comment by securedimensions** [comment]
Thanks a lot!
