### ISSUE TITLE
Normative references showing ISO documents with double org name

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#55]
A picture is worth more than 10 words, in this case.

<img width="1115" alt="image" src="https://user-images.githubusercontent.com/11865/68993593-d346f600-08b4-11ea-8879-94c1f916c674.png">

```adoc
[bibliography]
== References

* [[[ISO5127,ISO 5127]]], _Information and documentation — Foundation and vocabulary_

* [[[ISO15924,ISO 15924]]], _Information and documentation – Codes for the representation of names of scripts_
```

**Comment by opoudjis** [comment]
https://github.com/metanorma/metanorma-ogc/issues/46

> OGC has historically used a derivative of the LNCS referencing style for the normative references. See example usage below.

> ISO: ISO 19101-1:2014, Geographic information — Reference model — Part 1: Fundamentals, International Organization for Standardization, 2005

> OGC: OGC 07-036r1, OpenGIS® Geography Markup Language (GML) Encoding Standard, Open Geospatial Consortium, 2016

**Comment by ronaldtse** [comment]
ARGGGHGHHHHHGHGHGH
