### ISSUE TITLE
Ability to change copyright statement

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-ogc#550]
Some _Community Standards_ and _Community Practices_ require that the originating organisations retain copyright. 

There's a need for a document metadata property that overwrites the default copyright statement of **Copyright © 2023 Open Geospatial Consortium**.

This capability would only apply to Community Standards and Community Practices.

**Comment by opoudjis** [comment]
I had hard-coded the OGC as the copyright holder in the copyright statement.

Henceforth, please specify the originating organisations through:

`:copyright-holder: Organization 1;Organization 2`

(The organisations are given with full name, and are semicolon-delimited; these may include OGC itself.)

If none are given, the default remains "Open Geospatial Consortium".
