### ISSUE TITLE
Extraneous "CONTENTS" section in our Engineering Reports PDF only

### ISSUE THREAD

**Issue by gbuehler** [metanorma/metanorma-ogc#553]
I have been getting the Repos ready for Testbed-19 Engineering Reports according to our new outline (See: https://github.com/metanorma/metanorma-ogc/issues/527)

In the PDF output, I am getting an extraneous blank "CONTENTS" section:
![Screenshot 2023-05-18 at 12 16 34 PM](https://github.com/metanorma/metanorma-ogc/assets/221625/b45c7b22-55f0-4399-b28b-2e0e1a70a00c)

It is also in the TOC:
![Screenshot 2023-05-18 at 12 16 25 PM](https://github.com/metanorma/metanorma-ogc/assets/221625/62ca2415-9c33-4f7f-a862-804902797041)

But it is not in the HTML output:
![Screenshot 2023-05-18 at 12 35 34 PM](https://github.com/metanorma/metanorma-ogc/assets/221625/33a77615-8d09-4481-a001-17990eb578b9)

**Comment by ronaldtse** [comment]
@gbuehler thank you for raising this.

@Intelligent2013 @opoudjis can you please investigate? Thanks

**Comment by Intelligent2013** [comment]
@ronaldtse this issue occurs due the ToC clause:
```xml
<preface><clause type="toc" id="_" displayorder="1"><title depth="1">Contents</title></clause>
```
I've updated XSLT on 26 Apr to process it in https://github.com/metanorma/mn-native-pdf/issues/563, but latest metanorma-ogc gem released 25 Apr. So next Monday release will contain updated XSLT.
