### ISSUE TITLE
HTML TOC not hiding properly

### ISSUE THREAD

**Issue by gbuehler** [metanorma/metanorma-ogc#557]
Here is an issue with the HTML output. In the separator bar between the TOC and the contents, there is a little white dot on the page. When you click the button, the content disappears but then it leaves a white area. Clicking it again produces an even bigger white area. There is no way to actually hide the TOC and the associated area. 

See the following slides:

[HTML Query.pdf](https://github.com/metanorma/metanorma-ogc/files/11618212/HTML.Query.pdf)

**Comment by ghobona** [comment]
Appears to be related to https://github.com/metanorma/metanorma-ogc/issues/378

**Comment by opoudjis** [comment]
Indeed it does. I'm afraid I don't have front-end kung fu.

@ronaldtse assigning both #378 and this to you, since #378 has not been actioned; we still need a front end dev.

**Comment by ghobona** [comment]
@opoudjis @s4birli  Please note that @gbuehler and I have found a possible solution that appears to fix the issue. The code is below. 

```javascript
 <script>
  //TOC toggle animation
$('#toggle').on('click', function(){
    if( $('nav').is(':visible') ) {
        $('nav').animate({ 'left': '-353px' }, 'slow', function(){
            $('nav').hide();
        });
        $('body').animate({ 'margin-left': '-333px' }, 'slow');
    }
    else {
        $('nav').show();
        $('nav').animate({ 'left': '0px' }, 'slow');
        $('body').animate({ 'margin-left': '0' }, 'slow');
    }
});
</script>
```

Could you please try it out and if it works, please apply it?

NOTE: The solution adapts the suggestion from https://github.com/metanorma/metanorma-ogc/issues/326#issuecomment-986483460

**Comment by opoudjis** [comment]
Colour me mortified, I never saw the source fix. Fixing.
