### ISSUE TITLE
Text in some table columns is not wrapping around

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-ogc#559]
The text in some table columns is not wrapping around. Ideally text should not 'spill' from one column to another.

The issue was originally reported at https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/issues/428

See the screenshots below. The source files are [here](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/tree/master/standard).

![table1](https://github.com/metanorma/metanorma-ogc/assets/18121038/5344bc7d-6fbe-441c-af28-91ba26976eb8)

![table2](https://github.com/metanorma/metanorma-ogc/assets/18121038/9292c9b9-1724-40cf-9809-ef073590e2da)

**Comment by Intelligent2013** [comment]
Regarding PDF, I can confirm the issue in the `Table 2`:
![image](https://github.com/metanorma/metanorma-ogc/assets/5559926/ce5eb725-ac8f-4ba6-b3c9-ea4cc9d82bf4)

Will fix.

Looks like the issue in the table `A.45` fixed earlier (https://github.com/metanorma/metanorma-ogc/issues/473).

Currently rendering (`metanorma-ogc (2.3.10)`)
![image](https://github.com/metanorma/metanorma-ogc/assets/5559926/de746f85-47b9-4c04-bb0e-2814c33227cd)

**Comment by Intelligent2013** [comment]
It's not auto-layout table algorithm issue. The table has pre-defined columns width:
```adoc
[width="90%",cols="2,2,1,5",options="header"]
```
Presentation XML:
```
<colgroup>
	<col width="20%"/>
	<col width="20%"/>
	<col width="10%"/>
	<col width="50%"/>
</colgroup>
```
Without columns width (with auto-layout algorithm), PDF renders OK:
![image](https://github.com/metanorma/metanorma-ogc/assets/5559926/b5cb805a-1533-4431-a64b-42dbb327f46b)

I have to add a zero-width space before `(` to split string.

**Comment by Intelligent2013** [comment]
PDF issue fixed (will be available in metanorma-ogc soon):
![image](https://github.com/metanorma/metanorma-ogc/assets/5559926/3d9a081e-5ce8-47f3-8df9-256befc17029)

**Comment by Intelligent2013** [comment]
@opoudjis could you take a look at the HTML issue from the initial post?

**Comment by opoudjis** [comment]
I am unhappy with being asked to intervene in the text, to make it flow better in tables, because inevitably someone is going to come along  afterwards, and ask us to undo the change. And when people use Word (or for that matter LaTeX), they just go ahead and add zero width space on their own to the source text.

That said, we have already had to deal with this issue with URIs in the past in tables, and to that end we introduced `:break-up-urls-in-tables:`, which breaks up any string longer than 30 chars inside a table. That functionality currently is restricted to Word and HTML. It will in fact deal with this issue, since the characters it breaks long strings on are `,.?+;/=` . I will add `(`, and I will change the code to interpolate zero width space instead of normal space.

Ideally, I should hijack @Intelligent2013's solution, so this is implemented only once in Presentation XML, and as opt-in; holding off on that for now.

**Comment by opoudjis** [comment]
The breaking up of URLs was explicitly disabled in HTML. I no longer see that as justified.

**Comment by opoudjis** [comment]
Break up is only first 30 chars of string. It should be each 30 chars.

**Comment by opoudjis** [comment]
<img width="1066" alt="Screenshot 2023-06-06 at 22 02 14" src="https://github.com/metanorma/metanorma-ogc/assets/1911039/0bb09f72-3f34-4374-8109-361d745c3e15">

**Comment by opoudjis** [comment]
So @ghobona to get these results in HTML and Doc, insert `:break-up-urls-in-tables:` in the document header; my implementation of this is opt-in, not opt-out.

**Comment by opoudjis** [comment]
Well, almost.

We will break at 10 chars if there is a punct symbol in the word. We will break at 20 chars if there is not: I regard `Descriptio\{zwsp}n` as a bug not a feature.

**Comment by ghobona** [comment]
@opoudjis Ok, understood. The solution works. It will need to be documented at metanorma.org.

**Comment by ghobona** [comment]
Team, thanks for fixing the issue. 

@ronaldtse Please let us know when it is available on docker.

**Comment by opoudjis** [comment]
The outstanding issue is:

PDF and HTML/DOC have implemented this independently: I've done it as opt-in, @Intelligent2013 in PDF as mandatory. Do you have a preference either way? My preference is to have consistent behaviour across both PDF and HTML/DOC.

**Comment by opoudjis** [comment]
@ghobona Afraid we've just done a release, so it will be available in 2 weeks time.

**Comment by opoudjis** [comment]
Nervous about the char limits; without punctuation within the word, I might extend to 30 words. Will monitor.

**Comment by Intelligent2013** [comment]
Current for PDF rendering, XSLT adds zero-width spaces:
after
- dot with next non-digit
- dash, equal, underscore, em dash, thin space, arrow right, `;`
- colon, if there aren't digits after
- `>`, not followed by '>'
- `,`, if not followed by digit
- `/`, if not followed by `/`

before:
- `<`, if not preceded by `<`
- `{`, if not preceded by 'punctuation char'
- `(` if preceding and following are word chars (currently, for OGC documents only)

between:
-  lower and upper chars in the words like `adeOfAbstractTransportaonSpace` (currently, for OGC documents only)

Of course, it would be better to use one common approach for PDF/DOC/HTML, i.e. add zero-width-space in the presentation XML.
But I don't like the parameter name `:break-up-urls-in-tables:`. `urls` means the text interspersed by `/`?
What about text like `text=text=text=text=text=text=text=text=text=text=text=text=text=text`, or `text;text;text;text;text;text;text;text;text;text;text;text;`? Will it also processed? (Actually, I don't test how the long text interspersed by `=`, `;` and other characters renders in HTML and DOC).

In any case, if presentation XML will contain zero-width-space and PDF XSLT will add the additional zero-width-space, I think it will not have a negative impact.

**Comment by opoudjis** [comment]
The parameter name is legacy; the behaviour I have implemented is:

````
LONGSTR_THRESHOLD = 10
      LONGSTR_NOPUNCT = 2

      def break_up_long_str(text)
        /^\s*$/.match?(text) and return text
        text.split(/(?=\s)/).map do |w|
          if /^\s*$/.match(text) || (w.size < LONGSTR_THRESHOLD) then w
          else
            w.scan(/.{,#{LONGSTR_THRESHOLD}}/o).map.with_index do |w1, i|
              w1.size < LONGSTR_THRESHOLD ? w1 : break_up_long_str1(w1, i + 1)
            end.join
          end
        end.join
      end

      # break on punct every LONGSTRING_THRESHOLD chars
      # break regardless every LONGSTRING_THRESHOLD * LONGSTR_NOPUNCT
      def break_up_long_str1(text, iteration)
        s = text.split(%r{(?<=[,.?+;/=(\[])})
        if s.size == 1
          (iteration % LONGSTR_NOPUNCT).zero? and
            text += "\u200b"
          text
        else
          s[-1] = "\u200b#{s[-1]}"
          s.join
        end
      end
````

So, forced break if 20 chars long. If 10-20 chars long, break at: ,.?+;/=([])

Your condition is more refined. How about I implement it in Presentation XML, applicable to both our code, and overriding your conditions with mine? So:

* We agree on: =
* You also break on: _, em-dash, dash (which breaks anyway in HTML and DOC), thin space, arrow right
* I break on dot comma, you break only if followed by non-dgit
* You break on colon with no digits after
* You break on > not followed by >
* I break on /, you break only if not followed by /
* I break on ? + ; ( [ ] ) . I will continue to break on ? + ;  . I will stop breaking on ) } ] , and will follow your rules for [ { ( <
* You break before <, if not preceded by <
* You break before {, if not preceded by 'punctuation char'
* You break before ( if preceding and following are word chars (currently, for OGC documents only) . I will do so for ( { [
* You break between lower and upper chars in the words like adeOfAbstractTransportaonSpace (currently, for OGC documents only)

Are you comfortable with me generalising this to all documents?

**Comment by Intelligent2013** [comment]
@opoudjis agree, let's do so.

**Comment by Intelligent2013** [comment]
One comment about:

> I break on /, you break only if not followed by /

My code prevents break between `//`. For example, `https://www.google.com`, it allows to split on:
```
https://
www.google.com
```

but not:

```
https:/
/www.google.com
```

**Comment by Intelligent2013** [comment]
@opoudjis how can I generate the presentation XML with added zero-width space?

```
git clone https://github.com/opengeospatial/ogcapi-environmental-data-retrieval
cd ogcapi-environmental-data-retrieval/standard
```
update Gemfile:
```
source "https://rubygems.org"

gem "metanorma-cli"
gem "relaton-cli"
gem "isodoc", git: "https://github.com/metanorma/isodoc", branch: "main"
gem "metanorma-ogc", git: "https://github.com/metanorma/metanorma-ogc", branch: "main"
```
```
bundle exec metanorma -t ogc -x presentation document.adoc 
```

The resulted presentation XML doesn't contain the zero-width space characters.

Then, I've added `:break-up-urls-in-tables:` into `document.adoc`, and again there aren't spaces.

What did I do wrong?

**Comment by opoudjis** [comment]
Don't know! Reopening

**Comment by opoudjis** [comment]
It's not fetching the latest version from github. I do not know why, but I'm pressing ahead...

**Comment by opoudjis** [comment]
Found bug. Fixin
