### ISSUE TITLE
Elimination of post-editing Word: Requirement representation

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#56]
These very helpful issues have been raised by @rggibb . Thanks!

NOTE: We may want to split this issue.

## Requirement Specification

Requirement 1 in Sec 5.2.1 on p13 of ISO 19170 `.docx`:

Source:
```adoc
[[require-1]]
[.requirement,label=" "]
====
[.specification]
--
AA::
URI:: http://www.opengis.net/spec/DGGS/1.0/req/core/data_model
SPEC:: _A DGGS specification SHALL include DGGS Core Operations and a DGGS Earth Reference System based on Core Reference System._
--
====
```

Produces this:

<img width="768" alt="Screen Shot 2019-11-26 at 12 10 45 PM" src="https://user-images.githubusercontent.com/11865/69598914-0a9c6c00-1046-11ea-86c5-5dd07a143bbb.png">

Changes needed:
1. Requirement 1 is styled as `admonitiontitle`, so I can insert both a List of Figures and a List of Requirements after the Contents at the start of the document,
1. Set up a table style with header row in mid grey and remaining rows alternating no fill and light grey,
1. I can then move ‘Requirement 1:’ into the AA row of the table, delete the first column (containing AA, URI & SPEC), apply the table style from 2,
1. Repeat 3 for each Requirement.

## Requirement Verification

cf A.1: Core-Data Model in Annex A, on p33 of ISO 19170 `.docx`

Source:
```adoc
[[test-1]]
[.requirement,label="Core -- Data Model"]
====
 
[.verification]
--
AA::
URI:: http://www.opengis.net/spec/DGGS/1.0/conf/core/data_model
Title:: Core -- Data Model
Abbreviation:: core/data_model
Type:: Basic
Requirement:: Requirement {counter:req1}:
http://www.opengis.net/spec/DGGS/1.0/req/core/data_model
Reference Clause:: <<req-1>>
Test Purpose:: To verify the DGGS Specification conforms to the Core Data Model
Test Method:: Inspect documentation of the DGGS specification.
--
====
```

Produces this:
<img width="714" alt="Screen Shot 2019-11-26 at 12 22 42 PM" src="https://user-images.githubusercontent.com/11865/69599361-b6928700-1047-11ea-99b2-671d09dcc9ba.png">

Changes needed:
1. Restyle ‘Requirement A.1: Core – Data Model’ from admonitiontitle to h3annex
1. Set up a table style with header row in mid grey and remaining rows no fill
1. Delete the word ‘Requirement’ and the line-break after the colon, move ‘A.1: Core – Data Model’ into the AA row of the table, delete the AA and merge the two cells in the header row into one cell, apply the style in 2) to the table
1. Repeat 3) for each conformance test
1. Edit the table of contents to include header 3 level entries, and update the TOC, so the conformance tests are listed in the TOC, and update the Table of Requirements so it only contains Requirements.

## Other opportunities

1. You will have noticed that the Abbreviation in this case  <core/data_model> occurs in 4x places, which seems a tad overkill I know, but that aside, these are:
  1. Appended to <http://www.opengis.net/spec/DGGS/1.0/req/> in the Requirement’s URI entry
  1. Appended to <http://www.opengis.net/spec/DGGS/1.0/conf/> in the Conformance test’s URI entry
  1. As the Abbreviation in the Conformance test entry
  1. As the name of the associated Requirement in the Conformance test entry
.. and of course all of these have the same URI base of <http://www.opengis.net/spec/DGGS/> plus <1.0/> which is also crying out for automation.
1. The Conformance label ‘Core – Data Model’ occurs in 2x places in the Heading for the Conformance test and as the Conformance Test’s Title entry.
1. The Reference clause, might be able to be inferred from where the include statement is in the text, but I’m not too fussed at having to place a named reference at the appropriate clause.

NOTE: In the header the asciidoc ‘--’ converts to an n-dash, but it converts to an m-dash elsewhere. I’ve not bothered to change this, and I’m not particularly fussy about it, but it seems a tad odd.

**Comment by ronaldtse** [comment]
1. What does “AA” Mean in the Requirement and Test?
> AA has no meaning. AA:: is merely a construct (for later deletion) to create a blank header row for each Requirement and Test. I found that it wasn’t possible to embed the header text into a table row and still have the Requirement / Test number increment properly. So using asciidoc to create the header text outside the table with the auto-numbering and using the AA:: construct to create a blank header in the table seemed to me the optimum use of the available asciidoc tools that minimised the post processing. Note that I wasn’t using a standard asciidoc table construct either .. because it generated an unwanted auto-numbered Table n that I didn’t need. The :: construct limited me to a two column table, rather than me being able to have a table that had only one column (for Requirement) or dominantly one column but with the header as a single column (for the Test), but that still seemed the route of least post editing.

**Comment by ronaldtse** [comment]
2. Grey shading

This is the desired styling:
![WG9_N53_req-and-test-style_no-table-borders](https://user-images.githubusercontent.com/11865/71609891-6753ef00-2bcf-11ea-81e9-46c1fa8da62a.png)

**Comment by ronaldtse** [comment]
3. Need a "List of Requirements", no need for a "List of Tests".

> The "Requirement Tests" are in the TOC if they have an h3annex style. I’m also thinking that the Test’s header text should have the word Test in it, so in the N59 example where the header is currently ‘A.1: Core – Data Model’, it would be better as ‘Test A.1: Core – Data Model’, this would remove the current confusion between A.1 as a h1annex style vs the Test A.1 h3annex header used for the Tests. Notice that there are two conformance classes under A.1 Conformance class: Core and A.2 Conformance class: Equal Area Earth Reference system, but the Tests are continuously numbered from A.1 to A.23 irrespective of which conformance class they are in. ie there is a 1-1 relationship between a Requirement and a Test

**Comment by ronaldtse** [comment]
Resolutions as discussed on the call today with @opoudjis.

## The OGC Requirement Model

In general, we consider this data model as the "OGC Requirement Model". Since different organizations/standards may use different data models to represent requirements, this specifically is the version to be used for OGC (which can be used in OGC and ISO standards, for example).

Perhaps the requirement block will become:

Conformance class:
```adoc
[.requirement,model="ogc",type="class"]
====
...
```

Conformance item:
```adoc
[.requirement,model="ogc",type="item"]
====
...
```

-----

## For Requirement Specification

> 1. Requirement 1 is styled as admonitiontitle, so I can insert both a List of Figures and a List of Requirements after the Contents at the start of the document,

We will implement a List of Requirements, this should solve the said issues.

> 2. Set up a table style with header row in mid grey and remaining rows alternating no fill and light grey,

We will implement the new (grey) styling for Requirements.

> 3. I can then move ‘Requirement 1:’ into the AA row of the table, delete the first column (containing AA, URI & SPEC), apply the table style from 2,

The definition that contains "AA", "URI" and "SPEC" should be re-encoded in the ADoc file.

* "AA" is a placeholder and can be removed as mentioned by @rggibb in https://github.com/metanorma/metanorma-ogc/issues/56#issuecomment-569858995
* "URI" seems to be the "label". It should be placed as `[.requirement,label="XXX"]` or `[.specification,label="XXX"]`.
* "SPEC" should be implemented as text under the `[.specification]` block.

> 4. Repeat 3 for each Requirement.

As above.

------

## For Requirement Verification

> 1. Restyle ‘Requirement A.1: Core – Data Model’ from admonitiontitle to h3annex

The intention of this was to exclude Test(s) from the "List of Requirements" but include them in the normal TOC. This will be resolved by implementing the "List of Requirements".

Just like "Figure X" and "Table X" seen in ISO documents, we will consider "Requirement" and "Test" as special objects that will be individually numbered.

> 2. Set up a table style with header row in mid grey and remaining rows no fill

Yes we will implement this as the styling desired for Requirements.

> 3. Delete the word ‘Requirement’ and the line-break after the colon, move ‘A.1: Core – Data Model’ into the AA row of the table, delete the AA and merge the two cells in the header row into one cell, apply the style in 2) to the table

The intention of this operation is to display the "label" and "numbering" to a table row. We consider this as a styling change that will be resolved as mentioned above.

> 4. Repeat 3) for each conformance test

As above.

> 5. Edit the table of contents to include header 3 level entries, and update the TOC, so the conformance tests are listed in the TOC, and update the Table of Requirements so it only contains Requirements.

Will be fixed by the "List/Table of Requirements".

-----

## Other opportunities

> 1. You will have noticed that the Abbreviation in this case <core/data_model> occurs in 4x places, which seems a tad overkill I know, but that aside, these are:
>     1. Appended to http://www.opengis.net/spec/DGGS/1.0/req/ in the Requirement’s URI entry
>     2. Appended to http://www.opengis.net/spec/DGGS/1.0/conf/ in the Conformance test’s URI entry
>     3. As the Abbreviation in the Conformance test entry
>     4. As the name of the associated Requirement in the Conformance test entry
>     5. .. and of course all of these have the same URI base of http://www.opengis.net/spec/DGGS/ plus <1.0/> which is also crying out for automation.

We could provide an attribute called "Base URI" in the OGC Requirement Model, but it is unclear when the Base URI should be added to the specification and what should happen if people include the Base URI manually.

The easiest way to handle this may just using AsciiDoc attributes?


> 2. The Conformance label ‘Core – Data Model’ occurs in 2x places in the Heading for the Conformance test and as the Conformance Test’s Title entry.

This is because this line should not exist inside the `[.requirement]` block:
`Title:: Core -- Data Model`

The requirement label should only exist at the `[.requirement]` block level as:
`[.requirement,label="Core -- Data Model"]`


> 3. The Reference clause, might be able to be inferred from where the include statement is in the text, but I’m not too fussed at having to place a named reference at the appropriate clause.

A Requirement will now be a first-class numbered document element, so instead of:

```adoc
Requirement:: Requirement {counter:req1}: http://www.opengis.net/spec/DGGS/1.0/req/core/data_model
Reference Clause:: <<req-1>>
```

We can just do this:
```adoc
Requirement:: <<require-1>> (In this document: <<req-1>>)
```

(`require-1` is the anchor for the Requirement, `req-1` is the clause that contains the Requirement)


> 4. NOTE: In the header the asciidoc ‘--’ converts to an n-dash, but it converts to an m-dash elsewhere. I’ve not bothered to change this, and I’m not particularly fussy about it, but it seems a tad odd.

This will be fixed.

**Comment by opoudjis** [comment]
Restoring RecommendationTitle style to all captions of recommendations, requirements, permissions throughout Metanorma.

**Comment by opoudjis** [comment]
I have implemented alternating shading for recommendation tables; shading alternates recommendation components by default (so if a specification and a measurement are in the same recommendation, they will appear as two distinct rows). Exceptionally, if a recommendation component consists exclusively of a definition list, its entries will be presented as alternating rows in the table. 

The table header row consists of the requirement number + title (if provided); the first body row is the table label (if provided), and the second is the collection of other requirement metadata (if provided), as a definition list in alternating rows.

So the following is the expected markup for the verification above, and how it now renders in Word:

````
[[test-1]]
.Core -- Data Model
[.requirement,label="http://www.opengis.net/spec/DGGS/1.0/conf/core/data_model"]
====
 
[.verification]
--
Abbreviation:: core/data_model
Type:: Basic
Requirement:: <<require-1>>: http://www.opengis.net/spec/DGGS/1.0/req/core/data_model
Reference Clause:: <<req-1>>
Test Purpose:: To verify the DGGS Specification conforms to the Core Data Model
Test Method:: Inspect documentation of the DGGS specification.
--
====
````

<img width="411" alt="Στιγμιότυπο 2020-01-02, 22 48 50" src="https://user-images.githubusercontent.com/1911039/71665759-28ca5a00-2db2-11ea-835c-7cd73020d91c.png">


I have not yet implemented distinct shading for tests, or excluding them from the table of contents; that will be done by typing this recommendation block as "test" in #189, and rendering such tables differently.

**Comment by opoudjis** [comment]
To elaborate (now that https://github.com/metanorma/metanorma-standoc/issues/189 is implemented):

If a requirement is given type "verification", as part of the block metadata:

````
[.requirement,type=verification]
````

it will be rendered differently:

1. It will have a table with a distinct caption style, so it will not be included in the table of requirements
1. It will have Middle shaded title header and no alternating row shading, instead of Dark shaded title header and alternating medium and light row shading
1. It will be labelled and crossreferenced as "Requirement/Permission/Recommendation Test A.1", rather than as "Requirement/Permission/Recommendation A.1".

In all other regards, it will be rendered the same as other requirements.

**Comment by opoudjis** [comment]
Final issue is in https://github.com/metanorma/metanorma-standoc/issues/191

**Comment by ronaldtse** [comment]
@opoudjis quick clarification:

These input lines:
```adoc
Requirement:: <<require-1>>: http://www.opengis.net/spec/DGGS/1.0/req/core/data_model
Reference Clause:: <<req-1>>
```

Will be rendered as:
```
Requirement | Requirement 1: http://www.opengis.net/spec/DGGS/1.0/req/core/data_model
Reference Clause: 5.3
```

Correct?

**Comment by opoudjis** [comment]
Correct.
