### ISSUE TITLE
Engineering Reports: remove the automated placement of the "Terms" clause

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-ogc#567]
metanorma appears to still be enforcing the placement of the "Terms, Definitions and Abbreviated Terms" clause.

Please see the attached screenshot. The document was generated using the following version.

```
Metanorma 1.5.10
```

As a follow on to Issue https://github.com/metanorma/metanorma-ogc/issues/527 , **for engineering reports only**, please remove the automated placement of the  "Terms, Definitions and Abbreviated Terms" clause.

That is, the clause should appear where the editor has placed it. For example, on the attached screenshot the editor placed it after the Introduction clause.

![Screenshot 2023-06-26 at 12 52 13](https://github.com/metanorma/metanorma-ogc/assets/18121038/0dd711b0-7630-425e-96de-3dfcf34e157a)

**Comment by opoudjis** [comment]
This is going to need HTML and DOC respecting displayorder attribute, which to date is only used by PDF.

**Comment by opoudjis** [comment]
@Intelligent2013 Warning: as part of this refactor, I am going to move Normative References inside of //sections in Presentation XML, since it renders together with the other //sections clauses. Is this going to be a problem for you?

**Comment by opoudjis** [comment]
Need to add middle_title in Presentation XML, the title that is prefixed before sections: it will take the form of one or more paragraphs of classes zzSTDTitle1 and zzSTDTitle2.

**Comment by Intelligent2013** [comment]
@opoudjis the title at the start of the main sections renders in these XSLT:
- CSD
- IEC
- IEEE
- ISO
- ITU
- JCGM
- JIS
- MPFA

**Comment by opoudjis** [comment]
BSI also has a main title in my book, but we will sort that out eventually...
