### ISSUE TITLE
Supporting new OGC document stages (TBD)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#57]
We made a proposal to OGC on adopting these document stage codes.

UPDATED.

## Definitive stages

* SWG Draft: `swg-draft`
* OAB Review: `oab-review`
* Public RFC: `public-rfc`
* TC Vote: `tc-vote`
* Published: `published`
* Retired: `retired`
* Deprecated: `deprecated`

These are based on this diagram from the OGC/ISO stage alignment presentation:

<img width="923" alt="Screen Shot 2019-11-23 at 10 27 40 PM" src="https://user-images.githubusercontent.com/11865/70343616-b5a4f500-1892-11ea-992a-9a1fdfea374c.png">

These are currently being considered by the OGC Document Team Subcommittee.

**Comment by ogcscotts** [comment]
I will work through the OGC DocTeam to see if there is a desire to have a formal status indicator on standards documents. Proposal is to have the stage on the cover page.

**Comment by ronaldtse** [comment]
Thanks @ogcscotts ! We will use these stated stages for now (the codes following will be used in OGC XML):

* SWG Draft: `swg-draft`
* OAB Review: `oab-review`
* Public RFC: `public-rfc`
* TC Vote: `tc-vote`
* Published: `published`

**Comment by ronaldtse** [comment]
We will start implement of these on the cover page when @ogcscotts confirms with DocTeam.

**Comment by ronaldtse** [comment]
As per @ogcscott, we need to add "retired" and "deprecated".
