### ISSUE TITLE
Year missing from rendered ISO 19125-1 citation

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-ogc#572]
The year of publication appears to be missing from a rendered [ISO 19125-1](https://www.iso.org/standard/40114.html) citation.

I was expecting:

* ISO: ISO 19125-1:2004, Geographic information — Simple feature access — Part 1: Common architecture. International Organization for Standardization, Geneva https://www.iso.org/standard/40114.html.

but got:

* ISO: ISO 19125-1, Geographic information — Simple feature access — Part 1: Common architecture. International Organization for Standardization, Geneva https://www.iso.org/standard/40114.html.

![Screenshot 2023-07-10 at 16 19 50](https://github.com/metanorma/metanorma-ogc/assets/18121038/99865041-9a34-4ef4-8b36-3a5ae1f8b310)

**Comment by opoudjis** [comment]
ISO, and therefore Relaton, differentiates between ISO 19125-1 and ISO 19125-1:2004. The latter refers specifically to that year's edition of the document. The former refers to all versions of the document collectively, and to the latest by default. If you want to see  ISO 19125-1:2004, please provide  ISO 19125-1:2004 explicitly in the references; Relaton will fetch that specific edition.
