### ISSUE TITLE
Custom license agreements

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-ogc#574]
In some cases custom license agreements might apply to Community Standards, Community Profiles, or Discussion Papers.

Please create an ability to override the contents of the License Agreement section.

**Comment by opoudjis** [comment]
There is currently the facility to completely overwrite the built in boilerplate statement with a separate file. So if you take the file in

https://raw.githubusercontent.com/metanorma/metanorma-ogc/main/lib/metanorma/ogc/boilerplate.adoc

Then save it as boilerplate-custom.adoc

Then change the contents of the `== license-statement` clause to the text you want to see.

Then invoke the file as a document attribute, with 

````
:boilerplate-authority: boilerplate-custom.adoc
````

You will get the result you want.

I *could* introduce functionality to merge the built in boilerplate file and user-supplied clauses in the main document; but in my opinion that would likely lead to more trouble than it is worth.

This is documented in https://www.metanorma.org/builder/topics/metadata-and-boilerplate/ , although that page (a) is not linked in to the rest of the site, and (b) is months out of date, and (b) has not been updated in nine months; the relevant update (which is a bit too hesitant) is on https://github.com/metanorma/metanorma.org/blob/662cc4f139b3c4db7aed77990f1c0784f88d66a4/builder/topics/metadata-and-boilerplate.adoc

The boilerplate document is in Asciidoc, as you can now see, but Metanorma has only been able to process boilerplate in Asciidoc as of start of June; before that, it was Metanorma XML. So user-facing boilerplate editing, really, has only become available then.

You will notice that these documents are Liquid templates, which get document metadata injected into them (encased in `{{ ... }}`); the same page gives some generic documentation of available metadata, but please consult with me if you need more information derived from document metadata.
