### ISSUE TITLE
Refactor of Presentation XML for ordering and for supplying middle title

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-ogc#579]
Follow-on from #567 

Major refactor has been done to bring HTML/DOC in line with PDF, with the ordering of sections being determined by the `displayorder` attribute. However, this has unearthed another few features which have been changed in Presentation XML for greater consistency or explicitness. Notably:

1. The "middle title", so called, is now uniformly appearing at the start of `sections` of Presentation XML, instead of being supplied independently by PDF and HTML/DOC. The main such title is styled as `p[@class] = 'zzSTDTitle1`, and any subtitle is styled as `p[@class] = 'zzSTDTitle2`.

2. Paragraphs, notes, admonitions may also received a displayorder attribute. (This was happening already irregularly.)

3. When Normative References are to be rendered with other main section clauses, they are moved in Presentation XML to the end of `sections`.

4. In ISO, I've introduced `span[@class = 'nonboldtitle']` and `span[@class = 'boldtitle']` to deal with the fact that titles default in bold but contain non-bold text (needed for Word):

````
<p class="zzSTDTitle1" displayorder="2">
<span class="boldtitle">Introduction &#x2014; Main Title&#x2009;&#x2014;&#x2009;Title &#x2014; </span>
<span class="nonboldtitle">Part&#xA0;1:</span> <span class="boldtitle">Title Part</span></p>
````

5. An explicit keywords clauses has been added to ITU preface. If you are printing keywords in an infobox instead of as a clause, ignore the keywords clause; it will be signalled as `clause[@type = 'keyword']`

6. In ITU, title footnotes are no longer marked up as `note[@type = 'title-footnote']`, but as normally numbered `<fn>` elements on the middle title.

7. In JIS, the special header for commentaries is introduced in Presentation XML:

````
         <annex id="C" inline-header="false" obligation="informative" commentary="true" displayorder="13">
           <p class="CommentaryStandardNumber">
             JIS Z 1000-1.3 :
             <span class="CommentaryEffectiveYear">2000</span>
           </p>
           <p class="CommentaryStandardName">Introduction — Main Title — Title — </p>
           <p class="zzSTDTitle1">
             Part :
             <br/>
             <strong>Title Part</strong>
           </p>
           <title>Commentary</title>
             ...
 ````

**Comment by Intelligent2013** [comment]
@opoudjis could you point me the right GH branches in the `Gemfile` for testing purposes?

For https://github.com/opengeospatial/ogcapi-environmental-data-retrieval my `Gemfile` is:
```
source "https://rubygems.org"

gem "metanorma-cli"
gem "relaton-cli"
gem "isodoc", git: "https://github.com/metanorma/isodoc", branch: "main"
gem "metanorma-ogc", git: "https://github.com/metanorma/metanorma-ogc", branch: "features/displayorder"
```

but `Normative references` in the presentation XML still in the `bibliography/references`, not the last item in the `sections`:
```
<bibliography>
    <references id="_references" normative="true" obligation="informative" displayorder="10">
      <title depth="1">3.<tab/>Normative references</title>
```

**Comment by Intelligent2013** [comment]
@opoudjis please ignore my question. Fixed by:
```
gem "isodoc", git: "https://github.com/metanorma/isodoc", branch: "features/displayorder"
```

**Comment by Intelligent2013** [comment]
Currently, ISO XSLT renders titles in such order in the separate blocks:
- intro + main title
- part number
- part title

![image](https://github.com/metanorma/metanorma-ogc/assets/5559926/9ac816b9-d0ae-4033-a3f9-f142599fef9b)

Presentation XML contains the title in one `p`:
```
<sections>
		<p class="zzSTDTitle1" displayorder="4">
			<span class="boldtitle">Cereals and pulses — Specifications and test methods — </span>
			<span class="nonboldtitle">Part 1:</span>
			<span class="boldtitle">Rice (Final)</span>
		</p>
```
To do:
- render `<span class="nonboldtitle">` as block

**Comment by Intelligent2013** [comment]
> 1. The "middle title", so called, is now uniformly appearing at the start of `sections` of Presentation XML, instead of being supplied independently by PDF and HTML/DOC. The main such title is styled as `p[@class] = 'zzSTDTitle1`, and any subtitle is styled as `p[@class] = 'zzSTDTitle2`.

Need update for these XSLT:
- [ ] CSD
- [ ] IEC
- [ ] IEEE
- [x] ISO
- [ ] ITU
- [ ] JCGM
- [ ] JIS
- [ ] MPFA

**Comment by Intelligent2013** [comment]
Done.
