### ISSUE TITLE
Update document types, subtypes and stages (CONFIRMED)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#58]
This is the latest document type list from @ogcscott . A "forward-looking" list, but will be confirmed.

## Document types

* abstract specification topic
* best practice
* change request supporting document
* community practice
* community standard
* discussion paper
* engineering report
* other
* policy
* reference model
* release notes
* standard
* user guide
* white paper

## Document subtypes for standard

* conceptual model
* conceptual model and encoding
* conceptual model and implementation
* encoding
* extension
* implementation
* profile
* profile with extension

## Document subtypes for best practices

* (null) (i.e. no subtype, or just "general")
* encoding
* extension
* profile
* profile with extension

## Current doctype => New or current doctype mapping

* abstract-specification => abstract specification topic
* approved-technical-baseline => Not a document type, remove.
* best-practice => best practice
* candidate-standard => (standard, in draft stage)
* change-request => "Change Request supporting document" (the actual Change Request is a database entry)
* community-practice => community practice
* community-standard => community standard
* conformance-class => Not a stand-alone document, rather a part of a document, remove
* discussion-paper => discussion paper
* draft-discussion-paper => discussion paper in draft
* extension-package-standard => (standard: extension)
* implementation-standard => (standard: implementation)
* implementation-standard-corrigendum => (standard: implementation, with corrigendum)
* interoperability-program-report => (engineering report)
* notes => other
* ogc-reference-model => reference model
* policy => (standard: policy)
* policy-specification => remove
* primer => other
* profile => (standard: profile)
* profile-corrigendum => (standard: profile, with corrigendum)
* public-engineering-report =>  (engineering report)
* recommendation-paper =>  (discussion paper)
* request-for-comment => (standard, in a draft stage)
* retired => a lifecycle stage, remove
* standard-application-profile => (standard: profile)
* test-suite => *PENDING*
* whitepaper => white paper

The document stage values are in another issue: https://github.com/metanorma/metanorma-ogc/issues/57

**Comment by ronaldtse** [comment]
We will need to update the document model at https://github.com/metanorma/metanorma-model-ogc/

**Comment by opoudjis** [comment]
The current document types have not been implemented in essence, so I will overwrite them.

**Comment by ronaldtse** [comment]
Thanks @opoudjis !
