### ISSUE TITLE
Rendering of table footnotes in PDF: all caps

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-ogc#581]
Follow-on from https://github.com/metanorma/metanorma/issues/308, issue 3:

Table footnotes are rendering in all-caps. I am attaching Presentation XML for when this happens.

[a.presentation 3.xml.zip](https://github.com/metanorma/metanorma-ogc/files/12239222/a.presentation.3.xml.zip)

According to user, 

> Occurs if second row cells are introduced with h| instead of just | above (or if footnotes added to item in the first (header) row of the table

(I.e. are explicitly marked up as header rows, or if there are footnotes in the (first) header row.

**Comment by Intelligent2013** [comment]
The table header cell text transforms to all caps via XSLT. `fn` is part of `th`. Now `th//fn` excluded from the all caps transformation.
Fixed:
![image](https://github.com/metanorma/metanorma-ogc/assets/5559926/5473f699-6db4-4727-bdc6-3598afd170d2)
