### ISSUE TITLE
Table formatting issues/questions

### ISSUE THREAD

**Issue by ccrook** [metanorma/metanorma-ogc#584]
Possibly two issues.   I am trying to create a table with two rows of header, and footnotes.

At the moment I have the following code:

```
[[table-time-function-attributes]]
.Time function mandatory (M) and optional (O) attributes
[options="header"]
[valign="top"]
[cols="<,7^]
|=== 
| Function type  7+^h| Attribute

// Second heading line.
| 
^| Reference epoch footnote:tfepoch[Epochs may be specified as a date/time or epoch in decimal years] 
^| Start epoch footnote:tfepoch[] 
^| End epoch footnote:tfepoch[] 
^| Event epoch footnote:tfepoch[] 
^| Time constant footnote:[A time constant is in  years] 
^| Frequency footnote:[A frequency is specified in cycles per year] 
^| Scale factor

// Type             ^| Ref ^| Sta ^| End ^| Evt ^| TmC ^| Frq ^| Scl 
| velocity          ^|  M  ^|  O  ^| O   ^|  -  ^|  -  ^|  -  ^|  O
| acceleration      ^|  M  ^|  O  ^| O   ^|  -  ^|  -  ^|  -  ^|  O
| step              ^|  M  ^|  O  ^| O   ^|  -  ^|  -  ^|  -  ^|  O
| ramp              ^|  -  ^|  M  ^| M   ^|  -  ^|  -  ^|  -  ^|  O
| exponential       ^|  -  ^|  O  ^| O   ^|  M  ^|  M  ^|  -  ^|  O
| logBaseE          ^|  -  ^|  O  ^| O   ^|  M  ^|  M  ^|  -  ^|  O
| logBase10         ^|  -  ^|  O  ^| O   ^|  M  ^|  M  ^|  -  ^|  O
| hyperbolicTangent ^|  -  ^|  O  ^| O   ^|  M  ^|  M  ^|  -  ^|  O
| cyclic            ^|  M  ^|  O  ^| O   ^|  -  ^|  -  ^|  M  ^|  O

|
```

Issue 1:

I haven't figured out a way of making the second heading line part of the heading.   I can change the cell type to <th> in HTML using h| instead of h in the markdown, but this doesn't get reflected in the styling other than that the text is converted to upper case and bold.  The background is not changed, and the second line does not appear in headings on subsequent pages if the table spans a page boundary. 

This may not be addressable in metanorma as it appears to be an asciidoc issue https://github.com/asciidoctor/asciidoctor/issues/1687.

Issue 2:
Related to issue 1, I tried to merge the first two columns of the first row but haven't been able to find a syntax for this.  Everything I have tried creates more or less significant table layout changes.  

Issue 3:
A footnote to a table header is rendered in upper case.  This is very undesirable!  Occurs if second row cells are introduced with h| instead of just | above (or if footnotes added to item in the first (header) row of the table

Issue 4:
_Not really an issue but just raising in case someone can offer a better suggestion._  I tried using the cols= attribute to set the [cols="<,7^] attribute to set the column alignment to centred but it didn't seem to work, possibly a syntax error?

Issue 5:
_Not really an issue._  This would possibly be better posted to a mailing list or other user forum, but I couldn't find a reference to one on the [metanorma.org](https://metanorma.org) or index page of this repository :-(

**Comment by ronaldtse** [comment]
Sorry for the slow action here. Moved to metanorma-ogc now!
