### ISSUE TITLE
From OGC: Change table formatting to a uniform fill colour, and a single colour for the border and grid lines

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#59]
From @ghobona

Ideally a uniform colour for the fill.
..and a single colour for the border and grid lines.

**Comment by opoudjis** [comment]
We implemented this imitating asciidoc native HTML output, which we have seen used by OGC; that is built in to asciidoc native HTML output, and it's straightforward to get rid of.

**Comment by ghobona** [comment]
@ronaldtse Please let me know when metanorma-docker has been updated with this fix.

**Comment by ronaldtse** [comment]
@ghobona the latest metanorma-docker container is up!
