### ISSUE TITLE
Templates and Samples on GHA failing on template, somehow

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-ogc#594]
````
Removing gems from /Users/runner/work/metanorma-ogc/metanorma-ogc/samples/Gemfile
`metanorma-ogc` is not specified in
/Users/runner/work/metanorma-ogc/metanorma-ogc/samples/Gemfile so it could not
be removed.
````

https://github.com/metanorma/metanorma-ogc/actions/runs/6205369738/job/16848666587?pr=593

Given that metanorma-cli is testing everything, having samples and templates tested in flavours as well is now unwelcome. metanorma-cli is already going to be falling over individual flavours all the time; I don't need compilation to be falling over before it hits metanorma-cli on the same issues, and release is painful as is. Samples and templates should only be tested in one place, for efficiency.

**Comment by CAMOBAP** [comment]
Fixed, ci restarted

**Comment by CAMOBAP** [comment]
Fixed
