### ISSUE TITLE
Unexpected text at the top of the HTML cover page

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-ogc#595]
After using the following command to generate a copy of the template...

`docker run --rm -v "$(pwd)":/metanorma metanorma/metanorma  metanorma new -d standard -t ogc  -l https://github.com/metanorma/metanorma-templates-ogc folder_for_standard`

...and then compiling the document with the following command...

`docker run -v "$(pwd)":/metanorma -v ${HOME}/.fontist/fonts/:/config/fonts  metanorma/metanorma  metanorma compile --agree-to-terms -t ogc -x xml,html,doc document.adoc`

I found that the text `ext here>'/>` was at the top of the HTML cover page.

See attached.

<img width="954" alt="Screenshot 2023-10-27 at 23 12 06" src="https://github.com/metanorma/metanorma-ogc/assets/18121038/6b975c54-22e4-43f9-a85a-f770561b5558">

**Comment by opoudjis** [comment]
Replicated.

**Comment by opoudjis** [comment]
We had to sanitise quotes in keywords, because they end up in the HTML meta keyword attribute. We have to sanitise the abstract as well, because it ends up in HTML meta description attribute.
