### ISSUE TITLE
(URGENT, HTML) TOC order in HTML messed up

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#597]
Document: https://github.com/opengeospatial/Temporal-Abstract-Spec/pull/57

<img width="381" alt="Screenshot 2023-10-31 at 6 09 51 PM" src="https://github.com/metanorma/metanorma-ogc/assets/11865/cc89bb74-e765-4333-b4e2-a6db5d8da9f6">

**Comment by opoudjis** [comment]
No, it's my side.

Headings in the ToC in HTML are sorting by line number of the HTML. But the `<h1>` and `<h2>` occasionally appear on the same line with no line break between them. Fixed by introducing h1 vs h2 as secondary sort order.

**Comment by opoudjis** [comment]
![Screenshot 2023-11-12 at 16 54 14](https://github.com/metanorma/metanorma-ogc/assets/1911039/57313b4f-5abd-4b12-b70c-0d7e976f22f1)

**Comment by opoudjis** [comment]
Fix is not general enough: HTML is routinely putting very short clauses on the same line.

**Comment by opoudjis** [comment]
AGAIN it has failed in Github Actions

Clearly using node.line in Nokogiri is not reliable in Windows, even if I pretty-print the XML beforehand: there is no guarantee that tags will print in separate lines. Instead, I am going to store the ordinal locations of all headers in HTML, and sort on those.
