### ISSUE TITLE
(PDF, URGENT) "admitted term" being shown as part of term mistakenly

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#598]
<img width="549" alt="Screenshot 2023-11-01 at 8 17 06 PM" src="https://github.com/metanorma/metanorma-ogc/assets/11865/b8d180ca-d464-41b9-96a5-4c002de48039">

```adoc
==== datum
admitted:[reference frame]

parameter or set of parameters that realize the position of the origin, the scale, and the orientation of a {{coordinate system}}

[.source]
<<iso19111>>
```

Notice the "ADMITTED" stray word (the one next to the designation, not within the label) should not exist.

Document source:
* https://github.com/opengeospatial/Temporal-Abstract-Spec

**Comment by Intelligent2013** [comment]
Done:
![image](https://github.com/metanorma/metanorma-ogc/assets/5559926/eb48cb79-7a97-41a9-822f-8406c581ae05)

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 !
