### ISSUE TITLE
When doctype set to Engineering Report, an error is thrown: `'' is not a permitted subtype of Standard: reverting to 'implementation'`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#599]
When the document is set to:

```adoc
:doctype: engineering-report
```

This error shows. Clearly the document is not a "Standard".
```
Document Attributes: '' is not a permitted subtype of Standard: reverting to 'implementation'
```

**Comment by opoudjis** [comment]
The error is being falsely raised by the boilerplate processor; moreover, an empty subdoctype should not be triggering this warning to begin with.
