### ISSUE TITLE
URL not rendered as HTML link in requirements class table

### ISSUE THREAD

**Issue by alexrobin** [metanorma/metanorma-ogc#613]
I use the following AsciiDoc text:

```
[requirement,model=ogc]
====
[%metadata]
type:: class
identifier:: /req/create-replace-delete/update
subject:: Web API
inherit:: /req/create-replace-delete
inherit:: http://www.opengis.net/spec/ogcapi-features-4/1.0/req/update[^]
====
```

The table is rendered correctly, but the second inherit URL does not get converted to an HTML link.

**Comment by ghobona** [comment]
I tried a number of tricks but none worked. The only thing that worked was to use a reference to an item in the References/Bibliography section.

```
[[rc_create-replace-delete_update]]
[requirements_class]
.Requirements Class 'Update'
====
[%metadata]
identifier:: /req/create-replace-delete/update
subject:: Web API
inherit:: /req/create-replace-delete
inherit:: <<OGCAPI-Features-4,http://www.opengis.net/spec/ogcapi-features-4/1.0/req/update>>
====
```

**Comment by alexrobin** [comment]
@ghobona I don't get a link for the second URI in my case, although the local requirement is resolved correctly in my document (see screenshot). What version of Metanorma are you using?

![image](https://github.com/metanorma/metanorma-ogc/assets/9450210/3243d07f-c69d-498a-8ece-e6367316558d)

**Comment by opoudjis** [comment]
Hyperlinking any URI in a table cell other than requirement identifiers, which are treated separately as they are in  monospace (they are privileged as anchors within a document.)
