### ISSUE TITLE
JSON/YAML source blocks getting merged into a single line in HTML documents

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-ogc#614]
The latest version of metanorma (1.6.7) appears to be creating JSON/YAML source blocks that are merged into a single line. Please see the attached images. The generated document is [here](https://opengeospatial.github.io/ogcna-auto-review/18-062r3.html). 

![Screenshot 2023-12-10 at 10 09 18E](https://github.com/metanorma/metanorma-ogc/assets/18121038/70a00afc-9c44-42d5-a78d-a301fa5cf5db)

![Screenshot 2023-12-10 at 10 08 52E](https://github.com/metanorma/metanorma-ogc/assets/18121038/86a3bfb0-69cb-4a1a-bb13-b7572e5d4961)

The commands to generate it are [here](https://github.com/opengeospatial/ogcna-auto-review/blob/main/.github/workflows/generate_18-062.yml). I have verified that changing line 9 to reference `metanorma/metanorma:1.6.4` instead of `metanorma/metanorma:latest` addresses the issue.

I ran `metanorma --version` in a separate GitHub Action to determine the latest version number, which was reported as 1.6.7.

**Comment by ghobona** [comment]
Thanks to @TaehoonK for spotting the issue.

**Comment by ronaldtse** [comment]
Thank you @ghobona @TaehoonK for reporting this! I believe @opoudjis is already looking into this.

**Comment by opoudjis** [comment]
> Thank you @ghobona @TaehoonK for reporting this! I believe @opoudjis is already looking into this.

And as I am right now in the middle of trying to get out a release, Ronald should not be making any such undertakings on my behalf. The release comes first.

If this is a straightforward fix (30 minutes), it makes it out tonight, otherwise, it doesn't.

Btw, I don't use docker, so pointing me to docker won't help me replicate issues: I need the source repository. Fortunately the source repository was easy to find, and I have already replicated the issue.

**Comment by opoudjis** [comment]
This is an unintended consequence of https://github.com/metanorma/metanorma-standoc/issues/827 . The XML is being preprocessed in XSLT specific to each output format, before being rendered; but that preprocessing is chewing up blank spaces.

**Comment by opoudjis** [comment]
As far as I can tell, the fix has made it now to Docker, version 1.6.8 of Metanorma.

**Comment by ghobona** [comment]
@opoudjis I have just verified that the fix made it to Docker. Thanks for fixing the issue.
