### ISSUE TITLE
pdf-toclevels attribute

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-ogc#615]
To date, we have been able to specify the depth of Table of Content entries with `:htmltoclevels:` and `:doctoclevels:` (now changing to `:toclevels-html:` and `:toclevels-doc:`: https://github.com/metanorma/metanorma-ogc/issues/454.) 

I request that we add a similar variable specific to PDF, `:toclevels-pdf:`. Its value will go to `<presentation-metadata><name>PDF TOC Heading Levels</name><value>...</value></presentation-metadata>`. As before, if its value is not supplied, use the default in `<presentation-metadata><name>TOC Heading Levels</name><value>...</value></presentation-metadata>`

**Comment by opoudjis** [comment]
Nobody has asked for this, so this is not urgent.

**Comment by Intelligent2013** [comment]
Done.
