### ISSUE TITLE
Jumping one section number in OGC template

### ISSUE THREAD

**Issue by alexrobin** [metanorma/metanorma-ogc#618]
With the latest version of Metanorma, the section numbering seems to have changed when using the OGC spec template.

I used to have this (with 1.7.6):

![image](https://github.com/metanorma/metanorma-ogc/assets/9450210/806d159c-477c-4b08-ad8e-d87c0db88fcb)

Now I have this (with 1.8):

![image](https://github.com/metanorma/metanorma-ogc/assets/9450210/e7eb5929-13fc-4b6f-94d4-6cf232b67c43)

Notice the jump from section 4 to 6 (and the `VII. CONTRIBUTORS` section also being removed, although it is marked with `[.preface]`) on the second screenshot.

Any idea what could cause this?
I don't think I have changed the sections myself.

**Comment by opoudjis** [comment]
... Don't know, but I will find out. You've just missed release, so any fix to this in code rather than the template will go out in the next release, scheduled for Jan 8.

**Comment by opoudjis** [comment]
The change in behaviour dates  from some time after July 25. The change is associated with https://github.com/metanorma/metanorma-ogc/issues/527 , and appears to have conflated submitters and contributors incorrectly outside of engineering reports.

**Comment by opoudjis** [comment]
I have put `[.preface]` in front of both Submitters and Contributors in the templates, to ensure proper ordering.
