### ISSUE TITLE
From OGC: Title Page needs version (and other items)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#62]
```adoc
:major-version: 2
:minor-version: 3
:patch-version:
:doc-type: IS
:standard: GWML2
```

Updating:

```
:external-id: http://www.opengis.net/doc/{doc-type}/{standard}/{major-version}.{minor-version}
```

Thinking we could just add:
```
:version: 2.3
```

Thoughts?

**Comment by opoudjis** [comment]
Yes, would rather not break the metanorma model version unless there is compelling reason. Patch version can be tertiary point. Will need to document in metanorma.com.

**Comment by opoudjis** [comment]
The title page until now was using the `bibdata/edition` value, rather than then `bibdata/version/draft` value, and it shall continue to do so. Edition is a more appropriate choice of attribute for what is intended than the draft number of a version. I will add documentation to metanorma.com to explain the three-part numbering of versions.

**Comment by opoudjis** [comment]
The specification in https://github.com/opengeospatial/ogc-metanorma-testing/issues/6 is not clear, but I take it that the template `http://www.opengis.net/doc/{doctype}/{standard-abbrev}/{version}` is intended as a default value for external-id, if none is supplied, and I will realise it accordingly. If no version is supplied, it will not be appended. 

Only Engineering Reports and Discussion Papers do not have version numbers: if that rule is violated, I will issue a warning.

**Comment by opoudjis** [comment]
The "standard abbreviation" shall also be added as a document attribute: `:abbrev:` (also used in IETF).

**Comment by ronaldtse** [comment]
1. Agree to populating external-id be default if version number exists. Do we need a way to allow disabling of external-id?
2. Regarding version numbers not applying  to ER and DP doctypes, we need confirmation. 
3. Yes we should ensure specification of :abbrev: 

Ping @ogcscott @ghobona @gbuehler for questions 1, 2.
