### ISSUE TITLE
Highlight retired status in PDF cover page

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-ogc#622]
In https://github.com/metanorma/metanorma-ogc/issues/444, some additional deprecation statuses have been introduced, along with associated boilerplate. The impacted values are //bibdata/status/stage = deprecated, legacy, retired, rescinded.

I have updated //legal-statement/clause, as a result of which the appropriate boilerplate is making it to the PDF front cover. But there is an expectation from OGC that the retired state also is included in the front page, which is not currently happening:

[Archive 2.zip](https://github.com/metanorma/metanorma-ogc/files/13917797/Archive.2.zip)

This is the mockup from OGC:

[new_document_statuses_v2.pptx](https://github.com/metanorma/metanorma-ogc/files/13917799/new_document_statuses_v2.pptx)

This is the currently generated PDF front page; OGC would want to see the subtitle LEGACY in this particular document instance:

![Screenshot 2024-01-12 at 21 24 26](https://github.com/metanorma/metanorma-ogc/assets/1911039/06eba7db-b838-4abb-a311-cc8e6c8f212c)

**Comment by Intelligent2013** [comment]
Currently, OGC XSLT renders the `stage` already, but it expects the `@language` attribute (with value from `bibdata/language`):
```xml
<xsl:variable name="curr_lang" select="/ogc:ogc-standard/ogc:bibdata/ogc:language[@current = 'true']"/>
<xsl:variable name="stage" select="java:toUpperCase(java:java.lang.String.new(/ogc:ogc-standard/ogc:bibdata/ogc:status/ogc:stage[@language = $curr_lang]))"/>
<xsl:call-template name="addLetterSpacing">
	<xsl:with-param name="text" select="$stage"/>
</xsl:call-template>
```

I'll add the default behavior without `@language`.

**Comment by Intelligent2013** [comment]
Current PDF rendering:
![image](https://github.com/metanorma/metanorma-ogc/assets/5559926/c0b4fa51-9cc9-4025-a156-cb66bf66a67f)

Need update if value is `DEPRECATED`, `LEGACY`, `RETIRED` or `RESCINDED`:
- [ ] add the background box behind the status text, 
- [ ] increase the font size of the status text,
- [ ] change the font color for the notices at bottom page, and margins also

**Comment by Intelligent2013** [comment]
OGC XSLT updated:
![image](https://github.com/metanorma/metanorma-ogc/assets/5559926/04d393a8-a65b-4a0b-bb75-cce5b4a1c38c)
