### ISSUE TITLE
IDENTIFIER field name cropped on PDF

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-ogc#628]
Requirement 1 table on pdf page 40 has a cropped column (see IDENTIFIE which should be IDENTIFIER.

Several other Requirements have the same problem.

https://opengeospatial.github.io/ogcna-auto-review/22-003.pdf

![Screenshot 2024-02-05 at 12 08 08](https://github.com/metanorma/metanorma-ogc/assets/18121038/4a0cad01-6586-4135-bf84-3659fa76d9b7)

**Comment by ronaldtse** [comment]
Seems like a PDF column issue. @Intelligent2013 for you please… thanks.

**Comment by Intelligent2013** [comment]
I can't repeat this issue.

![image](https://github.com/metanorma/metanorma-ogc/assets/5559926/15e897e5-b1f1-4e8a-9ce1-a363561d0c1c)

How I've generated PDF:
```
git clone https://github.com/opengeospatial/ogcapi-movingfeatures
cd ogcapi-movingfeatures/standard
bundle exec metanorma -t ogc -x pdf document.adoc 
```



@ronaldtse the PDF from the initial post https://opengeospatial.github.io/ogcna-auto-review/22-003.pdf generated by `mn2pdf` version 1.50 (Sep 3, 2022)
![image](https://github.com/metanorma/metanorma-ogc/assets/5559926/33df47e1-eb1a-4506-8241-ea14226c0d5b)

The latest version is 1.82 (https://github.com/metanorma/mn2pdf/releases/tag/v1.82).  May be metanorma container contains old metanorma-ogc gem also?

**Comment by opoudjis** [comment]
Doc was autogenerated in docker 16 hrs ago, and docker does request metanorma-latest.

**Comment by ghobona** [comment]
Source document is at https://github.com/opengeospatial/ogcapi-movingfeatures/tree/master/standard

**Comment by opoudjis** [comment]
@CAMOBAP Help, we're not sure whether OGC's docker instance is using latest version of metanorma-ogc

**Comment by ghobona** [comment]
Discussed 2024-02-15

**Comment by CAMOBAP** [comment]
> @CAMOBAP Help, we're not sure whether OGC's docker instance is using latest version of metanorma-ogc

Per 1.9.1 docker release, there was used `metanorma-ogc@2.5.1`

Relevant log statement
- https://github.com/metanorma/metanorma-docker/actions/runs/7793125105/job/21252357687#step:8:3061
- https://github.com/metanorma/metanorma-docker/actions/runs/7793125105/job/21252357872#step:8:5853
- https://github.com/metanorma/metanorma-docker/actions/runs/7793125105/job/21252358033#step:8:1082

Also, this can be proven with `docker run metanorma/metanorma:1.9.1 metanorma --version`

if it was generated with `metanorma/metanorma:latest` locally there is high chance that some old image was used

Please check actual version with `docker run metanorma/metanorma:latest metanorma --version` command

**Comment by opoudjis** [comment]
@ghobona @gbuehler This is outside my domain, but do you have someone on your side who can check your docker instance?

**Comment by ronaldtse** [comment]
Just a note that Docker does cache the image, and if the tag is identical it is likely it is using a cached image. You’ll have to manually do a “docker pull” to fetch the updated image with the same “latest” tag.

**Comment by ghobona** [comment]
@opoudjis @ronaldtse The complete workflow is done from within a GitHub Action. To check which version of metanorma GitHub Actions use as the latest, I ran a `metanorma --version` command and got this output:

```
Metanorma 1.7.0
Metanorma::Cli 1.9.1
Metanorma::Standoc 2.8.1/IsoDoc 2.8.0
Metanorma::ISO 2.7.1
Metanorma::Iec 2.4.1
Metanorma::IEEE 1.2.1
Metanorma::Ietf 3.3.1
Metanorma::Generic 2.[6](https://github.com/ghobona/miscellaneous/actions/runs/7941630655/job/21684184879#step:5:7).0
Metanorma::BIPM 2.4.0
Metanorma::CC 2.4.1
Metanorma::Csa 2.4.1
Metanorma::IHO 0.[9](https://github.com/ghobona/miscellaneous/actions/runs/7941630655/job/21684184879#step:5:10).1
Metanorma::JIS 0.2.1
Metanorma::UN 0.[12](https://github.com/ghobona/miscellaneous/actions/runs/7941630655/job/21684184879#step:5:13).1
Metanorma::Ogc 2.5.1
Metanorma::ITU 2.4.1
```

**Comment by CAMOBAP** [comment]
@ghobona maybe you can share your Github Actions workflow yml?

**Comment by ghobona** [comment]
They are at https://github.com/opengeospatial/ogcna-auto-review/tree/main/.github/workflows

The one for document 22-003 is at https://github.com/opengeospatial/ogcna-auto-review/blob/main/.github/workflows/generate_22-003.yml

**Comment by ghobona** [comment]
A basic one is at https://github.com/opengeospatial/ogcna-auto-review/blob/main/.github/workflows/generate_21-009.yml

**Comment by CAMOBAP** [comment]
Those workflows looks good, maybe you can point me to run-workflow that generated this log https://github.com/metanorma/metanorma-ogc/issues/628#issuecomment-1950053922

**Comment by ghobona** [comment]
@CAMOBAP Here is one https://github.com/opengeospatial/ogcna-auto-review/blob/main/.github/workflows/check_metanorma_version.yml

Please see the output of the 'Check metanorma version' step at https://github.com/opengeospatial/ogcna-auto-review/actions/runs/7943849039/job/21688684081

**Comment by ghobona** [comment]
Fix confirmed.
