### ISSUE TITLE
Columns of requirements class table are too narrow on the PDF

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-ogc#629]
Requirements Class 2 on pdf page 52. Table is not filling the width of the page.

The result is that the columns become too narrow.

https://opengeospatial.github.io/ogcna-auto-review/22-003.pdf

![Screenshot 2024-02-05 at 12 12 13](https://github.com/metanorma/metanorma-ogc/assets/18121038/2b328453-e228-40e8-ba97-296d543da702)

**Comment by ronaldtse** [comment]
@Intelligent2013 could you please help urgently? Thanks.

**Comment by Intelligent2013** [comment]
XML fragment:
```xml
<table id="rc_movingfeature" class="modspec" type="recommendclass">
	<thead>
		<tr>
			<th scope="colgroup" colspan="2">
				<p class="RecommendationTitle">Requirements class 2: Requirements Class ‘Moving Features’</p>
			</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<th>Identifier</th>
			<td>
				<tt>http://www.opengis.net/spec/ogcapi-movingfeatures-1/1.0/req/movingfeatures</tt>
			</td>
		</tr>
```
Internally, in XSL-FO the table contains 6 columns with non determined widths:
```xml
<fo:table id="rc_movingfeature" table-omit-footer-at-break="true" table-layout="fixed" width="100%">
	<fo:table-column column-width="proportional-column-width(NaN)"/>
	<fo:table-column column-width="proportional-column-width(NaN)"/>
	<fo:table-column column-width="proportional-column-width(NaN)"/>
	<fo:table-column column-width="proportional-column-width(NaN)"/>
	<fo:table-column column-width="proportional-column-width(NaN)"/>
	<fo:table-column column-width="proportional-column-width(NaN)"/>
	<fo:table-header>
```
I'll investigate what's happened.


@ronaldtse FYI, the current issue doesn't relate to the `mn2pdf`, but https://opengeospatial.github.io/ogcna-auto-review/22-003.pdf generated by `mn2pdf` version 1.50 (Sep 3, 2022)
![image](https://github.com/metanorma/metanorma-ogc/assets/5559926/33df47e1-eb1a-4506-8241-ea14226c0d5b)

The latest version is 1.82 (https://github.com/metanorma/mn2pdf/releases/tag/v1.82)

May be something wrong in the metanorma container?
From https://github.com/opengeospatial/ogcna-auto-review/blob/main/.github/workflows/generate_22-003.yml:
```
jobs:
  build:
    runs-on: ubuntu-latest
    container: metanorma/metanorma:latest
...
```

**Comment by Intelligent2013** [comment]
@ronaldtse issue fixed in https://github.com/metanorma/metanorma-ogc and https://github.com/metanorma/mn2pdf/releases/tag/v1.83.
(The issue was in the table processing algorithm with the `id`s `rc_movingfeature` and `rc_movingfeature_collection`, both start with the same prefix `rc_movingfeature_` in the algorithm).

**Comment by Intelligent2013** [comment]
Resulted PDF:
![image](https://github.com/metanorma/metanorma-ogc/assets/5559926/4fde6d54-2f24-47da-9e0f-6290b92c54e9)

**Comment by ronaldtse** [comment]
@Intelligent2013 it's a little strange that the table column balancing depends on the ID...?

**Comment by Intelligent2013** [comment]
> @Intelligent2013 it's a little strange that the table column balancing depends on the ID...?

@ronaldtse table column balancing algorithm based on the Apache Intermediate Format (IF) XML processing. Apache IF XML doesn't contain table 'as is'. It contains the portions of the text with the 'x,y' coordinates. For identifying the relation each text to the table, we need to mark each text with id = table's id + row number + column number. In the algorithm there was issue with the extraction the row number + column number after the table's id. Now it's fixed.
