### ISSUE TITLE
Documentation link leads to 404 error

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-ogc#631]
[This page](https://www.metanorma.org/author/ogc/authoring-guide/sections/#refs) has a link that leads to a 404 error.

![Screenshot 2024-02-12 at 10 49 52](https://github.com/metanorma/metanorma-ogc/assets/18121038/843048fa-3fe1-4fda-973d-48f8069d2270)

**Comment by opoudjis** [comment]
@ronaldtse I have pushed this fix to main branch, exceptionally. Kindly release to metanorma.org

**Comment by ronaldtse** [comment]
@kwkwan please incorporate this fix into the latest PR. Thanks.
