### ISSUE TITLE
Build failing to make documents available to public pages

### ISSUE THREAD

**Issue by gbuehler** [metanorma/metanorma-ogc#644]
This is related to:  https://github.com/metanorma/metanorma-ogc/issues/641

The build works on the repo and produces the correct package, however the link where the documents are supposed to go:

http://ogc.pages.ogc.org/FORK_RBT_GPKG_Sprint/

be redirected to:

http://fork-rbt-gpkg-sprint-ogc-2bab981504266ec943d80b3c8b394739cb5cdb.pages.ogc.org/

and that file is incomplete (as there is no content in the "main-section":
<img width="966" alt="Screenshot 2024-03-13 at 9 28 57 AM" src="https://github.com/metanorma/metanorma-ogc/assets/221625/c48ac36b-09f3-4c47-99f0-5294fb48edef">

**Comment by opoudjis** [comment]
That looks like the site generation HTML code, which is not code I'm familiar with, but I'll have a look into it.

**Comment by opoudjis** [comment]
@gbuehler could you please give me access to

https://gitlab.ogc.org/ogc/FORK_RBT_GPKG_Sprint/-/tree/main

**Comment by jerstlouis** [comment]
@opoudjis @ronaldtse This is a major inconvenience for our short duration 3-weeks OGC RBT sprint (only next week left), and also for final editorial fixes to documents prior to the member meeting in Delft in little more than a week.

Is there something we can do to help move this forward? Thanks.

**Comment by opoudjis** [comment]
I was given access last night, and I will be actioning in the next few hours. It's not code I've written, but I'm hoping I can tackle it today.

It will however  require  a re-release if it is to make it to Docker; the only way to get to the results earlier is to pull from github and run from command line. A full re-release means nothing until at least Tuesday; but this error likely is happening late in the production chain, so I might be able to release with just one chain.

What you can do going forward as OGC is:

* Give me access proactive to gitlab as an OGC contributor, if you want me to do quick debugging.
* Make sure you have a fallback document production chain, based on running Metanorma on the command-line. There is nothing quick about updating Docker: it has to run through two gauntlets of tests across all flavours of Metanorma, which takes the better part of a day in the best case.

And I  need to manage expectations here: it's not my code and not my production chain. If I cannot replicate this result on the command line in my environment, then @CAMOBAP will need to be involved.

**Comment by opoudjis** [comment]
I've replicated the outcome. OK, wish me luck...

**Comment by jerstlouis** [comment]
Thanks a lot! Greatly appreciate it @opoudjis . Good luck!

+1 to giving you GitLab access and having a fallback production chain.

**Comment by ronaldtse** [comment]
So the fix is actually simple here.

<img width="1251" alt="Screenshot 2024-03-16 at 9 53 13 AM" src="https://github.com/metanorma/metanorma-ogc/assets/11865/c0557c61-e909-4caa-9471-3a44c35b6f6e">

Change this line:
```adoc
:mn-output-extensions: html,pdf
```

Into this:
```adoc
:mn-output-extensions: html,pdf,rxl
```

And you'll see the output.

**Comment by ronaldtse** [comment]
The reason being interesting enough, the `site generate` feature is actually part of Relaton, not Metanorma 😉  So the process only reads in bibliographic metadata, it does not actually read in any Metanorma documents.

What this means is that Relaton reads the `*.rxl` files in the output `_site` directory, and generates the index. Since the output extension of `rxl` is omitted, the `*.rxl` files are not generated and Relaton does not know what documents exist.

This is a *known* issue but we have not decided on the proper outcome:
* Option 1: mandate generation of `*.rxl` files.
* Option 2: do not rely on `*.rxl` files to generate the site.

**Comment by opoudjis** [comment]
I vote option 1. Easier to flow through, and RXL are useful metadata. I will see if I can add `rxl` to the outputs in case there is site compilation; we already implicitly add `presentation` to the outputs if there is html, doc, pdf involved.

**Comment by ronaldtse** [comment]
@gbuehler @jerstlouis here's the fix pushed to a GitLab Merge Request:
* https://gitlab.ogc.org/ogc/FORK_RBT_GPKG_Sprint/-/merge_requests/1

**Comment by ronaldtse** [comment]
> I vote option 1. Easier to flow through, and RXL are useful metadata. I will see if I can add `rxl` to the outputs in case there is site compilation; we already implicitly add `presentation` to the outputs if there is html, doc, pdf involved.

Ahh I didn't know there is already a precedent (well it was a while since I checked), then let's do that.

**Comment by opoudjis** [comment]
This is going well. I will not do an emergency release on Monday, since there is an easy work-around, but the implicit supplying of :rxl for site generation will be included in the release next Monday.

**Comment by opoudjis** [comment]
![Screenshot 2024-03-16 at 13 56 24](https://github.com/metanorma/metanorma-ogc/assets/1911039/00fdea59-2c65-402a-a28f-1154797d4fce)

Generated here with no manual insertion of `rxl`

**Comment by jerstlouis** [comment]
Thank you very much @opoudjis @ronaldtse for fixing this so quickly!

@gbuehler hoping we can deploy these workarounds to the RBT and GDC GitLab for early next week.
