### ISSUE TITLE
From OGC: Replicate small box to show document stage and type/subtype

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#65]
From @ghobona

The box should be placed on the cover page. See example from current OGC template http://docs.opengeospatial.org/is/14-065/14-065.html

![image](https://user-images.githubusercontent.com/11865/70935573-6c675900-207b-11ea-8d9e-9a85db29e214.png)

**Comment by ghobona** [comment]
The small box showing the document stage and type/substype is still missing.

![Screen Shot 2020-01-09 at 09 48 04](https://user-images.githubusercontent.com/18121038/72056859-4ec99000-32c5-11ea-836a-ae0bfd1d4f0c.png)

**Comment by ronaldtse** [comment]
@ghobona the new version hasn't been released yet. If you use the Git version of the gems the display should be correct.
