### ISSUE TITLE
Issue with `&` automatic link with query parameters in HTML

### ISSUE THREAD

**Issue by jerstlouis** [metanorma/metanorma-ogc#650]
In OGC API - Maps, the text displayed for links does not appear correctly when automatically generating a link for a URI:

See e.g., B.4. Temporal Subsetting
https://opengeospatial.github.io/ogcna-auto-review/20-058.html#_7b29d626-e927-428d-91c5-202feca2b788

The link target is correct, but not the text.

https://maps.gnosis.earth/ogcapi/collections/sentinel2-l2a/map?center=0,51.5&scale-denominator=50000&datetime=2022-04-01&width=1024&height=512

See also https://github.com/opengeospatial/ogcapi-maps/issues/129 .

Thanks!

@opoudjis

**Comment by opoudjis** [comment]
Fixed, will be included in release next Monday:

![Uploading Screenshot 2024-04-03 at 00.12.55.png…]()
