### ISSUE TITLE
Symbols rendering OK in HTML but not in PDF

### ISSUE THREAD

**Issue by jerstlouis** [metanorma/metanorma-ogc#655]
In Tesbed 19 GeoDataCube ER, symbols were used for TIE tables which display fine in HTML, but not in PDF.

That makes it impossible to understand these table in the PDF form.

See section 6.3.1 in:

http://ogc.pages.ogc.org/T19-GDC/documents/D011/document.html

http://ogc.pages.ogc.org/T19-GDC/documents/D011/document.pdf

Where the legend appears like:

```
## = Tested and functional
# = Tested and does not work
⚪# = Not tested
## = Does not exist / Not implemented
⚠# = Error / Problem
```

Instead of:

```
✔️ = Tested and functional
❌ = Tested and does not work
⚪️ = Not tested
⭕️ = Does not exist / Not implemented
⚠️ = Error / Problem
```

cc. @opoudjis @gbuehler @aljacob

**Comment by opoudjis** [comment]
For my colleague @Intelligent2013 to replicate this issue, we'll prefer the source asciidoc, but I'm assuming these are Unicode codepoints, and that the font used in the PDF generation does not happen to contain them...

So ⭕️ is &#x2B55;&#xFE0F; , where U+FE0F is a glyph variation selector. Clearly not all fonts will support it.

The HTML, with XML entities, is:

````
<div id="_legend">
                    <h3>6.3.1.&#xA0; Legend</h3>

                    <p id="_18a210bc-0885-2e70-c301-1817adfe997b">&#x2714;&#xFE0F; = Tested and functional</p>

                    <p id="_040c8c61-7837-3119-eb8e-882469a6ba28">&#x274C; = Tested and does not work</p>

                    <p id="_54074c3b-611e-983b-e0ba-8be4944a0685">&#x26AA;&#xFE0F; = Not tested</p>

                    <p id="_e5f37ae3-f355-c9c0-ef7b-943af6a21333">&#x2B55;&#xFE0F; = Does not exist / Not implemented</p>

                    <p id="_f6587dde-a7b8-d2cd-5626-0d2595b850be">&#x26A0;&#xFE0F; = Error / Problem</p>

                    <hr/>
                </div>
````

**Comment by jerstlouis** [comment]
Thank you @opoudjis for looking into this.

> For my colleague @Intelligent2013 to replicate this issue, we'll prefer the source asciidoc, 

Here is the source ASCIIDoc snippet:

```
==== Legend
✔️ = Tested and functional

❌ = Tested and does not work

⚪️ = Not tested

⭕️ = Does not exist / Not implemented

⚠️ = Error / Problem
```

> these are Unicode codepoints, and that the font used in the PDF generation does not happen to contain them...

Yes.

Would there be a way to ensure consistent results in terms of picking fonts that support the glyphs used in both HTML and PDF? Or otherwise ensure taht a particular font that does contain these glyphs would be used in the PDF?

I had initially suggested that we tried to stick to glyphs that do not suffer from these problems, but the feedback was that things work in HTML so this is something that metanorma should handle and not require additional work from editors to try to special-handle PDF generation.

**Comment by Intelligent2013** [comment]
The character 'hash' (`#`) in the generated PDF means that glyph is missing in the used font.
You can see http://ogc.pages.ogc.org/T19-GDC/documents/D011/document.pdf.err
```
Glyph "✅" (0x2705) not available in font "Lato-Regular".
Glyph "️" (0xfe0f) not available in font "STIXTwoMath-Regular". Found in the character sequence "⚠️".
Glyph "❌" (0x274c) not available in font "Lato-Regular".
Glyph "✔" (0x2714, a20) not available in font "Lato-Regular". Found in the character sequence "✔️".
Glyph "️" (0xfe0f) not available in font "Lato-Regular". Found in the character sequence "✔️".
...
Glyph "⭕" (0x2b55) not available in font "Lato-Regular". Found in the character sequence "⭕️".
Glyph "" (0xf4dd) not available in font "Lato-Regular". Found in the character sequence "📝".
```
The font 'Lato' (main font) is using for the text rendering in the OGC PDFs.
Secondary fonts (using when the glyph is missing in the 'main font') are:
- 'STIX Two Math',
-  'Noto Sans', 
- 'Noto Sans HK', Noto Sans JP, Noto Sans KR, Noto Sans SC, Noto Sans TC.

The font `Segoe UI Emoji` contains the missing glyphs. You can expand the supported fonts list by the document attribute:
```
:fonts: Segoe UI Emoji
```

(my `document.adoc` example: [document.adoc.zip](https://github.com/metanorma/metanorma-ogc/files/14923127/document.adoc.zip))

The PDF ([document.pdf](https://github.com/metanorma/metanorma-ogc/files/14923133/document.pdf)) rendering:

![image](https://github.com/metanorma/metanorma-ogc/assets/5559926/bb887d91-c5e6-4e4c-a276-b2f8cdba1b38)


Regarding colored glyphs, I don't sure that Apache FOP (PDF engine) supports them (as MS Word too, https://office-watch.com/2019/color-font-support-in-microsoft-office-the-story-so-far/). I need time for the investigation.

**Comment by jerstlouis** [comment]
Thank you very much for investigating this @Intelligent2013 !

I would be very happy with the rendering displayed above, the lack of color is not really an issue as long as the TIE tables are intelligible, which was not the case with the `##` symbols.

I added the `:fonts: Segoe UI Emoji` line, however I'm not sure how to get this font working?

On the OGC GitLab automated pipeline I get:

```
[fontist] 'Segoe UI Emoji' font is not supported. Please report this issue at github.com/metanorma/metanorma/issues to report this issue.
```

Locally, I simply still get the hashes.

I tried locally: `fontist install "Segoe UI Emoji"`

but that gives me:

```
Font "Segoe UI Emoji" not found locally.
Font 'Segoe UI Emoji' not found locally nor available in the Fontist formula repository.
Perhaps it is available at the latest Fontist formula repository.
You can update the formula repository using the command `fontist update` and try again
```

same after trying a `fontist update`.

Is there something special we should be doing to have access to that font?

Thanks again!

**Comment by opoudjis** [comment]
Google fonts have changed their API, so right now Fontist can't talk to it at all. That issue is also holding up our Metanorma release. My colleague Alexei is working on this, but I request you wait a few days

**Comment by Intelligent2013** [comment]
> I tried locally: `fontist install "Segoe UI Emoji"`

@jerstlouis which OS is installed locally? Thanks.

> I get the same error trying to run `fontist install "Noto Emoji"` locally:

I've installed Noto Emoji manually for testing purposes and tried to generate PDF. The Noto Emoji glyphs shifted up, looks like due the different base line:
![image](https://github.com/metanorma/metanorma-ogc/assets/5559926/6c1a124c-3e81-4ba7-9e15-7ae27d8c43c8)

**Comment by Intelligent2013** [comment]
@jerstlouis sorry, I've mistakenly thought that 'Segoe UI Emoji' available via fontist (
https://github.com/fontist/formulas/blob/v3/Formulas/segoe_ui.yml), but it installs 'Segoe UI' fonts only. The font 'Segoe UI Emoji' is available in Win OS only. I'll find the solution.

**Comment by Intelligent2013** [comment]
@jerstlouis I've tried a few fonts for display emoji glyphs:

### - the font 'Noto Color Emoji'
glyphs are missing in the PDF:
![image](https://github.com/metanorma/metanorma-ogc/assets/5559926/26d77a85-ca89-4126-9513-a366d88cf0cc)
but they can be copied:
![image](https://github.com/metanorma/metanorma-ogc/assets/5559926/248da1e1-402a-4cab-a4f9-94209be976f9)
and pasted into the Word:
![image](https://github.com/metanorma/metanorma-ogc/assets/5559926/005a158f-4665-43d1-b0c7-ef015e0f41df)


- ### the font `FreeSerif` (available via fontist)
contains the _most_ (but not all) glyphs. PDF renders so with `:fonts: FreeSerif`:
![image](https://github.com/metanorma/metanorma-ogc/assets/5559926/f227c229-6974-4770-9a1c-ef3e8b62698c)

The missing glyphs and proposal for replacement are:
- `0xfe0f` (emoji variation selector), https://www.fileformat.info/info/unicode/char/fe0f/index.htm
   - proposal: FreeSerif doesn't support variation selection, so remove this char across all document
- `0x2b55` (HEAVY LARGE CIRCLE), https://www.fileformat.info/info/unicode/char/2b55/fontsupport.htm
![image](https://github.com/metanorma/metanorma-ogc/assets/5559926/fabc4c0a-9929-493f-85ab-a8ee6934f263)
   - proposal: replace to `0x26AB` ('Medium Black Circle')
- `0x1f4dd` (Memo Emoji), https://www.fileformat.info/info/unicode/char/1f4dd/fontsupport.htm
![image](https://github.com/metanorma/metanorma-ogc/assets/5559926/204e3710-e4b6-4337-9b44-203606e5a910)
   - replace to `0x270d` (Writing Hand):
![image](https://github.com/metanorma/metanorma-ogc/assets/5559926/e0217962-f431-45bd-99f5-e184c67feb08)

- the font 'OpenEmoji-Color' (not available via fontist)
- (working .ttf instance found in https://issues.apache.org/jira/browse/FOP-2997)
PDF with OpenEmoji-Color renders so:
![image](https://github.com/metanorma/metanorma-ogc/assets/5559926/82f24992-78e2-4c7a-9264-4a980ec3af71)

Without `0xfe0f` (emoji variation selector)` (missing in OpenEmoji-Color):
![image](https://github.com/metanorma/metanorma-ogc/assets/5559926/a20edc3c-5353-4f08-8563-bd7d7cdfc993)

There is a bit baseline shifted down.

So, currently there are two variants:
- the font FreeSerif with some char replacements in the document
- the font OpenEmoji (fontist formulas should be updated, and properly working latest .ttf source should be found).

**Comment by jerstlouis** [comment]
Thanks so much for this deep dive @Intelligent2013 !

cc. @aljacob

**Comment by ronaldtse** [comment]
Thank you @Intelligent2013 !

Can you please write a blog post on how to use emojis in Metanorma and that now we support them? Thanks!

**Comment by jerstlouis** [comment]
We were just able to build the GDC ER PDF, and it looks great!

http://ogc.pages.ogc.org/T19-GDC/documents/D011/document.pdf

Thanks again @Intelligent2013 @opoudjis @ronaldtse .
