### ISSUE TITLE
Images default size huge and outside of document in PDF

### ISSUE THREAD

**Issue by jerstlouis** [metanorma/metanorma-ogc#656]
In the PDF rendering of Tesbed 19 GeoDataCube ER, inline images appear huge (much larger than their resolution supports) with a large portion of the content outside of the page.

See section 5.2.3 of:

http://ogc.pages.ogc.org/T19-GDC/documents/D011/document.pdf

e.g. page 79+

cc. @opoudjis @gbuehler @aljacob

**Comment by opoudjis** [comment]
@jerstlouis Please provide the source repository for my colleague @Intelligent2013 (or give me the link, and I'll download it for him).

**Comment by jerstlouis** [comment]
@opoudjis https://gitlab.ogc.org/ogc/T19-GDC/-/tree/main/D011 is the source repo, if you can get OGC to grant you access.

Sorry, I did not realize it was not obvious from the pages link.

Note that these are inline images (`image:` with a single colon).

Thanks!

**Comment by opoudjis** [comment]
Yes, I have access. @Intelligent2013 do you? I'm going to zip you a copy just in case...

**Comment by ronaldtse** [comment]
We recently ran into an issue that the PDF images are exceedingly large because of image DPI settings. We will provide some documentation on that here:
* https://github.com/metanorma/metanorma.org/issues/757

**Comment by ronaldtse** [comment]
@jerstlouis I've reviewed the images and indeed there is an out of bounds issue with inline images.

There is however an editorial issue -- since these images are large and illustrative, maybe they are better presented as actual Figures (block images)?

**Comment by Intelligent2013** [comment]
The block image renders not properly also:
![image](https://github.com/metanorma/metanorma-ogc/assets/5559926/11c08d99-6ac5-45be-b0e5-16af9f5e3803)
`mn2pdf` resizes the image to the effective page width size (page width minus page left/right margins), but the list item left indent shifts the image to the right. I'll fix it.

**Comment by jerstlouis** [comment]
@Intelligent2013 Those images in the bullet lists are inline images (`image:` with single colon), since that is the only thing that works in bullet lists.
As far as I know the block images (`image::` with two colons) are fine.

Those are inline images.

@ronaldtse 

> since these images are large and illustrative, maybe they are better presented as actual Figures (block images)?

I agree -- I had raised the issue that these images should not be in bullet lists. This is not my content, I am not the editor, the ER has been aproved, and the ER is now in the hands of OGC staff for the final edits and publishing.

The issue I was pointing out here is that this metanorma behavior of images going out of range is unexpected.
It would make much more sense to ensure the image is rescaled to fit within the available space.
Especially since the image seems to be enlarged beyond the DPI it can support without being pixelated.

@Intelligent2013

> resizes the image to the effective page width size (page width minus page left/right margins), but the list item left indent shifts the image to the right. I'll fix it.

Exactly, it would be great if that indentation is taken into consideration.

Actually, I was looking at the PDF I generated locally, and it seems that it did not suffer from that issue.

So maybe this is something that was broken recently in an update in the docker version running on the OGC GitLab pipeline?

Thanks!

**Comment by Intelligent2013** [comment]
@jerstlouis I've updated OGC XSLT for properly image resizing:
![image](https://github.com/metanorma/metanorma-ogc/assets/5559926/20d59335-8785-4731-8981-c3c5a94b7799)

This update will be included in the next release (I think on April, 21, @opoudjis please correct me).
But you can use it today,  by updating `Gemfile` locally. Add these line:
```
gem "metanorma-ogc", git: "https://github.com/metanorma/metanorma-ogc", branch: "main"
```
then run `bundle update`.
Then `bundle exec metanorma -t ogc -x pdf document.adoc`

**Comment by jerstlouis** [comment]
Thanks a lot @Intelligent2013 . That looks good, and identical to how things were building for me locally with an older metanorma build.

I guess we will have to wait for the release for the OGC GitLab docker to pick up the fix.

**Comment by opoudjis** [comment]
The release just was forced out a couple of hours ago, so it is on its way to Docker; please check tomorrow. Barring problems (and we do keep having them), the next release is indeed intended for Monday 22 April, but it tends to go out to docker some time on the following day.

Because things keep disrupting releases, I'm going to create a Github discussion thread where we notify users of releases when they go live, and what their content is.

**Comment by jerstlouis** [comment]
Things look great now with the latest release (the inline images are in section 5.2.3 on pages 78+):

http://ogc.pages.ogc.org/T19-GDC/documents/D011/document.pdf

Thanks @opoudjis @ronaldtse
