### ISSUE TITLE
From OGC: Change the title and section header font type to be the same as that of the body text

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#66]

**Comment by opoudjis** [comment]
Changed headerfont "Teko" to "Overpass", same as bodyfont.

**Comment by ghobona** [comment]
The solution is not what we expected. Looks like the Title font has been changed to Teko. 

Could you please change the font of both the title and section headers to Overpass?

**Comment by ronaldtse** [comment]
@ghobona I believe the font is now Overpass; but the latest code is not yet released. We will ensure the title and all section headers are in Overpass.

**Comment by opoudjis** [comment]
@ghobona Metanorma software releases are fortnightly, because we need to synchronise a lot of development across dozens of gems. Next release will be tomorrow.
