### ISSUE TITLE
Documentation page returning 404 error

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-ogc#660]
The link to mod spec documentation is returning a 404 error. Visit the links shown on the attached screenshot.

![Screenshot 2024-04-26 at 17 22 48](https://github.com/metanorma/metanorma-ogc/assets/18121038/b9abd3d2-6f5f-4cea-a424-2577622c5f62)

**Comment by opoudjis** [comment]
The directory pointed to has been rearranged, and the person doing so has neglected to update the sidebar links.
