### ISSUE TITLE
URL in query string breaks PDF compilation

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-ogc#664]
Arises in compiling document in https://github.com/opengeospatial/ogcapi-maps/pull/132

as reported in https://github.com/opengeospatial/ogcapi-maps/issues/129

dealing with URLs like

`https://maps.gnosis.earth/ogcapi/collections/blueMarble/map?center=0,51.5&scale-denominator=20000000&crs=%5BEPSG:4326%5D["https://maps.gnosis.earth/ogcapi/collections/blueMarble/map?center=0,51.5&scale-denominator=20000000&crs=[EPSG:4326\]"]`

with & in the URL string

This was breaking HTML, and I've fixed that in https://github.com/metanorma/metanorma-ogc/issues/650

I think the issue is that the URL content is being rendered as content of the hyperlink if the `<link target="..."/>` element is empty, and the ampersand is not being XML-escaped...

**Comment by Intelligent2013** [comment]
I can't repeat this issue. PDF generated successfully:
![image](https://github.com/metanorma/metanorma-ogc/assets/5559926/33846589-cc18-44bc-8e88-c6d7fefd9f6a)
(Note: A.7 instead of B.7, because I use `annex_examples.adoc` only in the test generation.)

I use this https://github.com/opengeospatial/ogcapi-maps/pull/132/commits/12a0c59d90a99e28c761067c006939203346f8e5

```
git clone https://github.com/opengeospatial/ogcapi-maps
cd ogcapi-maps
git checkout fix_issue_129
cd core\standard 
```
I've just generated the presentation XML for this parts:
```
include::clause_0_front_material.adoc[]

include::clause_1_scope.adoc[]

include::annex_examples.adoc[]
```

**Comment by Intelligent2013** [comment]
What is the concrete error do you have?
Please attach the error from .err file near where the resulted PDF should be generated.

**Comment by opoudjis** [comment]
Attention @jerstlouis

But the `<link/>` in the Presentation XML is clearly a bug on my side.

**Comment by opoudjis** [comment]
Asciidoc is not that smart, @jerstlouis, and your HTTP link is killing it.

Asciidoc processes http links by Regex.

It can cope with

````
https://maps.gnosis.earth/ogcapi/collections/blueMarble/map?center=0,51.5&scale-denominator=20000000&crs=%5BEPSG:4326%5D
````

and it can cope with

````
https://maps.gnosis.earth/ogcapi/collections/blueMarble/map?center=0,51.5&scale-denominator=20000000&crs=[EPSG:4326]
````

But when you give it:

````
https://maps.gnosis.earth/ogcapi/collections/blueMarble/map?center=0,51.5&scale-denominator=20000000&crs=%5BEPSG:4326%5D["https://maps.gnosis.earth/ogcapi/collections/blueMarble/map?center=0,51.5&scale-denominator=20000000&crs=[EPSG:4326\]"]
````

it is using a Regex to resolve, not only the https:// at the start, but also the https:// inside of the https:....[] "macro", and the results ends up being complete confusion. That confusion ends up turning into a nested `<link/>` when Metanorma receives the results of Asciidoctor parsing.

In order to prevent that confusion, you need to escape the internal `https:` instance:

````
https://maps.gnosis.earth/ogcapi/collections/blueMarble/map?center=0,51.5&scale-denominator=20000000&crs=%5BEPSG:4326%5D["\https://maps.gnosis.earth/ogcapi/collections/blueMarble/map?center=0,51.5&scale-denominator=20000000&crs=[EPSG:4326\]"]
````

That renders sensibly in Presentation XML as:

````
<p id="_3ba27ef8-64b8-2244-828b-f8fd7970c523"><link target="https://maps.gnosis.earth/ogcapi/collections/blueMarble/map?center=0,51.5&amp;scale-denominator=20000000&amp;crs=%5BEPSG:4326%5D">https://maps.gnosis.earth/ogcapi/collections/blueMarble/map?center=0,51.5&amp;scale-denominator=20000000&amp;crs=[EPSG:4326]</link></p>
````

@Intelligent2013 @jerstlouis Does this address the issue?

**Comment by Intelligent2013** [comment]
@opoudjis I've checked:
```xml
<p id="_3ba27ef8-64b8-2244-828b-f8fd7970c523"><link target="https://maps.gnosis.earth/ogcapi/collections/blueMarble/map?center=0,51.5&amp;scale-denominator=20000000&amp;crs=%5BEPSG:4326%5D">https://maps.gnosis.earth/ogcapi/collections/blueMarble/map?center=0,51.5&amp;scale-denominator=20000000&amp;crs=[EPSG:4326]</link></p>
```
renders in PDF correctly:
![image](https://github.com/metanorma/metanorma-ogc/assets/5559926/ca2bc4db-7cf4-4ab2-b430-0c055826b4e0)

**Comment by opoudjis** [comment]
OK, closing.

**Comment by opoudjis** [comment]
alert editors
