### ISSUE TITLE
From OGC: Requirements classes encoding

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#67]
Requirement class source:

```adoc
[requirement,type="class",id="http://www.opengis.net/spec/waterml/2.0/req/xsd-xml-rules\[*req/core*\]",obligation="requirement"]
====

Name:: GWML2 core logical model

Target type:: Encoding of logical models

[dependency]
--
* urn:iso:dis:iso:19156:clause:7.2.2
* urn:iso:dis:iso:19156:clause:8
* http://www.opengis.net/doc/IS/GML/3.2/clause/2.4
* O&M Abstract model, OGC 10-004r3, clause D.3.4
* http://www.opengis.net/spec/SWE/2.0/req/core/core-concepts-used
--

[requirement,type="general",id="/req/core/encoding"]
======
======
[requirement,type="general",id="/req/core/quantities-uom"]
======
======
[recommendation,type="general",id="/req/core/codelist"]
======
======
[requirement,type="general",id="/req/core/codelistURI"]
======
======
[requirement,type="general",id="/req/core/identifier"]
======
======
[requirement,type="general",id="/req/core/feature"]
======
======
====
```

Requirement class proper rendering (something like this):
<img width="1082" alt="Screen Shot 2019-12-17 at 3 29 54 AM" src="https://user-images.githubusercontent.com/11865/70936560-8144ec00-207d-11ea-8131-1bff650771ad.png">

Requirement class current rendering:

<img width="1093" alt="Screen Shot 2019-12-17 at 3 29 44 AM" src="https://user-images.githubusercontent.com/11865/70936547-7b4f0b00-207d-11ea-925a-f9efa7c38869.png">

Single requirement source:

```adoc
[requirement,type="general",id="/req/core/encoding",obligation="requirement"]
====
All target implementations SHALL conform to the appropriate GroundWaterML2 Logical Model UML defined in Section 8.
====
```

Single requirement proper rendering (something like this):

<img width="1098" alt="Screen Shot 2019-12-17 at 3 30 06 AM" src="https://user-images.githubusercontent.com/11865/70936572-87d36380-207d-11ea-8a73-d40683bbe1cd.png">

Single requirement current rendering:
(missing URI)

<img width="1083" alt="Screen Shot 2019-12-17 at 3 30 16 AM" src="https://user-images.githubusercontent.com/11865/70936581-8d30ae00-207d-11ea-9bca-18180f7718cb.png">

**Comment by ronaldtse** [comment]
Point of this ticket is to allow creation of a "Requirement Class" that aligns with the existing "Requirement" from OGC Requirements model.

**Comment by opoudjis** [comment]
Our design approach is to use existing elements in the Metanorma Requirements specification whensoever possible. So:

* Requirement classes shall have type "class"
* Target type shall be the "subject" attribute
* Dependency shall be the "inherit" attribute
* The "inherit" attribute can have many values, semicolon-delimited
* Nested requirements may be rendered as lines

**Comment by opoudjis** [comment]
So the proper markup shall be:

````
[requirement,type="class",label="http://www.opengis.net/spec/waterml/2.0/req/xsd-xml-rules\[*req/core*\]",obligation="requirement",subject="Encoding of logical models",inherit="urn:iso:dis:iso:19156:clause:7.2.2;urn:iso:dis:iso:19156:clause:8;http://www.opengis.net/doc/IS/GML/3.2/clause/2.4;O&M Abstract model, OGC 10-004r3, clause D.3.4;http://www.opengis.net/spec/SWE/2.0/req/core/core-concepts-used"]
.GWML2 core logical model
====

[requirement,type="general",label="/req/core/encoding"]
======
======
[requirement,type="general",label="/req/core/quantities-uom"]
======
======
[recommendation,type="general",label="/req/core/codelist"]
======
======
[requirement,type="general",label="/req/core/codelistURI"]
======
======
[requirement,type="general",label="/req/core/identifier"]
======
======
[requirement,type="general",label="/req/core/feature"]
======
======
====
````

**Comment by opoudjis** [comment]
And this is what a requirement class renders as:

[reqtclass.zip](https://github.com/metanorma/metanorma-ogc/files/4035385/reqtclass.zip)
