### ISSUE TITLE
Forced Page Break (`<<<`) to keep example request with output image causes blank pages

### ISSUE THREAD

**Issue by jerstlouis** [metanorma/metanorma-ogc#674]
In OGC API - Maps ( and now OGC API - DGGS ), we forced page break with `<<<` so that a URL shows together with the following figure that illustrates its output.

The behavior seems to have changed either in metanorma itself, or as a result of moving from asciidoctor-pdf to metanorma.

In OGC API - Maps, the approach that used to work before was to include a page break _**after**_ the image.
Now this just results in creating an empty page and the image not on the same page as the previous requests.

e.g., see page 223 in https://docs.ogc.org/DRAFTS/20-058.pdf ( https://github.com/opengeospatial/ogcapi-maps/blob/master/core/standard/annex_examples.adoc )

In OGC API - DGGS, I am attempting to put force a page break before the request, to make sure that the request and image have plenty of room to be together on the same page. This does result in them being together on the same page, however it still results in fully empty pages.

e.g., see the end of the examples annex ( https://github.com/opengeospatial/ogcapi-discrete-global-grid-systems/blob/master/core/sections/annex-c-examples.adoc -- the draft at https://docs.ogc.org/DRAFTS/21-038.pdf is not yet generated).

**Comment by Intelligent2013** [comment]
The issue confirmed
The presentation XML:
```xml
<pagebreak/>
```
The XSL-FO:
```xml
<fo:block break-after="page"/>
 <fo:block> </fo:block>
 <fo:block break-after="page"/>
```

**Comment by Intelligent2013** [comment]
Metanorma OGC XSLT updated for fixing the double page break issue.

**Comment by Intelligent2013** [comment]
I hope the ticket can be closed.

Tip: instead of page break `<<<` you can use `[keep-with-next=true]`, for example:
```
[keep-with-next=true]
https://maps.gnosis.earth/ogcapi/collections...
```

(https://www.metanorma.org/author/topics/document-format/page-flow/#avoiding-page-breaks)

**Comment by jerstlouis** [comment]
Thanks for that @Intelligent2013 , will definitely try `[keep-with-next=true]` out -- seems less likely to result in extra page break issues.
