### ISSUE TITLE
Bibliography can appear before Annexes

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-ogc#706]
Follow-on from https://github.com/metanorma/metanorma-ogc/issues/704

In engineering reports, it is possible for the bibliography to appear before the annexes. In the PDF, the ToC ordering respects that, following the displayorder attribute; but the actual positions of the annex and bibliography do not. Sample attached.

[Archive 4.zip](https://github.com/user-attachments/files/16588293/Archive.4.zip)

**Comment by Intelligent2013** [comment]
Fixed.
[a1.presentation.pdf](https://github.com/user-attachments/files/16591429/a1.presentation.pdf)
