### ISSUE TITLE
Indent on bibliography title in ToC, PDF

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-ogc#715]
In Tables of Contents in PDF, the bibliography is indented, so that its lack of a clause number aligns the title text with other clauses' text:

![Screenshot 2024-09-09 at 23 28 11](https://github.com/user-attachments/assets/90a6f32f-c8cc-44e3-b255-ba656eac8bb2)

By the time we have annexes, though, this looks odd:

![Screenshot 2024-09-09 at 23 29 44](https://github.com/user-attachments/assets/5196a7fc-0409-45d6-9a27-42e77095788f)

@gbuehler @ghobona @ogcscotts we saw this in today's teleconference. Unless any of you object, I request we not indent the bibliography in ToC, and we treated as Annexes, left-aligned.

**Comment by Intelligent2013** [comment]
Done:
![image](https://github.com/user-attachments/assets/0e12da35-5f47-4e7d-9141-47344d405a6d)
