### ISSUE TITLE
Update document.adoc file of Engineering Report template generated by metanorma

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-ogc#721]
Please update the document.adoc file of the Engineering Report template generated by metanorma.

It should look like [this one](https://raw.githubusercontent.com/opengeospatial/templates/refs/heads/master/engineering_report/template/document.adoc).

**Comment by opoudjis** [comment]
@ghobona That should be actioned  already under https://github.com/metanorma/mn-templates-ogc/issues/54 (which you had raised, and I migrated to mn-templates-ogc from metanorma-ogc). Could you please confirm it matches your expectation?

**Comment by ghobona** [comment]
@opoudjis Apologies. Yes, it's a duplicate. Closing this ticket.
