### ISSUE TITLE
Offer an option for compiling document without embedding images

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-ogc#722]
Currently the `compile` option of the command line interface embeds images into HTML documents by default.

Whereas this is a very useful feature, there are some situations when it is not necessary to embed images in the HTML document. Offering the option of not embedding images might also save sometime during compilation when an editor is authoring a document.

For example, during authoring of the document, an editor might compile the document without embedding the images. Then when the document is ready to be submitted to the OGC Technical Committee, the editor would compile the document with images embedded using dataURLs as is the case now.

**Comment by opoudjis** [comment]
To disable embedding images, set `:data-uri-image: false` in the document header.

**Comment by ghobona** [comment]
@opoudjis That's excellent! Thanks.
