### ISSUE TITLE
Unable to pull ISO 19168-1:2020 into the bibliography

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-ogc#740]
I have tried all of the following combinations and am unable to pull [ISO 19168-1:2020](https://www.iso.org/standard/32586.html) into the bibliography. 

```
* [[iso19168-1,ISO 19168-1:2020]]],
* [[ISO19168-1,ISO 19168-1:2020]]],
* [[ISO19168-1-2020,ISO 19168-1:2020]]],
```

Could you please advise on how to pull it into the bibliography?

**Comment by ronaldtse** [comment]
@ghobona the three above forms are identical in what is being fetched, because the document identifier that is referenced is the one after the “comma”. 

They all look correct and I’m not sure why it isn’t fetched. Ping @andrew2net

**Comment by ghobona** [comment]
@ronaldtse @andrew2net Apologies. I was missing one more square bracket. It's [fixed](https://github.com/opengeospatial/ogcapi-common/commit/eda5e428c21bec81991d2eae2d4cc60847ca75db) now, thanks.
