### ISSUE TITLE
Boilerplate refactor broke OGC layout

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#78]
A picture is worth many words:

<img width="849" alt="image" src="https://user-images.githubusercontent.com/11865/73763910-14142400-47ad-11ea-8f56-142bac5db51a.png">

**Comment by opoudjis** [comment]
have had to do some cleanup in isodoc:

* If there is an id, but no associated :level, `<h#{node[:level]}>` was still generating incorrect `<h[id]>` tags; stopped that
* Removing empty headers from boilerplate sections: they were taking up redundant space in HTML

And debugged the invoked anchor for boilerplate-contact in OGC.
