### ISSUE TITLE
Preface section is not numbered

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-ogc#82]
The Preface section is not getting numbered like the other sections from the front material (Abstract, Keywords, Submitting Organizations, Submitters). 

For example:
![preface-issue-capture](https://user-images.githubusercontent.com/33627611/74210161-005f3680-4c61-11ea-9b12-b7c5b5bd1cb1.JPG)

Following the numbering of the previous sections (Abstract and Keywords), the Preface should have a section number of `iii`.

File sample:
[preface-issue.zip](https://github.com/metanorma/metanorma-ogc/files/4184045/preface-issue.zip)

**Comment by opoudjis** [comment]
Is failing because forewords are not getting clause IDs. Annulling that behaviour in standoc, there is no good reason for it.
