### ISSUE TITLE
Allow preliminary sections outside the 5 mandatory ones

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#83]
Authors are allowed to add extra preliminary sections outside the mandatory 5 (Abstract, Keywords, Preface, Submitting organizations, Submitters).

Let's re-use the `[.preface]` syntax from Metanorma NIST.

UPDATE: All extra preliminary sections will occur in the order they are defined, but AFTER the 5 mandatory sections. (https://github.com/metanorma/metanorma-ogc/issues/83#issuecomment-585631360)

Originally from #80.

**Comment by ronaldtse** [comment]
One more question for @ghobona @ogcscotts. The 5 mandatory preliminary sections have a fixed order, of: Abstract, Keywords, Preface, Submitting organizations, Submitters. Should we require all non-mandatory preliminary sections to be placed after these mandatory 5? This seems to be the most reasonable and consistent approach across documents.

**Comment by ogcscotts** [comment]
makes sense to me to do so!

**Comment by ronaldtse** [comment]
Confirmed. Thank you @ogcscotts !

**Comment by opoudjis** [comment]
Implemented as part of https://github.com/metanorma/metanorma-standoc/issues/203
