### ISSUE TITLE
Allow "`Preface`" (a preliminary section itself) to have subsections

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#84]
The Preface, currently set using `.Preface`, should support sub-sections.

For example, 19-013 contains:

```adoc
.Preface

*Motivation*

A significant portion of the global water supply can be attributed to groundwater resources.
...

*Historical background*
...
```

It should instead support subsections, perhaps like this?

```
[.preface]
== Preface

=== Motivation
...
=== Historical background
...
```

Originally from #80.

**Comment by opoudjis** [comment]
The OGC preface is the Standoc foreword. The foreword currently is defined as the asciidoc preamble (https://asciidoctor.org/docs/user-manual/#doc-preamble), and that hardcodes it as impossible to provide subsections. 

There are two possible solutions here.

* Make the OGC preface be something other than the standoc foreword: a normal clause marked with a preface role (although we already use the preface role to move clauses to the preface!), which can take subclauses
* Allow a clause in standoc to be marked up as a foreword, and to take subclauses.

The latter is the more general solution, and is what we will implement. 

So, clauses in generic Metanorma can be titled as Foreword; they will be recognised as such, and treated as the document preamble:

````
== Foreword

=== Subclauses
````

In the case of OGC, we will treat any clause titled "Preface" as the document preamble instead.
