### ISSUE TITLE
When source code gets too wide in HTML, provide a scrollbar within the source code block

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#86]
When source code gets too wide in HTML, provide a scrollbar within the source code block. In fact this approach should be expanded to Metanorma proper.

EXAMPLE:
![image](https://user-images.githubusercontent.com/11865/74566719-147f9c80-4faf-11ea-9e8e-8cd0f032fe54.png)

Originally from https://github.com/opengeospatial/ogc-metanorma-testing/issues/11#issuecomment-586331746

cc: @ghobona @ogcscotts @gbuehler

**Comment by ronaldtse** [comment]
@w00lf are you handling the stylesheets? Perhaps this would be an easy fix while you're at it? Thanks 😉

**Comment by w00lf** [comment]
> @w00lf are you handling the stylesheets? Perhaps this would be an easy fix while you're at it? Thanks 😉

@ronaldtse ok, will look into this after finish with metanorma-rsd scss migration.

**Comment by w00lf** [comment]
@ronaldtse , done, added styles for source code scroll on wide blocks:
![image](https://user-images.githubusercontent.com/1158036/74609803-a8ac4980-50fe-11ea-9336-7451217f37a3.png)
![image](https://user-images.githubusercontent.com/1158036/74609806-b2ce4800-50fe-11ea-9d9e-ad40d9ad14be.png)

**Comment by ronaldtse** [comment]
Thanks @w00lf ! Perhaps this PR should be set on metanorma-standoc for all other flavors to inherit?

**Comment by ronaldtse** [comment]
Ping @opoudjis

**Comment by opoudjis** [comment]
https://github.com/metanorma/isodoc/issues/146. I addressed this, in the proper place to address this (the global stylesheets) a month ago. 

* The entire point of having stylesheet inheritance is so we do not do ad hoc implementation on each flavour separately.
* The point of having Mikl expedite work on the CSS is so we do not do ad hoc implementation on each flavour separately.

Mikl, please make sure whatever you did in #87 does not contradict https://github.com/metanorma/isodoc/issues/146.

**Comment by w00lf** [comment]
> [metanorma/isodoc#146](https://github.com/metanorma/isodoc/issues/146). I addressed this, in the proper place to address this (the global stylesheets) a month ago.
> 
> * The entire point of having stylesheet inheritance is so we do not do ad hoc implementation on each flavour separately.
> * The point of having Mikl expedite work on the CSS is so we do not do ad hoc implementation on each flavour separately.
> 
> @w00lf, please make sure whatever you did in #87 does not contradict [metanorma/isodoc#146](https://github.com/metanorma/isodoc/issues/146).

@opoudjis should i move this fix to metanorma/isodoc#146 and close this PR?

**Comment by ronaldtse** [comment]
metanorma/isodoc#146 is already closed. @opoudjis can we close this too? Thanks.

**Comment by opoudjis** [comment]
@w00lf merge it, yes. Note that I think you are detecting distinct container to what I was seeking, pre vs .Sourcedode; both should be non-scrolling. For now, the solution can be duplicated in both OGC and Isodoc stylesheet, until OGC stylesheet is refactored to inherit from Isodoc.

**Comment by opoudjis** [comment]
w00lf, I'm confused: the solution is meant to apply to `pre`. You've implemented it for dl.pre, and I don't see why.

````
// Scroll too wide source code
dl {
  grid-template-columns: minmax(0, 1fr) 93%;
  pre {
    overflow-x: scroll;
  }
}
````

I'm jamming in separately:

````
pre {
    overflow-x: scroll;
  }
````

But please clarify what the intent is here. There is no dl wrapping source code in the general case, and you shouldn't assume there is.

**Comment by opoudjis** [comment]
@w00lf, I see there's something else wrong: the isodoc base classes are not being applied to pre, but to p.Sourcecode. That's an error.

**Comment by opoudjis** [comment]
Am taking this issue over, there's a fundamental misunderstanding in the code. .Sourcecode is not being used for sourcecode, pre is, and I need to change all stylesheets.
