### ISSUE TITLE
Confirm official header/footer content

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#92]
It is unclear what header and footer content should be for OGC documents. HTML doesn't have any header/footer, and the PDFs we see don't have them.

In Word, header is:
"Open Geospatial Consortium 08-062r7:YYYY"

Footer is currently applied as alternatives:

Odd: "© 2020 OGC"
Even "© Open Geospatial Consortium 2020 – All rights reserved"

Pending clarification from @ogcscotts @gbuehler @ghobona.

**Comment by ogcscotts** [comment]
I think that we should have the header and even footer for all pages in Word and PDF.

**Comment by ronaldtse** [comment]
Thanks @ogcscotts , can we confirm that the header and footer for all Word and PDF should be:

Header: "Open Geospatial Consortium {doc identifier}"

Footer on alternative pages:

Odd: "© {editionyear} OGC"
Even "© Open Geospatial Consortium {editionyear} – All rights reserved"

?

**Comment by ogcscotts** [comment]
@ronaldtse let's just make all footers the same and use the "even" example.

**Comment by ronaldtse** [comment]
Got it, thanks @ogcscotts !

**Comment by ronaldtse** [comment]
Closing this in favor of #97.
