### ISSUE TITLE
Clarification on text justification

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#93]
OGC text alignment is currently not "justified".

Either all text is to be justified, or not.

Pending clarification from @ogcscotts @gbuehler @ghobona.

_Originally posted by @opoudjis in https://github.com/metanorma/mn-samples-ogc/issues/22#issuecomment-593946322_

**Comment by ogcscotts** [comment]
I'm not a fan of justification on technical documentation; W3C does not justify web standards.

**Comment by ronaldtse** [comment]
@ogcscotts sorry my bad -- I meant "justification" in terms of alignment. Usual text is "left aligned", but text can also be "left justified" meaning the text is spread out across the same line so that text touches both left and right sides.

**Comment by ogcscotts** [comment]
@ronaldtse I support left aligned, but would prefer that we not go to fully-justified (left and right aligned) as the white space in lines looks terrible!

**Comment by ronaldtse** [comment]
@ogcscotts agree. Let's go with left aligned!

**Comment by ronaldtse** [comment]
Closing in favor of #98.
