### ISSUE TITLE
Clarification on usage of "informative" vs "non-normative"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#94]
In 08-062r7 we see the usage of an Annex being "non-normative" instead of "informative".

Would like to seek clarification from @ogcscotts @ghobona @gbuehler to settle on a single term.

**Comment by ogcscotts** [comment]
informative

**Comment by ronaldtse** [comment]
Thanks @ogcscotts . There is no action needed here, OGC in MN has always used the term "informative".

FYI @opoudjis .
