### ISSUE TITLE
Clarification on label usage of ordered lists

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#95]
In 18-046, there are ordered lists that start with "1, 2, 3..." but by default styling it is "a), b), c)..." following ISO style. In ISO/IEC there is no exception.

In ITU, they have two semantic types for ordered lists -- usually "a), b)..." but if it is defined as a "sequence of steps", the labelling goes by "1, 2, 3...".

We need to determine whether there is a semantic difference here or there is only one kind of ordered list and the style to be standardized.

Pending clarification from @ogcscotts @gbuehler @ghobona.

**Comment by ogcscotts** [comment]
hmmm, I did not know that ISO styled only as letters, not numbers. I prefer the ITU semantics, but if it is easier to stick to one style only, we can use letters.

**Comment by ronaldtse** [comment]
@ogcscotts it is not difficult for us to support the ITU semantics, but it may be a burden for authors to know which style to use.

In defense of the ISO style, ISO uses alphabetical list numbering because it makes the clause references clear "Clause 1.2.3.4 a)" vs "Clause 1.2.3.4 1.".

**Comment by ogcscotts** [comment]
@ronaldtse I am fine with just using letters.

**Comment by ronaldtse** [comment]
Perfect, thank you @ogcscotts !

(No further action needed here, closing).

**Comment by ronaldtse** [comment]
Actually a documentation task is needed on metanorma.com. Will make new ticket.
