### ISSUE TITLE
Engineering Reports and Discussion Papers do not have version numbers?

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#96]
Currently, version numbers are not used for Engineering Reports. Can we have a confirmation that these two doctypes are the only ones that versions cannot be set? Thanks!

Question for @ogcscotts @gbuehler @ghobona

Originally from #62.

**Comment by ogcscotts** [comment]
Engineering Reports, Discussion Papers, and White Papers do not have version numbers.

**Comment by ronaldtse** [comment]
Thanks. Does this also mean that they can *never* have version numbers?

**Comment by ogcscotts** [comment]
NEVER!!!! ;-)

**Comment by ronaldtse** [comment]
THANKS!! :wink:
