### ISSUE TITLE
OGC document text is aligned as "left justified"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#98]
As confirmed in #93, all OGC document body text should be "left justified" across all output formats.

**Comment by opoudjis** [comment]
In Word currently, the following styles are justified:

* Note
* Definition (of term)
* ForewordTitle
* IntroTitle
* CopyrightNotice
* Quote
* Footnote
* MsoBodyText

Can I confirm that all of these should be left aligned?

**Comment by ronaldtse** [comment]
I think so, unless some style looks awfully off then we should discuss.
